CREATE TABLE `ACADEMIC_CALENDAR` (
  `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
  `TITLE` longtext,
  `DESCRIPTION` longtext,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`)
) ENGINE=InnoDB;

CREATE TABLE `ACADEMIC_CALENDAR_ENTRY` (
  `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
  `TITLE` longtext,
  `DESCRIPTION` longtext,
  `BEGIN` timestamp NOT NULL default '0000-00-00 00:00:00',
  `END` timestamp NOT NULL default '0000-00-00 00:00:00',
  `OJB_CONCRETE_CLASS` varchar(255) NOT NULL default '',
  `KEY_ACADEMIC_CALENDAR` int(11) unsigned default NULL,
  `KEY_PARENT_ENTRY` int(11) unsigned default NULL,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_PARENT_ENTRY` (`KEY_PARENT_ENTRY`),
  KEY `KEY_ACADEMIC_CALENDAR` (`KEY_ACADEMIC_CALENDAR`),
  KEY `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`)
) ENGINE=InnoDB;
