UPDATE POSTING_RULE SET ENTRY_TYPE = 'PHD_GRATUITY_FEE' WHERE OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.phd.debts.PhdGratuityPR';
UPDATE POSTING_RULE SET ENTRY_TYPE = 'EXTERNAL_SCOLARSHIP_PAYMENT' WHERE OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.phd.debts.ExternalScholarshipPhdGratuityContribuitionPR';
UPDATE ENTRY SET ENTRY_TYPE = 'EXTERNAL_SCOLARSHIP_PAYMENT' WHERE ENTRY_TYPE = 'FCT_SCOLARSHIP_PAYMENT';
