--ResearchUnit
update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='e9ab1a2b-cfd2-4c6d-9476-27c7c3caf4c6' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ResearchUnitSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='2a487bf2-9986-40cf-923d-c571c211491f' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ResearchUnitSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='5a35c10e-2108-412d-94f5-8ba12f051305' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ResearchUnitSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='8c4b7680-93bd-4c17-b346-9af510d13eaa' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ResearchUnitSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='27c395f9-5d79-4172-b33c-4779fedf6cc8' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ResearchUnitSite';


-- Homepage
update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='129fcf2c-4edb-4273-a58e-6d504ea3964c' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.homepage.Homepage';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='31fd792e-73c4-4a78-88ee-36d73347caf4' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.homepage.Homepage';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='9d51e9a0-801f-48f1-b0f0-09a44c423010' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.homepage.Homepage';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='405b9767-a4d7-4bd7-93ec-00fe1e21d941' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.homepage.Homepage';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='9e0b010c-48bc-480f-9530-c7b83a4c37e0' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.homepage.Homepage';


--Concelho Cientifico

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='524cbbcd-5fd3-4d83-9a9a-827828a7eb21' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificCouncilSite';

-- Area Cientifica

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='cca7ce00-11a6-48ce-bb6f-d211fe30f5fa' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificAreaSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='a7c5115f-f926-4d76-93d6-a548af78a33c' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificAreaSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='70693e3c-0213-46b6-b6e8-9f4201e00bbb' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificAreaSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='9f6c2043-438d-4e7f-a445-6c3d403d5186' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificAreaSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='3f0275bf-5337-4895-840e-002d21c3765f' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificAreaSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='33cfd048-18a9-444d-98dd-2e4c7029b53c' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificAreaSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='d17a324d-9028-416b-9227-d88d259d932c' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.ScientificAreaSite';

-- Departamento

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='173e00ae-66ff-408b-a8ce-d4a4011fe3f5' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='3bd0759b-edca-4ff7-87d6-6e03b6be1b3c' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='85372e2e-ffe0-48ff-a758-1017a11c797f' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='931438dc-b0e2-4d2a-b017-1a449adf59e3' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='95b0bf15-1f4d-4430-815a-dfc1fb373ea6' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='11239b0e-e42a-438a-a2d0-db13c1b034c6' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='23cfd678-1f9a-4d56-a717-7112b0ca67b5' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='a1032483-0c50-4d6d-aa01-ff4c39dcfcea' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

update CONTENT C, CONTENT C2, META_DOMAIN_OBJECT MDO set C.KEY_PORTAL=C2.ID_INTERNAL WHERE C.CONTENT_ID='73bd2f92-0d09-48d5-ae78-ea1e15653077' AND C2.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';



