UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=723,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='2553ca76-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt11:disciplinas',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '2553ca76-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=724,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='2574818a-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt8:homepage',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '2574818a-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=725,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='2574881a-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt6:cursos',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '2574881a-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=726,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='25782740-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt13:departamentos',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '25782740-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=727,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='2586b648-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt8:research',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '2586b648-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=728,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='259fb95e-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt18:concelhoCientifico',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '259fb95e-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=729,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='259fbb84-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt17:concelhoPedagocio',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '259fbb84-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT SET KEY_META_DOMAIN_OBJECT=730,KEY_PORTAL_ROOT_DOMAIN_OBJECT=null,MAXIMIZABLE=null,PREFIX='',KEY_INITIAL_CONTENT=null,CONTENT_ID='25abc654-f86e-102a-aeb6-0013d3b09da0',CREATION_DATE=null,NAME='pt14:areaCientifica',TITLE=null,BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.MetaDomainObjectPortal' WHERE CONTENT_ID = '25abc654-f86e-102a-aeb6-0013d3b09da0'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));


DROP TABLE UUID_TEMP_TABLE;

UPDATE CONTENT C, META_DOMAIN_OBJECT MDO SET NAME='pt13:departamentos' WHERE C.KEY_META_DOMAIN_OBJECT=MDO.ID_INTERNAL AND MDO.TYPE='net.sourceforge.fenixedu.domain.DepartmentSite';

