--  SQL file representing changes to the functionalities model
--  Generated at Tue Jul 24 19:11:15 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 248490 UUID: 'cee30a90-1b15-42b6-96f9-8149ad624d5a'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PARAMETERS` = NULL WHERE own.`UUID` = 'cee30a90-1b15-42b6-96f9-8149ad624d5a';

--  ID: 248491 UUID: '48e76566-47fd-4b59-8597-1f13462f0aef'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PARAMETERS` = NULL WHERE own.`UUID` = '48e76566-47fd-4b59-8597-1f13462f0aef';

--  ID: 248492 UUID: 'c6213501-f95d-468c-8761-43bce6fdebea'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PARAMETERS` = NULL WHERE own.`UUID` = 'c6213501-f95d-468c-8761-43bce6fdebea';

--  ID: 248493 UUID: '182704f1-d1be-446f-8de2-12df8be889af'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PARAMETERS` = NULL WHERE own.`UUID` = '182704f1-d1be-446f-8de2-12df8be889af';

--  ID: 248494 UUID: '0cf4cba6-0f3f-4da1-a336-b274479ac6f2'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PARAMETERS` = NULL WHERE own.`UUID` = '0cf4cba6-0f3f-4da1-a336-b274479ac6f2';

--  ID: 248495 UUID: '4c9eac8c-13c1-49be-9119-8f2c0c973513'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PARAMETERS` = NULL WHERE own.`UUID` = '4c9eac8c-13c1-49be-9119-8f2c0c973513';

--  ID: 248499 UUID: '93535d48-b149-482c-99fa-cb50d7e5996e'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PATH` = '/assiduousnessParametrization.do?method=showSchedules' WHERE own.`UUID` = '93535d48-b149-482c-99fa-cb50d7e5996e';

--  ID: 248500 UUID: 'c022c4c9-0844-4a0d-860e-c2d305f26acb'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PATH` = '/assiduousnessParametrization.do?method=showJustificationMotives' WHERE own.`UUID` = 'c022c4c9-0844-4a0d-860e-c2d305f26acb';

--  ID: 248501 UUID: 'c875286c-89ce-46e6-b92a-89ff729a2347'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PATH` = '/assiduousnessParametrization.do?method=showRegularizationMotives' WHERE own.`UUID` = 'c875286c-89ce-46e6-b92a-89ff729a2347';

--  ID: 248511 UUID: '89d46288-56e6-4f1a-af68-58a0ffe801bf'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PATH` = '/manageExtraWorkAuthorization.do?method=prepareExtraWorkAuthorizationsSearch' WHERE own.`UUID` = '89d46288-56e6-4f1a-af68-58a0ffe801bf';

COMMIT;
