alter table `CANDIDACY` add column `KEY_GRANT_OWNER_PROVIDER` int(11);
alter table `CANDIDACY` add column `OID_GRANT_OWNER_PROVIDER` bigint(20);
alter table `CANDIDACY` add index (`KEY_GRANT_OWNER_PROVIDER`);
alter table `INDIVIDUAL_CANDIDACY` add column `KEY_GRANT_OWNER_PROVIDER` int(11);
alter table `INDIVIDUAL_CANDIDACY` add column `OID_GRANT_OWNER_PROVIDER` bigint(20);
alter table `INDIVIDUAL_CANDIDACY` add index (`KEY_GRANT_OWNER_PROVIDER`);
alter table `CANDIDACY_PRECEDENT_DEGREE_INFORMATION` add column `KEY_SOURCE_INSTITUTION` int(11), add column `OID_SOURCE_INSTITUTION` bigint unsigned default null;
alter table `CANDIDACY_PRECEDENT_DEGREE_INFORMATION` add column `NUMBER_OF_ENROLED_CURRICULAR_COURSES` int(11);
alter table `CANDIDACY_PRECEDENT_DEGREE_INFORMATION` add index (`KEY_SOURCE_INSTITUTION`), add index (`OID_SOURCE_INSTITUTION`);
alter table `PRECEDENT_DEGREE_INFORMATION` add column `KEY_SOURCE_INSTITUTION` int(11), add column `OID_SOURCE_INSTITUTION` bigint unsigned default null;
alter table `PRECEDENT_DEGREE_INFORMATION` add index (`KEY_SOURCE_INSTITUTION`), add index (`OID_SOURCE_INSTITUTION`);

update PARTY, PARTY_TYPE set PARTY.KEY_PARTY_TYPE = PARTY_TYPE.ID_INTERNAL where PARTY_TYPE.TYPE = "SCHOOL" and PARTY.ID_INTERNAL = 61559;
