#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Add Person to Department Credits Management" addPersonToDepartmentCreditsManagement.sql
execute "Create evaluation participant table" createThesisEvaluationParticipantTable.sql
execute "Added column REJECTION_COMMENT to THESIS table" addRejectionCommentThesisTable.sql
execute "Create RegistrationNumber Table" CreateRegistrationNumberTable.sql
execute "Add Event Key To Enrolment Evaluation" addEventKeyToEnrolmentEvaluation.sql
execute "Migrate ResearchType Local to National"  migrateResearchTypeLocalToNational.sql
execute "Changing External Registration Data" alterTableExternalRegistrationData.sql

