
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida;


public class Almeida_escola  
{
  private String code;

  private long id_internal;

  private String name;

  public String getCode()
  {
     return this.code;
  }
  public void setCode(String param)
  {
    this.code = param;
  }


  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public String getName()
  {
     return this.name;
  }
  public void setName(String param)
  {
    this.name = param;
  }


  public String toString(){
    return  " [CODE] " + code + " [ID_INTERNAL] " + id_internal + " [NAME] " + name;

  }
  
  public boolean equals(Object obj) {
    boolean resultado = false;
    if (obj instanceof Almeida_escola) {
      Almeida_escola Almeida_escola = (Almeida_escola) obj;
      resultado = this.code == Almeida_escola.getCode() && this.name == Almeida_escola.getName();
    }
    return resultado;
  }
}