
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida;


public class Almeida_coddisc 
{
  private String coddis;

  private long codint;

  private String nomedis;

  public String getCoddis()
  {
     return this.coddis;
  }
  public void setCoddis(String param)
  {
    this.coddis = param;
  }


  public long getCodint()
  {
     return this.codint;
  }
  public void setCodint(long param)
  {
    this.codint = param;
  }


  public String getNomedis()
  {
     return this.nomedis;
  }
  public void setNomedis(String param)
  {
    this.nomedis = param;
  }


  public String toString(){
    return  " [coddis] " + coddis + " [codint] " + codint + " [nomedis] " + nomedis;

  }
}

