
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida;


public class Almeida_curram  
{
  private long codcur;

  private long codint;

  private long codorien;

  private long codram;

  private String descri;

  public long getCodcur()
  {
     return this.codcur;
  }
  public void setCodcur(long param)
  {
    this.codcur = param;
  }


  public long getCodint()
  {
     return this.codint;
  }
  public void setCodint(long param)
  {
    this.codint = param;
  }


  public long getCodorien()
  {
     return this.codorien;
  }
  public void setCodorien(long param)
  {
    this.codorien = param;
  }


  public long getCodram()
  {
     return this.codram;
  }
  public void setCodram(long param)
  {
    this.codram = param;
  }


  public String getDescri()
  {
     return this.descri;
  }
  public void setDescri(String param)
  {
    this.descri = param;
  }


  public String toString(){
    return  " [codCur] " + codcur + " [codInt] " + codint + " [codOrien] " + codorien + " [codRam] " + codram + " [descri] " + descri;

  }
}

