
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida;


public class Almeida_nacionalidade  
{
  private String nome;

  private long numero;

  public String getNome()
  {
     return this.nome;
  }
  public void setNome(String param)
  {
    this.nome = param;
  }


  public long getNumero()
  {
     return this.numero;
  }
  public void setNumero(long param)
  {
    this.numero = param;
  }


  public String toString(){
    return  " [nome] " + nome + " [numero] " + numero;

  }
}

