
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida;


public class Almeida_inscricoes  
{
  private long ano;

  private long anoinscricao;

  private String coddis;

  private long codint;

  private long curso;

  private long numero;

  private String ramo;

  private long semestre;

  public long getAno()
  {
     return this.ano;
  }
  public void setAno(long param)
  {
    this.ano = param;
  }


  public long getAnoinscricao()
  {
     return this.anoinscricao;
  }
  public void setAnoinscricao(long param)
  {
    this.anoinscricao = param;
  }


  public String getCoddis()
  {
     return this.coddis;
  }
  public void setCoddis(String param)
  {
    this.coddis = param;
  }


  public long getCodint()
  {
     return this.codint;
  }
  public void setCodint(long param)
  {
    this.codint = param;
  }


  public long getCurso()
  {
     return this.curso;
  }
  public void setCurso(long param)
  {
    this.curso = param;
  }


  public long getNumero()
  {
     return this.numero;
  }
  public void setNumero(long param)
  {
    this.numero = param;
  }


  public String getRamo()
  {
     return this.ramo;
  }
  public void setRamo(String param)
  {
    this.ramo = param;
  }


  public long getSemestre()
  {
     return this.semestre;
  }
  public void setSemestre(long param)
  {
    this.semestre = param;
  }


  public String toString(){
    return  " [ano] " + ano + " [anoInscricao] " + anoinscricao + " [codDis] " + coddis + " [codInt] " + codint + " [curso] " + curso + " [numero] " + numero + " [ramo] " + ramo + " [semestre] " + semestre;

  }
}

