ALTER TABLE RESEARCHER CHANGE COLUMN KEYWORDS KEYWORDS_PT text;
ALTER TABLE RESEARCHER ADD COLUMN KEYWORDS_EN text(65535);
UPDATE RESEARCHER SET ALLOWS_TO_BE_SEARCHED=1;
UPDATE RESEARCHER SET KEYWORDS_PT = '' WHERE KEYWORDS_PT IS NULL;
UPDATE RESEARCHER SET KEYWORDS_EN = '' WHERE KEYWORDS_EN IS NULL;
