
ALTER TABLE EXAM_EXECUTION_COURSE RENAME EVALUATION_EXECUTION_COURSE;
ALTER TABLE NON_AFFILIATED_TEACHER_PROFESSORSHIPS RENAME NON_AFFILIATED_TEACHER_EXECUTION_COURSE;
ALTER TABLE FINAL_DEGREE_WORK_PROPOSAL_BRANCH RENAME PROPOSAL_BRANCH;
ALTER TABLE EQUIVALENCY_THEME RENAME COURSE_EQUIVALENCY_THEME;
ALTER TABLE CMS_MAIL_ADDRESS_ALIAS_MAILING_LIST RENAME MAILING_LIST_ALIAS;
ALTER TABLE CMS_MAIL_MESSAGE_MAIL_QUEUE RENAME MAILING_LIST_QUEUE_OUTGOING_MAILS;
ALTER TABLE crd_CREDITS_MANAGER_DEPARTMENT RENAME PERSON_DEPARTMENT;
ALTER TABLE CMS_CONTENT_OWNERSHIP RENAME CONTENT_OWNERSHIP;
ALTER TABLE CLASS_SHIFT RENAME SHIFT_SCHOOL_CLASS;
ALTER TABLE CMS_FUNCTIONALITY_LINK_AVAILABILITY RENAME FUNCTIONALITY_LINK_AVAILABLE_TO_WEBSITE_TYPE;
ALTER TABLE CMS_MANDATORY_CONTENTS RENAME WEBSITE_TYPE_MANDATORY_CONTENT;

ALTER TABLE GROUPING_ATTENDS CHANGE KEY_ATTEND KEY_ATTENDS int(11) NOT NULL default '0';
ALTER TABLE PROPOSAL_BRANCH CHANGE KEY_FINAL_DEGREE_WORK_PROPOSAL KEY_PROPOSAL int(11) NOT NULL default '0';
ALTER TABLE COURSE_EQUIVALENCY_THEME CHANGE THEME_ID KEY_THEME int(11) NOT NULL default '0';
ALTER TABLE COURSE_EQUIVALENCY_THEME CHANGE EQUIVALENCY_ID KEY_COURSE_EQUIVALENCY int(11) NOT NULL default '0';
ALTER TABLE STUDENT_GROUP_ATTEND CHANGE KEY_ATTEND KEY_ATTENDS int(11) NOT NULL default '0';
ALTER TABLE GROUPING_ATTENDS CHANGE KEY_ATTEND KEY_ATTENDS int(11) NOT NULL default '0';
ALTER TABLE CONTENT_OWNERSHIP CHANGE KEY_OWNER KEY_PERSON int(11) NOT NULL default '0';
ALTER TABLE SHIFT_SCHOOL_CLASS CHANGE KEY_CLASS KEY_SCHOOL_CLASS int(11) NOT NULL default '0';
ALTER TABLE FUNCTIONALITY_LINK_AVAILABLE_TO_WEBSITE_TYPE CHANGE KEY_LINK KEY_FUNCTIONALITY_LINK int(11) NOT NULL default '0';
ALTER TABLE FUNCTIONALITY_LINK_AVAILABLE_TO_WEBSITE_TYPE CHANGE KEY_TYPE KEY_WEBSITE_TYPE int(11) NOT NULL default '0';
ALTER TABLE WRITTEN_EVALUATION_CURRICULAR_COURSE_SCOPE CHANGE KEY_EVALUATION KEY_WRITTEN_EVALUATION int(11) NOT NULL default '0';

ALTER TABLE PARTY_PARTY CHANGE KEY_SUB_PARTY KEY_PARTY_CHILDS int(11) NOT NULL default '0';
ALTER TABLE PARTY_PARTY CHANGE KEY_PARENT_PARTY KEY_PARTY_PARENTS int(11) NOT NULL default '0';

alter table STUDENT add column KEY_PERSONAL_DATA_USE_INQUIRY_ANSWERS int default null;
alter table STUDENT add column KEY_ASSOCIATED_TUTOR int default null;
alter table STUDENT add column KEY_ASSOCIATED_GAUGING_TEST_RESULT int default null;

alter table ROOM add column KEY_SUROUNDING_SPACE int default null;
alter table BUILDING add column KEY_SUROUNDING_SPACE int default null;
