CREATE TABLE `BLUEPRINT` (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `VALID_UNTIL` varchar(10) default NULL,
  `VALID_FROM` varchar(10) default NULL,
  `KEY_SPACE` int(11) NOT NULL default '0',
  `KEY_BLUEPRINT_FILE` int(11) NOT NULL default '0', 
  `KEY_CREATION_PERSON` int(11) NOT NULL default '0', 
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_SPACE` (`KEY_SPACE`),  
  KEY `KEY_BLUEPRINT_FILE` (`KEY_BLUEPRINT_FILE`),
  KEY `KEY_CREATION_PERSON` (`KEY_CREATION_PERSON`), 
  KEY `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`)
) ENGINE=InnoDB;