#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Fix Old DFA Candidacy Posting Rule Date" FixOldDFACandidacyPostingRuleDate.sql
execute "AlterTableAssiduousnessClosedMonth" AlterTableAssiduousnessClosedMonth.sql
execute "CreateClosedMonthJustificationAndExtraWorkTables" CreateClosedMonthJustificationAndExtraWorkTables.sql
execute "Adding publications functionalities" changes-20070130163908.sql
execute "Adding publication sections in public page" sections.sql
execute "Adding publication options to homePage" addPublicationOptionsToSite.sql
execute "Fixing values in publications" fixValuesInTablePublication.sql
execute "Performing Researcher modifications" researcherModifications.sql