select concat('update EXECUTION_YEAR set EXECUTION_YEAR.KEY_INSURANCE_VALUE = ',
	INSURANCE_VALUE.ID_INTERNAL, 
	' where EXECUTION_YEAR.ID_INTERNAL = ', 
	INSURANCE_VALUE.KEY_EXECUTION_YEAR, ';') 
as "" from INSURANCE_VALUE;