#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Remove Last Modification Date From Table Degree Info" removeLastModificationDateFromTableDegreeInfo.sql
execute "Adding dynamic mail distribution to execution course's site table (default 0, not null)" alterSiteTable.sql
execute "Creating new announcement tables" createNewAnnouncementTables.sql
execute "Add columns to Execution Degree" alterTableExecutionDegree.sql
execute "Alter table EXECUTION_COURSE" alterExecutionCourseTable.sql