DROP TABLE IF EXISTS FUNCTIONALITY;
CREATE TABLE `FUNCTIONALITY` (
  `ID_INTERNAL` INTEGER  NOT NULL AUTO_INCREMENT,
  `OJB_CONCRETE_CLASS` VARCHAR(255)  NOT NULL DEFAULT '',
  `KEY_ROOT_DOMAIN_OBJECT` INTEGER  NOT NULL DEFAULT 1,
  `KEY_PARENT` INTEGER,
  `KEY_MODULE` INTEGER,
  `NAME` TEXT NOT NULL,
  `TITLE` TEXT,
  `DESCRIPTION` TEXT,
  `PATH` TEXT NOT NULL,
  `RELATIVE` BOOLEAN NOT NULL DEFAULT 1,
  `ENABLED` BOOLEAN NOT NULL DEFAULT 1,
  `ORDER_IN_MODULE` INTEGER,
  PRIMARY KEY(`ID_INTERNAL`)
) ENGINE = InnoDB DEFAULT CHARACTER SET latin1;
