--  SQL file representing changes to the functionalities model
--  Generated at Thu Jan 4 20:52:19 WET 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 16196 UUID: '8b992ca5-c112-4963-a2ca-91a5713e3f0a'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt14:Página Inicialen12:Initial Page' WHERE own.`UUID` = '8b992ca5-c112-4963-a2ca-91a5713e3f0a';

--  ID: 16197 UUID: 'c168fb54-39ed-4e76-8c7d-df4827aefc4d'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Anúnciosen13:Announcements' WHERE own.`UUID` = 'c168fb54-39ed-4e76-8c7d-df4827aefc4d';

--  ID: 16198 UUID: 'a7ae9674-17c9-4166-91f4-a80b38d79a41'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt11:Planeamentoen8:Planning' WHERE own.`UUID` = 'a7ae9674-17c9-4166-91f4-a80b38d79a41';

--  ID: 16199 UUID: '729d1770-b7f0-4bf9-acd0-b07b951b2e2e'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Sumáriosen9:Summaries' WHERE own.`UUID` = '729d1770-b7f0-4bf9-acd0-b07b951b2e2e';

--  ID: 16200 UUID: '9a31d73a-a1d4-462a-af5c-0fb6ffb15761'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt10:Objectivosen10:Objectives' WHERE own.`UUID` = '9a31d73a-a1d4-462a-af5c-0fb6ffb15761';

--  ID: 16201 UUID: 'c71ee66b-5246-4259-b135-c6eed8d21e7a'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Programaen7:Program' WHERE own.`UUID` = 'c71ee66b-5246-4259-b135-c6eed8d21e7a';

--  ID: 16202 UUID: '51b95e9b-f636-4466-ab5b-f455184b9fe3'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt19:Método de Avaliaçãoen17:Evaluation Method' WHERE own.`UUID` = '51b95e9b-f636-4466-ab5b-f455184b9fe3';

--  ID: 16203 UUID: '672d9b28-2100-46ba-9586-f9bb09692747'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt12:Bibliografiaen12:Bibliography' WHERE own.`UUID` = '672d9b28-2100-46ba-9586-f9bb09692747';

--  ID: 16204 UUID: '98b12f32-87b6-4c9d-8c18-8bd5c00d303c'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt7:Horárioen9:Timesheet' WHERE own.`UUID` = '98b12f32-87b6-4c9d-8c18-8bd5c00d303c';

--  ID: 16205 UUID: '859fb0f6-ee73-4baa-bf34-80ea3ec8ab5f'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt6:Turnosen6:Shifts' WHERE own.`UUID` = '859fb0f6-ee73-4baa-bf34-80ea3ec8ab5f';

--  ID: 16206 UUID: 'bf220aff-96eb-4a67-ab1c-848f90b6aaa3'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt9:Avaliaçãoen10:Evaluation' WHERE own.`UUID` = 'bf220aff-96eb-4a67-ab1c-848f90b6aaa3';

--  ID: 16207 UUID: 'cc6df75a-3be9-45d9-b47b-3b7544565251'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt12:Agrupamentosen6:Groups' WHERE own.`UUID` = 'cc6df75a-3be9-45d9-b47b-3b7544565251';

--  ID: 16208 UUID: 'b7a06c06-79aa-4efb-b132-567798b64be0'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 13 WHERE own.`UUID` = 'b7a06c06-79aa-4efb-b132-567798b64be0';

-- 
--  Inserting new functionalities
-- 

--  ID: 21909 UUID: '360d6646-953c-45cc-a0bf-721365af5e00'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`) SELECT '360d6646-953c-45cc-a0bf-721365af5e00', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'en15:Search Contentspt21:Pesquisa de Conteúdos', 'en15:Search Contentspt19:Pesquisar Conteúdos', NULL, '/searchScormContent.do?method=prepareSearchForExecutionCourse', NULL, 1, 1, 'executionCourseID', 12, 1, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = '197325b3-e343-4945-9dba-dacb86df3112';

COMMIT;
