DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal IN (219,241,242,235,236,237,238);

ALTER TABLE ENROLMENT ADD COLUMN FNL_TMP_STATE varchar(4) NOT NULL AFTER STATE;

UPDATE ENROLMENT SET FNL_TMP_STATE = "FNL";

