alter table `INDIVIDUAL_CANDIDACY` add `NATIONAL_ID_CARD_AVOIDANCE_ANSWER_DATE` timestamp NULL default NULL, add `ID_CARD_AVOIDANCE_OTHER_REASON` text, add `NATIONAL_ID_CARD_AVOIDANCE_QUESTION` text;
