ALTER TABLE ACADEMIC_SERVICE_REQUEST ADD COLUMN KEY_OLD_COURSE_GROUP INT(11) DEFAULT NULL;
ALTER TABLE ACADEMIC_SERVICE_REQUEST ADD COLUMN KEY_NEW_COURSE_GROUP INT(11) DEFAULT NULL;
ALTER TABLE ACADEMIC_SERVICE_REQUEST ADD COLUMN KEY_ENROLMENT INT(11) DEFAULT NULL;
ALTER TABLE ACADEMIC_SERVICE_REQUEST ADD COLUMN PURPOSE TEXT DEFAULT NULL;
