ALTER TABLE DEGREE_MODULE ADD COLUMN REGIME_TYPE varchar(255) default NULL;

UPDATE DEGREE_MODULE SET DEGREE_MODULE.REGIME_TYPE = "SEMESTRIAL" WHERE DEGREE_MODULE.OJB_CONCRETE_CLASS = "net.sourceforge.fenixedu.domain.CurricularCourse" AND DEGREE_MODULE.CURRICULAR_STAGE = "OLD";