alter table PERSON add (`KEY_PERSONAL_PHOTO` int(11) default null);

DROP TABLE IF EXISTS `FILE_ENTRY`;
CREATE TABLE `FILE_ENTRY` (
	`ID_INTERNAL` int(11) NOT NULL auto_increment, 
	`KEY_PERSON` int(11),
	`CONTENT` blob NOT NULL,
	`CONTENT_TYPE` varchar(50),
    PRIMARY KEY (`ID_INTERNAL`),
    KEY `KEY_PERSON` (`KEY_PERSON`)    
)TYPE=InnoDB;
