--  SQL file representing changes to the functionalities model
--  Generated at Thu Apr 19 13:26:16 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 26328 UUID: '173e00ae-66ff-408b-a8ce-d4a4011fe3f5'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 3 WHERE own.`UUID` = '173e00ae-66ff-408b-a8ce-d4a4011fe3f5';

--  ID: 26329 UUID: '3bd0759b-edca-4ff7-87d6-6e03b6be1b3c'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 4 WHERE own.`UUID` = '3bd0759b-edca-4ff7-87d6-6e03b6be1b3c';

--  ID: 26330 UUID: '85372e2e-ffe0-48ff-a758-1017a11c797f'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 5 WHERE own.`UUID` = '85372e2e-ffe0-48ff-a758-1017a11c797f';

-- 
--  Inserting new functionalities
-- 

--  ID: 108069 UUID: '931438dc-b0e2-4d2a-b017-1a449adf59e3'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`) SELECT '931438dc-b0e2-4d2a-b017-1a449adf59e3', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'en6:Eventspt7:Eventos', NULL, NULL, '/events.do?method=viewAnnouncements', NULL, 1, 1, 'selectedDepartmentUnitID', 2, 1, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = '3adea1cf-e612-456f-b8be-c24882b77c3e';

COMMIT;
