ALTER TABLE ACCOUNTING_EVENT ADD COLUMN KEY_EXECUTION_YEAR INT(11) NULL;
ALTER TABLE ACCOUNTING_EVENT ADD INDEX (KEY_EXECUTION_YEAR);

ALTER TABLE ACCOUNTING_EVENT CHANGE COLUMN KEY_ADMINISTRATIVE_OFFICE KEY_ADMINISTRATIVE_OFFICE INT(11) NULL;
