CREATE TABLE NON_AFFILIATED_TEACHER_PROFESSORSHIPS(
	ID_INTERNAL int(11) NOT NULL auto_increment, 
	KEY_NON_AFFILIATED_TEACHER int(11) NOT NULL,
	KEY_EXECUTION_COURSE  int(11) NOT NULL,
	ACK_OPT_LOCK int(11) default NULL,
    PRIMARY KEY  (ID_INTERNAL),
    UNIQUE KEY U1 (KEY_NON_AFFILIATED_TEACHER, KEY_EXECUTION_COURSE)
) TYPE=InnoDB;