-- Journal required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Journal%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Journal%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Journal%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'observation';

-- Conference required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Conference%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

-- Book required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Book%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'editorCity';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Book%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'country';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Book%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Book%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Book%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'scope';

-- Thesis required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Thesis%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Thesis%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

-- Technical report required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Technical%Report%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Technical%Report%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Technical%Report%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'instituition';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Technical%Report%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'number';

-- Patent required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Patent%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'numberPages';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Patent%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Patent%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Patent%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'scope';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Patent%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'local';

-- Translation required/non-required fields

-- is this ok?
-- update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Translation%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

-- is this ok?
-- update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Translation%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'editor';

-- is this ok?
-- update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Translation%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'editorCity';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Translation%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'country';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Translation%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'numberPages';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Translation%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

-- Critique required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Critique%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Critique%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'country';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Critique%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'volume';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Critique%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Critique%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'scope';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Critique%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'criticizedAuthor';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Critique%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'title';

-- Other required/non-required fields

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Other%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'language';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Other%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'editor';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 0 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Other%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'format';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 1 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Other%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'month';

update PUBLICATION_ATTRIBUTE, PUBLICATION_TYPE, ATTRIBUTE set PUBLICATION_ATTRIBUTE.REQUIRED = 1 where PUBLICATION_TYPE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_PUBLICATION_TYPE and ATTRIBUTE.ID_INTERNAL = PUBLICATION_ATTRIBUTE.KEY_ATTRIBUTE and PUBLICATION_TYPE.PUBLICATION_TYPE like 'Other%' and ATTRIBUTE.ATTRIBUTE_TYPE = 'year';