-- Seminary
insert into SEMINARY (id_internal, name,description,allowed_candidacies_per_student,ACK_OPT_LOCK,enrollment_begin_time,enrollment_begin_date,enrollment_end_time,enrollment_end_date,has_theme,has_case_study) values (5,"Desenvolvimento Sustent?vel 2005/2006","Ano Lectivo de 2005 / 2006",1,1,'00:00:00','2005-9-1','23:59:59','2005-9-23',0,0);

-- Equivalencies
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (2102,5,3840,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (2103,5,3769,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,3528,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,3418,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,4918,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,11983,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,2818,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,4920,3,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12229,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12230,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,4922,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,4923,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,3631,3,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,11665,3,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,11681,3,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12228,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12018,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12231,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,11959,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12232,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12248,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,15113,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12248,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,15048,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,4925,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12250,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12251,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12252,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,14011,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12972,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,14672,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12606,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,15253,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,5034,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,13298,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,12258,1,1);
insert into SEMINARY_CURRICULARCOURSE (id_internal,seminary_id_internal,curricular_course_id_internal,modality_id_internal,ACK_OPT_LOCK) values (null,5,15588,1,1);