select concat('update PERSON set PERSON.KEY_PERSON_ACCOUNT = ',
	PERSON_ACCOUNT.ID_INTERNAL, 
	' where PERSON.ID_INTERNAL = ', 
	PERSON_ACCOUNT.KEY_PERSON, ';') 
as "" from PERSON_ACCOUNT where PERSON_ACCOUNT.KEY_PERSON IS NOT NULL;