alter table CANDIDACY add column DISLOCATED_FROM_PERMANENT_RESIDENCE tinyint(1);
alter table CANDIDACY add column DISTRICT_OF_RESIDENCE varchar(255);
alter table CANDIDACY add column DISTRICT_SUBDIVISION_OF_RESIDENCE varchar(255);
alter table CANDIDACY add column FATHER_PROFESSIONAL_CONDITION varchar(255);
alter table CANDIDACY add column FATHER_PROFESSION_TYPE varchar(255);
alter table CANDIDACY add column FATHER_SCHOOL_LEVEL varchar(255);
alter table CANDIDACY add column GRANT_OWNER_TYPE varchar(255);
alter table CANDIDACY add column HIGH_SCHOOL_TYPE varchar(255);
alter table CANDIDACY add column KEY_COUNTRY_OF_RESIDENCE int(11);
alter table CANDIDACY add column MARITAL_STATUS varchar(255);
alter table CANDIDACY add column MOTHER_PROFESSIONAL_CONDITION varchar(255);
alter table CANDIDACY add column MOTHER_PROFESSION_TYPE varchar(255);
alter table CANDIDACY add column MOTHER_SCHOOL_LEVEL varchar(255);
alter table CANDIDACY add column NUMBER_OF_CANDIDACIES_TO_HIGHER_SCHOOL int(11);
alter table CANDIDACY add column NUMBER_OF_FLUNKS_ON_HIGH_SCHOOL int(11);
alter table CANDIDACY add column PLACING_OPTION int(11);
alter table CANDIDACY add column PROFESSIONAL_CONDITION varchar(255);
alter table CANDIDACY add column PROFESSION_TYPE varchar(255);
alter table CANDIDACY add column SCHOOL_TIME_DISTRICT_OF_RESIDENCE varchar(255);
alter table CANDIDACY add column SCHOOL_TIME_DISTRICT_SUB_DIVISION_OF_RESIDENCE varchar(255);
alter table CANDIDACY add column SPOUSE_PROFESSIONAL_CONDITION varchar(255);
alter table CANDIDACY add column SPOUSE_PROFESSION_TYPE varchar(255);
alter table CANDIDACY add column SPOUSE_SCHOOL_LEVEL varchar(255);
alter table CANDIDACY add index (KEY_COUNTRY_OF_RESIDENCE);
alter table COUNTRY add column DEFAULT_COUNTRY tinyint(1) default false;
alter table PRECEDENT_DEGREE_INFORMATION add column SCHOOL_LEVEL varchar(255);
alter table PRECEDENT_DEGREE_INFORMATION add column OTHER_SCHOOL_LEVEL varchar(255);
