ALTER TABLE MARK ADD CLASS_NAME VARCHAR(255) NOT NULL default '';
ALTER TABLE MARK ADD SUBMITED_MARK VARCHAR(4) DEFAULT NULL;
ALTER TABLE MARK ADD GRADE_LIST_VERSION INT(11) DEFAULT 0;
ALTER TABLE MARK ADD SUBMIT_DATE DATETIME DEFAULT NULL;
ALTER TABLE MARK ADD WHEN_SUBMITED DATETIME DEFAULT NULL;

