#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Change Event Edition" changeEventEdition.sql
execute "Create Prize Tables" createPrizeTables.sql
execute "Add Show Prizes to homepage" addShowPrizesToHomePage.sql
execute "Create functioanlities" changes-20070625183052.sql
execute "Add Prizes functionality" addShowPrizesFunctionality.sql
execute "Changing Table Gratuity Situation: Adding penalty exemption" alterTableGratuitySituation.sql
execute "Alter Table Registration" alterTableRegistration-HomologationDate.sql