
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_candidato_mestrado  
{
  private long anocandidatura;

  private long anolicenciatura;

  private long codigocursomestrado;

  private long codigointerno;

  private String codigopostal;

  private String concelhomorada;

  private String concelhonaturalidade;

  private java.sql.Date dataemissaodocumentoidentificacao;

  private String distritomorada;

  private String distritonaturalidade;

  private String email;

  private String enderecoweb;

  private String escolalicenciatura;

  private String especializacao;

  private String estadocivil;

  private String freguesiamorada;

  private String freguesianaturalidade;

  private String licenciatura;

  private String localemissaodocumentoidentificacao;

  private String localidade;

  private Double media;

  private String morada;

  private String nacionalidade;

  private java.sql.Date nascimento;

  private String nome;

  private String nomemae;

  private String nomepai;

  private String numcontribuinte;

  private long numerocandidato;

  private String numerodocumentoidentificacao;

  private String password;

  private String profissao;

  private String sexo;

  private String telefone;

  private String telemovel;

  private String tipodocumentoidentificacao;

  private String username;

  public long getAnocandidatura()
  {
     return this.anocandidatura;
  }
  public void setAnocandidatura(long param)
  {
    this.anocandidatura = param;
  }


  public long getAnolicenciatura()
  {
     return this.anolicenciatura;
  }
  public void setAnolicenciatura(long param)
  {
    this.anolicenciatura = param;
  }


  public long getCodigocursomestrado()
  {
     return this.codigocursomestrado;
  }
  public void setCodigocursomestrado(long param)
  {
    this.codigocursomestrado = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String getCodigopostal()
  {
     return this.codigopostal;
  }
  public void setCodigopostal(String param)
  {
    this.codigopostal = param;
  }


  public String getConcelhomorada()
  {
     return this.concelhomorada;
  }
  public void setConcelhomorada(String param)
  {
    this.concelhomorada = param;
  }


  public String getConcelhonaturalidade()
  {
     return this.concelhonaturalidade;
  }
  public void setConcelhonaturalidade(String param)
  {
    this.concelhonaturalidade = param;
  }


  public java.sql.Date getDataemissaodocumentoidentificacao()
  {
     return this.dataemissaodocumentoidentificacao;
  }
  public void setDataemissaodocumentoidentificacao(java.sql.Date param)
  {
    this.dataemissaodocumentoidentificacao = param;
  }


  public String getDistritomorada()
  {
     return this.distritomorada;
  }
  public void setDistritomorada(String param)
  {
    this.distritomorada = param;
  }


  public String getDistritonaturalidade()
  {
     return this.distritonaturalidade;
  }
  public void setDistritonaturalidade(String param)
  {
    this.distritonaturalidade = param;
  }


  public String getEmail()
  {
     return this.email;
  }
  public void setEmail(String param)
  {
    this.email = param;
  }


  public String getEnderecoweb()
  {
     return this.enderecoweb;
  }
  public void setEnderecoweb(String param)
  {
    this.enderecoweb = param;
  }


  public String getEscolalicenciatura()
  {
     return this.escolalicenciatura;
  }
  public void setEscolalicenciatura(String param)
  {
    this.escolalicenciatura = param;
  }


  public String getEspecializacao()
  {
     return this.especializacao;
  }
  public void setEspecializacao(String param)
  {
    this.especializacao = param;
  }


  public String getEstadocivil()
  {
     return this.estadocivil;
  }
  public void setEstadocivil(String param)
  {
    this.estadocivil = param;
  }


  public String getFreguesiamorada()
  {
     return this.freguesiamorada;
  }
  public void setFreguesiamorada(String param)
  {
    this.freguesiamorada = param;
  }


  public String getFreguesianaturalidade()
  {
     return this.freguesianaturalidade;
  }
  public void setFreguesianaturalidade(String param)
  {
    this.freguesianaturalidade = param;
  }


  public String getLicenciatura()
  {
     return this.licenciatura;
  }
  public void setLicenciatura(String param)
  {
    this.licenciatura = param;
  }


  public String getLocalemissaodocumentoidentificacao()
  {
     return this.localemissaodocumentoidentificacao;
  }
  public void setLocalemissaodocumentoidentificacao(String param)
  {
    this.localemissaodocumentoidentificacao = param;
  }


  public String getLocalidade()
  {
     return this.localidade;
  }
  public void setLocalidade(String param)
  {
    this.localidade = param;
  }


  public Double getMedia()
  {
     return this.media;
  }
  public void setMedia(Double param)
  {
    this.media = param;
  }


  public String getMorada()
  {
     return this.morada;
  }
  public void setMorada(String param)
  {
    this.morada = param;
  }


  public String getNacionalidade()
  {
     return this.nacionalidade;
  }
  public void setNacionalidade(String param)
  {
    this.nacionalidade = param;
  }


  public java.sql.Date getNascimento()
  {
     return this.nascimento;
  }
  public void setNascimento(java.sql.Date param)
  {
    this.nascimento = param;
  }


  public String getNome()
  {
     return this.nome;
  }
  public void setNome(String param)
  {
    this.nome = param;
  }


  public String getNomemae()
  {
     return this.nomemae;
  }
  public void setNomemae(String param)
  {
    this.nomemae = param;
  }


  public String getNomepai()
  {
     return this.nomepai;
  }
  public void setNomepai(String param)
  {
    this.nomepai = param;
  }


  public String getNumcontribuinte()
  {
     return this.numcontribuinte;
  }
  public void setNumcontribuinte(String param)
  {
    this.numcontribuinte = param;
  }


  public long getNumerocandidato()
  {
     return this.numerocandidato;
  }
  public void setNumerocandidato(long param)
  {
    this.numerocandidato = param;
  }


  public String getNumerodocumentoidentificacao()
  {
     return this.numerodocumentoidentificacao;
  }
  public void setNumerodocumentoidentificacao(String param)
  {
    this.numerodocumentoidentificacao = param;
  }


  public String getPassword()
  {
     return this.password;
  }
  public void setPassword(String param)
  {
    this.password = param;
  }


  public String getProfissao()
  {
     return this.profissao;
  }
  public void setProfissao(String param)
  {
    this.profissao = param;
  }


  public String getSexo()
  {
     return this.sexo;
  }
  public void setSexo(String param)
  {
    this.sexo = param;
  }


  public String getTelefone()
  {
     return this.telefone;
  }
  public void setTelefone(String param)
  {
    this.telefone = param;
  }


  public String getTelemovel()
  {
     return this.telemovel;
  }
  public void setTelemovel(String param)
  {
    this.telemovel = param;
  }


  public String getTipodocumentoidentificacao()
  {
     return this.tipodocumentoidentificacao;
  }
  public void setTipodocumentoidentificacao(String param)
  {
    this.tipodocumentoidentificacao = param;
  }


  public String getUsername()
  {
     return this.username;
  }
  public void setUsername(String param)
  {
    this.username = param;
  }


  public String toString(){
    return  " [anoCandidatura] " + anocandidatura + " [anoLicenciatura] " + anolicenciatura + " [codigoCursoMestrado] " + codigocursomestrado + " [codigoInterno] " + codigointerno + " [codigoPostal] " + codigopostal + " [concelhoMorada] " + concelhomorada + " [concelhoNaturalidade] " + concelhonaturalidade + " [dataEmissaoDocumentoIdentificacao] " + dataemissaodocumentoidentificacao + " [distritoMorada] " + distritomorada + " [distritoNaturalidade] " + distritonaturalidade + " [email] " + email + " [enderecoWeb] " + enderecoweb + " [escolaLicenciatura] " + escolalicenciatura + " [especializacao] " + especializacao + " [estadoCivil] " + estadocivil + " [freguesiaMorada] " + freguesiamorada + " [freguesiaNaturalidade] " + freguesianaturalidade + " [licenciatura] " + licenciatura + " [localEmissaoDocumentoIdentificacao] " + localemissaodocumentoidentificacao + " [localidade] " + localidade + " [media] " + media + " [morada] " + morada + " [nacionalidade] " + nacionalidade + " [nascimento] " + nascimento + " [nome] " + nome + " [nomeMae] " + nomemae + " [nomePai] " + nomepai + " [numContribuinte] " + numcontribuinte + " [numeroCandidato] " + numerocandidato + " [numeroDocumentoIdentificacao] " + numerodocumentoidentificacao + " [password] " + password + " [profissao] " + profissao + " [sexo] " + sexo + " [telefone] " + telefone + " [telemovel] " + telemovel + " [tipoDocumentoIdentificacao] " + tipodocumentoidentificacao + " [username] " + username;

  }
}

