
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_disc_area_aluno  
{
  private long codigoaluno;

  private long codigoareadisciplina;

  private long codigointerno;

  private String creditos;

  private java.sql.Date dataexame;

  private java.sql.Date datalancamento;

  private String equivalencia;

  private String nota;

  public long getCodigoaluno()
  {
     return this.codigoaluno;
  }
  public void setCodigoaluno(long param)
  {
    this.codigoaluno = param;
  }


  public long getCodigoareadisciplina()
  {
     return this.codigoareadisciplina;
  }
  public void setCodigoareadisciplina(long param)
  {
    this.codigoareadisciplina = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String getCreditos()
  {
     return this.creditos;
  }
  public void setCreditos(String param)
  {
    this.creditos = param;
  }


  public java.sql.Date getDataexame()
  {
     return this.dataexame;
  }
  public void setDataexame(java.sql.Date param)
  {
    this.dataexame = param;
  }


  public java.sql.Date getDatalancamento()
  {
     return this.datalancamento;
  }
  public void setDatalancamento(java.sql.Date param)
  {
    this.datalancamento = param;
  }


  public String getEquivalencia()
  {
     return this.equivalencia;
  }
  public void setEquivalencia(String param)
  {
    this.equivalencia = param;
  }


  public String getNota()
  {
     return this.nota;
  }
  public void setNota(String param)
  {
    this.nota = param;
  }


  public String toString(){
    return  " [codigoAluno] " + codigoaluno + " [codigoAreaDisciplina] " + codigoareadisciplina + " [codigoInterno] " + codigointerno + " [creditos] " + creditos + " [dataExame] " + dataexame + " [dataLancamento] " + datalancamento + " [equivalencia] " + equivalencia + " [nota] " + nota;

  }
}

