
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_guia  
{
  private long anoguia;

  private long codigocursomestrado;

  private long codigointerno;

  private java.sql.Date dataemissao;

  private long entidadecontribuinte;

  private String entidademorada;

  private String entidadenome;

  private long numeroaluno;

  private long numeroguia;

  private byte[] observacoes;

  private String situacao;

  private String tipoaluno;

  private float total;

  public long getAnoguia()
  {
     return this.anoguia;
  }
  public void setAnoguia(long param)
  {
    this.anoguia = param;
  }


  public long getCodigocursomestrado()
  {
     return this.codigocursomestrado;
  }
  public void setCodigocursomestrado(long param)
  {
    this.codigocursomestrado = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public java.sql.Date getDataemissao()
  {
     return this.dataemissao;
  }
  public void setDataemissao(java.sql.Date param)
  {
    this.dataemissao = param;
  }


  public long getEntidadecontribuinte()
  {
     return this.entidadecontribuinte;
  }
  public void setEntidadecontribuinte(long param)
  {
    this.entidadecontribuinte = param;
  }


  public String getEntidademorada()
  {
     return this.entidademorada;
  }
  public void setEntidademorada(String param)
  {
    this.entidademorada = param;
  }


  public String getEntidadenome()
  {
     return this.entidadenome;
  }
  public void setEntidadenome(String param)
  {
    this.entidadenome = param;
  }


  public long getNumeroaluno()
  {
     return this.numeroaluno;
  }
  public void setNumeroaluno(long param)
  {
    this.numeroaluno = param;
  }


  public long getNumeroguia()
  {
     return this.numeroguia;
  }
  public void setNumeroguia(long param)
  {
    this.numeroguia = param;
  }


  public byte[] getObservacoes()
  {
     return this.observacoes;
  }
  public void setObservacoes(byte[] param)
  {
    this.observacoes = param;
  }


  public String getSituacao()
  {
     return this.situacao;
  }
  public void setSituacao(String param)
  {
    this.situacao = param;
  }


  public String getTipoaluno()
  {
     return this.tipoaluno;
  }
  public void setTipoaluno(String param)
  {
    this.tipoaluno = param;
  }


  public float getTotal()
  {
     return this.total;
  }
  public void setTotal(float param)
  {
    this.total = param;
  }


  public String toString(){
    return  " [anoGuia] " + anoguia + " [codigoCursoMestrado] " + codigocursomestrado + " [codigoInterno] " + codigointerno + " [dataEmissao] " + dataemissao + " [entidadeContribuinte] " + entidadecontribuinte + " [entidadeMorada] " + entidademorada + " [entidadeNome] " + entidadenome + " [numeroAluno] " + numeroaluno + " [numeroGuia] " + numeroguia + " [observacoes] " + observacoes + " [situacao] " + situacao + " [tipoAluno] " + tipoaluno + " [total] " + total;

  }
}

