
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_disc_area  
{
  private String anolectivo;

  private long codigoareacientifica;

  private long codigodisciplina;

  private long codigointerno;

  public String getAnolectivo()
  {
     return this.anolectivo;
  }
  public void setAnolectivo(String param)
  {
    this.anolectivo = param;
  }


  public long getCodigoareacientifica()
  {
     return this.codigoareacientifica;
  }
  public void setCodigoareacientifica(long param)
  {
    this.codigoareacientifica = param;
  }


  public long getCodigodisciplina()
  {
     return this.codigodisciplina;
  }
  public void setCodigodisciplina(long param)
  {
    this.codigodisciplina = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String toString(){
    return  " [anoLectivo] " + anolectivo + " [codigoAreaCientifica] " + codigoareacientifica + " [codigoDisciplina] " + codigodisciplina + " [codigoInterno] " + codigointerno;

  }
}

