
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_pagamento_guia  
{
  private long codigoguia;

  private long codigointerno;

  private java.sql.Date datapagamento;

  private float montante;

  private long numeroprestacao;

  public long getCodigoguia()
  {
     return this.codigoguia;
  }
  public void setCodigoguia(long param)
  {
    this.codigoguia = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public java.sql.Date getDatapagamento()
  {
     return this.datapagamento;
  }
  public void setDatapagamento(java.sql.Date param)
  {
    this.datapagamento = param;
  }


  public float getMontante()
  {
     return this.montante;
  }
  public void setMontante(float param)
  {
    this.montante = param;
  }


  public long getNumeroprestacao()
  {
     return this.numeroprestacao;
  }
  public void setNumeroprestacao(long param)
  {
    this.numeroprestacao = param;
  }


  public String toString(){
    return  " [codigoGuia] " + codigoguia + " [codigoInterno] " + codigointerno + " [dataPagamento] " + datapagamento + " [montante] " + montante + " [numeroPrestacao] " + numeroprestacao;

  }
}

