
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_curso_mestrado  
{
  private String anolectivo;

  private long codigointerno;

  private String nomemestrado;

  public String getAnolectivo()
  {
     return this.anolectivo;
  }
  public void setAnolectivo(String param)
  {
    this.anolectivo = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String getNomemestrado()
  {
     return this.nomemestrado;
  }
  public void setNomemestrado(String param)
  {
    this.nomemestrado = param;
  }


  public String toString(){
    return  " [anoLectivo] " + anolectivo + " [codigoInterno] " + codigointerno + " [nomeMestrado] " + nomemestrado;

  }
}

