
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_aluno_mestrado  
{
  private long anocandidatura;

  private long anolicenciatura;

  private long codigocursomestrado;

  private long codigointerno;

  private long codigopessoa;

  private String creditos;

  private String escolalicenciatura;

  private String especializacao;

  private Double media;

  private long numero;

  private String observacoes;

  public long getAnocandidatura()
  {
     return this.anocandidatura;
  }
  public void setAnocandidatura(long param)
  {
    this.anocandidatura = param;
  }


  public long getAnolicenciatura()
  {
     return this.anolicenciatura;
  }
  public void setAnolicenciatura(long param)
  {
    this.anolicenciatura = param;
  }


  public long getCodigocursomestrado()
  {
     return this.codigocursomestrado;
  }
  public void setCodigocursomestrado(long param)
  {
    this.codigocursomestrado = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public long getCodigopessoa()
  {
     return this.codigopessoa;
  }
  public void setCodigopessoa(long param)
  {
    this.codigopessoa = param;
  }


  public String getCreditos()
  {
     return this.creditos;
  }
  public void setCreditos(String param)
  {
    this.creditos = param;
  }


  public String getEscolalicenciatura()
  {
     return this.escolalicenciatura;
  }
  public void setEscolalicenciatura(String param)
  {
    this.escolalicenciatura = param;
  }


  public String getEspecializacao()
  {
     return this.especializacao;
  }
  public void setEspecializacao(String param)
  {
    this.especializacao = param;
  }


  public Double getMedia()
  {
     return this.media;
  }
  public void setMedia(Double param)
  {
    this.media = param;
  }


  public long getNumero()
  {
     return this.numero;
  }
  public void setNumero(long param)
  {
    this.numero = param;
  }


  public String getObservacoes()
  {
     return this.observacoes;
  }
  public void setObservacoes(String param)
  {
    this.observacoes = param;
  }


  public String toString(){
    return  " [anoCandidatura] " + anocandidatura + " [anoLicenciatura] " + anolicenciatura + " [codigoCursoMestrado] " + codigocursomestrado + " [codigoInterno] " + codigointerno + " [codigoPessoa] " + codigopessoa + " [creditos] " + creditos + " [escolaLicenciatura] " + escolalicenciatura + " [especializacao] " + especializacao + " [media] " + media + " [numero] " + numero + " [observacoes] " + observacoes;

  }
}

