
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_pessoa_cargo  
{
  private long codigocargo;

  private long codigointerno;

  private long codigopessoa;

  private java.sql.Date data;

  public long getCodigocargo()
  {
     return this.codigocargo;
  }
  public void setCodigocargo(long param)
  {
    this.codigocargo = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public long getCodigopessoa()
  {
     return this.codigopessoa;
  }
  public void setCodigopessoa(long param)
  {
    this.codigopessoa = param;
  }


  public java.sql.Date getData()
  {
     return this.data;
  }
  public void setData(java.sql.Date param)
  {
    this.data = param;
  }


  public String toString(){
    return  " [codigoCargo] " + codigocargo + " [codigoInterno] " + codigointerno + " [codigoPessoa] " + codigopessoa + " [data] " + data;

  }
}

