
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_candidato_situacao  
{
  private long codigocandidato;

  private long codigointerno;

  private long codigosituacao;

  private java.sql.Date data;

  private byte[] observacoes;

  private long valido;

  public long getCodigocandidato()
  {
     return this.codigocandidato;
  }
  public void setCodigocandidato(long param)
  {
    this.codigocandidato = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public long getCodigosituacao()
  {
     return this.codigosituacao;
  }
  public void setCodigosituacao(long param)
  {
    this.codigosituacao = param;
  }


  public java.sql.Date getData()
  {
     return this.data;
  }
  public void setData(java.sql.Date param)
  {
    this.data = param;
  }


  public byte[] getObservacoes()
  {
     return this.observacoes;
  }
  public void setObservacoes(byte[] param)
  {
    this.observacoes = param;
  }


  public long getValido()
  {
     return this.valido;
  }
  public void setValido(long param)
  {
    this.valido = param;
  }


  public String toString(){
    return  " [codigoCandidato] " + codigocandidato + " [codigoInterno] " + codigointerno + " [codigoSituacao] " + codigosituacao + " [data] " + data + " [observacoes] " + observacoes + " [valido] " + valido;

  }
}

