
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_cargo  
{
  private String cargonome;

  private long codigointerno;

  public String getCargonome()
  {
     return this.cargonome;
  }
  public void setCargonome(String param)
  {
    this.cargonome = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String toString(){
    return  " [cargoNome] " + cargonome + " [codigoInterno] " + codigointerno;

  }
}

