
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_area_cientifica  
{
  private String anolectivo;

  private long codigocursomestrado;

  private long codigointerno;

  private String nome;
  
  private Integer codigoInternoRamo;

  public String getAnolectivo()
  {
     return this.anolectivo;
  }
  public void setAnolectivo(String param)
  {
    this.anolectivo = param;
  }


  public long getCodigocursomestrado()
  {
     return this.codigocursomestrado;
  }
  public void setCodigocursomestrado(long param)
  {
    this.codigocursomestrado = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String getNome()
  {
     return this.nome;
  }
  public void setNome(String param)
  {
    this.nome = param;
  }


  public String toString(){
    return  " [anoLectivo] " + anolectivo + " [codigoCursoMestrado] " + codigocursomestrado + " [codigoInterno] " + codigointerno + " [nome] " + nome;

  }
/**
 * @return
 */
public Integer getCodigoInternoRamo() {
	return codigoInternoRamo;
}

/**
 * @param integer
 */
public void setCodigoInternoRamo(Integer integer) {
	codigoInternoRamo = integer;
}

}

