
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_guia_tabela  
{
  private long codigoguia;

  private long codigointerno;

  private long codigotabela;

  public long getCodigoguia()
  {
     return this.codigoguia;
  }
  public void setCodigoguia(long param)
  {
    this.codigoguia = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public long getCodigotabela()
  {
     return this.codigotabela;
  }
  public void setCodigotabela(long param)
  {
    this.codigotabela = param;
  }


  public String toString(){
    return  " [codigoGuia] " + codigoguia + " [codigoInterno] " + codigointerno + " [codigoTabela] " + codigotabela;

  }
}

