
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_tabela_precos  
{
  private long codigointerno;

  private String designacao;

  private float montante;

  private String tipo;

  private long valido;

  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String getDesignacao()
  {
     return this.designacao;
  }
  public void setDesignacao(String param)
  {
    this.designacao = param;
  }


  public float getMontante()
  {
     return this.montante;
  }
  public void setMontante(float param)
  {
    this.montante = param;
  }


  public String getTipo()
  {
     return this.tipo;
  }
  public void setTipo(String param)
  {
    this.tipo = param;
  }


  public long getValido()
  {
     return this.valido;
  }
  public void setValido(long param)
  {
    this.valido = param;
  }


  public String toString(){
    return  " [codigoInterno] " + codigointerno + " [designacao] " + designacao + " [montante] " + montante + " [tipo] " + tipo + " [valido] " + valido;

  }
}

