
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_situacao  
{
  private long codigointerno;

  private String situacao;

  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String getSituacao()
  {
     return this.situacao;
  }
  public void setSituacao(String param)
  {
    this.situacao = param;
  }


  public String toString(){
    return  " [codigoInterno] " + codigointerno + " [situacao] " + situacao;

  }
}

