
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.posgrad;


public class Posgrad_docente  
{
  private String bi;

  private String cat;

  private long codigointerno;

  private String cont;

  private String nome;

  private long numdec;

  public String getBi()
  {
     return this.bi;
  }
  public void setBi(String param)
  {
    this.bi = param;
  }


  public String getCat()
  {
     return this.cat;
  }
  public void setCat(String param)
  {
    this.cat = param;
  }


  public long getCodigointerno()
  {
     return this.codigointerno;
  }
  public void setCodigointerno(long param)
  {
    this.codigointerno = param;
  }


  public String getCont()
  {
     return this.cont;
  }
  public void setCont(String param)
  {
    this.cont = param;
  }


  public String getNome()
  {
     return this.nome;
  }
  public void setNome(String param)
  {
    this.nome = param;
  }


  public long getNumdec()
  {
     return this.numdec;
  }
  public void setNumdec(long param)
  {
    this.numdec = param;
  }


  public String toString(){
    return  " [bi] " + bi + " [cat] " + cat + " [codigoInterno] " + codigointerno + " [cont] " + cont + " [nome] " + nome + " [numdec] " + numdec;

  }
}

