// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch
// created at 30 Sep 2003 12:17:16 GMT

package middleware.middlewareDomain;


public class MWCurricularCourse extends MWDomainObject
{

  private String coursecode;
  private String coursename;
  private String universitycode;



  public String getCoursecode()
  {
     return this.coursecode;
  }
  public void setCoursecode(String param)
  {
    this.coursecode = param;
  }


  public String getCoursename()
  {
     return this.coursename;
  }
  public void setCoursename(String param)
  {
    this.coursename = param;
  }


  public String getUniversitycode()
  {
     return this.universitycode;
  }
  public void setUniversitycode(String param)
  {
    this.universitycode = param;
  }


  public String toString(){
    return  " [courseCode] " + coursecode + " [courseName] " + coursename + " [universityCode] " + universitycode;

  }
}
