// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch
// created at 30 Sep 2003 12:17:16 GMT

package middleware.middlewareDomain;


public class MwCurricularCourseScope  
{

  private Integer branchcode;
  private String coursecode;
  private Integer coursetype;
  private Float credits;
  private Integer curricularsemester;
  private Integer curricularyear;
  private Integer degreecode;
  private Integer executionyear;
  private Float labhours;
  private String orientation;
  private Float praticahours;
  private Float theoprathours;
  private Float theoreticalhours;



  public Integer getBranchcode()
  {
     return this.branchcode;
  }
  public void setBranchcode(Integer param)
  {
    this.branchcode = param;
  }


  public String getCoursecode()
  {
     return this.coursecode;
  }
  public void setCoursecode(String param)
  {
    this.coursecode = param;
  }


  public Integer getCoursetype()
  {
     return this.coursetype;
  }
  public void setCoursetype(Integer param)
  {
    this.coursetype = param;
  }


  public Float getCredits()
  {
     return this.credits;
  }
  public void setCredits(Float param)
  {
    this.credits = param;
  }


  public Integer getCurricularsemester()
  {
     return this.curricularsemester;
  }
  public void setCurricularsemester(Integer param)
  {
    this.curricularsemester = param;
  }


  public Integer getCurricularyear()
  {
     return this.curricularyear;
  }
  public void setCurricularyear(Integer param)
  {
    this.curricularyear = param;
  }


  public Integer getDegreecode()
  {
     return this.degreecode;
  }
  public void setDegreecode(Integer param)
  {
    this.degreecode = param;
  }


  public Integer getExecutionyear()
  {
     return this.executionyear;
  }
  public void setExecutionyear(Integer param)
  {
    this.executionyear = param;
  }


  public Float getLabhours()
  {
     return this.labhours;
  }
  public void setLabhours(Float param)
  {
    this.labhours = param;
  }


  public String getOrientation()
  {
     return this.orientation;
  }
  public void setOrientation(String param)
  {
    this.orientation = param;
  }


  public Float getPraticahours()
  {
     return this.praticahours;
  }
  public void setPraticahours(Float param)
  {
    this.praticahours = param;
  }


  public Float getTheoprathours()
  {
     return this.theoprathours;
  }
  public void setTheoprathours(Float param)
  {
    this.theoprathours = param;
  }


  public Float getTheoreticalhours()
  {
     return this.theoreticalhours;
  }
  public void setTheoreticalhours(Float param)
  {
    this.theoreticalhours = param;
  }


  public String toString(){
    return  " [branchCode] " + branchcode + " [courseCode] " + coursecode + " [courseType] " + coursetype + " [credits] " + credits + " [curricularSemester] " + curricularsemester + " [curricularYear] " + curricularyear + " [degreeCode] " + degreecode + " [executionYear] " + executionyear + " [labHours] " + labhours + " [orientation] " + orientation + " [praticaHours] " + praticahours + " [theoPratHours] " + theoprathours + " [theoreticalHours] " + theoreticalhours;

  }
}
