// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch
// created at 30 Sep 2003 12:17:16 GMT

package middleware.middlewareDomain;


public class MwEnrolment  
{

  private Integer branchcode;
  private String coursecode;
  private Integer curricularcoursesemester;
  private Integer curricularcourseyear;
  private Integer degreecode;
  private Integer enrolmentyear;
  private java.sql.Date examdate;
  private String grade;
  private Integer idinternal;
  private Integer number;
  private String remarks;
  private Integer season;
  private Integer teachernumber;
  private String universitycode;



  public Integer getBranchcode()
  {
     return this.branchcode;
  }
  public void setBranchcode(Integer param)
  {
    this.branchcode = param;
  }



  public Integer getCurricularcoursesemester()
  {
     return this.curricularcoursesemester;
  }
  public void setCurricularcoursesemester(Integer param)
  {
    this.curricularcoursesemester = param;
  }


  public Integer getCurricularcourseyear()
  {
     return this.curricularcourseyear;
  }
  public void setCurricularcourseyear(Integer param)
  {
    this.curricularcourseyear = param;
  }


  public Integer getDegreecode()
  {
     return this.degreecode;
  }
  public void setDegreecode(Integer param)
  {
    this.degreecode = param;
  }


  public Integer getEnrolmentyear()
  {
     return this.enrolmentyear;
  }
  public void setEnrolmentyear(Integer param)
  {
    this.enrolmentyear = param;
  }


  public java.sql.Date getExamdate()
  {
     return this.examdate;
  }
  public void setExamdate(java.sql.Date param)
  {
    this.examdate = param;
  }


  public String getGrade()
  {
     return this.grade;
  }
  public void setGrade(String param)
  {
    this.grade = param;
  }


  public Integer getIdinternal()
  {
     return this.idinternal;
  }
  public void setIdinternal(Integer param)
  {
    this.idinternal = param;
  }


  public Integer getNumber()
  {
     return this.number;
  }
  public void setNumber(Integer param)
  {
    this.number = param;
  }


  public String getRemarks()
  {
     return this.remarks;
  }
  public void setRemarks(String param)
  {
    this.remarks = param;
  }


  public Integer getSeason()
  {
     return this.season;
  }
  public void setSeason(Integer param)
  {
    this.season = param;
  }


  public Integer getTeachernumber()
  {
     return this.teachernumber;
  }
  public void setTeachernumber(Integer param)
  {
    this.teachernumber = param;
  }


  public String getUniversitycode()
  {
     return this.universitycode;
  }
  public void setUniversitycode(String param)
  {
    this.universitycode = param;
  }


  public String toString(){
    return  " [branchCode] " + branchcode + " [courseCode] " + coursecode + " [curricularCourseSemester] " + curricularcoursesemester + " [curricularCourseYear] " + curricularcourseyear + " [degreeCode] " + degreecode + " [enrolmentYear] " + enrolmentyear + " [examDate] " + examdate + " [grade] " + grade + " [idinternal] " + idinternal + " [number] " + number + " [remarks] " + remarks + " [season] " + season + " [teacherNumber] " + teachernumber + " [universityCode] " + universitycode;

  }
  
	/**
	 * @return
	 */
	public String getCoursecode() {
		return coursecode;
	}
	
	/**
	 * @param coursecode
	 */
	public void setCoursecode(String coursecode) {
		this.coursecode = coursecode;
	}

}
