// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch
// created at 18 Sep 2003 13:25:08 GMT

package middleware.middlewareDomain;

public class MWPessoa extends MWDomainObject
{

	private String address;
	private String addressAreaCode;
	private Integer contributornumber;
	private Integer countrycode;
	private java.sql.Date dateofbirth;
	private String districtofaddress;
	private String districtofbirth;
	private java.sql.Date documentiddate;
	private String documentidnumber;
	private String documentidplace;
	private String documentidtype;
	private java.sql.Date documentidvalidation;
	private String email;
	private String fathername;
	private String financialrepcode;
	private String fiscalcode;
	private String homepage;
	private String maritalstatus;
	private String mobilephone;
	private String mothername;
	private String municipalityofaddress;
	private String municipalityofbirth;
	private String name;
	private String parishofaddress;
	private String parishofbirth;
	private String password;
	private String phone;
	private String sex;
	private String username;
	private String zipcode;
	private String zipAreaCode;
	private String job;

	public String getAddress() {
		return this.address;
	}
	public void setAddress(String param) {
		this.address = param;
	}

	public String getAddressAreaCode() {
		return this.addressAreaCode;
	}
	public void setAddressAreaCode(String param) {
		this.addressAreaCode = param;
	}

	public Integer getContributornumber() {
		return this.contributornumber;
	}
	public void setContributornumber(Integer param) {
		this.contributornumber = param;
	}

	public Integer getCountrycode() {
		return this.countrycode;
	}
	public void setCountrycode(Integer param) {
		this.countrycode = param;
	}

	public java.sql.Date getDateofbirth() {
		return this.dateofbirth;
	}
	public void setDateofbirth(java.sql.Date param) {
		this.dateofbirth = param;
	}

	public String getDistrictofaddress() {
		return this.districtofaddress;
	}
	public void setDistrictofaddress(String param) {
		this.districtofaddress = param;
	}

	public String getDistrictofbirth() {
		return this.districtofbirth;
	}
	public void setDistrictofbirth(String param) {
		this.districtofbirth = param;
	}

	public java.sql.Date getDocumentiddate() {
		return this.documentiddate;
	}
	public void setDocumentiddate(java.sql.Date param) {
		this.documentiddate = param;
	}

	public String getDocumentidnumber() {
		return this.documentidnumber;
	}
	public void setDocumentidnumber(String param) {
		this.documentidnumber = param;
	}

	public String getDocumentidplace() {
		return this.documentidplace;
	}
	public void setDocumentidplace(String param) {
		this.documentidplace = param;
	}

	public String getDocumentidtype() {
		return this.documentidtype;
	}
	public void setDocumentidtype(String param) {
		this.documentidtype = param;
	}

	public java.sql.Date getDocumentidvalidation() {
		return this.documentidvalidation;
	}
	public void setDocumentidvalidation(java.sql.Date param) {
		this.documentidvalidation = param;
	}

	public String getEmail() {
		return this.email;
	}
	public void setEmail(String param) {
		this.email = param;
	}

	public String getFathername() {
		return this.fathername;
	}
	public void setFathername(String param) {
		this.fathername = param;
	}

	public String getFinancialrepcode() {
		return this.financialrepcode;
	}
	public void setFinancialrepcode(String param) {
		this.financialrepcode = param;
	}

	public String getFiscalcode() {
		return this.fiscalcode;
	}
	public void setFiscalcode(String param) {
		this.fiscalcode = param;
	}

	public String getHomepage() {
		return this.homepage;
	}
	public void setHomepage(String param) {
		this.homepage = param;
	}

	public String getMaritalstatus() {
		return this.maritalstatus;
	}
	public void setMaritalstatus(String param) {
		this.maritalstatus = param;
	}

	public String getMobilephone() {
		return this.mobilephone;
	}
	public void setMobilephone(String param) {
		this.mobilephone = param;
	}

	public String getMothername() {
		return this.mothername;
	}
	public void setMothername(String param) {
		this.mothername = param;
	}

	public String getMunicipalityofaddress() {
		return this.municipalityofaddress;
	}
	public void setMunicipalityofaddress(String param) {
		this.municipalityofaddress = param;
	}

	public String getMunicipalityofbirth() {
		return this.municipalityofbirth;
	}
	public void setMunicipalityofbirth(String param) {
		this.municipalityofbirth = param;
	}

	public String getName() {
		return this.name;
	}
	public void setName(String param) {
		this.name = param;
	}

	public String getParishofaddress() {
		return this.parishofaddress;
	}
	public void setParishofaddress(String param) {
		this.parishofaddress = param;
	}

	public String getParishofbirth() {
		return this.parishofbirth;
	}
	public void setParishofbirth(String param) {
		this.parishofbirth = param;
	}

	public String getPassword() {
		return this.password;
	}
	public void setPassword(String param) {
		this.password = param;
	}

	public String getPhone() {
		return this.phone;
	}
	public void setPhone(String param) {
		this.phone = param;
	}

	public String getSex() {
		return this.sex;
	}
	public void setSex(String param) {
		this.sex = param;
	}

	public String getUsername() {
		return this.username;
	}
	public void setUsername(String param) {
		this.username = param;
	}

	public String getZipcode() {
		return this.zipcode;
	}
	public void setZipcode(String param) {
		this.zipcode = param;
	}

	public String toString() {
		return " [address] "
			+ address
			+ " [areaCode] "
			+ addressAreaCode
			+ " [contributorNumber] "
			+ contributornumber
			+ " [countryCode] "
			+ countrycode
			+ " [dateOfBirth] "
			+ dateofbirth
			+ " [districtOfAddress] "
			+ districtofaddress
			+ " [districtOfBirth] "
			+ districtofbirth
			+ " [documentIdDate] "
			+ documentiddate
			+ " [documentIdNumber] "
			+ documentidnumber
			+ " [documentIdPlace] "
			+ documentidplace
			+ " [documentIdType] "
			+ documentidtype
			+ " [documentIdValidation] "
			+ documentidvalidation
			+ " [email] "
			+ email
			+ " [fatherName] "
			+ fathername
			+ " [financialRepCode] "
			+ financialrepcode
			+ " [fiscalCode] "
			+ fiscalcode
			+ " [homePage] "
			+ homepage
			+ " [maritalStatus] "
			+ maritalstatus
			+ " [mobilePhone] "
			+ mobilephone
			+ " [motherName] "
			+ mothername
			+ " [municipalityOfAddress] "
			+ municipalityofaddress
			+ " [municipalityOfBirth] "
			+ municipalityofbirth
			+ " [name] "
			+ name
			+ " [parishOfAddress] "
			+ parishofaddress
			+ " [parishOfBirth] "
			+ parishofbirth
			+ " [password] "
			+ password
			+ " [phone] "
			+ phone
			+ " [sex] "
			+ sex
			+ " [username] "
			+ username
			+ " [zipCode] "
			+ zipcode;

	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getZipAreaCode() {
		return zipAreaCode;
	}

	public void setZipAreaCode(String zipAreaCode) {
		this.zipAreaCode = zipAreaCode;
	}
}
