update EVENT set EVENT_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDIDACY' where EVENT_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDICAY';
update EVENT set EVENT_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDIDACY' where EVENT_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDICAY';

update POSTING_RULE set EVENT_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDIDACY' where EVENT_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDICAY';
update POSTING_RULE set EVENT_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDIDACY' where EVENT_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDICAY';

update POSTING_RULE set ENTRY_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDIDACY_FEE' where ENTRY_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDICAY_FEE';
update POSTING_RULE set ENTRY_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDIDACY_FEE' where ENTRY_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDICAY_FEE';

update ENTRY set ENTRY_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDIDACY_FEE' where ENTRY_TYPE='DEGREE_CHANGE_INDIVIDUAL_CANDICAY_FEE';
update ENTRY set ENTRY_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDIDACY_FEE' where ENTRY_TYPE='DEGREE_TRANSFER_INDIVIDUAL_CANDICAY_FEE';


