#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

echo Using database: $1
echo Enter password for $2:
read -s password

# Alter Student Table
mysql -u$2 -f $1 < alterTableStudent.sql
mysql -u$2 -f $1 < alterTableExecutionPeriod.sql
