#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Rename table Receipt Version to ReceiptPrintVersion" renameTableReceiptVersion.sql
execute "Add column whenCreated to Receipt table" alterTableReceiptAddColumn.sql
executeWithTempFile "Update whenCreated date to existing Receipts" updateTableReceipt.sql
execute "Alter table whenCreated to Not Null" alterTableReceiptAlterColumn.sql
execute "Changing Accounting Transaction Table" AlterTableAccountingTransaction.sql
execute "Changing Accounting Entry Table" AlterTableAccountingEntry.sql
execute "Adding Index to accounting tables" AddIndexesToAccountingTables.sql
