drop table MONTH_CLOSURE;
CREATE TABLE `CLOSED_MONTH` (
  `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
  `CLOSED_YEAR_MONTH` VARCHAR(24) NOT NULL,
  `CLOSED_FOR_BALANCE` TINYINT(1) DEFAULT NULL,
  `CLOSED_FOR_EXTRA_WORK` TINYINT(1) DEFAULT NULL,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `CLOSED_YEAR_MONTH` (`CLOSED_YEAR_MONTH`)
) ENGINE=InnoDB;

CREATE TABLE `ASSIDUOUSNESS_CLOSED_MONTH` (
  `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
  `KEY_ASSIDUOUSNESS` int(11) unsigned NOT NULL,
  `KEY_CLOSED_MONTH` int(11) unsigned NOT NULL,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  UNIQUE KEY `u1` (`KEY_ASSIDUOUSNESS`, `KEY_CLOSED_MONTH`)
) ENGINE=InnoDB;