alter table `PARTY` add column `OID_PERSON_PROFESSIONAL_DATA` bigint(20);


create table `PERSON_CONTRACT_SITUATION` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `BEGIN_DATE` text,
  `CONTRACT_SITUATION_GIAF_ID` longtext,
  `CREATION_DATE` timestamp NULL default NULL,
  `END_DATE` text,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_CONTRACT_SITUATION` bigint(20),
  `OID_PERSON_PROFESSIONAL_DATA` bigint(20),
  `OID_PROFESSIONAL_CATEGORY` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `PROFESSIONAL_CATEGORY_GIAF_ID` longtext,
  `STEP` longtext,
  primary key (ID_INTERNAL),
) type=InnoDB, character set latin1 ;

create table `PERSON_FUNCTIONS_ACCUMULATION` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `BEGIN_DATE` text,
  `CREATION_DATE` timestamp NULL default NULL,
  `END_DATE` text,
  `FUNCTIONS_ACCUMULATION_GIAF_ID` longtext,
  `HOURS` longtext,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_FUNCTIONS_ACCUMULATION` bigint(20),
  `OID_PERSON_PROFESSIONAL_DATA` bigint(20),
  `OID_PROFESSIONAL_REGIME` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `PROFESSIONAL_REGIME_GIAF_ID` longtext,
  primary key (ID_INTERNAL),
) type=InnoDB, character set latin1 ;

create table `PERSON_PROFESSIONAL_CATEGORY` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `BEGIN_DATE` text,
  `CREATION_DATE` timestamp NULL default NULL,
  `END_DATE` text,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `LEVEL` longtext,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_PERSON_PROFESSIONAL_DATA` bigint(20),
  `OID_PROFESSIONAL_CATEGORY` bigint(20),
  `OID_PROFESSIONAL_REGIME` bigint(20),
  `OID_PROFESSIONAL_RELATION` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `PROFESSIONAL_CATEGORY_GIAF_ID` longtext,
  `PROFESSIONAL_REGIME_GIAF_ID` longtext,
  `PROFESSIONAL_RELATION_GIAF_ID` longtext,
  `STEP` longtext,
  primary key (ID_INTERNAL),
  index (OID),
) type=InnoDB, character set latin1 ;

create table `PERSON_PROFESSIONAL_CONTRACT` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `BEGIN_DATE` text,
  `CONTRACT_SITUATION_GIAF_ID` longtext,
  `CREATION_DATE` timestamp NULL default NULL,
  `END_DATE` text,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_CONTRACT_SITUATION` bigint(20),
  `OID_PERSON_PROFESSIONAL_DATA` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  primary key (ID_INTERNAL),
  index (OID),
) type=InnoDB, character set latin1 ;

create table `PERSON_PROFESSIONAL_DATA` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `CONTRACT_SITUATION_DATE` text,
  `CONTRACT_SITUATION_GIAF_ID` longtext,
  `CREATION_DATE` timestamp NULL default NULL,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_CONTRACT_SITUATION` bigint(20),
  `OID_PERSON` bigint(20),
  `OID_PROFESSIONAL_CATEGORY` bigint(20),
  `OID_PROFESSIONAL_CONTRACT_TYPE` bigint(20),
  `OID_PROFESSIONAL_REGIME` bigint(20),
  `OID_PROFESSIONAL_RELATION` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `PROFESSIONAL_CATEGORY_DATE` text,
  `PROFESSIONAL_CATEGORY_GIAF_ID` longtext,
  `PROFESSIONAL_CONTRACT_TYPE_GIAF_ID` longtext,
  `PROFESSIONAL_REGIME_DATE` text,
  `PROFESSIONAL_REGIME_GIAF_ID` longtext,
  `PROFESSIONAL_RELATION_DATE` text,
  `PROFESSIONAL_RELATION_GIAF_ID` longtext,
  primary key (ID_INTERNAL),
) type=InnoDB, character set latin1 ;

create table `PERSON_PROFESSIONAL_EXEMPTION` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `BEGIN_DATE` text,
  `CREATION_DATE` timestamp NULL default NULL,
  `END_DATE` text,
  `GIAF_COUNTRY_NAME` longtext,
  `GRANT_OWNER_EQUIVALENT_GIAF_ID` longtext,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `LOCAL` longtext,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `MOTIVE` longtext,
  `OJB_CONCRETE_CLASS` varchar(255) default NULL,
  `OID` bigint(20),
  `OID_COUNTRY` bigint(20),
  `OID_GRANT_OWNER_EQUIVALENT` bigint(20),
  `OID_PERSON_PROFESSIONAL_DATA` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `OID_SERVICE_EXEMPTION` bigint(20),
  `SERVICE_EXEMPTION_GIAF_ID` longtext,
  primary key (ID_INTERNAL),
  index (OID),
) type=InnoDB, character set latin1 ;

create table `PERSON_PROFESSIONAL_REGIME` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `BEGIN_DATE` text,
  `CREATION_DATE` timestamp NULL default NULL,
  `END_DATE` text,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_PERSON_PROFESSIONAL_DATA` bigint(20),
  `OID_PROFESSIONAL_REGIME` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `PROFESSIONAL_REGIME_GIAF_ID` longtext,
  primary key (ID_INTERNAL),
  index (OID),
) type=InnoDB, character set latin1 ;

create table `PERSON_PROFESSIONAL_RELATION` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `BEGIN_DATE` text,
  `CREATION_DATE` timestamp NULL default NULL,
  `END_DATE` text,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_PERSON_PROFESSIONAL_DATA` bigint(20),
  `OID_PROFESSIONAL_CATEGORY` bigint(20),
  `OID_PROFESSIONAL_RELATION` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `PROFESSIONAL_CATEGORY_GIAF_ID` longtext,
  `PROFESSIONAL_RELATION_GIAF_ID` longtext,
  primary key (ID_INTERNAL),
  index (OID),
) type=InnoDB, character set latin1 ;

