
CREATE TABLE `EXTERNAL_REGISTRATION_DATA` (
  `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
  `KEY_INSTITUTION` int(11),
  `COORDINATOR_NAME` varchar(255),
  `KEY_REGISTRATION` int(11) NOT NULL, 
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`)
) ENGINE=InnoDB;

alter table REGISTRATION add column KEY_EXTERNAL_REGISTRATION_DATA int(11);