UPDATE STUDENT_CURRICULAR_PLAN SET STUDENT_CURRICULAR_PLAN.SPECIALIZATION = "STUDENT_CURRICULAR_PLAN_MASTER_DEGREE" WHERE STUDENT_CURRICULAR_PLAN.SPECIALIZATION = "MASTER_DEGREE";
UPDATE STUDENT_CURRICULAR_PLAN SET STUDENT_CURRICULAR_PLAN.SPECIALIZATION = "STUDENT_CURRICULAR_PLAN_INTEGRATED_MASTER_DEGREE" WHERE STUDENT_CURRICULAR_PLAN.SPECIALIZATION = "INTEGRATED_MASTER_DEGREE";
UPDATE STUDENT_CURRICULAR_PLAN SET STUDENT_CURRICULAR_PLAN.SPECIALIZATION = "STUDENT_CURRICULAR_PLAN_SPECIALIZATION" WHERE STUDENT_CURRICULAR_PLAN.SPECIALIZATION = "SPECIALIZATION";
