ALTER TABLE `SITE`
	DROP COLUMN `SHOW_SECTION_TEACHERS`,
	DROP COLUMN `SHOW_SECTION_EMPLOYEES`,
	DROP COLUMN `SHOW_SECTION_COURSES`,
	DROP COLUMN `SHOW_SECTION_DEGREES`,
	DROP COLUMN `SHOW_RESEARCH_MEMBERS`;
