create table SUPPORT_REQUEST (
  ID_INTERNAL int(11) not null auto_increment,
  KEY_ROOT_DOMAIN_OBJECT int(11) not null,
  KEY_REQUESTER int(11) NULL,
  KEY_REQUEST_CONTEXT int(11) NULL,
  KEY_ERROR_LOG int(11) NULL,
  REQUEST_PRIORITY VARCHAR(100) not null,
  RESPONSE_EMAIL VARCHAR(100) NULL,
  SUBJECT VARCHAR(100) NULL,
  MESSAGE text NULL,
  REQUEST_TIME DATETIME not null,
  OJB_CONCRETE_CLASS text,
  PRIMARY KEY (ID_INTERNAL),
  KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT)
) type=InnoDB;


alter table ERROR_LOG add column KEY_SUPPORT_EXCEPTION int(11) default NULL;