update PERSON set PERSON.KEY_COUNTRY = 16 where PERSON.NATIONALITY = 'REPUBLICA FEDERAL DA ALEMANHA';
update PERSON set PERSON.KEY_COUNTRY = 150 where PERSON.NATIONALITY = 'REPUBLICA DA MACEDONIA';
update PERSON set PERSON.KEY_COUNTRY = 123 where PERSON.NATIONALITY = 'REPUBLICA DA ESLOVENIA';
update PERSON set PERSON.KEY_COUNTRY = 53 where PERSON.NATIONALITY = 'REPUBLICA DA CHECOSLOVÁQUIA';
update PERSON set PERSON.KEY_COUNTRY = 10 where PERSON.NATIONALITY = 'Espanhol';
update PERSON set PERSON.KEY_COUNTRY = 150 where PERSON.NATIONALITY = 'Eslovaco';
update PERSON set PERSON.KEY_COUNTRY = 38 where PERSON.NATIONALITY = 'U.S.A.';
update PERSON set PERSON.KEY_COUNTRY = 17 where PERSON.NATIONALITY = 'British Citizen';
update PERSON set PERSON.KEY_COUNTRY = 24 where PERSON.NATIONALITY = 'Russo';
update PERSON set PERSON.KEY_COUNTRY = 57 where PERSON.NATIONALITY = 'Indiano';
update PERSON set PERSON.KEY_COUNTRY = 63 where PERSON.NATIONALITY = 'UKR';
update PERSON set PERSON.KEY_COUNTRY = 53 where PERSON.NATIONALITY = 'Czech';
update PERSON set PERSON.KEY_COUNTRY = 151 where PERSON.NATIONALITY = 'Correia do Sul';

update PERSON set PERSON.KEY_COUNTRY = 1 where PERSON.NATIONALITY is null OR PERSON.NATIONALITY = '' OR PERSON.NATIONALITY = 'PORTUGUES' OR PERSON.NATIONALITY = '0' OR PERSON.NATIONALITY = 'Portuguesa' OR PERSON.NATIONALITY = 'PORTUGUES' OR PERSON.NATIONALITY = 'Portufguesa' OR PERSON.NATIONALITY = 'Portugal' OR PERSON.NATIONALITY = 'PORTO' OR PERSON.NATIONALITY = 'Poruuguesa' OR PERSON.NATIONALITY = 'S. Lourenço'; 

select concat('update PERSON set PERSON.KEY_COUNTRY = ', COUNTRY.ID_INTERNAL,' where PERSON.KEY_COUNTRY is null and (PERSON.NATIONALITY like \'',  COUNTRY.NAME, '\' or PERSON.NATIONALITY like \'', COUNTRY.NATIONALITY, '\');' )  as "" from COUNTRY; 