CREATE TABLE REGISTRATION_STATE (
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  STATE_DATE DATETIME,  
  REMARKS varchar(255),  
  KEY_RESPONSIBLE_PERSON int(11) unsigned NOT NULL default '0',
  KEY_REGISTRATION int(11) unsigned NOT NULL default '0',   
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  OJB_CONCRETE_CLASS VARCHAR(255) not null,
  PRIMARY KEY  (ID_INTERNAL),
  KEY (KEY_REGISTRATION),
  KEY (KEY_RESPONSIBLE_PERSON),
  KEY (KEY_ROOT_DOMAIN_OBJECT)
) ENGINE=InnoDB;
