CREATE TABLE DEPARTMENT_DEGREE (
  KEY_DEPARTMENT int(11) NOT NULL default '0',
  KEY_DEGREE int(11) NOT NULL default '0',
  UNIQUE KEY (KEY_DEPARTMENT, KEY_DEGREE),
  KEY (KEY_DEPARTMENT),
  KEY (KEY_DEGREE)
) type=InnoDB;
