UPDATE DEGREE_MODULE SET DEGREE_MODULE.OJB_CONCRETE_CLASS = "net.sourceforge.fenixedu.domain.degreeStructure.CycleCourseGroup"  WHERE DEGREE_MODULE.NAME LIKE "%Ciclo" AND DEGREE_MODULE.OJB_CONCRETE_CLASS LIKE "%.CourseGroup";

UPDATE DEGREE_MODULE SET DEGREE_MODULE.CYCLE_TYPE = "FIRST_CYCLE" WHERE DEGREE_MODULE.OJB_CONCRETE_CLASS = "net.sourceforge.fenixedu.domain.degreeStructure.CycleCourseGroup" AND DEGREE_MODULE.NAME = "1º Ciclo";

UPDATE DEGREE_MODULE SET DEGREE_MODULE.CYCLE_TYPE = "SECOND_CYCLE" WHERE DEGREE_MODULE.OJB_CONCRETE_CLASS = "net.sourceforge.fenixedu.domain.degreeStructure.CycleCourseGroup" AND DEGREE_MODULE.NAME = "2º Ciclo";