CREATE TABLE `DOMAIN_ROOT` (
  `OID` bigint(20) unsigned DEFAULT NULL,
  `OID_SCHEDULER_SYSTEM` bigint(20) unsigned DEFAULT NULL,
  `OID_DOMAIN_META_OBJECT` bigint(20) unsigned DEFAULT NULL,
  `OID_REMOTE_SYSTEM` bigint(20) unsigned DEFAULT NULL,
  `OID_DOMAIN_FENIX_FRAMEWORK_ROOT` bigint(20) unsigned DEFAULT NULL,
  `OID_ROOT_DOMAIN_OBJECT` bigint(20) unsigned DEFAULT NULL,
  `ID_INTERNAL` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_INTERNAL`),
  KEY `OID` (`OID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `DOMAIN_ROOT` VALUES (1,6313601925122,NULL,5484673236993,6880537608193,1035087118337,1);


RENAME TABLE FF$ABSTRACT_NODE TO ABSTRACT_NODE;
RENAME TABLE FF$B_PLUS_TREE TO B_PLUS_TREE;
RENAME TABLE FF$DEPENDED_DOMAIN_META_OBJECTS_DEPENDING_DEPENDENCE_RECORDS TO DEPENDED_DOMAIN_META_OBJECTS_DEPENDING_DEPENDENCE_RECORDS;
RENAME TABLE FF$DOMAIN_CONSISTENCY_PREDICATE TO DOMAIN_CONSISTENCY_PREDICATE;
RENAME TABLE FF$DOMAIN_DEPENDENCE_RECORD TO DOMAIN_DEPENDENCE_RECORD;
RENAME TABLE FF$DOMAIN_FENIX_FRAMEWORK_ROOT TO DOMAIN_FENIX_FRAMEWORK_ROOT;
RENAME TABLE FF$DOMAIN_META_CLASS TO DOMAIN_META_CLASS;
RENAME TABLE FF$DOMAIN_META_OBJECT TO DOMAIN_META_OBJECT;

UPDATE FF$DOMAIN_CLASS_INFO SET DOMAIN_CLASS_NAME = REPLACE(DOMAIN_CLASS_NAME, 'pt.ist.fenixframework.pstm', 'pt.ist.fenixframework');

alter table DOMAIN_META_CLASS change FINALIZED INITIALIZED tinyint(1);
alter table DOMAIN_CONSISTENCY_PREDICATE change FINALIZED INITIALIZED tinyint(1);

CREATE TABLE FF$SERVER_ID_LEASE(
        ID int not null,
        SERVER varchar(255) not null default '',
        EXPIRATION timestamp null,
        UNIQUE KEY U1 (ID)
) ENGINE=InnoDB;

alter table `ROOT_DOMAIN_OBJECT` add `OID_DOMAIN_ROOT` bigint unsigned, add index (OID_DOMAIN_ROOT);
update `ROOT_DOMAIN_OBJECT` set `OID_DOMAIN_ROOT` = 1;

alter table `REMOTE_SYSTEM` add `OID_DOMAIN_ROOT` bigint unsigned;
update `REMOTE_SYSTEM` set `OID_DOMAIN_ROOT` = 1;

create table `B_PLUS_TREE_ARRAY` (`OID` bigint unsigned, `OID_DOMAIN_META_OBJECT` bigint unsigned, `OID_ROOT` bigint unsigned, `ID_INTERNAL` int(11) NOT NULL auto_increment, primary key (ID_INTERNAL), index (OID)) ENGINE=InnoDB, character set utf8;
alter table `B_PLUS_TREE` add `OID_TREE_DATA` bigint unsigned;
alter table `ABSTRACT_NODE` add `SUB_NODES_BY_OID` text, add `DOMAIN_ENTRIES` text;

alter table `SCHEDULER_SYSTEM` add `OID_DOMAIN_ROOT` bigint unsigned;
update `SCHEDULER_SYSTEM` set `OID_DOMAIN_ROOT` = 1;

alter table `DOMAIN_FENIX_FRAMEWORK_ROOT` add `OID_DOMAIN_ROOT` bigint unsigned;
update `DOMAIN_FENIX_FRAMEWORK_ROOT` set `OID_DOMAIN_ROOT` = 1;

create table `ABSTRACT_NODE_ARRAY` (`OID` bigint unsigned, `SUB_NODES` blob, `OID_NEXT` bigint unsigned, `OID_DOMAIN_META_OBJECT` bigint unsigned, `ENTRIES` blob, `OID_PARENT` bigint unsigned, `OID_PREVIOUS` bigint unsigned, `ID_INTERNAL` int(11) NOT NULL auto_increment, primary key (ID_INTERNAL), index (OID), index (OID_PARENT)) ENGINE=InnoDB, character set utf8;
create table `DOMAIN_B_PLUS_TREE_DATA` (`OID` bigint unsigned, `OID_DOMAIN_META_OBJECT` bigint unsigned, `OID_TREE` bigint unsigned, `SIZE` int(11), `ID_INTERNAL` int(11) NOT NULL auto_increment, primary key (ID_INTERNAL), index (OID)) ENGINE=InnoDB, character set utf8;
