alter table `FILE` add `OID_PHD_STUDENT_REINGRESSION_REQUEST` bigint unsigned;
alter table `ACADEMIC_SERVICE_REQUEST` add `OID_PHD_STUDENT_REINGRESSION_REQUEST_DOCUMENT` bigint unsigned, add `OID_PHD_INDIVIDUAL_PROGRAM_PROCESS` bigint unsigned, add index (OID_PHD_INDIVIDUAL_PROGRAM_PROCESS);
