create table EXAM_DATE_CERTIFICATE_REQUEST_ENROLMENT (
	KEY_ENROLMENT int(11) not null, 
	KEY_EXAM_DATE_CERTIFICATE_REQUEST int(11) not null,  
	primary key (KEY_ENROLMENT, KEY_EXAM_DATE_CERTIFICATE_REQUEST), 
	key(KEY_ENROLMENT), 
	key(KEY_EXAM_DATE_CERTIFICATE_REQUEST)
) type=InnoDB;
