ALTER TABLE DEGREE ADD GRADE_SCALE VARCHAR(255) DEFAULT NULL;
ALTER TABLE DEGREE_CURRICULAR_PLAN ADD GRADE_SCALE VARCHAR(255) DEFAULT NULL;
ALTER TABLE DEGREE_MODULE ADD GRADE_SCALE VARCHAR(255) DEFAULT NULL;