--  SQL file representing changes to the functionalities model
--  Generated at Tue Oct 3 14:23:25 WEST 2006
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 175 UUID: 'fc0ecef4-7163-497e-b032-3131c00f8249'
UPDATE `FUNCTIONALITY` AS own SET own.`ORDER_IN_MODULE` = 2 WHERE own.`UUID` = 'fc0ecef4-7163-497e-b032-3131c00f8249';

--  ID: 176 UUID: '90591da3-2f93-480a-80a7-e80104af05d3'
UPDATE `FUNCTIONALITY` AS own SET own.`ORDER_IN_MODULE` = 3 WHERE own.`UUID` = '90591da3-2f93-480a-80a7-e80104af05d3';

--  ID: 177 UUID: '7529e22b-4f3c-4ef5-b698-b2fb77217c3f'
UPDATE `FUNCTIONALITY` AS own SET own.`ORDER_IN_MODULE` = 4 WHERE own.`UUID` = '7529e22b-4f3c-4ef5-b698-b2fb77217c3f';

-- 
--  Inserting new functionalities
-- 

--  ID: 278 UUID: '71063574-238d-4018-b4df-9b3408c14f62'
INSERT INTO `FUNCTIONALITY` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`) SELECT '71063574-238d-4018-b4df-9b3408c14f62', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt19:Linguagem de Grupos', NULL, NULL, '/groupLanguage.do', NULL, 1, 1, NULL, 1, 1, 0, 1 FROM `FUNCTIONALITY` WHERE `UUID` = '1b3a09b7-e04f-47b7-8298-bb5ffeff489d';

COMMIT;
