alter table ACCOUNT ADD INDEX (KEY_ROOT_DOMAIN_OBJECT);
alter table ACCOUNT ADD INDEX (KEY_PARTY);

alter table ACCOUNTING_TRANSACTION ADD INDEX (KEY_EVENT);
alter table ACCOUNTING_TRANSACTION ADD INDEX (KEY_RESPONSIBLE_USER);
alter table ACCOUNTING_TRANSACTION ADD INDEX (KEY_ROOT_DOMAIN_OBJECT);

alter table ACCOUNTING_ENTRY ADD INDEX (KEY_ROOT_DOMAIN_OBJECT);
alter table ACCOUNTING_ENTRY ADD INDEX (KEY_ACCOUNT);
alter table ACCOUNTING_ENTRY ADD INDEX (KEY_RECEIPT);
alter table ACCOUNTING_ENTRY ADD INDEX (KEY_ACCOUNTING_TRANSACTION);

alter table ACCOUNTING_EVENT ADD INDEX (KEY_ROOT_DOMAIN_OBJECT);
alter table ACCOUNTING_EVENT ADD INDEX (KEY_PERSON);
alter table ACCOUNTING_EVENT ADD INDEX (KEY_CANDIDACY);

alter table RECEIPT ADD INDEX (KEY_PERSON);
alter table RECEIPT ADD INDEX (KEY_CONTRIBUTOR);
alter table RECEIPT ADD INDEX (KEY_ROOT_DOMAIN_OBJECT);

alter table RECEIPT_PRINT_VERSION ADD INDEX (KEY_ROOT_DOMAIN_OBJECT);
alter table RECEIPT_PRINT_VERSION ADD INDEX (KEY_RECEIPT);
alter table RECEIPT_PRINT_VERSION ADD INDEX (KEY_EMPLOYEE);
	