alter table EXECUTION_DEGREE add column KEY_PERIOD_EXAMS_SPECIAL_SEASON int(11) default NULL;
alter table PAYMENT_TRANSACTION change column TRANSACTION_DATE TRANSACTION_DATE_DATE_TIME timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
 