alter table ACADEMIC_CALENDAR_ENTRY drop column REFERENCE_KEY;

alter table EXECUTION_PERIOD drop column BEGIN_DATE_YEAR_MONTH_DAY;
alter table EXECUTION_PERIOD drop column END_DATE_YEAR_MONTH_DAY;
alter table EXECUTION_PERIOD drop column SEMESTER;
alter table EXECUTION_PERIOD drop column KEY_PREVIOUS_EXECUTION_PERIOD;
alter table EXECUTION_PERIOD drop column KEY_NEXT_EXECUTION_PERIOD;

alter table EXECUTION_YEAR drop column BEGIN_DATE_YEAR_MONTH_DAY;
alter table EXECUTION_YEAR drop column END_DATE_YEAR_MONTH_DAY;

