ALTER TABLE `PHD_PROCESS_STATE` ADD `STATE_DATE` varchar(255);
ALTER TABLE `PROCESS` ADD `PRESENTATION_REQUEST_DATE` varchar(255);

UPDATE PHD_PROCESS_STATE SET TYPE = 'WAITING_FOR_COMMISSION_CONSTITUTION' WHERE TYPE = 'WAITING_FOR_COMISSION_CONSTITUTION';