alter table ACADEMIC_SERVICE_REQUEST add column SERVICE_REQUEST_YEAR int(4) default NULL;
alter table ACADEMIC_SERVICE_REQUEST drop key SERVICE_REQUEST_NUMBER;
alter table ACADEMIC_SERVICE_REQUEST add unique key SERVICE_REQUEST_NUMBER_YEAR (SERVICE_REQUEST_NUMBER, SERVICE_REQUEST_YEAR);
update ACADEMIC_SERVICE_REQUEST set ACADEMIC_SERVICE_REQUEST.SERVICE_REQUEST_YEAR = year(ACADEMIC_SERVICE_REQUEST.REQUEST_DATE);
