create table `RESIDENCE_MANAGEMENT_STUDENTS_PERFORMANCE_REPORT_STUDENT` (`OID_STUDENT` bigint unsigned, `OID_STUDENTS_PERFORMANCE_REPORT` bigint unsigned, primary key (OID_STUDENT, OID_STUDENTS_PERFORMANCE_REPORT), index (OID_STUDENT), index (OID_STUDENTS_PERFORMANCE_REPORT)) type=InnoDB, character set latin1;
alter table `FILE` add `OID_EXECUTION_SEMESTER` bigint(20);
