create table EXAM_DATE_CERTIFICATE_REQUEST_EXAM (
	KEY_EXAM int(11) not null, 
	KEY_EXAM_DATE_CERTIFICATE_REQUEST int(11) not null,  
	primary key (KEY_EXAM, KEY_EXAM_DATE_CERTIFICATE_REQUEST), 
	key(KEY_EXAM), 
	key(KEY_EXAM_DATE_CERTIFICATE_REQUEST)
) type=InnoDB;
