ALTER TABLE EXTRA_WORK_REQUEST ADD COLUMN WORKDAY_FIRST_LEVEL_AMOUNT Double default '0';
ALTER TABLE EXTRA_WORK_REQUEST ADD COLUMN WORKDAY_SECOND_LEVEL_AMOUNT Double default '0';
ALTER TABLE EXTRA_WORK_REQUEST ADD COLUMN WORKDAY_FIRST_LEVEL_HOURS int(11) default NULL;
ALTER TABLE EXTRA_WORK_REQUEST ADD COLUMN WORKDAY_SECOND_LEVEL_HOURS int(11) default NULL;
