alter table ASSIDUOUSNESS_CLOSED_MONTH add column KEY_ASSIDUOUSNESS_STATUS_HISTORY int(11);
alter table ASSIDUOUSNESS_CLOSED_MONTH add index (KEY_ASSIDUOUSNESS_STATUS_HISTORY);
alter table ASSIDUOUSNESS_CLOSED_MONTH drop KEY U1;
alter table ASSIDUOUSNESS_CLOSED_MONTH add UNIQUE KEY U1 (KEY_ASSIDUOUSNESS_STATUS_HISTORY,KEY_ASSIDUOUSNESS,KEY_CLOSED_MONTH);

alter table ASSIDUOUSNESS_CLOSED_MONTH add column BEGIN_DATE text;
alter table ASSIDUOUSNESS_CLOSED_MONTH add column END_DATE text;



