alter table REGISTRATION add column REGISTRATION_AGREEMENT varchar(50);

update REGISTRATION set REGISTRATION_AGREEMENT = 'NORMAL' where KEY_STUDENT_KIND = 1;
update REGISTRATION set REGISTRATION_AGREEMENT = 'ERASMUS' where KEY_STUDENT_KIND = 2;
update REGISTRATION set REGISTRATION_AGREEMENT = 'OTHER_EXTERNAL' where KEY_STUDENT_KIND = 3;
