
DELETE FROM ADMINISTRATIVE_OFFICE_PERMISSION;
DELETE FROM ADMINISTRATIVE_OFFICE_PERMISSION_GROUP;

-- Inserted at 2009-03-20T14:19:07.725Z

alter table `ADMINISTRATIVE_OFFICE_PERMISSION_GROUP` add column `KEY_ADMINISTRATIVE_OFFICE` int(11);
alter table `ADMINISTRATIVE_OFFICE_PERMISSION_GROUP` add index (`KEY_ADMINISTRATIVE_OFFICE`);
alter table `ADMINISTRATIVE_OFFICE_PERMISSION_GROUP` add index (`KEY_ROOT_DOMAIN_OBJECT`);
alter table `ADMINISTRATIVE_OFFICE_PERMISSION` add index (`KEY_ADMINISTRATIVE_OFFICE_PERMISSION_GROUP`);
alter table `ADMINISTRATIVE_OFFICE_PERMISSION` add index (`KEY_ROOT_DOMAIN_OBJECT`);
