alter table TEACHING_INQUIRY add column SEMESTER_END_AVERAGE_STUDENT_NUMBER int(11);
alter table TEACHING_INQUIRY add column SEMESTER_MIDDLE_AVERAGE_STUDENT_NUMBER int(11);
alter table TEACHING_INQUIRY add column SEMESTER_START_AVERAGE_STUDENT_NUMBER int(11);
alter table TEACHING_INQUIRY add column OTHER_TEACHING_LANGUAGE text;