-- if the commented command was never run, ignore this file
-- ALTER TABLE `PROFESSORSHIPS` ADD `KEY_NON_AFFILIATED_TEACHER` int(11)  default NULL;

ALTER TABLE PROFESSORSHIPS DROP KEY_NON_AFFILIATED_TEACHER ;