alter table ACADEMIC_SERVICE_REQUEST drop column KEY_STUDENT_CURRICULAR_PLAN;
alter table ACADEMIC_SERVICE_REQUEST add column KEY_REGISTRATION int(11) NOT NULL default '0';
alter table ACADEMIC_SERVICE_REQUEST add index KEY_REGISTRATION (KEY_REGISTRATION);

alter table ACADEMIC_SERVICE_REQUEST change column SERVICE_REQUEST_NUMBER SERVICE_REQUEST_NUMBER int NOT NULL default '0' unique;