ALTER TABLE POSTING_RULE CHANGE COLUMN TOTAL_AMOUNT DFA_TOTAL_AMOUNT VARCHAR(255) NULL;
ALTER TABLE POSTING_RULE CHANGE COLUMN PARTIAL_ACCEPTED_PERCENTAGE DFA_PARTIAL_ACCEPTED_PERCENTAGE VARCHAR(255) NULL;
ALTER TABLE POSTING_RULE ADD COLUMN DFA_AMOUNT_PER_ECTS_CREDIT VARCHAR(255) NULL;
ALTER TABLE POSTING_RULE ADD COLUMN FIXED_AMOUNT_PENALTY VARCHAR(255) NULL;
