 alter table VIGILANT_GROUP add column POINTS_FOR_TEACHER INTEGER;
 alter table VIGILANT_GROUP add column POINTS_FOR_CONVOKED INTEGER;
 alter table VIGILANT_GROUP add column POINTS_FOR_DISMISSED INTEGER;
 alter table VIGILANT_GROUP add column POINTS_FOR_MISSING INTEGER;
 alter table VIGILANT_GROUP add column POINTS_FOR_DISCONVOKED INTEGER;

 update VIGILANT_GROUP set POINTS_FOR_TEACHER=0;
 update VIGILANT_GROUP set POINTS_FOR_CONVOKED=1;
 update VIGILANT_GROUP set POINTS_FOR_DISMISSED=0;
 update VIGILANT_GROUP set POINTS_FOR_MISSING=-2;
 update VIGILANT_GROUP set POINTS_FOR_DISCONVOKED=0;



