update TEACHER_SERVICE_ITEM set CREDITS = 8.41 where ID_INTERNAL = 69117;

update TEACHER_SERVICE_ITEM set CREDITS = -5.89  where ID_INTERNAL = 69118;

update TEACHER_SERVICE_ITEM set CREDITS = 0.0  where ID_INTERNAL = 69136;

update TEACHER_SERVICE_ITEM set CREDITS = -7.4  where ID_INTERNAL = 69267;

update TEACHER_SERVICE_ITEM set CREDITS = 0.0 where ID_INTERNAL = 69779;
