ALTER TABLE REGISTRATION DROP COLUMN KEY_PERSONAL_DATA_USE_INQUIRY_ANSWERS;
ALTER TABLE REGISTRATION CHANGE COLUMN KEY_CANDIDACY KEY_STUDENT_CANDIDACY INT(11) NULL;
ALTER TABLE REGISTRATION CHANGE COLUMN ENTRY_PHASE ENTRY_PHASE INT(11) NULL;