alter table TEACHER_PERSONAL_EXPECTATION modify DEPARTMENT_ORGANS text NULL;
alter table TEACHER_PERSONAL_EXPECTATION modify IST_ORGANS text NULL;
alter table TEACHER_PERSONAL_EXPECTATION modify UTL_ORGANS text NULL;
alter table TEACHER_PERSONAL_EXPECTATION modify CIENTIFIC_COMUNITY_SERVICE text NULL;
alter table TEACHER_PERSONAL_EXPECTATION modify SOCIETY_SERVICE text NULL;
alter table TEACHER_PERSONAL_EXPECTATION modify CONSULTING text NULL;
alter table TEACHER_PERSONAL_EXPECTATION modify COMPANY_SOCIAL_ORGANS text NULL;
alter table TEACHER_PERSONAL_EXPECTATION modify COMPANY_POSITIONS text NULL;

