ALTER TABLE ASSIDUOUSNESS_CAMPUS_HISTORY CHANGE LAST_MODIFIED_DATE LAST_MODIFIED_DATE datetime;

ALTER TABLE ASSIDUOUSNESS_RECORD CHANGE DATE DATE datetime;
ALTER TABLE ASSIDUOUSNESS_RECORD CHANGE LAST_MODIFIED_DATE LAST_MODIFIED_DATE datetime default '0000-00-00 00:00:00';

ALTER TABLE ASSIDUOUSNESS_STATUS CHANGE LAST_MODIFIED_DATE LAST_MODIFIED_DATE datetime;
ALTER TABLE JUSTIFICATION_MOTIVE CHANGE LAST_MODIFIED_DATE LAST_MODIFIED_DATE datetime;


ALTER TABLE PROJECT_ACCESS CHANGE BEGIN_DATE_TIME BEGIN_DATE_TIME datetime;
ALTER TABLE PROJECT_ACCESS CHANGE END_DATE_TIME END_DATE_TIME datetime;


ALTER TABLE STUDENT_TEST_LOG CHANGE DATE_DATE_TIME DATE_DATE_TIME datetime;

ALTER TABLE TEST CHANGE CREATION_DATE_DATE_TIME CREATION_DATE_DATE_TIME datetime;
ALTER TABLE TEST CHANGE LAST_MODIFIED_DATE_DATE_TIME LAST_MODIFIED_DATE_DATE_TIME;


ALTER TABLE WORK_SCHEDULE_TYPE CHANGE LAST_MODIFIED_DATE LAST_MODIFIED_DATE datetime;


