ALTER TABLE EXEMPTION ADD COLUMN WHEN_CREATED DATETIME NULL;
UPDATE EXEMPTION SET WHEN_CREATED = CURRENT_DATE;
ALTER TABLE EXEMPTION MODIFY COLUMN WHEN_CREATED DATETIME NOT NULL;

ALTER TABLE EXEMPTION CHANGE COLUMN KEY_GRATUITY_EVENT KEY_EVENT INT(11) NOT NULL;

ALTER TABLE EXEMPTION ADD COLUMN KEY_INSTALLMENT INT(11) NULL;

ALTER TABLE EXEMPTION CHANGE COLUMN EXEMPTION_TYPE GRATUITY_EXEMPTION_TYPE VARCHAR(255) NULL;

ALTER TABLE EXEMPTION ADD COLUMN KEY_PENALTY_EXEMPTION_JUSTIFICATION INT(11) NULL;
