ALTER TABLE CURRICULAR_RULE ADD KEY_NOT_RULE int(11) default NULL;
ALTER TABLE CURRICULAR_RULE ADD KEY KEY_NOT_RULE (KEY_NOT_RULE);
ALTER TABLE CURRICULAR_RULE ADD KEY_WRAPPED_RULE int(11) default NULL;
ALTER TABLE CURRICULAR_RULE ADD KEY KEY_WRAPPED_RULE (KEY_WRAPPED_RULE);
