alter table CATEGORY add column WEEKLY_LESSON_HOURS int(2) default 0;
alter table CATEGORY add column CATEGORY_TYPE varchar(100) NOT NULL default '';
alter table CATEGORY change column CODE CODE varchar(20) default '';
alter table CATEGORY drop KEY U1;
alter table PROFESSIONAL_SITUATION drop column WEEKLY_WORKING_HOURS;

update CATEGORY set CATEGORY_TYPE = 'TEACHER';

update CATEGORY set WEEKLY_LESSON_HOURS = 9 where CATEGORY.SHORT_NAME like 'ASSISTENTE';
update CATEGORY set WEEKLY_LESSON_HOURS = 9 where CATEGORY.SHORT_NAME like 'ASSIST.ESTAGIARIO';

update CATEGORY set WEEKLY_LESSON_HOURS = 6 where CATEGORY.SHORT_NAME like 'MONITOR-ECD C/LIC';
update CATEGORY set WEEKLY_LESSON_HOURS = 6 where CATEGORY.SHORT_NAME like 'MONITOR-ECD S/LIC';
update CATEGORY set WEEKLY_LESSON_HOURS = 6 where CATEGORY.SHORT_NAME like 'PROF.ASSOCIADO';
update CATEGORY set WEEKLY_LESSON_HOURS = 6 where CATEGORY.SHORT_NAME like 'PROF.AUXILIAR';
update CATEGORY set WEEKLY_LESSON_HOURS = 6 where CATEGORY.SHORT_NAME like 'PROF.CATEDRATICO';

update CATEGORY set WEEKLY_LESSON_HOURS = 12 where CATEGORY.SHORT_NAME like 'ASSIST.CONVIDADO';
update CATEGORY set WEEKLY_LESSON_HOURS = 12 where CATEGORY.SHORT_NAME like 'PROF.CAT.CONVIDADO';
update CATEGORY set WEEKLY_LESSON_HOURS = 12 where CATEGORY.SHORT_NAME like 'PROF.ASSOC.CONVIDADO';
update CATEGORY set WEEKLY_LESSON_HOURS = 12 where CATEGORY.SHORT_NAME like 'PROF.AUX.CONVIDADO';


