rename table GROUP_PROPERTIES to GROUPING;
alter table GROUPING drop index KEY_ATTENDS_SET;
alter table GROUPING drop index NAME_KEY_ATTENDS_SET;
alter table GROUPING drop column KEY_ATTENDS_SET;

rename table GROUP_PROPERTIES_EXECUTION_COURSE to GROUPING_EXECUTION_COURSE;
alter table GROUPING_EXECUTION_COURSE change KEY_GROUP_PROPERTIES KEY_GROUPING int(11) unsigned NOT NULL default 0;
alter table GROUPING_EXECUTION_COURSE drop index KEY_GROUP_PROPERTIES;
alter table GROUPING_EXECUTION_COURSE add index (KEY_GROUPING);

alter table STUDENT_GROUP add column KEY_GROUPING int(11) unsigned default null;
alter table STUDENT_GROUP add index (KEY_GROUPING);

rename table ATTEND_ATTENDS_SET to GROUPING_ATTENDS;
alter table GROUPING_ATTENDS change KEY_ATTENDS_SET KEY_GROUPING int(11) NOT NULL default 0;
alter table GROUPING_ATTENDS drop index KEY_ATTENDS_SET;
alter table GROUPING_ATTENDS add index (KEY_GROUPING);
