alter table CANDIDACY add column KEY_DISTRICT_SUBDIVISION_OF_RESIDENCE int(11);
alter table CANDIDACY add column KEY_SCHOOL_TIME_DISTRICT_SUB_DIVISION_OF_RESIDENCE int(11);
alter table CANDIDACY add index (KEY_DISTRICT_SUBDIVISION_OF_RESIDENCE);
alter table CANDIDACY add index (KEY_SCHOOL_TIME_DISTRICT_SUB_DIVISION_OF_RESIDENCE);

