ALTER TABLE CANDIDACY ADD COLUMN STUDENT_PERSONAL_DATA_AUTHORIZATION_CHOICE VARCHAR(255) NULL;
ALTER TABLE CANDIDACY ADD COLUMN APPLY_FOR_RESIDENCE BIT NULL;
ALTER TABLE CANDIDACY ADD COLUMN NOTES_ABOUT_RESIDENCE_APPLIANCE TEXT NULL;
ALTER TABLE CANDIDACY ADD COLUMN ENTRY_GRADE FLOAT(10,2) NULL;
ALTER TABLE CANDIDACY ADD COLUMN CONTIGENT VARCHAR(10) NULL;
ALTER TABLE CANDIDACY ADD COLUMN INGRESSION VARCHAR(10) NULL;
ALTER TABLE CANDIDACY ADD COLUMN IST_UNIVERSITY VARCHAR(10) NULL;
ALTER TABLE CANDIDACY ADD COLUMN ENTRY_PHASE VARCHAR(255) NULL;


