alter table `FILE` add `OID_DGES_STUDENT_IMPORTATION_PROCESS` bigint unsigned, add index (OID_EXECUTION_YEAR);
alter table `QUEUE_JOB` add `OID_DGES_STUDENT_IMPORTATION_FILE` bigint unsigned, add `OID_DGES_STUDENT_IMPORTATION_FOR_CAMPUS` bigint unsigned, add `ENTRY_PHASE` text, add index (OID_DGES_STUDENT_IMPORTATION_FOR_CAMPUS);
alter table `ERASMUS_INDIVIDUAL_CANDIDACY_CURRICULAR_COURSES` add index (OID_ERASMUS_INDIVIDUAL_CANDIDACY), add index (OID_CURRICULAR_COURSE);

