alter table EXECUTION_DEGREE add column KEY_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_FIRST_SEMESTER int(11) default NULL;
alter table EXECUTION_DEGREE add column KEY_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_SECOND_SEMESTER int(11) default NULL;
alter table EXECUTION_DEGREE add column KEY_PERIOD_GRADE_SUBMISSION_SPECIAL_SEASON int(11) default NULL;
