ALTER TABLE `CURRICULAR_COURSE` ADD `NAME_EN` VARCHAR(100)  AFTER `NAME`;
ALTER TABLE `CURRICULAR_COURSE` ADD `KEY_COURSE_HISTORIC` INTEGER AFTER `KEY_SCIENTIFIC_AREA`;
ALTER TABLE `CURRICULAR_COURSE` ADD `KEY_STUDENT_COURSE_REPORT` INTEGER AFTER `KEY_SCIENTIFIC_AREA`;
