alter table POSTING_RULE add column PHD_GRATUITY_AMOUNT VARCHAR(255);
alter table POSTING_RULE add column INITIAL_PAYMENT VARCHAR(255); 
alter table POSTING_RULE add column PENALTY_PERCENTAGE VARCHAR(255);
