ALTER TABLE POSTING_RULE ADD COLUMN TOTAL_PAYMENT_ENTRY_TYPE VARCHAR(255) NULL;
ALTER TABLE POSTING_RULE ADD COLUMN PARTIAL_PAYMENT_ENTRY_TYPE VARCHAR(255) NULL;
ALTER TABLE POSTING_RULE ADD COLUMN PARTIAL_ACCEPTED_PERCENTAGE VARCHAR(255) NULL;
ALTER TABLE POSTING_RULE ADD COLUMN TOTAL_AMOUNT VARCHAR(255) NULL;
ALTER TABLE POSTING_RULE CHANGE COLUMN ENTRY_TYPE ENTRY_TYPE VARCHAR(250) NULL;
