alter table `ASSIDUOUSNESS_CLOSED_MONTH` add column `WORKED_DAYS_WITH_A17_DAYS_DISCOUNT` int(11);
alter table `ASSIDUOUSNESS_CLOSED_MONTH` add column `TOTAL_WORKED_TIME_FOR_A17_VACATIONS` bigint(20);
