update ACCOUNTABILITY_TYPE set NAME = 'WORKING_CONTRACT', TYPE = 'WORKING_CONTRACT' where NAME = 'EMPLOYEE_CONTRACT' and TYPE = 'EMPLOYEE_CONTRACT';
update ACCOUNTABILITY_TYPE set NAME = 'MAILING_CONTRACT', TYPE = 'MAILING_CONTRACT' where NAME = 'RESEARCHER_CONTRACT' and TYPE = 'RESEARCHER_CONTRACT';

select concat('update ACCOUNTABILITY set ACCOUNTABILITY.KEY_ACCOUNTABILITY_TYPE = ' , ACCOUNTABILITY_TYPE.ID_INTERNAL , ' where ACCOUNTABILITY.OJB_CONCRETE_CLASS like \"%EmployeeMailingContract%\";') as "" from ACCOUNTABILITY_TYPE where ACCOUNTABILITY_TYPE.TYPE = 'MAILING_CONTRACT';

update ACCOUNTABILITY set OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.organizationalStructure.EmployeeContract' where OJB_CONCRETE_CLASS like '%EmployeeMailingContract%' or OJB_CONCRETE_CLASS like '%EmployeeWorkingContract%'; 