ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN HAS_PAID_FOR_CANDIDACY tinyint(1);
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN OBSERVATIONS varchar(255);
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN LANGUAGES_READ varchar(30);
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN LANGUAGES_WRITE varchar(30);
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN LANGUAGES_SPEAK varchar(30);
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN FORMER_STUDENT_NUMBER varchar(30);

ALTER TABLE PROCESS ADD COLUMN ACCESS_HASH varchar(32);

ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN NAME varchar(255);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN DOCUMENT_ID_NUMBER VARCHAR(50);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN ID_DOCUMENT_TYPE VARCHAR(50);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN EMISSION_DATE_OF_DOCUMENT_ID_YEAR_MONTH_DAY DATE;
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN EMISSION_LOCATION_OF_DOCUMENT_ID VARCHAR(100);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN EXPIRATION_DATE_OF_DOCUMENT_ID_YEAR_MONTH_DAY DATE;
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN DATE_OF_BIRTH_YEAR_MONTH_DAY DATE;
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN GENDER VARCHAR(6);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN FISCAL_CODE VARCHAR(50);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN TELEPHONE_CONTACT VARCHAR(50);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN EMAIL VARCHAR(100);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN ADDRESS VARCHAR(255);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN AREA VARCHAR(100);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN AREA_CODE VARCHAR(50);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN AREA_OF_AREA_CODE VARCHAR(100);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN MARITAL_STATUS VARCHAR(50);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN KEY_COUNTRY_OF_RESIDENCE INT(11);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN KEY_NATIONALITY INT(11);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN PROFESSION VARCHAR(255);


ALTER TABLE FILE ADD COLUMN CANDIDACY_FILE_TYPE VARCHAR(50);
ALTER TABLE FILE ADD COLUMN KEY_INDIVIDUAL_CANDIDACY INT(11);

DROP TABLE PUBLIC_CANDIDACY_HASH_CODE;
CREATE TABLE PUBLIC_CANDIDACY_HASH_CODE (
	ID_INTERNAL int(11) PRIMARY KEY,
	KEY_INDIVIDUAL_CANDIDACY_PROCESS int(11),
	EMAIL VARCHAR(255) NOT NULL,
	`VALUE` VARCHAR(255) NOT NULL,
	KEY_ROOT_DOMAIN_OBJECT INT(11)
);

ALTER TABLE PROCESS ADD COLUMN KEY_CANDIDACY_HASH_CODE int(11);

ALTER TABLE QUALIFICATION MODIFY KEY_PERSON int(11);
ALTER TABLE QUALIFICATION ADD COLUMN CONCLUDED tinyint(1);
ALTER TABLE QUALIFICATION ADD COLUMN KEY_INDIVIDUAL_CANDIDACY int(11);
ALTER TABLE QUALIFICATION ADD COLUMN DESIGNATION varchar(255);
ALTER TABLE QUALIFICATION ADD COLUMN CONCLUSION_GRADE varchar(255);
ALTER TABLE QUALIFICATION ADD COLUMN KEY_CONCLUSION_EXECUTION_YEAR int(11);

ALTER TABLE PARTY_CONTACT MODIFY COLUMN AREA_CODE VARCHAR(50);

ALTER TABLE COUNTRY ADD COLUMN LOCALIZED_NAME longtext;
