--  SQL file representing changes to the functionalities model
--  Generated at Thu Oct 18 12:02:15 BST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 277520 UUID: '5ea34ab2-e69c-445c-aef3-7296600d6c8b'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PATH` = '/payments.do?method=prepareSearchPerson' WHERE own.`UUID` = '5ea34ab2-e69c-445c-aef3-7296600d6c8b';

COMMIT;
