UPDATE COMPETENCE_COURSE_INFORMATION SET COMPETENCE_COURSE_INFORMATION.COMPETENCE_COURSE_LEVEL = "DOCTORATE" WHERE COMPETENCE_COURSE_INFORMATION.COMPETENCE_COURSE_LEVEL = "SCIENTIFIC";
UPDATE COMPETENCE_COURSE_INFORMATION SET COMPETENCE_COURSE_INFORMATION.COMPETENCE_COURSE_LEVEL = "FORMATION" WHERE COMPETENCE_COURSE_INFORMATION.COMPETENCE_COURSE_LEVEL = "TECHNOLOGICAL";
