--  SQL file representing changes to the functionalities model
--  Generated at Tue May 15 16:30:16 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Inserting new functionalities
-- 

--  ID: 118086 UUID: '5a35c10e-2108-412d-94f5-8ba12f051305'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`) SELECT '5a35c10e-2108-412d-94f5-8ba12f051305', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'en12:Publicationspt11:Publicações', 'en12:Publicationspt11:Publicações', NULL, '/viewResearchUnitSite.do?method=showPublications', NULL, 1, 1, 'siteID', 4, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 FROM `ACCESSIBLE_ITEM` WHERE `UUID` = 'aade3f06-9faf-49cc-a28b-d2cf136f8469';
INSERT INTO `AVAILABILITY_POLICY` (`OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_ACCESSIBLE_ITEM`, `EXPRESSION`, `TARGET_GROUP`) SELECT 'net.sourceforge.fenixedu.domain.functionalities.ExpressionGroupAvailability', 1, `ID_INTERNAL`, 'ifTrue($I(siteID, \'UnitSite\').showPublications)', 'ifTrue($I(siteID, \'UnitSite\').showPublications)' FROM `ACCESSIBLE_ITEM` WHERE `UUID` = '5a35c10e-2108-412d-94f5-8ba12f051305';
UPDATE `ACCESSIBLE_ITEM` AS f, `AVAILABILITY_POLICY` AS ap SET f.`KEY_AVAILABILITY_POLICY` = ap.`ID_INTERNAL` WHERE f.`UUID` = '5a35c10e-2108-412d-94f5-8ba12f051305' AND ap.`KEY_ACCESSIBLE_ITEM` = f.`ID_INTERNAL`;

COMMIT;
