--  SQL file representing changes to the functionalities model
--  Generated at Tue Nov 13 15:13:15 WET 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 283322 UUID: '6797c053-576f-4ec4-b50a-489470709106'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt13:Gerar Cartões' WHERE own.`UUID` = '6797c053-576f-4ec4-b50a-489470709106';

--  ID: 283323 UUID: 'dc040672-f9f9-4bb4-a1c3-21bcc55ba8f7'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt12:Gerar Cartas' WHERE own.`UUID` = 'dc040672-f9f9-4bb4-a1c3-21bcc55ba8f7';

--  ID: 307329 UUID: '13edb156-6d32-4a07-a76f-f695ed331719'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt36:Gerar Cartas para Alunos e Bolseiros' WHERE own.`UUID` = '13edb156-6d32-4a07-a76f-f695ed331719';

COMMIT;
