--  SQL file representing changes to the functionalities model
--  Generated at Mon Jul 23 12:40:16 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 133472 UUID: '8d123cd3-b4ce-4152-9860-ab3b1b8ab900'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en20:Unit Site Managementpt26:Gestão de Sites de Unidade', own.`TITLE` = NULL, own.`PATH` = '/unitSiteManagement.do?method=prepare' WHERE own.`UUID` = '8d123cd3-b4ce-4152-9860-ab3b1b8ab900';

COMMIT;
