-- Inserted at 2009-03-11T12:47:20.516Z

alter table `PROFESSORSHIP` add column `KEY_PERSON` int(11);
alter table `PROFESSORSHIP` add index (`KEY_PERSON`);

update PROFESSORSHIP,TEACHER
set PROFESSORSHIP.KEY_PERSON = TEACHER.KEY_PERSON
where PROFESSORSHIP.KEY_TEACHER = TEACHER.ID_INTERNAL;
alter table `PROFESSORSHIP` DROP column `KEY_TEACHER`;

