--  SQL file representing changes to the functionalities model
--  Generated at Thu Nov 15 12:13:14 WET 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 277719 UUID: '23842dee-e243-4027-91dc-1567ec1930e9'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`PATH` = '/cardManagement.do?method=showUsers&dontSearch=yes' WHERE own.`UUID` = '23842dee-e243-4027-91dc-1567ec1930e9';

COMMIT;
