--  SQL file representing changes to the functionalities model
--  Generated at Mon May 21 15:10:26 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 26328 UUID: '173e00ae-66ff-408b-a8ce-d4a4011fe3f5'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Docentesen7:Faculty' WHERE own.`UUID` = '173e00ae-66ff-408b-a8ce-d4a4011fe3f5';

--  ID: 26329 UUID: '3bd0759b-edca-4ff7-87d6-6e03b6be1b3c'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt12:Funcionáriosen5:Staff' WHERE own.`UUID` = '3bd0759b-edca-4ff7-87d6-6e03b6be1b3c';

COMMIT;
