--  SQL file representing changes to the functionalities model
--  Generated at Thu Jun 21 16:04:47 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 6 UUID: '9f33514d-c6c3-4acb-b1ca-a02980128d90'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 7 WHERE own.`UUID` = '9f33514d-c6c3-4acb-b1ca-a02980128d90';

--  ID: 7 UUID: 'ffa828bb-e3d5-4b3d-9996-39b4cb226ba8'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 8 WHERE own.`UUID` = 'ffa828bb-e3d5-4b3d-9996-39b4cb226ba8';

--  ID: 9 UUID: '85ce6f13-fddd-44dd-941e-25a1c2dd857e'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 10 WHERE own.`UUID` = '85ce6f13-fddd-44dd-941e-25a1c2dd857e';

--  ID: 10 UUID: '232d33c1-c50a-418b-a61f-c652539b90cf'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 11 WHERE own.`UUID` = '232d33c1-c50a-418b-a61f-c652539b90cf';

--  ID: 11 UUID: '36496cce-ebc4-4a27-b16e-a408672f0bf6'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 12 WHERE own.`UUID` = '36496cce-ebc4-4a27-b16e-a408672f0bf6';

--  ID: 12 UUID: '4d6686aa-9e47-4a47-a08a-a37d69f94eb5'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 13 WHERE own.`UUID` = '4d6686aa-9e47-4a47-a08a-a37d69f94eb5';

--  ID: 200 UUID: '8dfee1bd-dbf7-45b0-ae2b-d8136998106b'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 18 WHERE own.`UUID` = '8dfee1bd-dbf7-45b0-ae2b-d8136998106b';

--  ID: 216 UUID: '9ba1269a-0b8f-4daa-bde2-abbd0132327b'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 14 WHERE own.`UUID` = '9ba1269a-0b8f-4daa-bde2-abbd0132327b';

--  ID: 217 UUID: '63bb3ae4-d1a0-4fc7-be16-ae25918a8831'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 15 WHERE own.`UUID` = '63bb3ae4-d1a0-4fc7-be16-ae25918a8831';

--  ID: 218 UUID: '05edef46-6c85-4361-b35e-017d73f9bd6c'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 16 WHERE own.`UUID` = '05edef46-6c85-4361-b35e-017d73f9bd6c';

--  ID: 219 UUID: '64d01274-211d-49c1-b1ed-aa07a368efd2'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 17 WHERE own.`UUID` = '64d01274-211d-49c1-b1ed-aa07a368efd2';

--  ID: 220 UUID: 'b5d85b58-d775-4fca-8f0c-30e2fdb60cba'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 18 WHERE own.`UUID` = 'b5d85b58-d775-4fca-8f0c-30e2fdb60cba';

--  ID: 221 UUID: 'ec219d83-2928-4c5f-84ea-28768c22d5bd'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 19 WHERE own.`UUID` = 'ec219d83-2928-4c5f-84ea-28768c22d5bd';

--  ID: 222 UUID: '264b6a46-3a52-4935-9094-88be1fbfb33d'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 20 WHERE own.`UUID` = '264b6a46-3a52-4935-9094-88be1fbfb33d';

--  ID: 223 UUID: '97805947-1f30-4780-8fc6-ee283514f534'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 21 WHERE own.`UUID` = '97805947-1f30-4780-8fc6-ee283514f534';

--  ID: 225 UUID: '615aa695-c4e3-445c-b63b-7ea40768b4f9'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 22 WHERE own.`UUID` = '615aa695-c4e3-445c-b63b-7ea40768b4f9';

--  ID: 226 UUID: '30316818-7aaf-4b0c-a770-6ac47463fd09'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 23 WHERE own.`UUID` = '30316818-7aaf-4b0c-a770-6ac47463fd09';

--  ID: 227 UUID: 'fcf57231-df5b-4173-8db3-46bf9676ef9f'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 24 WHERE own.`UUID` = 'fcf57231-df5b-4173-8db3-46bf9676ef9f';

--  ID: 228 UUID: 'd63322ea-b9c3-402a-85b1-07577df66635'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 25 WHERE own.`UUID` = 'd63322ea-b9c3-402a-85b1-07577df66635';

--  ID: 229 UUID: '20ae78b6-6c5a-4705-b5f5-e233862178ca'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 26 WHERE own.`UUID` = '20ae78b6-6c5a-4705-b5f5-e233862178ca';

--  ID: 230 UUID: 'e5325cd5-5fd1-4213-af66-42fc9ed00892'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 27 WHERE own.`UUID` = 'e5325cd5-5fd1-4213-af66-42fc9ed00892';

--  ID: 231 UUID: '353e875a-75c6-40c9-92bf-88de23686f08'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 28 WHERE own.`UUID` = '353e875a-75c6-40c9-92bf-88de23686f08';

--  ID: 232 UUID: '35fc54d5-7ae9-4195-ad94-be98894ce012'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 29 WHERE own.`UUID` = '35fc54d5-7ae9-4195-ad94-be98894ce012';

--  ID: 233 UUID: '2fc34f7f-e879-42b7-936a-e9d60db53875'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 30 WHERE own.`UUID` = '2fc34f7f-e879-42b7-936a-e9d60db53875';

--  ID: 234 UUID: 'ebad2636-7c48-402d-944e-95bc587724be'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 31 WHERE own.`UUID` = 'ebad2636-7c48-402d-944e-95bc587724be';

--  ID: 235 UUID: '315334e8-bfd5-4d19-b4c2-4097393d7dda'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 32 WHERE own.`UUID` = '315334e8-bfd5-4d19-b4c2-4097393d7dda';

--  ID: 236 UUID: 'eabed4f4-7a0b-4e77-8edb-e8525857f934'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 34 WHERE own.`UUID` = 'eabed4f4-7a0b-4e77-8edb-e8525857f934';

--  ID: 252 UUID: '9cf56518-f706-4854-b28e-2108ba374c43'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt11:Comunicaçãoen9:Messaging' WHERE own.`UUID` = '9cf56518-f706-4854-b28e-2108ba374c43';

--  ID: 16193 UUID: '1b6d4c06-fdfb-4426-a4a1-c3a217e89977'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 33 WHERE own.`UUID` = '1b6d4c06-fdfb-4426-a4a1-c3a217e89977';

--  ID: 16195 UUID: '197325b3-e343-4945-9dba-dacb86df3112'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 2 WHERE own.`UUID` = '197325b3-e343-4945-9dba-dacb86df3112';

--  ID: 16196 UUID: '8b992ca5-c112-4963-a2ca-91a5713e3f0a'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt14:Página Inicialen12:Initial Page' WHERE own.`UUID` = '8b992ca5-c112-4963-a2ca-91a5713e3f0a';

--  ID: 16197 UUID: 'c168fb54-39ed-4e76-8c7d-df4827aefc4d'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Anúnciosen13:Announcements' WHERE own.`UUID` = 'c168fb54-39ed-4e76-8c7d-df4827aefc4d';

--  ID: 16198 UUID: 'a7ae9674-17c9-4166-91f4-a80b38d79a41'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt11:Planeamentoen8:Planning' WHERE own.`UUID` = 'a7ae9674-17c9-4166-91f4-a80b38d79a41';

--  ID: 16199 UUID: '729d1770-b7f0-4bf9-acd0-b07b951b2e2e'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Sumáriosen9:Summaries' WHERE own.`UUID` = '729d1770-b7f0-4bf9-acd0-b07b951b2e2e';

--  ID: 16200 UUID: '9a31d73a-a1d4-462a-af5c-0fb6ffb15761'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt10:Objectivosen10:Objectives' WHERE own.`UUID` = '9a31d73a-a1d4-462a-af5c-0fb6ffb15761';

--  ID: 16201 UUID: 'c71ee66b-5246-4259-b135-c6eed8d21e7a'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Programaen7:Program' WHERE own.`UUID` = 'c71ee66b-5246-4259-b135-c6eed8d21e7a';

--  ID: 16202 UUID: '51b95e9b-f636-4466-ab5b-f455184b9fe3'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt19:Método de Avaliaçãoen17:Evaluation Method' WHERE own.`UUID` = '51b95e9b-f636-4466-ab5b-f455184b9fe3';

--  ID: 16203 UUID: '672d9b28-2100-46ba-9586-f9bb09692747'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt12:Bibliografiaen12:Bibliography' WHERE own.`UUID` = '672d9b28-2100-46ba-9586-f9bb09692747';

--  ID: 16204 UUID: '98b12f32-87b6-4c9d-8c18-8bd5c00d303c'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt7:Horárioen9:Timesheet' WHERE own.`UUID` = '98b12f32-87b6-4c9d-8c18-8bd5c00d303c';

--  ID: 16205 UUID: '859fb0f6-ee73-4baa-bf34-80ea3ec8ab5f'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt6:Turnosen6:Shifts' WHERE own.`UUID` = '859fb0f6-ee73-4baa-bf34-80ea3ec8ab5f';

--  ID: 16206 UUID: 'bf220aff-96eb-4a67-ab1c-848f90b6aaa3'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt9:Avaliaçãoen10:Evaluation' WHERE own.`UUID` = 'bf220aff-96eb-4a67-ab1c-848f90b6aaa3';

--  ID: 16207 UUID: 'cc6df75a-3be9-45d9-b47b-3b7544565251'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt12:Agrupamentosen6:Groups' WHERE own.`UUID` = 'cc6df75a-3be9-45d9-b47b-3b7544565251';

--  ID: 22170 UUID: '360d6646-953c-45cc-a0bf-721365af5e00'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt21:Pesquisa de Conteúdosen15:Search Contents', own.`TITLE` = 'pt19:Pesquisar Conteúdosen15:Search Contents' WHERE own.`UUID` = '360d6646-953c-45cc-a0bf-721365af5e00';

--  ID: 24843 UUID: 'ab4c28f5-1803-4f98-a900-87ee6705b79e'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt5:Cursoen6:Degree' WHERE own.`UUID` = 'ab4c28f5-1803-4f98-a900-87ee6705b79e';

--  ID: 24844 UUID: 'd30145de-ed6b-4abb-a760-50753d4de23b'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt9:Descriçãoen11:Description' WHERE own.`UUID` = 'd30145de-ed6b-4abb-a760-50753d4de23b';

--  ID: 24845 UUID: 'b36012ae-41f4-401d-9297-2f5d2e55c5da'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Anúnciosen13:Announcements' WHERE own.`UUID` = 'b36012ae-41f4-401d-9297-2f5d2e55c5da';

--  ID: 24846 UUID: '5204408e-7703-413d-adec-bc50eeebc1f3'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt16:Regime de Acessoen22:Admission Requirements' WHERE own.`UUID` = '5204408e-7703-413d-adec-bc50eeebc1f3';

--  ID: 24847 UUID: 'febb72c5-4263-43f4-bcc5-5df5eac6e148'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt21:Estatuto Profissionalen19:Professional Status' WHERE own.`UUID` = 'febb72c5-4263-43f4-bcc5-5df5eac6e148';

--  ID: 24848 UUID: 'd1f52ea5-1280-4ae0-ac2e-e43ca44dad34'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt16:Plano Curricularen15:Curricular Plan' WHERE own.`UUID` = 'd1f52ea5-1280-4ae0-ac2e-e43ca44dad34';

--  ID: 24849 UUID: 'e570d796-43e6-4499-87bb-99a59bd3b608'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt22:Páginas de Disciplinasen16:Course Web Pages' WHERE own.`UUID` = 'e570d796-43e6-4499-87bb-99a59bd3b608';

--  ID: 24850 UUID: '10085a1d-de69-4803-af0f-c084a80f37fe'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt18:Horários por Turmaen15:Class timetable' WHERE own.`UUID` = '10085a1d-de69-4803-af0f-c084a80f37fe';

--  ID: 24851 UUID: '7e7160fe-0f68-4886-9599-8dc92ba4eb12'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt10:Avaliaçõesen11:Evaluations' WHERE own.`UUID` = '7e7160fe-0f68-4886-9599-8dc92ba4eb12';

--  ID: 26327 UUID: 'c113952d-6c49-44c0-b30b-d56ab1d2d047'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Anúnciosen13:Announcements' WHERE own.`UUID` = 'c113952d-6c49-44c0-b30b-d56ab1d2d047';

--  ID: 26330 UUID: '85372e2e-ffe0-48ff-a758-1017a11c797f'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt11:Disciplinasen7:Courses' WHERE own.`UUID` = '85372e2e-ffe0-48ff-a758-1017a11c797f';

--  ID: 103664 UUID: '3cc0ecf4-b897-48d7-925c-af865f028b9b'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 9 WHERE own.`UUID` = '3cc0ecf4-b897-48d7-925c-af865f028b9b';

--  ID: 133470 UUID: 'aade3f06-9faf-49cc-a28b-d2cf136f8469'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt20:Site de Investigaçãoen13:Research Site' WHERE own.`UUID` = 'aade3f06-9faf-49cc-a28b-d2cf136f8469';

--  ID: 133472 UUID: '8d123cd3-b4ce-4152-9860-ab3b1b8ab900'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt31:Gestão de Sites de Investigaçãoen24:Research Site Management', own.`TITLE` = 'pt43:Gestão de Sites de Unidades de Investigaçãoen29:Research Unit Site Management' WHERE own.`UUID` = '8d123cd3-b4ce-4152-9860-ab3b1b8ab900';

--  ID: 133474 UUID: '931438dc-b0e2-4d2a-b017-1a449adf59e3'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt7:Eventosen6:Events' WHERE own.`UUID` = '931438dc-b0e2-4d2a-b017-1a449adf59e3';

--  ID: 140670 UUID: 'e9ab1a2b-cfd2-4c6d-9476-27c7c3caf4c6'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt7:Eventosen6:Events', own.`TITLE` = 'pt7:Eventosen6:Events' WHERE own.`UUID` = 'e9ab1a2b-cfd2-4c6d-9476-27c7c3caf4c6';

--  ID: 140671 UUID: '8481d1a7-1b95-43f6-b091-e0d582aa86e5'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt8:Anúnciosen13:Announcements', own.`TITLE` = 'pt8:Anúnciosen13:Announcements' WHERE own.`UUID` = '8481d1a7-1b95-43f6-b091-e0d582aa86e5';

--  ID: 140674 UUID: '95b0bf15-1f4d-4430-815a-dfc1fb373ea6'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt6:Cursosen7:Degrees' WHERE own.`UUID` = '95b0bf15-1f4d-4430-815a-dfc1fb373ea6';

--  ID: 163278 UUID: '2a487bf2-9986-40cf-923d-c571c211491f'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt7:Membrosen7:Members', own.`TITLE` = 'pt7:Membrosen7:Members' WHERE own.`UUID` = '2a487bf2-9986-40cf-923d-c571c211491f';

--  ID: 163280 UUID: '5a35c10e-2108-412d-94f5-8ba12f051305'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt11:Publicaçõesen12:Publications', own.`TITLE` = 'pt11:Publicaçõesen12:Publications' WHERE own.`UUID` = '5a35c10e-2108-412d-94f5-8ba12f051305';

--  ID: 189877 UUID: '4cbd4716-40e1-4052-ac47-b24db983efd4'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`ORDER_IN_MODULE` = 35 WHERE own.`UUID` = '4cbd4716-40e1-4052-ac47-b24db983efd4';

--  ID: 189878 UUID: '4caaa9c0-1db1-449b-a91a-487454cc62ec'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt6:Inícioen5:Start', own.`TITLE` = 'pt24:Página inicial do portalen19:Portal inicial page' WHERE own.`UUID` = '4caaa9c0-1db1-449b-a91a-487454cc62ec';

--  ID: 189879 UUID: '9dc80775-4df0-4876-b991-cff3bcbd59cb'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt12:Dissertaçõesen6:Theses' WHERE own.`UUID` = '9dc80775-4df0-4876-b991-cff3bcbd59cb';

-- 
--  Inserting new functionalities
-- 

--  ID: 203879 UUID: '7a8440b9-8a15-4111-a71a-4f4e2ac6fcc8'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT '7a8440b9-8a15-4111-a71a-4f4e2ac6fcc8', 'net.sourceforge.fenixedu.domain.functionalities.Module', 1, NULL, NULL, NULL, 'pt20:Gestão de Património', 'pt20:Gestão de Património', NULL, '/resourceManager/index.do', '/resourceManager', 1, 1, NULL, 6, 1, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL;
INSERT INTO `AVAILABILITY_POLICY` (`OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_ACCESSIBLE_ITEM`, `EXPRESSION`, `TARGET_GROUP`) SELECT 'net.sourceforge.fenixedu.domain.functionalities.ExpressionGroupAvailability', 1, `ID_INTERNAL`, 'role(RESOURCE_MANAGER)', 'role(RESOURCE_MANAGER)' FROM `ACCESSIBLE_ITEM` WHERE `UUID` = '7a8440b9-8a15-4111-a71a-4f4e2ac6fcc8';
UPDATE `ACCESSIBLE_ITEM` AS f, `AVAILABILITY_POLICY` AS ap SET f.`KEY_AVAILABILITY_POLICY` = ap.`ID_INTERNAL` WHERE f.`UUID` = '7a8440b9-8a15-4111-a71a-4f4e2ac6fcc8' AND ap.`KEY_ACCESSIBLE_ITEM` = f.`ID_INTERNAL`;

COMMIT;
