--  SQL file representing changes to the functionalities model
--  Generated at Mon Jul 23 12:40:16 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Inserting new functionalities
-- 

--  ID: 240889 UUID: '23cfd678-1f9a-4d56-a717-7112b0ca67b5'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT '23cfd678-1f9a-4d56-a717-7112b0ca67b5', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt11:Subunidadesen8:Subunits', NULL, NULL, '/departmentSite.do?method=subunits', NULL, 1, 1, 'selectedDepartmentUnitID', 7, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = '3adea1cf-e612-456f-b8be-c24882b77c3e';
--  ID: 241294 UUID: '27c395f9-5d79-4172-b33c-4779fedf6cc8'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT '27c395f9-5d79-4172-b33c-4779fedf6cc8', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'en8:Subunitspt11:Subunidades', NULL, NULL, '/viewResearchUnitSite.do?method=subunits', NULL, 1, 1, 'siteID', 5, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = 'aade3f06-9faf-49cc-a28b-d2cf136f8469';

-- 
--  Updating existing functionalities
-- 

--  ID: 133472 UUID: '8d123cd3-b4ce-4152-9860-ab3b1b8ab900'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en20:Unit Site Managementpt26:Gestão de Sites de Unidade', own.`TITLE` = NULL, own.`PATH` = '/unitSiteManagement.do?method=prepare' WHERE own.`UUID` = '8d123cd3-b4ce-4152-9860-ab3b1b8ab900';

COMMIT;
