alter table `CANDIDACY_PERIOD` add `TYPE` text;
create table `INSTITUTION_PHD_CANDIDACY_PERIOD_PHD_PROGRAMS` (`OID_INSTITUTION_PHD_CANDIDACY_PERIOD` bigint unsigned, `OID_PHD_PROGRAM` bigint unsigned, primary key (OID_INSTITUTION_PHD_CANDIDACY_PERIOD, OID_PHD_PROGRAM), index (OID_INSTITUTION_PHD_CANDIDACY_PERIOD), index (OID_PHD_PROGRAM)) ENGINE=InnoDB, character set latin1;
alter table `PROCESS` add `OID_PUBLIC_PHD_CANDIDACY_PERIOD` bigint unsigned, add index (OID_PUBLIC_PHD_CANDIDACY_PERIOD);
