insert into NODE(KEY_PARENT,KEY_CHILD,NODE_ORDER,VISIBLE,OJB_CONCRETE_CLASS,ASCENDING,CONTENT_ID) 
select S.ID_INTERNAL, F.ID_INTERNAL, (SELECT COUNT(*) FROM  NODE WHERE NODE.KEY_PARENT = S.ID_INTERNAL) + 1,'0','net.sourceforge.fenixedu.domain.contents.ExplicitOrderNode','1', UUID() 
FROM CONTENT F INNER JOIN EXECUTION_COURSE ON F.KEY_FORUM_EXECUTION_COURSE = EXECUTION_COURSE.ID_INTERNAL 
INNER JOIN CONTENT S ON EXECUTION_COURSE.ID_INTERNAL = S.KEY_SITE_EXECUTION_COURSE  
WHERE F.OJB_CONCRETE_CLASS LIKE "%.ExecutionCourseForum";