delete from STUDENT_TEST_QUESTION where STUDENT_TEST_QUESTION.KEY_STUDENT =52046 and STUDENT_TEST_QUESTION.KEY_DISTRIBUTED_TEST in (31725, 31125);
delete from STUDENT_TEST_QUESTION where STUDENT_TEST_QUESTION.KEY_STUDENT =360469 and STUDENT_TEST_QUESTION.KEY_DISTRIBUTED_TEST in (31725);
update STUDENT_TEST_LOG set  STUDENT_TEST_LOG.KEY_STUDENT=374671 where STUDENT_TEST_LOG.KEY_STUDENT =173322;