create table RECEIPT (
	ID_INTERNAL int(11) NOT NULL auto_increment,
	KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
	KEY_PARTY int(11) NOT NULL,
	VERSION int(11) NOT NULL,
	PRIMARY KEY (ID_INTERNAL)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
