
CREATE TABLE FUNCTIONALITY_PRINTERS (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  FUNCTIONALITY varchar(255) not null,
  KEY_PRINTERS varchar(255) not null,
  PRIMARY KEY (ID_INTERNAL),
  KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT)
);

CREATE TABLE UNIT_FUNCTIONALITY_PRINTERS (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  KEY_UNIT int(11) NOT NULL,
  KEY_FUNCTIONALITY_PRINTERS int(11) NOT NULL,
  PRIMARY KEY (ID_INTERNAL),
  KEY KEY_UNIT (KEY_UNIT),
  KEY KEY_FUNCTIONALITY_PRINTERS (KEY_FUNCTIONALITY_PRINTERS)
);

INSERT INTO FUNCTIONALITY_PRINTERS (ID_INTERNAL, FUNCTIONALITY, KEY_PRINTERS) VALUES (1, "markSheet", "markSheet.printers.graduacao");
INSERT INTO UNIT_FUNCTIONALITY_PRINTERS (KEY_UNITS, KEY_FUNCTIONALITY_PRINTERS) VALUES (74678, 1);
INSERT INTO FUNCTIONALITY_PRINTERS (ID_INTERNAL, FUNCTIONALITY, KEY_PRINTERS) VALUES (2, "markSheet", "markSheet.printers.pos.graduacao");
INSERT INTO UNIT_FUNCTIONALITY_PRINTERS (KEY_UNIT, KEY_FUNCTIONALITY_PRINTERS) VALUES (61061, 2);