
alter table ACCOUNTABILITY add column KEY_DELEGATE int(11);
alter table ACCOUNTABILITY add index (KEY_DELEGATE);

drop table DELEGATE;

create table DELEGATE (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `KEY_DELEGATE_FUNCTION` int(11),
  `KEY_REGISTRATION` int(11),
  `KEY_ROOT_DOMAIN_OBJECT` int(11),
  `OJB_CONCRETE_CLASS` text,
  primary key (ID_INTERNAL),
  index (KEY_DELEGATE_FUNCTION),
  index (KEY_REGISTRATION),
  index (KEY_ROOT_DOMAIN_OBJECT)
) type=InnoDB ;

create table YEAR_DELEGATE_COURSE_INQUIRY (
  `ANSWER_DURATION` bigint(20),
  `CLEAR_ONLINE_C_U_INFORMATION` int(11),
  `CLEAR_ONLINE_C_U_INFORMATION_REASONS` text,
  `ENOUGH_ONLINE_C_U_INFORMATION` int(11),
  `ENOUGH_ONLINE_C_U_INFORMATION_REASONS` text,
  `EVALUATION_DATES_SCHEDULE_ACTIVE_PARTICIPATION` int(11),
  `EVALUATION_DATES_SCHEDULE_ACTIVE_PARTICIPATION_REASONS` text,
  `EVALUATION_METHODS_DISCLOSED_TO_SPECIAL_SEASON_STUDENTS` text,
  `EVALUATION_METHODS_DISCLOSED_TO_WORKING_STUDENTS` text,
  `EVALUATION_METHODS_WELL_APPLIED` int(11),
  `EVALUATION_METHODS_WELL_APPLIED_REASONS` text,
  `EXPLICIT_EVALUATION_METHODS` int(11),
  `EXPLICIT_EVALUATION_METHODS_REASONS` text,
  `FINAL_COMMENTS_AND_IMPROOVEMENTS` text,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `KEY_DELEGATE` int(11),
  `KEY_EXECUTION_COURSE` int(11),
  `KEY_ROOT_DOMAIN_OBJECT` int(11),
  `PREVIOUS_KNOWLEGDE_ARTICULATION` int(11),
  `PREVIOUS_KNOWLEGDE_ARTICULATION_REASONS` text,
  `RESPONSE_DATE_TIME` timestamp NULL default NULL,
  `STRONG_AND_WEAK_POINTS_OF_C_U_TEACHING_PROCESS` text,
  `SUGGESTED_BEST_PRACTICES` text,
  `SUPPORT_MATERIAL_AVAILABLE_ON_TIME` int(11),
  `SUPPORT_MATERIAL_AVAILABLE_ON_TIME_REASONS` text,
  `WORK_LOAD_CLASSIFICATION` int(11),
  `WORK_LOAD_CLASSIFICATION_REASONS` text,
  primary key (ID_INTERNAL),
  index (KEY_DELEGATE),
  index (KEY_EXECUTION_COURSE),
  index (KEY_ROOT_DOMAIN_OBJECT)
) type=InnoDB ;
