 ALTER TABLE EVENT ADD COLUMN KEY_RESIDENCE_MONTH INT(11) NULL;
 ALTER TABLE EVENT ADD COLUMN ROOM_VALUE VARCHAR(255);
 ALTER TABLE POSTING_RULE ADD column PENALTY_PER_DAY varchar(255); 

 CREATE TABLE RESIDENCE_YEAR (
	ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
        KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
        KEY_RESIDENCE_MANAGEMENT_UNIT int(11) NOT NULL, 
        YEAR INTEGER, 
        PRIMARY KEY  (ID_INTERNAL),
        KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT)
)type=InnoDB;

 CREATE TABLE RESIDENCE_MONTH (
        ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
        KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
        KEY_RESIDENCE_YEAR int(11) NOT NULL,  
        MONTH VARCHAR(255),
        PRIMARY KEY  (ID_INTERNAL),
        KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT)
)type=InnoDB;


