CREATE TABLE `FUNCTIONALITY_PARAMETER` (
  `ID_INTERNAL` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `KEY_FUNCTIONALITY` INTEGER NOT NULL,
  `KEY_TYPE` INTEGER NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1'
) TYPE=INNODB;
