create table ANNOUNCEMENT_MESSAGING (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  KEY_CREATOR int(11),
  KEY_ROOT_DOMAIN_OBJECT int not null,
  KEY_ANNOUNCEMENT_BOARD int NOT NULL,
  CREATION_DATE DATETIME NOT NULL,
  REFERED_SUBJECT_BEGIN DATETIME,
  REFERED_SUBJECT_END DATETIME,
  PUBLICATION_BEGIN DATETIME,
  PUBLICATION_END DATETIME,
  LAST_MODIFICATION DATETIME,
  SUBJECT text,
  BODY text,
  KEYWORDS text,
  AUTHOR VARCHAR(255),
  AUTHOR_EMAIL VARCHAR(255),
  EXCERPT text,
  HIDDEN int(11),
  PRIMARY KEY(ID_INTERNAL)
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

create table ANNOUNCEMENT_BOARD (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  READERS blob,
  WRITERS blob,
  KEY_ROOT_DOMAIN_OBJECT int(11) not null,  
  KEY_PARTY int(11),
  NAME VARCHAR(255),
  MANDATORY int(11) not null,
  OJB_CONCRETE_CLASS VARCHAR(255) not null,
  PRIMARY KEY(ID_INTERNAL)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

drop table if exists ANNOUNCEMENT_BOARD_BOOKMARK;
create table ANNOUNCEMENT_BOARD_BOOKMARK (
  KEY_PERSON int(11),
  KEY_ANNOUNCEMENT_BOARD int(11)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
