CREATE TABLE ALLOWED_TO_UPLOAD_IN_UNIT (
  `KEY_UNIT` INTEGER(11) NOT NULL,
  `KEY_PERSON` INTEGER(11) NOT NULL,
   PRIMARY KEY(`KEY_UNIT`,`KEY_PERSON`),
   KEY KEY_UNIT (`KEY_UNIT`),
   KEY KEY_PERSON (`KEY_PERSON`)
) type=InnoDB;
