CREATE TABLE `PARTY_PARTY` (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `KEY_SUB_PARTY` int(11) NOT NULL default '0',
  `KEY_PARENT_PARTY` int(11) NOT NULL default '0',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_SUB_PARTY` (`KEY_SUB_PARTY`),
  KEY `KEY_PARENT_PARTY` (`KEY_PARENT_PARTY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1