-- DROP TABLE IF EXISTS SERVICE_LOG;
CREATE TABLE SERVICE_LOG (
	INVOCATION_DATE timestamp NOT NULL,
	INVOKER_USERNAME varchar(10) default NULL,
	SERVICE_NAME varchar(255) NOT NULL,
	SERVICE_ARGUMENTS text default NULL
) TYPE=InnoDB;

-- DROP TABLE IF EXISTS MONITORED_SERVICE;
CREATE TABLE MONITORED_SERVICE (
	ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
	SERVICE_NAME varchar(50) NOT NULL,
	ACK_OPT_LOCK int(11) default NULL,
	PRIMARY KEY  (ID_INTERNAL),
	UNIQUE KEY U1 (SERVICE_NAME)	
) TYPE=InnoDB;

-- DROP TABLE IF EXISTS MONITORED_USER;
CREATE TABLE MONITORED_USER (
	ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
	USERNAME varchar(50) NOT NULL,
	ACK_OPT_LOCK int(11) default NULL,
	PRIMARY KEY  (ID_INTERNAL),
	UNIQUE KEY U1 (USERNAME)	
) TYPE=InnoDB;
