CREATE TABLE RESEARCH_EVENT (
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  ACK_OPT_LOCK int(11) default NULL,
  FEE_OR_FREE int(11) default NULL,
  START_DATE varchar(10),
  END_DATE varchar(10),
  LOCATION varchar(100),
  PRIMARY KEY  (`ID_INTERNAL`)
) Type=InnoDB;

CREATE TABLE PROJECT_EVENT (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  KEY_PROJECT int(11) NOT NULL,
  KEY_EVENT int(11) NOT NULL,
  PRIMARY KEY (ID_INTERNAL),
  UNIQUE KEY (KEY_PROJECT, KEY_EVENT)
) Type=InnoDB;

CREATE TABLE UNIT_EVENT (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  KEY_UNIT int(11) NOT NULL,
  KEY_EVENT int(11) NOT NULL,
  PRIMARY KEY (ID_INTERNAL),
  UNIQUE KEY (KEY_UNIT, KEY_EVENT)
) Type=InnoDB;

CREATE TABLE RESEARCHER_EVENT (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  KEY_RESEARCHER int(11) NOT NULL,
  KEY_EVENT int(11) NOT NULL,
  PRIMARY KEY (ID_INTERNAL),
  UNIQUE KEY (KEY_RESEARCHER, KEY_EVENT)
) Type=InnoDB;