CREATE TABLE COURSE_LOAD_REQUEST_ENROLMENT (
  KEY_COURSE_LOAD_REQUEST INT(11) NOT NULL,
  KEY_ENROLMENT INT(11) NOT NULL,
  PRIMARY KEY (KEY_COURSE_LOAD_REQUEST, KEY_ENROLMENT),
  KEY (KEY_COURSE_LOAD_REQUEST),
  KEY (KEY_ENROLMENT)
) ENGINE=InnoDB;
