CREATE TABLE EXTERNAL_CURRICULAR_COURSE(
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  KEY_UNIT int(11) NOT NULL,
  NAME varchar(250) NOT NULL,
  CODE varchar(50) NOT NULL,
  PRIMARY KEY  (ID_INTERNAL),
  KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT),
  KEY KEY_UNIT (KEY_UNIT)
) ENGINE=InnoDB;
