CREATE TABLE THESIS_EVALUATION_PARTICIPANT (
  ID_INTERNAL int(11) not null auto_increment,
  KEY_ROOT_DOMAIN_OBJECT int(11) not null default '1',
  KEY_PERSON int(11) not null,
  KEY_ORIENTATED_THESIS int(11) not null,
  KEY_COORIENTATED_THESIS int(11) not null,
  KEY_PRESIDENT_THESIS int(11) not null,
  KEY_VOWEL_THESIS int(11) not null,
  CATEGORY text not null default "",
  AFFILIATION text not null default "",
  PRIMARY KEY (ID_INTERNAL),
  KEY KEY_PERSON (KEY_PERSON),
  KEY KEY_ORIENTATED_THESIS (KEY_ORIENTATED_THESIS),
  KEY KEY_COORIENTATED_THESIS (KEY_COORIENTATED_THESIS),
  KEY KEY_PRESIDENT_THESIS (KEY_PRESIDENT_THESIS),
  KEY KEY_VOWEL_THESIS (KEY_VOWEL_THESIS),
  KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT)
);

insert into THESIS_EVALUATION_PARTICIPANT(ID_INTERNAL, KEY_PERSON, KEY_ORIENTATED_THESIS)
select THESIS.KEY_ORIENTATOR, THESIS.KEY_ORIENTATOR, THESIS.ID_INTERNAL from THESIS;

insert into THESIS_EVALUATION_PARTICIPANT(ID_INTERNAL, KEY_PERSON, KEY_COORIENTATED_THESIS)
select THESIS.KEY_COORIENTATOR, THESIS.KEY_COORIENTATOR, THESIS.ID_INTERNAL from THESIS;

insert into THESIS_EVALUATION_PARTICIPANT(ID_INTERNAL, KEY_PERSON, KEY_PRESIDENT_THESIS)
select THESIS.KEY_PRESIDENT, THESIS.KEY_PRESIDENT, THESIS.ID_INTERNAL from THESIS;

insert into THESIS_EVALUATION_PARTICIPANT(KEY_PERSON, KEY_VOWEL_THESIS)
select THESIS_JURY_VOWELS.KEY_PERSON, THESIS_JURY_VOWELS.KEY_THESIS from THESIS_JURY_VOWELS;

drop table THESIS_JURY_VOWELS;