DROP TABLE IF EXISTS RESIDENCE_PRICE_TABLE;
create TABLE RESIDENCE_PRICE_TABLE (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,  
  `PAYMENT_LIMIT_DAY` int(2),
  `SINGLE_ROOM_VALUE` TEXT,
  `DOUBLE_ROOM_VALUE` TEXT,
  `KEY_ROOT_DOMAIN_OBJECT` INT(11) NOT NULL DEFAULT '1',
   primary key(ID_INTERNAL),
   index (KEY_ROOT_DOMAIN_OBJECT)
)type=InnoDB;


alter table RESIDENCE_YEAR drop column PAYMENT_LIMIT_DAY;
alter table RESIDENCE_YEAR drop column SINGLE_ROOM_VALUE;
alter table RESIDENCE_YEAR drop column DOUBLE_ROOM_VALUE;

alter table PARTY ADD COLUMN KEY_RESIDENCE_PRICE_TABLE INT(11);
alter table PARTY ADD index (KEY_RESIDENCE_PRICE_TABLE);
