DROP TABLE IF EXISTS GRATUITY_EXEMPTION;
CREATE TABLE GRATUITY_EXEMPTION (
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  EXEMPTION_TYPE varchar(255) NOT NULL,
  PERCENTAGE varchar(255) NULL,
  VALUE varchar(255) NULL,
  OJB_CONCRETE_CLASS varchar(255) NOT NULL,
  KEY_GRATUITY_EVENT int(11) NOT NULL,
  KEY_EMPLOYEE int(11) NOT NULL,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  PRIMARY KEY  (ID_INTERNAL),
  KEY (KEY_ROOT_DOMAIN_OBJECT),
  KEY (KEY_EMPLOYEE),
  KEY (KEY_GRATUITY_EVENT)
) ENGINE=InnoDB;



