CREATE TABLE SIBS_PAYMENT_FILE_PROCESS_REPORT (
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  KEY_ROOT_DOMAIN_OBJECT INT(11) NOT NULL default '1',
  FILENAME VARCHAR(255) NOT NULL,
  WHEN_PROCESSED_BY_SIBS VARCHAR(10) NOT NULL,
  WHEN_PROCESSED DATETIME NOT NULL,
  FILE_VERSION INT(2) NOT NULL,
  DEGREE_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  BOLONHA_DEGREE_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  INTEGRATED_MASTER_DEGREE_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  INTEGRATED_BOLONHA_MASTER_DEGREE_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  ADMINISTRATIVE_OFFICE_TAX_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  GRADUATION_INSURANCE_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  SPECIALIZATION_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  MASTER_DEGREE_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  BOLONHA_MASTER_DEGREE_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  DFA_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  AFTER_GRADUATION_INSURANCE_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  PHD_GRATUITY_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  TRANSACTIONS_TOTAL_AMOUNT VARCHAR(255) NOT NULL,
  TOTAL_COST VARCHAR(255) NOT NULL,
  PRIMARY KEY  (ID_INTERNAL),
  UNIQUE (FILENAME),
  UNIQUE (WHEN_PROCESSED_BY_SIBS,FILE_VERSION),
  KEY `KEY_ROOT_DOMAIN_OBJECT`  (KEY_ROOT_DOMAIN_OBJECT)
) ENGINE=InnoDB;


