CREATE TABLE ENROLMENT_WRAPPER(
  `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
  `KEY_CREDITS` int(11) NOT NULL,
  `CLASS_NAME` varchar(250) NOT NULL,  
  `OBJECT_ID` int(11) NOT NULL,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY KEY_CREDITS (KEY_CREDITS),
  KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT)
) ENGINE=InnoDB;
