CREATE TABLE RESULT_TEACHER (
 	ID_INTERNAL int(11) NOT NULL auto_increment,
  	KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
 	KEY_RESULT int(11) NOT NULL,
 	KEY_TEACHER int(11) NOT NULL,
 	PUBLICATION_AREA varchar(255) NOT NULL,
	PRIMARY KEY (ID_INTERNAL),
	UNIQUE (KEY_RESULT, KEY_TEACHER, PUBLICATION_AREA)
)TYPE=InnoDB;

