CREATE TABLE TEST_CHECKSUM(
	ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
	KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
	CHECKSUM_CODE text,
	PRIMARY KEY  (ID_INTERNAL),
	KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT)
)type=InnoDB;