-- Inserted at 2008-12-10T17:46:29.277Z

alter table ACADEMIC_CALENDAR_ENTRY add column KEY_ROOT_DOMAIN_OBJECT_FOR_DEFAULT_ROOT_ENTRY int(11);
alter table ACADEMIC_CALENDAR_ENTRY add index (KEY_ROOT_DOMAIN_OBJECT_FOR_DEFAULT_ROOT_ENTRY);
alter table ROOT_DOMAIN_OBJECT add column KEY_DEFAULT_ACADEMIC_CALENDAR int(11);
alter table ROOT_DOMAIN_OBJECT add index (KEY_DEFAULT_ACADEMIC_CALENDAR);

insert into ROOT_DOMAIN_OBJECT (KEY_DEFAULT_ACADEMIC_CALENDAR) values (1);
insert into ACADEMIC_CALENDAR_ENTRY (KEY_ROOT_DOMAIN_OBJECT_FOR_DEFAULT_ROOT_ENTRY) values (1);
