UPDATE DEGREE_CURRICULAR_PLAN SET DEGREE_CURRICULAR_PLAN.KEY_EQUIVALENCE_PLAN = NULL WHERE DEGREE_CURRICULAR_PLAN.KEY_EQUIVALENCE_PLAN = 1401;
DELETE FROM EQUIVALENCE_PLAN_ENTRY WHERE EQUIVALENCE_PLAN_ENTRY.KEY_EQUIVALENCE_PLAN = 1401;
DELETE FROM EQUIVALENCE_PLAN WHERE ID_INTERNAL = 1401;
