CREATE TABLE DEPLOY_NOTIFIER(
ID_INTERNAL int(11) NOT NULL auto_increment,
NOTIFY_USERS tinyint(1),
TIME_STAMP timestamp,
KEY_ROOT_DOMAIN_OBJECT INTEGER,
PRIMARY KEY (ID_INTERNAL)
);

alter table ROOT_DOMAIN_OBJECT add column KEY_DEPLOY_NOTIFIER INT(11);

insert into DEPLOY_NOTIFIER(NOTIFY_USERS,TIME_STAMP,KEY_ROOT_DOMAIN_OBJECT) values('0',NULL,'1');
update ROOT_DOMAIN_OBJECT set KEY_DEPLOY_NOTIFIER = (SELECT MAX(ID_INTERNAL) FROM DEPLOY_NOTIFIER);
