alter table ASSIDUOUSNESS_VACATIONS DROP COLUMN EFECTIVE_WORK_DAYS;
alter table ASSIDUOUSNESS_VACATIONS DROP COLUMN EFECTIVE_WORK_YEAR;
alter table ASSIDUOUSNESS_VACATIONS DROP COLUMN ART17_AND18_LIMIT_DAYS;
alter table ASSIDUOUSNESS_VACATIONS DROP COLUMN ART17_AND18_MAXIMUM_LIMIT_DAYS;
alter table ASSIDUOUSNESS_VACATIONS DROP COLUMN NUMBER_OF_ART17;
alter table ASSIDUOUSNESS_VACATIONS DROP COLUMN NUMBER_OF_ART18;
