DROP TABLE MAILING_LIST_QUEUE_OUTGOING_MAILS;
DROP TABLE MAILING_LIST_ALIAS;
DROP TABLE CMS_MAILING_LIST;
DROP TABLE CMS_MAIL_MESSAGE;
DROP TABLE CMS_MAIL_CONVERSATION;
DROP TABLE CMS_MAIL_QUEUE;
DROP TABLE CMS_MAIL_ADDRESS_ALIAS;
