DROP TABLE RESEARCH_EVENT;
DROP TABLE RESEARCH_EVENT_TRANSLATION;
DROP TABLE PROJECT_TITLE;
DROP TABLE PROJECT_ABSTRACT;

CREATE TABLE RESEARCH_EVENT (
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  NAME text,
  START_DATE varchar(10),
  END_DATE varchar(10),
  LOCATION varchar(50),
  FEE_OR_FREE int(11),
  TYPE varchar(50),
  PRIMARY KEY  (`ID_INTERNAL`)
) Type=InnoDB;