update COMPETENCE_COURSE_INFORMATION
set COMPETENCE_COURSE_INFORMATION.BIBLIOGRAPHIC_REFERENCES =
   replace(COMPETENCE_COURSE_INFORMATION.BIBLIOGRAPHIC_REFERENCES, "||null||", "||||")
where COMPETENCE_COURSE_INFORMATION.BIBLIOGRAPHIC_REFERENCES like '%||null||%';
