delete FROM EVENT WHERE OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.accounting.events.phd.PhDCandidacyEvent';
DELETE FROM R1 USING REGISTRATION R1, REGISTRATION R2,DEGREE D WHERE R1.NUMBER=R2.NUMBER AND R1.ID_INTERNAL>R2.ID_INTERNAL AND R1.KEY_DEGREE = R2.KEY_DEGREE AND R1.START_DATE = R2.START_DATE AND R1.KEY_DEGREE = D.ID_INTERNAL AND D.TIPO_CURSO ='BOLONHA_PHD_PROGRAM';
delete FROM REGISTRATION_NUMBER WHERE KEY_REGISTRATION NOT IN (SELECT ID_INTERNAL FROM REGISTRATION);
