update DEGREE_CURRICULAR_PLAN 
set DEGREE_CURRICULAR_PLAN.CONCRETE_CLASS_FOR_STUDENT_CURRICULAR_PLANS = 'net.sourceforge.fenixedu.domain.StudentCurricularPlanPastLEEC' 
where DEGREE_CURRICULAR_PLAN.NAME = 'PAST-LEEC';

update STUDENT_CURRICULAR_PLAN 
set STUDENT_CURRICULAR_PLAN.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.StudentCurricularPlanPastLEEC' 
where STUDENT_CURRICULAR_PLAN.KEY_DEGREE_CURRICULAR_PLAN = 175;
