
update SENT_SMS set DELIVERY_TYPE = '1' where DELIVERY_TYPE = 'NOT_SENT_TYPE';
update SENT_SMS set DELIVERY_TYPE = '2' where DELIVERY_TYPE = 'DELIVERY_SUCCESS_TYPE';
update SENT_SMS set DELIVERY_TYPE = '3' where DELIVERY_TYPE = 'DELIVERY_FAILURE_TYPE';
update SENT_SMS set DELIVERY_TYPE = '4' where DELIVERY_TYPE = 'MESSAGE_BUFFERED_TYPE';
update SENT_SMS set DELIVERY_TYPE = '5' where DELIVERY_TYPE = 'SMSC_SUBMIT_TYPE';
update SENT_SMS set DELIVERY_TYPE = '6' where DELIVERY_TYPE = 'SMSC_REJECT_TYPE';

update SENT_SMS set DELIVERY_TYPE = 'NOT_SENT_TYPE' where DELIVERY_TYPE = 2;
update SENT_SMS set DELIVERY_TYPE = 'DELIVERY_SUCCESS_TYPE' where DELIVERY_TYPE = 1;
update SENT_SMS set DELIVERY_TYPE = 'DELIVERY_FAILURE_TYPE' where DELIVERY_TYPE = 2;
update SENT_SMS set DELIVERY_TYPE = 'MESSAGE_BUFFERED_TYPE' where DELIVERY_TYPE = 4;
update SENT_SMS set DELIVERY_TYPE = 'SMSC_SUBMIT_TYPE' where DELIVERY_TYPE = 8;
update SENT_SMS set DELIVERY_TYPE = 'SMSC_REJECT_TYPE' where DELIVERY_TYPE = 16;

