UPDATE ACADEMIC_SERVICE_REQUEST SET NUMBER_OF_PAGES = 3 WHERE ACADEMIC_SERVICE_REQUEST.SERVICE_REQUEST_NUMBER = 10572;
UPDATE ACADEMIC_SERVICE_REQUEST SET NUMBER_OF_PAGES = 2 WHERE ACADEMIC_SERVICE_REQUEST.SERVICE_REQUEST_NUMBER = 10802;
UPDATE ACADEMIC_SERVICE_REQUEST SET NUMBER_OF_PAGES = 2 WHERE ACADEMIC_SERVICE_REQUEST.SERVICE_REQUEST_NUMBER = 10697;
