CREATE TABLE META_DOMAIN_OBJECT (
  `ID_INTERNAL` INTEGER NOT NULL AUTO_INCREMENT,
  `KEY_ROOT_DOMAIN_OBJECT` INTEGER NOT NULL DEFAULT '1',
  `TYPE` VARCHAR(255),
  PRIMARY KEY (ID_INTERNAL)
) TYPE=INNODB;
