CREATE TABLE `PERSISTENT_GROUP_MEMBERS` (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `NAME` varchar(255) NOT NULL default '',
  `TYPE` varchar(100) NOT NULL default '',
  `KEY_ROOT_DOMAIN_OBJECT` int(11) unsigned default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`)
) ENGINE=InnoDB;

CREATE TABLE `PERSISTENT_GROUP_MEMBERS_PERSON` (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `KEY_PERSISTENT_GROUP_MEMBERS` int(11) NOT NULL default '0',
  `KEY_PERSON` int(11) NOT NULL default '0',
  PRIMARY KEY  (`ID_INTERNAL`),
  UNIQUE KEY `U1` (`KEY_PERSISTENT_GROUP_MEMBERS`,`KEY_PERSON`),
  KEY `KEY_PERSON` (`KEY_PERSON`),
  KEY `KEY_PERSISTENT_GROUP_MEMBERS` (`KEY_PERSISTENT_GROUP_MEMBERS`)
) ENGINE=InnoDB;
