--  SQL file representing changes to the functionalities model
--  Generated at Thu Nov 23 11:38:11 WET 2006
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 135 UUID: '4e133362-ab11-432d-8c1d-ab17cf967025'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`VISIBLE` = 0 WHERE own.`UUID` = '4e133362-ab11-432d-8c1d-ab17cf967025';

COMMIT;
