alter table SUMMARY drop column OLD_TITLE;
alter table SUMMARY drop column OLD_SUMMARY_TEXT;

alter table LESSON_PLANNING drop column OLD_TITLE;
alter table LESSON_PLANNING drop column OLD_PLANNING;

alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_ASSISTENT_GUIDER drop key U1;
alter table MASTER_DEGREE_PROOF_VERSION_EXTERNAL_JURY drop key U1;
alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_GUIDER drop key U1;

alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_ASSISTENT_GUIDER drop column KEY_EXTERNAL_PERSON;
alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_GUIDER drop column KEY_EXTERNAL_PERSON;
alter table MASTER_DEGREE_PROOF_VERSION_EXTERNAL_JURY drop column KEY_EXTERNAL_PERSON;

alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_GUIDER add unique key U1 (`KEY_MASTER_DEGREE_THESIS_DATA_VERSION`,`KEY_EXTERNAL_CONTRACT`);
alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_ASSISTENT_GUIDER add unique key U1 (`KEY_MASTER_DEGREE_THESIS_DATA_VERSION`,`KEY_EXTERNAL_CONTRACT`);
alter table MASTER_DEGREE_PROOF_VERSION_EXTERNAL_JURY add unique key U1 (`KEY_MASTER_DEGREE_PROOF_VERSION`,`KEY_EXTERNAL_CONTRACT`);

alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_ASSISTENT_GUIDER add key KEY_EXTERNAL_CONTRACT (KEY_EXTERNAL_CONTRACT);
alter table MASTER_DEGREE_THESIS_DATA_VERSION_EXTERNAL_GUIDER add key KEY_EXTERNAL_CONTRACT (KEY_EXTERNAL_CONTRACT);
alter table MASTER_DEGREE_PROOF_VERSION_EXTERNAL_JURY add key KEY_EXTERNAL_CONTRACT (KEY_EXTERNAL_CONTRACT);

alter table PARTY drop column KEY_EXTERNAL_PERSON;
alter table PARTY drop key KEY_EXTERNAL_PERSON;

drop table EXTERNAL_PERSON;
