rename table crd_SERVICE_EXEMPTION_CREDIT_LINE to TEACHER_SERVICE_EXEMPTION;

alter table TEACHER_SERVICE_EXEMPTION change END_DATE END_DATE date default NULL;
alter table TEACHER_SERVICE_EXEMPTION add column INSTITUTION varchar(100) default NULL;