alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_3 DEVIATION3_3  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column AVERAGE_2_7 AVERAGE2_7  varchar(255) default NULL;
alter table RESTRICTION change column KEY_CURRICULAR_COURSE KEY_PRECEDENT_CURRICULAR_COURSE  int(11) default NULL;
alter table EXTRA_WORK_REQUESTS change column OPTION_5 OPTION5  tinyint(1) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_10 TOLERANCE3_10  double unsigned default NULL;
alter table GRANT_PAYMENT_ENTITY change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(250) NOT NULL default '';
alter table DEGREE_MODULE change column MAX_INCREMENT_NAC MAXIMUM_VALUE_FOR_ACUMULATED_ENROLLMENTS  int(11) default '2';
alter table FINAL_DEGREE_WORK_GROUP_STUDENT change column KEY_FINAL_DEGREE_WORK_GROUP KEY_FINAL_DEGREE_DEGREE_WORK_GROUP  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_7_INTERVAL AVERAGE2_7_INTERVAL  varchar(255) default NULL;
alter table SPACE_INFORMATION change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(250) NOT NULL default '';
alter table EVALUATION change column BEGINNING BEGINNING_DATE  time default NULL;
alter table DISTRIBUTED_TESTS change column TEST_BEGIN_DATE BEGIN_DATE_DATE  date default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_5 AVERAGE2_5  double unsigned default NULL;
alter table GRATUITY_SITUATION change column KEY_GRATUITY KEY_GRATUITY_VALUES  int(11) default NULL;
alter table EXTRA_WORK_REQUESTS change column OPTION_7 OPTION7  tinyint(1) default NULL;
alter table ass_CENTRO_CUSTO change column sigla CODE  varchar(50) NOT NULL default '';
alter table SEMINARY_CURRICULARCOURSE change column SEMINARY_ID_INTERNAL KEY_SEMINARY  int(11) NOT NULL default '0';
alter table ass_FUNCIONARIO_HISTORICO change column dataFim END_DATE  date default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column TOLERANCE_2_3 TOLERANCE2_3  double unsigned default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_10 AVERAGE3_10  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_8 NUM_ANSWERS2_8  int(11) unsigned default NULL;
alter table ACCOUNTABILITY_TYPE change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_6 TOLERANCE3_6  double unsigned default NULL;
alter table EXTRA_WORK_REQUESTS change column OPTION_10 OPTION10  tinyint(1) default NULL;
alter table EXECUTION_DEGREE change column KEY_FINAL_DEGREE_WORK_SCHEDULEING KEY_SCHEDULING  int(11) default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column AVERAGE_2_8 AVERAGE2_8  double unsigned default NULL;
alter table INQUIRIES_TEACHER change column CLASS_TYPE SHIFT_TYPE  varchar(50) NOT NULL default '';
alter table CLASS change column CURRICULAR_YEAR ANO_CURRICULAR  int(11) NOT NULL default '0';
alter table ass_STATUS change column sigla SIGLA  varchar(10) NOT NULL default '';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_5 AVERAGE3_5  double unsigned default NULL;
alter table RESULT change column FORMAT_TYPE FORMAT  varchar(50) default NULL;
alter table ENROLMENT_EVALUATION change column EVALUATION_TYPE ENROLMENT_EVALUATION_TYPE  varchar(50) NOT NULL default '';
alter table STUDENT_CURRICULAR_PLAN change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table ass_STATUS change column quem QUEM  int(11) NOT NULL default '0';
alter table WEBSITE_ITEM change column KEY_WEBSITE_SECTION KEY_WEB_SITE_SECTION  int(11) unsigned NOT NULL default '0';
alter table STUDENT_CURRICULAR_PLAN change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default 'Dominio.StudentCurricularPlan';
alter table TESTS change column LAST_MODIFICATION_DATE LAST_MODIFIED_DATE  timestamp NOT NULL default '0000-00-00 00:00:00';
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_9 AVERAGE3_9  double unsigned default NULL;
alter table EXTRA_WORK_COMPENSATION change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table DISTRIBUTED_TESTS change column TEST_END_HOUR END_HOUR_DATE  time default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_6 AVERAGE2_6  double unsigned default NULL;
alter table SHIFT change column AVAILLABILITY_FINAL AVAILABILITY_FINAL  int(11) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_6 NUM_ANSWERS3_6  int(11) unsigned default NULL;
alter table ass_STATUS change column assiduidade ASSIDUIDADE  enum('true','false') NOT NULL default 'true';
alter table LESSON change column TYPE TIPO  varchar(50) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_7 DEVIATION3_7  double unsigned default NULL;
alter table TEACHER change column KEY_WEEKLY_OCCUPATION KEY_WEEKLY_OCUPATION  int(11) default NULL;
alter table SEMINARY_CANDIDACY change column seminary_id_internal KEY_SEMINARY  int(11) NOT NULL default '0';
alter table EXTRA_WORK_REQUESTS change column OPTION_3 OPTION3  tinyint(1) default NULL;
alter table PROJECT_ACCESS change column BEGIN_DATE BEGIN  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table ENROLMENT_EVALUATION change column WHEN_ALTER WHEN_DATE_TIME  datetime default NULL;
alter table PROFESSORSHIPS change column INTERNAL_CODE ID_INTERNAL  int(11) NOT NULL auto_increment;
alter table SEMINARY change column ENROLLMENT_BEGIN_TIME ENROLLMENT_TIME_BEGIN  time default NULL;
alter table DEGREE_CURRICULAR_PLAN change column KEY_DEGREE_MODULE KEY_ROOT  int(11) default NULL;
alter table MONEY_COST_CENTER change column KEY_EMPLOYEE KEY_WHO_EMPLOYEE  int(11) unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_10 NUM_ANSWERS3_10  int(11) unsigned default NULL;
alter table CURRICULAR_COURSE_SCOPE change column END_DATE END  date default NULL;
alter table TEACHER_LEGAL_REGIMEM change column TOTAL_HOURS_NUMBER TOTAL_HOURS  double default NULL;
alter table EXTRA_WORK_HISTORIC change column KEY_EMPLOYEE_DB KEY_WHO_EMPLOYEE  int(11) unsigned default NULL;
alter table ass_CENTRO_CUSTO change column departamento DEPARTAMENT  varchar(50) default NULL;
alter table EVALUATION change column ENROLLMENT_END_DAY ENROLLMENT_END_DAY_DATE  date default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_2 AVERAGE2_2  double unsigned default NULL;
alter table PARTY change column KEY_COUNTRY KEY_PAIS  int(11) default NULL;
alter table crd_MANAGEMENT_POSITION_CREDIT_LINE change column END_DATE END  date NOT NULL default '0000-00-00';
alter table EVALUATION change column END END_DATE  time default NULL;
alter table DEPARTMENT change column KEY_UNIT KEY_DEPARTMENT_UNIT  int(11) unsigned default NULL;
alter table ass_STATUS change column quando QUANDO  datetime NOT NULL default '0000-00-00 00:00:00';
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_11 AVERAGE3_11  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column AVERAGE_2_3 AVERAGE2_3  double unsigned default NULL;
alter table CMS_EXECUTION_COURSE_WEBSITE change column KEY_TYPE KEY_WEBSITE_TYPE  int(11) NOT NULL default '0';
alter table LESSON change column START_TIME BEGIN  time NOT NULL default '00:00:00';
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_6 NUM_ANSWERS2_6  int(11) unsigned default NULL;
alter table crd_MANAGEMENT_POSITION_CREDIT_LINE change column START_DATE START  date NOT NULL default '0000-00-00';
alter table STUDENT_KIND change column MAX_NAC_TO_ENROL MAX_N_A_C_TO_ENROL  int(11) NOT NULL default '0';
alter table PROJECT_ACCESS change column END_DATE END  timestamp NOT NULL default '0000-00-00 00:00:00';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_8 AVERAGE2_8  double unsigned default NULL;
alter table SEMINARY_CANDIDACY change column seminary_modality_id_internal KEY_MODALITY  int(11) NOT NULL default '0';
alter table crd_TEACHER_INSTITUTION_WORK_TIME change column WEEKDAY WEEK_DAY  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_8 DEVIATION3_8  double unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_6 AVERAGE3_6  double unsigned default NULL;
alter table TEACHER_SERVICE_ITEM change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table GRANT_ORIENTATION_TEACHER change column KEY_GRANT_TEACHER KEY_ORIENTATION_TEACHER  int(11) unsigned NOT NULL default '0';
alter table ass_FUNCIONARIO_HISTORICO change column chaveCCLocalTrabalho KEY_WORKING_PLACE_COST_CENTER  int(11) default '0';
alter table PAYMENT_TRANSACTION change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default 'net.sourceforge.fenixedu.domain.transactions.PaymentTransaction';
alter table MARKSHEET change column MARKSHEET_TYPE MARK_SHEET_TYPE  varchar(150) NOT NULL default '';
alter table DEGREE change column NAME NOME  varchar(100) NOT NULL default '';
alter table OLD_INQUIRIES_COURSES_RES change column DEVIATION_2_2 DEVIATION2_2  double unsigned default NULL;
alter table EVALUATION change column ENROLLMENT_BEGIN_DAY ENROLLMENT_BEGIN_DAY_DATE  date default NULL;
alter table DEGREE_MODULE change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_3 AVERAGE2_3  double unsigned default NULL;
alter table GRANT_CONTRACT_REGIME change column DATE_DISPATCH_CC DATE_DISPATCH_C_C  date default NULL;
alter table GRANT_CONTRACT change column KEY_COST_CENTER KEY_GRANT_COST_CENTER  int(11) unsigned default NULL;
alter table SUPPORT_LESSON change column WEEKDAY WEEK_DAY  varchar(50) NOT NULL default '';
alter table ass_FUNCIONARIO change column numeroMecanografico EMPLOYEE_NUMBER  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_9 TOLERANCE3_9  double unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_4 AVERAGE3_4  varchar(255) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_5 TOLERANCE3_5  double unsigned default NULL;
alter table STUDENT_TEST_QUESTION change column KEY_XML_DOCUMENT KEY_QUESTION  int(11) unsigned NOT NULL default '0';
alter table BRANCH change column BRANCH_NAME NAME  varchar(255) NOT NULL default '';
alter table EXTRA_WORK_REQUESTS change column OPTION_6 OPTION6  tinyint(1) default NULL;
alter table EVALUATION change column PROJECT_BEGIN PROJECT_BEGIN_DATE_TIME  timestamp NOT NULL default '0000-00-00 00:00:00';
alter table ROOM change column FLOOR PISO  int(11) NOT NULL default '0';
alter table MASTER_DEGREE_THESIS_DATA_VERSION change column KEY_EMPLOYEE KEY_RESPONSIBLE_EMPLOYEE  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_11 TOLERANCE3_11  double unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_10 AVERAGE3_10  double unsigned default NULL;
alter table SHIFT change column KEY_EXECUTION_COURSE KEY_DISCIPLINA_EXECUCAO  int(11) NOT NULL default '0';
alter table LESSON change column KEY_ROOM KEY_SALA  int(11) NOT NULL default '0';
alter table PERIOD change column KEY_PERIOD KEY_NEXT_PERIOD  int(11) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_10 DEVIATION3_10  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_4 NUM_ANSWERS2_4  int(11) unsigned default NULL;
alter table REIMBURSEMENT_GUIDE_SITUATION change column OFFICIAL_DATE OFFICIAL  date NOT NULL default '0000-00-00';
alter table FORUM change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table ass_FUNCIONARIO change column codigoInterno ID_INTERNAL  int(11) NOT NULL auto_increment;
alter table TEACHER_SERVICE_ITEM change column WEEKDAY WEEK_DAY  varchar(50) default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column TOLERANCE_2_4 TOLERANCE2_4  double unsigned default NULL;
alter table EVALUATION change column ENROLLMENT_BEGIN_TIME ENROLLMENT_BEGIN_TIME_DATE  time default NULL;
alter table GRANT_PAYMENT_ENTITY change column KEY_COST_CENTER KEY_GRANT_COST_CENTER  int(11) unsigned default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_7_NUMERICAL AVERAGE2_7_NUMERICAL  double unsigned default NULL;
alter table ass_FUNCIONARIO_HISTORICO change column chaveFuncionario KEY_EMPLOYEE  int(11) NOT NULL default '0';
alter table ass_STATUS change column codigoInterno ID_INTERNAL  int(11) NOT NULL auto_increment;
alter table GRANT_PAYMENT_ENTITY change column KEY_TEACHER KEY_RESPONSIBLE_TEACHER  int(11) unsigned default NULL;
alter table PAYMENT_PHASE change column KEY_GRATUITY KEY_GRATUITY_VALUES  int(11) default NULL;
alter table GRANT_CONTRACT_REGIME change column DATE_SEND_DISPATCH_CC DATE_SEND_DISPATCH_C_C  date default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_4_INTERVAL AVERAGE3_4_INTERVAL  varchar(255) default NULL;
alter table DEGREE_CURRICULAR_PLAN change column DEGREE_CURRICULAR_PLAN_MEMBERS_GROUP CURRICULAR_PLAN_MEMBERS_GROUP  blob;
alter table LESSON change column END_TIME END  time NOT NULL default '00:00:00';
alter table GRANT_CONTRACT change column NUMBER CONTRACT_NUMBER  int(11) unsigned NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_7 NUM_ANSWERS3_7  int(11) unsigned default NULL;
alter table CURRICULUM_MODULE change column EVALUATION_TYPE ENROLMENT_EVALUATION_TYPE  varchar(50) NOT NULL default '';
alter table PARTY change column AVAILABLE_WEBSITE AVAILABLE_WEB_SITE  tinyint(1) NOT NULL default '0';
alter table EXTRA_WORK_REQUESTS change column OPTION_1 OPTION1  tinyint(1) default NULL;
alter table GENERAL_CLASS_PROPERTY change column KEY_OWNER_OF_PROPERTY KEY_EXECUTION_COURSE  int(11) NOT NULL default '0';
alter table PARTY change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_COURSES_RES change column AVERAGE_2_5 AVERAGE2_5  double unsigned default NULL;
alter table REIMBURSEMENT_TRANSACTION change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) default NULL;
alter table DEGREE_CURRICULAR_PLAN change column CLASS_NAME_FOR_STUDENT_CURRICULAR_PLANS CONCRETE_CLASS_FOR_STUDENT_CURRICULAR_PLANS  varchar(255) default NULL;
alter table DEGREE_MODULE change column EXECUTION_SCOPE CURRICULAR_COURSE_EXECUTION_SCOPE  int(11) default NULL;
alter table ROOM_OCCUPATION change column START_TIME START_TIME_DATE  time NOT NULL default '00:00:00';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_6_3 AVERAGE6_3  double unsigned default NULL;
alter table ass_FUNCIONARIO_HISTORICO change column chaveFuncResponsavel KEY_RESPONSABLE_EMPLOYEE  int(11) default '0';
alter table TEST_QUESTION change column KEY_XML_DOCUMENT KEY_QUESTION  int(11) unsigned NOT NULL default '0';
alter table ENROLMENT_LOG change column CREATION_DATE DATE  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table PERIOD change column START_DATE START  date NOT NULL default '0000-00-00';
alter table BRANCH change column BRANCH_NAME_EN NAME_EN  varchar(255) default NULL;
alter table GRATUITY_SITUATION change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table RESTRICTION change column NUMBER_OF_CURRICULAR_COURSE_DONE NUMBER_OF_CURRICULAR_COURSES  int(11) default NULL;
alter table CURRICULUM_MODULE change column FNL_TMP_STATE ENROLMENT_CONDITION  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_6_2 AVERAGE6_2  double unsigned default NULL;
alter table DEGREE_MODULE change column MIN_INCREMENT_NAC MINIMUM_VALUE_FOR_ACUMULATED_ENROLLMENTS  int(11) default '1';
alter table EXTRA_WORK_REQUESTS change column OPTION_11 OPTION11  tinyint(1) default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_3 NUM_ANSWERS2_3  int(11) unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column TOLERANCE_2_8 TOLERANCE2_8  double unsigned default NULL;
alter table ass_STATUS change column designacao DESIGNACAO  varchar(50) NOT NULL default '';
alter table ass_FUNCIONARIO_HISTORICO change column chaveStatus KEY_STATUS  int(11) default '0';
alter table SUMMARY change column LAST_MODIFICATION_DATE LAST_MODIFIED_DATE  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table SEMINARYCANDIDACY_SEMINARYCASESTUDY change column CANDIDACY_ID_INTERNAL KEY_CANDIDACY  int(11) NOT NULL default '0';
alter table ROOM_OCCUPATION change column END_TIME END_TIME_DATE  time NOT NULL default '00:00:00';
alter table MARK change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table PARTY change column WEB_ADRDRESS WEB_ADDRESS  varchar(200) default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column AVERAGE_2_2 AVERAGE2_2  double unsigned default NULL;
alter table COMPETENCE_COURSE change column KEY_UNIT KEY_COMPETENCE_COURSE_GROUP_UNIT  int(11) unsigned default NULL;
alter table SEMINARY_CASESTUDY change column seminary_theme_id_internal KEY_SEMINARY_THEME  int(11) default NULL;
alter table GROUPING change column ENROLMENT_BEGIN_DAY ENROLMENT_BEGIN_DAY_DATE  datetime default NULL;
alter table MASTER_DEGREE_PROOF_VERSION change column KEY_EMPLOYEE KEY_RESPONSIBLE_EMPLOYEE  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_3_NUMERICAL AVERAGE3_3_NUMERICAL  double unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_3 TOLERANCE3_3  double unsigned default NULL;
alter table ass_FUNCIONARIO_HISTORICO change column chaveCCCorrespondencia KEY_MAILING_COST_CENTER  int(11) default '0';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_6_1 AVERAGE6_1  double unsigned default NULL;
alter table EXTRA_WORK_HISTORIC change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table EXTRA_WORK change column KEY_EMPLOYEE_DB KEY_WHO_EMPLOYEE  int(11) unsigned default NULL;
alter table RESULT change column KEY_PUBLICATION_TYPE KEY_TYPE  int(11) NOT NULL default '0';
alter table EVALUATION change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(250) NOT NULL default '';
alter table MASTER_DEGREE_CANDIDATE change column TEACHER_KEY KEY_GUIDER  int(11) default NULL;
alter table ATTEND change column KEY_STUDENT KEY_ALUNO  int(11) NOT NULL default '0';
alter table METADATA change column LEARNINGTIME LEARNING_TIME_DATE  time default NULL;
alter table SEMINARYCANDIDACY_SEMINARYCASESTUDY change column CASESTUDY_ID_INTERNAL KEY_CASE_STUDY  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_7 AVERAGE3_7  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column DEVIATION_2_5 DEVIATION2_5  double unsigned default NULL;
alter table CONTEXT change column KEY_DEGREE_MODULE KEY_CHILD_DEGREE_MODULE  int(11) NOT NULL default '0';
alter table USER change column USER_UID USER_U_ID  varchar(100) default NULL;
alter table GRATUITY_VALUES change column SCHOLARSHIP_VALUE SCHOLAR_SHIP_VALUE  float default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_9 NUM_ANSWERS3_9  int(11) unsigned default NULL;
alter table TEACHER_LEGAL_REGIMEM change column LESSON_HOURS_NUMBER LESSON_HOURS  int(11) default NULL;
alter table CURRICULAR_RULE change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_7 AVERAGE3_7  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_5_TEXT NUM_ANSWERS2_5_TEXT  int(11) unsigned default NULL;
alter table CANDIDATE_SITUATION change column CANDIDATE_KEY KEY_MASTER_DEGREE_CANDIDATE  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_8 NUM_ANSWERS3_8  int(11) unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_5 DEVIATION3_5  double unsigned default NULL;
alter table EVALUATION change column PROJECT_END PROJECT_END_DATE_TIME  timestamp NOT NULL default '0000-00-00 00:00:00';
alter table GRANT_PART change column KEY_TEACHER KEY_RESPONSIBLE_TEACHER  int(11) unsigned default NULL;
alter table BRANCH change column BRANCH_ACRONYM ACRONYM  varchar(50) default NULL;
alter table ENROLMENT_EVALUATION change column CHECKSUM CHECK_SUM  varchar(50) default NULL;
alter table GRANT_ORIENTATION_TEACHER change column DATE_BEGIN BEGIN_DATE  date NOT NULL default '0000-00-00';
alter table SPACE change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(250) NOT NULL default '';
alter table ass_FUNCIONARIO_HISTORICO change column quem WHO  int(11) NOT NULL default '0';
alter table EXTRA_WORK_REQUESTS change column OPTION_2 OPTION2  tinyint(1) default NULL;
alter table MASTER_DEGREE_CANDIDATE change column EXECUTION_DEGREE_KEY KEY_EXECUTION_DEGREE  int(11) NOT NULL default '0';
alter table SEMINARY_CURRICULARCOURSE change column CURRICULAR_COURSE_ID_INTERNAL KEY_CURRICULAR_COURSE  int(11) NOT NULL default '0';
alter table GRANT_CONTRACT_REGIME change column DATE_DISPATCH_CD DATE_DISPATCH_C_D  date default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_6 AVERAGE3_6  double unsigned default NULL;
alter table EXTRA_WORK_REQUESTS change column KEY_EMPLOYEE_DB KEY_WHO_EMPLOYEE  int(11) unsigned default NULL;
alter table SHIFT change column TYPE TIPO  varchar(50) default NULL;
alter table TEACHER_SERVICE_EXEMPTION change column START_DATE START  date NOT NULL default '0000-00-00';
alter table EXECUTION_DEGREE change column ACADEMIC_YEAR KEY_EXECUTION_YEAR  int(11) NOT NULL default '0';
alter table ENROLMENT_EVALUATION change column STATE ENROLMENT_EVALUATION_STATE  int(11) NOT NULL default '0';
alter table ACCOUNTABILITY_TYPE change column KEY_INHERENT_PARENT_FUNCTION KEY_PARENT_INHERENT_FUNCTION  int(11) default NULL;
alter table GENERAL_CLASS_PROPERTY change column VALUE VALUE_STRING  varchar(255) NOT NULL default '';
alter table MARKSHEET change column MARKSHEET_STATE MARK_SHEET_STATE  varchar(150) NOT NULL default '';
alter table EXTRA_WORK_REQUESTS change column OPTION_4 OPTION4  tinyint(1) default NULL;
alter table SEMINARY change column ENROLLMENT_END_TIME ENROLLMENT_TIME_END  time default NULL;
alter table ROOM change column TYPE TIPO  int(11) NOT NULL default '0';
alter table DEGREE change column CODE SIGLA  varchar(100) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_9 DEVIATION3_9  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_5_NUMBER NUM_ANSWERS2_5_NUMBER  int(11) unsigned default NULL;
alter table FINAL_DEGREE_WORK_PROPOSAL change column DELIVERAVLE DELIVERABLE  text;
alter table DEGREE_CURRICULAR_PLAN change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) default NULL;
alter table ROOM change column NAME NOME  varchar(100) NOT NULL default '';
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_11 DEVIATION3_11  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_2 NUM_ANSWERS2_2  int(11) unsigned default NULL;
alter table EXTRA_WORK_REQUESTS change column OPTION_12 OPTION12  tinyint(1) default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_8 AVERAGE3_8  double unsigned default NULL;
alter table ass_FUNCIONARIO_HISTORICO change column codigoInterno ID_INTERNAL  int(11) NOT NULL auto_increment;
alter table ENROLMENT_EVALUATION change column KEY_MARKSHEET KEY_MARK_SHEET  int(11) default NULL;
alter table GRANT_CONTRACT_REGIME change column KEY_COST_CENTER KEY_GRANT_COST_CENTER  int(11) unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column TOLERANCE_2_6 TOLERANCE2_6  double unsigned default NULL;
alter table ROOM change column EXAM_CAPACITY CAPACIDADE_EXAME  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_COURSES_RES change column DEVIATION_2_6 DEVIATION2_6  double unsigned default NULL;
alter table EXTRA_WORK_HISTORIC change column HOURS_EXTRAWORK_PER_YEAR HOURS_EXTRA_WORK_PER_YEAR  time default NULL;
alter table SEMINARY change column ENROLLMENT_END_DATE ENROLLMENT_END  date default NULL;
alter table RESEARCH_EVENT change column LOCATION EVENT_LOCATION  varchar(50) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_4 TOLERANCE3_4  double unsigned default NULL;
alter table SEMINARY change column ENROLLMENT_BEGIN_DATE ENROLLMENT_BEGIN  date default NULL;
alter table ANNOUNCEMENT change column LAST_MODIFICATION_DATE LAST_MODIFIED_DATE  timestamp NOT NULL default '0000-00-00 00:00:00';
alter table IDENTIFICATION change column IS_PASS_KERBEROS IS_PASS_IN_KERBEROS  tinyint(1) NOT NULL default '0';
alter table CURRICULAR_COURSE_GROUP change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table INQUIRIES_COURSE change column KEY_SCHOOL_CLASS KEY_STUDENT_SCHOOL_CLASS  int(11) unsigned default NULL;
alter table GRANT_CONTRACT_MOVEMENT change column DATE_ARRIVAL ARRIVAL_DATE  date NOT NULL default '0000-00-00';
alter table REIMBURSEMENT_GUIDE change column CREATION_DATE CREATION  date NOT NULL default '0000-00-00';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_3_INTERVAL AVERAGE3_3_INTERVAL  varchar(255) default NULL;
alter table RESULT change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_6 DEVIATION3_6  double unsigned default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_11 AVERAGE3_11  double unsigned default NULL;
alter table CMS_FUNCTIONALITY_LINK change column description DESCRIPTION  text;
alter table OLD_INQUIRIES_COURSES_RES change column TOLERANCE_2_5 TOLERANCE2_5  double unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_5 AVERAGE3_5  double unsigned default NULL;
alter table CURRICULUM_MODULE change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table DEGREE_CURRICULAR_PLAN change column KEY_DEGREE_CURRICULAR_PERIOD KEY_DEGREE_STRUCTURE  int(11) default NULL;
alter table CURRICULAR_RULE change column KEY_END_EXECUTION_PERIOD KEY_END  int(11) default NULL;
alter table DEGREE_MODULE change column KEY_NEW_DEGREE_CURRICULAR_PLAN KEY_PARENT_DEGREE_CURRICULAR_PLAN  int(11) default NULL;
alter table EXTERNAL_PERSON change column KEY_UNIT KEY_INSTITUTION_UNIT  int(11) unsigned NOT NULL default '0';
alter table ass_FUNCIONARIO_HISTORICO change column quando WHEN_DATE_TIME  datetime NOT NULL default '0000-00-00 00:00:00';
alter table ass_FUNCIONARIO change column chavePessoa KEY_PERSON  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_3 NUM_ANSWERS3_3  int(11) unsigned default NULL;
alter table EXTRA_WORK_COMPENSATION change column KEY_EMPLOYEE_DB KEY_WHO_EMPLOYEE  int(11) unsigned default NULL;
alter table CURRICULUM_MODULE change column STATE ENROLLMENT_STATE  varchar(50) NOT NULL default '';
alter table DISTRIBUTED_TESTS change column TEST_END_DATE END_DATE_DATE  date default NULL;
alter table EXECUTION_DEGREE change column KEY_EXAMS_TWO KEY_PERIOD_EXAMS_SECOND_SEMESTER  int(11) default NULL;
alter table EVALUATION change column DAY DAY_DATE  date default NULL;
alter table EXECUTION_COURSE change column NAME NOME  varchar(100) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_8 AVERAGE3_8  double unsigned default NULL;
alter table GRANT_OWNER change column DATE_SEND_CGD DATE_SEND_C_G_D  date default NULL;
alter table GENERAL_CLASS_PROPERTY change column NAME NAME_STRING  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_COURSES_RES change column AVERAGE_2_4 AVERAGE2_4  double unsigned default NULL;
alter table ATTEND change column KEY_EXECUTION_COURSE KEY_DISCIPLINA_EXECUCAO  int(11) NOT NULL default '0';
alter table SEMINARY_CANDIDACY change column student_id_internal KEY_STUDENT  int(11) NOT NULL default '0';
alter table SHIFT change column CAPACITY LOTACAO  int(11) NOT NULL default '0';
alter table GRATUITY_VALUES change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table CMS_WEBSITE_ITEM change column description DESCRIPTION  text;
alter table ROOM_OCCUPATION change column START_WEEK WEEK_OF_QUINZENAL_START  int(11) default NULL;
alter table SEMINARY_CANDIDACY change column seminary_theme_id_internal KEY_THEME  int(11) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column TOTAL_N_ANSWERS TOTAL_NUMBER_ANSWERS  int(11) unsigned default NULL;
alter table ROOM_OCCUPATION change column WEEKDAY DAY_OF_WEEK  int(11) NOT NULL default '0';
alter table PARTY change column TYPE_ID_DOCUMENT ID_DOCUMENT_TYPE  varchar(50) NOT NULL default '';
alter table GROUPING change column ENROLMENT_END_DAY ENROLMENT_END_DAY_DATE  datetime default NULL;
alter table EXTRA_WORK_REQUESTS change column OPTION_9 OPTION9  tinyint(1) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column DEVIATION_3_4 DEVIATION3_4  double unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column TOLERANCE_2_2 TOLERANCE2_2  double unsigned default NULL;
alter table STUDENT_CURRICULAR_PLAN change column KEY_SPECIALIZATION_BRANCH KEY_BRANCH  int(11) default NULL;
alter table DEGREE change column CLASS_NAME_FOR_DEGREE_CURRICULAR_PLANS CONCRETE_CLASS_FOR_DEGREE_CURRICULAR_PLANS  varchar(255) default NULL;
alter table EXECUTION_DEGREE change column KEY_LESSONS_TWO KEY_PERIOD_LESSONS_SECOND_SEMESTER  int(11) default NULL;
alter table BRANCH change column BRANCH_CODE CODE  varchar(50) NOT NULL default '';
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_7 TOLERANCE3_7  double unsigned default NULL;
alter table ass_FUNCIONARIO_HISTORICO change column calendario CALENDAR  varchar(50) default '';
alter table ROOM change column NORMAL_CAPACITY CAPACIDADE_NORMAL  int(11) NOT NULL default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column TOLERANCE_3_8 TOLERANCE3_8  double unsigned default NULL;
alter table EXTRA_WORK_HISTORIC change column HOURS_EXTRAWORK_PER_DAY HOURS_EXTRA_WORK_PER_DAY  time default NULL;
alter table TEACHER_SERVICE_EXEMPTION change column END_DATE END  date default NULL;
alter table ass_CENTRO_CUSTO change column codigoInterno ID_INTERNAL  int(11) NOT NULL auto_increment;
alter table PARTY change column SEX GENDER  varchar(6) NOT NULL default '';
alter table REIMBURSEMENT_GUIDE_SITUATION change column MODIFICATION_DATE MODIFICATION  date NOT NULL default '0000-00-00';
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_9 AVERAGE3_9  double unsigned default NULL;
alter table DEGREE change column TYPE_DEGREE TIPO_CURSO  varchar(50) default NULL;
alter table SUMMARY change column EXTRA_LESSON IS_EXTRA_LESSON  tinyint(1) NOT NULL default '0';
alter table OLD_INQUIRIES_COURSES_RES change column N_ANSWERS_2_7 NUM_ANSWERS2_7  int(11) unsigned default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_11 NUM_ANSWERS3_11  int(11) unsigned default NULL;
alter table GRANT_CONTRACT_MOVEMENT change column DATE_DEPARTURE DEPARTURE_DATE  date NOT NULL default '0000-00-00';
alter table EXECUTION_DEGREE change column KEY_LESSONS_ONE KEY_PERIOD_LESSONS_FIRST_SEMESTER  int(11) default NULL;
alter table RESTRICTION change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(250) NOT NULL default '';
alter table SEMINARY_CANDIDACY change column curricular_course_id_internal KEY_CURRICULAR_COURSE  int(11) NOT NULL default '0';
alter table ass_STATUS change column estado ESTADO  enum('activo','inactivo','pendente') NOT NULL default 'activo';
alter table EXTRA_WORK change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table WEBSITE change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(250) default NULL;
alter table MONEY_COST_CENTER change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table GENERAL_CLASS_PROPERTY change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table ass_CENTRO_CUSTO change column seccao2 SECTION2  varchar(50) default NULL;
alter table FINAL_DEGREE_WORK_GROUP_PROPOSAL change column KEY_FINAL_DEGREE_WORK_GROUP KEY_FINAL_DEGREE_DEGREE_WORK_GROUP  int(11) NOT NULL default '0';
alter table ENROLMENT_EVALUATION change column RESPONSIBLE_PERSON KEY_PERSON_RESPONSIBLE_FOR_GRADE  int(11) default NULL;
alter table EVALUATION change column ENROLLMENT_END_TIME ENROLLMENT_END_TIME_DATE  time default NULL;
alter table RESEARCH_EVENT change column TYPE EVENT_TYPE  varchar(50) default NULL;
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_4 NUM_ANSWERS3_4  int(11) unsigned default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column DEVIATION_2_8 DEVIATION2_8  double unsigned default NULL;
alter table CLASS change column NAME NOME  varchar(50) NOT NULL default '';
alter table OLD_INQUIRIES_COURSES_RES change column AVERAGE_2_6 AVERAGE2_6  double unsigned default NULL;
alter table SEMINARY_CURRICULARCOURSE change column MODALITY_ID_INTERNAL KEY_MODALITY  int(11) NOT NULL default '0';
alter table SHIFT change column NAME NOME  varchar(50) NOT NULL default '';
alter table CAREER change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(250) NOT NULL default '';
alter table IDENTIFICATION change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table OLD_INQUIRIES_COURSES_RES change column DEVIATION_2_4 DEVIATION2_4  double unsigned default NULL;
alter table PARTY change column KEY_PERSON_ACCOUNT KEY_ASSOCIATED_PERSON_ACCOUNT  int(11) unsigned default NULL;
alter table CURRICULAR_RULE change column KEY_BEGIN_EXECUTION_PERIOD KEY_BEGIN  int(11) default NULL;
alter table GRANT_CONTRACT_REGIME change column DATE_SEND_DISPATCH_CD DATE_SEND_DISPATCH_C_D  date default NULL;
alter table RESULT change column PATENT_TYPE TYPE  varchar(50) default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_3_4_NUMERICAL AVERAGE3_4_NUMERICAL  double unsigned default NULL;
alter table CURRICULUM_MODULE change column KEY_NEW_STUDENT_CURRICULAR_PLAN KEY_PARENT_STUDENT_CURRICULAR_PLAN  int(11) NOT NULL default '0';
alter table ass_CENTRO_CUSTO change column seccao1 SECTION1  varchar(50) default NULL;
alter table INQUIRIES_TEACHER change column TEACHER_INTEREST_SIMULATION TEACHER_INTEREST_STIMULATION  double unsigned default NULL;
alter table MARKSHEET change column CHECKSUM CHECK_SUM  varchar(150) NOT NULL default '';
alter table EXECUTION_COURSE change column CODE SIGLA  varchar(50) NOT NULL default '';
alter table EXECUTION_DEGREE change column KEY_EXAMS_ONE KEY_PERIOD_EXAMS_FIRST_SEMESTER  int(11) default NULL;
alter table OLD_INQUIRIES_COURSES_RES change column DEVIATION_2_3 DEVIATION2_3  double unsigned default NULL;
alter table STUDENT_CURRICULAR_PLAN change column KEY_CURRICULUM_GROUP KEY_ROOT  int(11) default '0';
alter table EXTRA_WORK_REQUESTS change column WHEN_ALTER WHEN_DATE_TIME  timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table NON_AFFILIATED_TEACHER change column KEY_UNIT KEY_INSTITUTION_UNIT  int(11) unsigned default NULL;
alter table PERIOD change column END_DATE END  date NOT NULL default '0000-00-00';
alter table GRANT_ORIENTATION_TEACHER change column DATE_END END_DATE  date default NULL;
alter table OLD_INQUIRIES_SUMMARY change column AVERAGE_2_4 AVERAGE2_4  double unsigned default NULL;
alter table ACCOUNTABILITY change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(255) NOT NULL default '';
alter table ass_FUNCIONARIO change column chaveHorarioActual WORKING_HOURS  int(11) NOT NULL default '0';
alter table WEBSITE_SECTION change column KEY_WEBSITE KEY_WEB_SITE  int(11) unsigned NOT NULL default '0';
alter table EXTRA_WORK_REQUESTS change column OPTION_8 OPTION8  tinyint(1) default NULL;
alter table CONTEXT change column KEY_COURSE_GROUP KEY_PARENT_COURSE_GROUP  int(11) NOT NULL default '0';
alter table SHIFT_PROFESSORSHIP change column KEY_PROFESSOR_SHIP KEY_PROFESSORSHIP  int(11) NOT NULL default '0';
alter table RESULT change column TYPE PUBLICATION_TYPE  varchar(250) default NULL;
alter table CURRICULAR_COURSE_SCOPE change column BEGIN_DATE BEGIN  date NOT NULL default '2003-10-24';
alter table ass_FUNCIONARIO_HISTORICO change column chaveCCVencimento KEY_SALARY_COST_CENTER  int(11) default '0';
alter table OLD_INQUIRIES_TEACHERS_RES change column AVERAGE_3_3 AVERAGE3_3  varchar(255) default NULL;
alter table CMS_CONFIGURATION change column MAILING_LIST_HOST MAILING_LISTS_HOST  text NOT NULL;
alter table PARTY change column PARTY_TYPE TYPE  varchar(80) default 'UNKNOWN';
alter table LESSON change column WEEKDAY DIA_SEMANA  int(11) NOT NULL default '0';
alter table PARTY change column EXPERATION_DATE_OF_DOCUMENT_ID EXPIRATION_DATE_OF_DOCUMENT_ID  date default NULL;
alter table MASTER_DEGREE_CANDIDATE change column PERSON_KEY KEY_PERSON  int(11) NOT NULL default '0';
alter table ass_FUNCIONARIO change column antiguidade ANTIQUITY  date NOT NULL default '0000-00-00';
alter table ass_FUNCIONARIO_HISTORICO change column dataInicio BEGIN_DATE  date NOT NULL default '0000-00-00';
alter table ENROLMENT_PERIOD change column CLASS_NAME OJB_CONCRETE_CLASS  varchar(150) NOT NULL default '';
alter table OLD_INQUIRIES_TEACHERS_RES change column N_ANSWERS_3_5 NUM_ANSWERS3_5  int(11) unsigned default NULL;
alter table DISTRIBUTED_TESTS change column TEST_BEGIN_HOUR BEGIN_HOUR_DATE  time default NULL;
alter table RESTRICTION change column PERIOD_TO_APPLY PERIOD_TO_APPLY_RESTRICTION  int(11) default NULL;
