#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Alter table Academic Service Request" alterAcademicServiceRequest.sql
execute "Alter table candidacy" alterTableCandidacy.sql
execute "Alter table Event" alterTableEvent.sql
execute "Alter table Posting Rule" alterTablePostingRule.sql
execute "Alter table registration" alterTableRegistration.sql
execute "Update Permissions" updatePermissions.sql
execute "Update accountability types" updateAccountabilityTypes.sql
execute "Update REsearch Contract" updateResearchContracts.sql