#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

echo Using database: $1
echo Enter password for $2:
read -s password

echo Add new columns
mysql -u$2 -f -p$password $1 < changeMarkTable.sql
echo done.

echo Update Mark class
mysql -u$2 -f -p$password $1 < updateMarkClassName.sql > res.sql
mysql -u$2 -f -p$password $1 < res.sql
echo done.

echo Update Mark class
mysql -u$2 -f -p$password $1 < updateFinalMarkClassName.sql > res.sql
mysql -u$2 -f -p$password $1 < res.sql
echo done.