create table `TUTORSHIP_SUMMARY` (
  `DIFFICULTIES` longtext,
  `GAINS` longtext,
  `GAINS_OTHER` longtext,
  `GAINS_R1` tinyint(1),
  `GAINS_R10` tinyint(1),
  `GAINS_R2` tinyint(1),
  `GAINS_R3` tinyint(1),
  `GAINS_R4` tinyint(1),
  `GAINS_R5` tinyint(1),
  `GAINS_R6` tinyint(1),
  `GAINS_R7` tinyint(1),
  `GAINS_R8` tinyint(1),
  `GAINS_R9` tinyint(1),
  `HOW_MANY_CONTACTS_EMAIL` int(11),
  `HOW_MANY_CONTACTS_PHONE` int(11),
  `HOW_MANY_REUNIONS_GROUP` int(11),
  `HOW_MANY_REUNIONS_INDIVIDUAL` int(11),
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `OID` bigint(20),
  `OID_DEGREE` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `OID_SEMESTER` bigint(20),
  `OID_TEACHER` bigint(20),
  `PROBLEMS_OTHER` longtext,
  `PROBLEMS_R1` tinyint(1),
  `PROBLEMS_R10` tinyint(1),
  `PROBLEMS_R2` tinyint(1),
  `PROBLEMS_R3` tinyint(1),
  `PROBLEMS_R4` tinyint(1),
  `PROBLEMS_R5` tinyint(1),
  `PROBLEMS_R6` tinyint(1),
  `PROBLEMS_R7` tinyint(1),
  `PROBLEMS_R8` tinyint(1),
  `PROBLEMS_R9` tinyint(1),
  `SUGGESTIONS` longtext,
  `TUTORSHIP_SUMMARY_PROGRAM_ASSESSMENT` text,
  `TUTORSHIP_SUMMARY_SATISFACTION` text,
  primary key (ID_INTERNAL),
  index (OID),
  index (OID_DEGREE),
  index (OID_ROOT_DOMAIN_OBJECT),
  index (OID_SEMESTER),
  index (OID_TEACHER)
) type=InnoDB, character set latin1 ;

create table `TUTORSHIP_SUMMARY_PERIOD` (
  `BEGIN_DATE` text,
  `END_DATE` text,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `OID` bigint(20),
  `OID_EXECUTION_SEMESTER` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  primary key (ID_INTERNAL),
  index (OID),
  index (OID_ROOT_DOMAIN_OBJECT)
) type=InnoDB, character set latin1 ;

create table `TUTORSHIP_SUMMARY_RELATION` (
  `HIGH_PERFORMANCE` tinyint(1),
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `LOW_PERFORMANCE` tinyint(1),
  `OID` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `OID_TUTORSHIP` bigint(20),
  `OID_TUTORSHIP_SUMMARY` bigint(20),
  `OUT_OF_TOUCH` tinyint(1),
  `PARTICIPATION_NONE` tinyint(1),
  `PARTICIPATION_REGULARLY` tinyint(1),
  `PARTICIPATION_TYPE` text,
  primary key (ID_INTERNAL),
  index (OID),
  index (OID_ROOT_DOMAIN_OBJECT),
  index (OID_TUTORSHIP),
  index (OID_TUTORSHIP_SUMMARY)
) type=InnoDB, character set latin1 ;


alter table `EXECUTION_INTERVAL` add column `OID_TUTORSHIP_SUMMARY_PERIOD` bigint(20);

