ALTER TABLE LIBRARY_CARD change USER_NAME USER_NAME VARCHAR(60) DEFAULT '';
ALTER TABLE LIBRARY_CARD change UNIT_NAME UNIT_NAME VARCHAR(50) DEFAULT '';
alter table LIBRARY_CARD add column IS_CARD_EMITED tinyint(1) default 0;
alter table LIBRARY_CARD add column IS_LETTER_GENERATED tinyint(1) default 0;