select concat('update PROFESSORSHIPS set PROFESSORSHIPS.RESPONSIBLE_FOR = 1, ACK_OPT_LOCK=ACK_OPT_LOCK+1 where PROFESSORSHIPS.INTERNAL_CODE = ', PROFESSORSHIPS.INTERNAL_CODE, ';' )
	as "" From RESPONSIBLEFOR inner join PROFESSORSHIPS on RESPONSIBLEFOR.KEY_EXECUTION_COURSE = PROFESSORSHIPS.KEY_EXECUTION_COURSE
	and RESPONSIBLEFOR.KEY_TEACHER = PROFESSORSHIPS.KEY_TEACHER;