update EXECUTION_DEGREE, PERIOD set PERIOD.START_YEAR_MONTH_DAY = '2007-06-20', PERIOD.END_YEAR_MONTH_DAY = '2007-07-24'
where PERIOD.ID_INTERNAL = EXECUTION_DEGREE.KEY_PERIOD_EXAMS_SECOND_SEMESTER
and EXECUTION_DEGREE.KEY_EXECUTION_YEAR = 45;