-- Inserted at 2012-09-05T17:42:08.157+01:00

drop table REMOTE_DOMAIN_OBJECT_INDEX;
drop table ERASMUS_INDIVIDUAL_CANDIDACY_CURRICULAR_COURSES;
drop table SECOND_CYCLE_CANDIDACY_PROCESS_DEGREE;
drop table ERASMUS_CANDIDACY_EXECUTED_ACTION_ERASMUS_INDIVIDUAL_PROCESS;
drop table ERASMUS_STUDENT_DATA;
drop table REMOTE_DOMAIN_OBJECT;
drop table ERASMUS_COORDINATOR;
alter table `FILE` drop key OID_PHD_PARTICIPANT, drop key OID_INDIVIDUAL_CANDIDACY, drop OID_PHD_PARTICIPANT, drop OID_INDIVIDUAL_CANDIDACY;
alter table `STUDENT_DATA_SHARE_AUTHORIZATION` add `OID_STUDENT_FOR_STUDENTS_ASSOCIATION` bigint unsigned, add index (OID_STUDENT_FOR_STUDENTS_ASSOCIATION);
alter table `PARTY` drop AVAILABLE_PHOTO;
alter table `PRECEDENT_DEGREE_INFORMATION` add index (OID_STUDENT_CURRICULAR_PLAN);
alter table `CANDIDACY` add `STUDENT_PERSONAL_DATA_STUDENTS_ASSOCIATION_AUTHORIZATION` text;
alter table `OCCUPATION_PERIOD` drop START_YEAR_MONTH_DAY, drop END_YEAR_MONTH_DAY;
alter table `PHD_LOG_ENTRY` add index (OID_RESPONSIBLE), add index (OID_PHD_PROGRAM_PROCESS);
alter table `ABSENCE` drop GIVE_CREDITS_IF_CATEGORY_BELLOW_ASSISTANT;
alter table `EXECUTION_DEGREE` drop key OID_PERIOD_EXAMS_FIRST_SEMESTER, drop key OID_PERIOD_EXAMS_SECOND_SEMESTER, drop key OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_SECOND_SEMESTER, drop key OID_PERIOD_LESSONS_FIRST_SEMESTER, drop key OID_PERIOD_EXAMS_SPECIAL_SEASON, drop key OID_PERIOD_GRADE_SUBMISSION_SPECIAL_SEASON, drop key OID_PERIOD_LESSONS_SECOND_SEMESTER, drop key OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_FIRST_SEMESTER, drop OID_PERIOD_EXAMS_SPECIAL_SEASON, drop OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_SECOND_SEMESTER, drop OID_PERIOD_LESSONS_FIRST_SEMESTER, drop OID_PERIOD_LESSONS_SECOND_SEMESTER, drop OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_FIRST_SEMESTER, drop OID_PERIOD_GRADE_SUBMISSION_SPECIAL_SEASON, drop OID_PERIOD_EXAMS_FIRST_SEMESTER, drop OID_PERIOD_EXAMS_SECOND_SEMESTER;
alter table `PHD_GRATUITY_PAYMENT_PERIOD` drop DAY_LAST_PAYMENT, drop MONTH_LAST_PAYMENT, drop MONTH_START, drop DAY_END, drop MONTH_END, drop DAY_START;
alter table `PROGRAM` drop OID_LEARNING_AGREEMENT;
alter table `DEGREE_DESIGNATION` add `OID_INSTITUTION` bigint unsigned, add `EDUCATION_LEVEL` text, add index (OID_INSTITUTION);
alter table `SERVICE_EXEMPTION` drop GIVE_CREDITS_IF_CATEGORY_BELLOW_ASSISTANT;
alter table `GRANT_OWNER_EQUIVALENT` drop GIVE_CREDITS_IF_CATEGORY_BELLOW_ASSISTANT;



-- Inserted at 2012-09-06T14:28:34.729+01:00

drop table REMOTE_DOMAIN_OBJECT_INDEX;
drop table ERASMUS_INDIVIDUAL_CANDIDACY_CURRICULAR_COURSES;
drop table SECOND_CYCLE_CANDIDACY_PROCESS_DEGREE;
drop table ERASMUS_CANDIDACY_EXECUTED_ACTION_ERASMUS_INDIVIDUAL_PROCESS;
drop table ERASMUS_STUDENT_DATA;
drop table REMOTE_DOMAIN_OBJECT;
drop table ERASMUS_COORDINATOR;
alter table `FILE` drop key OID_PHD_PARTICIPANT, drop key OID_INDIVIDUAL_CANDIDACY, drop OID_INDIVIDUAL_CANDIDACY, drop OID_PHD_PARTICIPANT;
alter table `STUDENT_DATA_SHARE_AUTHORIZATION` drop key OID_STUDENT_FOR_STUDENTS_ASSOCIATION, drop OID_STUDENT_FOR_STUDENTS_ASSOCIATION, add `OJB_CONCRETE_CLASS` varchar(255) NOT NULL DEFAULT '';
alter table `PARTY` drop AVAILABLE_PHOTO;
alter table `PRECEDENT_DEGREE_INFORMATION` add index (OID_STUDENT_CURRICULAR_PLAN);
alter table `OCCUPATION_PERIOD` drop END_YEAR_MONTH_DAY, drop START_YEAR_MONTH_DAY;
alter table `PHD_LOG_ENTRY` add index (OID_RESPONSIBLE), add index (OID_PHD_PROGRAM_PROCESS);
alter table `ABSENCE` drop GIVE_CREDITS_IF_CATEGORY_BELLOW_ASSISTANT;
alter table `EXECUTION_DEGREE` drop key OID_PERIOD_EXAMS_FIRST_SEMESTER, drop key OID_PERIOD_EXAMS_SECOND_SEMESTER, drop key OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_SECOND_SEMESTER, drop key OID_PERIOD_LESSONS_FIRST_SEMESTER, drop key OID_PERIOD_EXAMS_SPECIAL_SEASON, drop key OID_PERIOD_GRADE_SUBMISSION_SPECIAL_SEASON, drop key OID_PERIOD_LESSONS_SECOND_SEMESTER, drop key OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_FIRST_SEMESTER, drop OID_PERIOD_LESSONS_SECOND_SEMESTER, drop OID_PERIOD_EXAMS_SECOND_SEMESTER, drop OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_SECOND_SEMESTER, drop OID_PERIOD_GRADE_SUBMISSION_NORMAL_SEASON_FIRST_SEMESTER, drop OID_PERIOD_EXAMS_SPECIAL_SEASON, drop OID_PERIOD_LESSONS_FIRST_SEMESTER, drop OID_PERIOD_GRADE_SUBMISSION_SPECIAL_SEASON, drop OID_PERIOD_EXAMS_FIRST_SEMESTER;
alter table `PHD_GRATUITY_PAYMENT_PERIOD` drop MONTH_END, drop DAY_END, drop DAY_START, drop DAY_LAST_PAYMENT, drop MONTH_LAST_PAYMENT, drop MONTH_START;
alter table `PROGRAM` drop OID_LEARNING_AGREEMENT;
alter table `DEGREE_DESIGNATION` add `OID_INSTITUTION` bigint unsigned, add `EDUCATION_LEVEL` text, add index (OID_INSTITUTION);
alter table `SERVICE_EXEMPTION` drop GIVE_CREDITS_IF_CATEGORY_BELLOW_ASSISTANT;
alter table `GRANT_OWNER_EQUIVALENT` drop GIVE_CREDITS_IF_CATEGORY_BELLOW_ASSISTANT;
