select concat('update STUDENT set STUDENT.KEY_DISLOCATED_STUDENT = ',
	DISLOCATED_STUDENT.ID_INTERNAL,' where STUDENT.ID_INTERNAL = ', 
	DISLOCATED_STUDENT.KEY_STUDENT, ';') 
as "" from DISLOCATED_STUDENT where DISLOCATED_STUDENT.KEY_STUDENT IS NOT NULL;