
ALTER TABLE CONTENT
	ADD COLUMN OLD_ID INTEGER;

INSERT INTO CONTENT (OJB_CONCRETE_CLASS, KEY_ROOT_DOMAIN_OBJECT, NAME, CREATION_DATE, PREFIX, OLD_ID)
SELECT 'net.sourceforge.fenixedu.domain.contents.TempSection', 1, C.NAME, NOW(), C.PREFIX, C.ID_INTERNAL
FROM CONTENT C
WHERE C.OJB_CONCRETE_CLASS LIKE '%Module'
  AND C.NAME NOT LIKE 'pt4:Raizen4:Root';

INSERT INTO NODE (OJB_CONCRETE_CLASS, KEY_ROOT_DOMAIN_OBJECT, KEY_PARENT, KEY_CHILD, NODE_ORDER)
SELECT 'net.sourceforge.fenixedu.domain.contents.ExplicitOrderNode', 1, CP1.ID_INTERNAL, CC1.ID_INTERNAL, N2.NODE_ORDER
FROM CONTENT CP1, CONTENT CC1, CONTENT CP2, NODE N2
WHERE CP1.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.contents.TempSection'
  AND CC1.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.contents.TempSection'
  AND CP2.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.functionalities.Module'
  AND N2.KEY_PARENT = CP2.ID_INTERNAL
  AND N2.KEY_CHILD  = CC1.OLD_ID
  AND CP1.NAME = 'pt7:Privadoen7:Private'
  AND CP1.PREFIX = '/private'
  AND CP2.KEY_MODULE_ROOT_DOMAIN_OBJECT IS NOT NULL;

INSERT INTO NODE (OJB_CONCRETE_CLASS, KEY_ROOT_DOMAIN_OBJECT, KEY_PARENT, KEY_CHILD, NODE_ORDER)
SELECT 'net.sourceforge.fenixedu.domain.contents.ExplicitOrderNode', 1, PARENT.ID_INTERNAL, CHILD.ID_INTERNAL, N.NODE_ORDER
FROM CONTENT PARENT, CONTENT CHILD, NODE N
WHERE PARENT.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.contents.TempSection'
  AND CHILD.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.contents.TempSection'
  AND N.KEY_PARENT = PARENT.OLD_ID
  AND N.KEY_CHILD  = CHILD.OLD_ID;

INSERT INTO NODE (OJB_CONCRETE_CLASS, KEY_ROOT_DOMAIN_OBJECT, KEY_PARENT, KEY_CHILD, NODE_ORDER)
SELECT 'net.sourceforge.fenixedu.domain.contents.ExplicitOrderNode', 1, PARENT.ID_INTERNAL, CHILD.ID_INTERNAL, N.NODE_ORDER
FROM CONTENT PARENT, CONTENT CHILD, NODE N
WHERE PARENT.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.contents.TempSection'
  AND CHILD.OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.functionalities.Functionality'
  AND N.KEY_PARENT = PARENT.OLD_ID
  AND N.KEY_CHILD  = CHILD.ID_INTERNAL;

ALTER TABLE CONTENT
	DROP COLUMN OLD_ID;
