#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Remove unnecessary table Equivalence CurricularCourse CurricularCourse" dropEquivalenceCurricularCourseCurricularCourseTable.sql
execute "Remove unnecessary party columns due to PartyContacts refactoring" removeUnnecessaryPartyColumns.sql
execute "Added translations to departments and scientific areas" translateAcademicUnits.sql
execute "Added some fields to support fully extra work" alterTableExtraWorkRequest.sql
execute "Fix File Entry" fixFileEntry.sql
