#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

execute "Modify column BIBLIOGRAPHIC_REFERENCES on CompetenceCourseInformation" alterTableCompetenceCourseInformation.sql
execute "Update column TYPE on Unit" updateUnit.sql > res.sql
execute "Update column TYPE on Unit" res.sql
execute "Update column TYPE on Function" updateFunctionTypes.sql 

