
alter table TEACHING_INQUIRY add column SEMESTER_END_AVERAGE_STUDENT_NUMBER_IN_LABS int(11);
alter table TEACHING_INQUIRY add column SEMESTER_END_AVERAGE_STUDENT_NUMBER_IN_PROBLEMS int(11);
alter table TEACHING_INQUIRY add column SEMESTER_END_AVERAGE_STUDENT_NUMBER_IN_PROJECT int(11);
alter table TEACHING_INQUIRY add column SEMESTER_END_AVERAGE_STUDENT_NUMBER_IN_SEMINARY int(11);
alter table TEACHING_INQUIRY add column SEMESTER_END_AVERAGE_STUDENT_NUMBER_IN_THEORICAL int(11);
alter table TEACHING_INQUIRY add column SEMESTER_MIDDLE_AVERAGE_STUDENT_NUMBER_IN_LABS int(11);
alter table TEACHING_INQUIRY add column SEMESTER_MIDDLE_AVERAGE_STUDENT_NUMBER_IN_PROBLEMS int(11);
alter table TEACHING_INQUIRY add column SEMESTER_MIDDLE_AVERAGE_STUDENT_NUMBER_IN_PROJECT int(11);
alter table TEACHING_INQUIRY add column SEMESTER_MIDDLE_AVERAGE_STUDENT_NUMBER_IN_SEMINARY int(11);
alter table TEACHING_INQUIRY add column SEMESTER_MIDDLE_AVERAGE_STUDENT_NUMBER_IN_THEORICAL int(11);
alter table TEACHING_INQUIRY add column SEMESTER_START_AVERAGE_STUDENT_NUMBER_IN_LABS int(11);
alter table TEACHING_INQUIRY add column SEMESTER_START_AVERAGE_STUDENT_NUMBER_IN_PROBLEMS int(11);
alter table TEACHING_INQUIRY add column SEMESTER_START_AVERAGE_STUDENT_NUMBER_IN_PROJECT int(11);
alter table TEACHING_INQUIRY add column SEMESTER_START_AVERAGE_STUDENT_NUMBER_IN_SEMINARY int(11);
alter table TEACHING_INQUIRY add column SEMESTER_START_AVERAGE_STUDENT_NUMBER_IN_THEORICAL int(11);
