alter table EXEMPTION_JUSTIFICATION change column KEY_PENALTY_EXEMPTION KEY_EXEMPTION int(11) NOT NULL;
alter table EXEMPTION_JUSTIFICATION change column JUSTIFICATION_TYPE PENALTY_EXEMPTION_JUSTIFICATION_TYPE varchar(255) NULL;
alter table EXEMPTION_JUSTIFICATION change column DISPATCH_DATE PENALTY_EXEMPTION_DISPATCH_DATE  varchar(10) default NULL;
alter table EXEMPTION_JUSTIFICATION add column GRATUITY_EXEMPTION_JUSTIFICATION_TYPE varchar(255) NULL;
alter table EXEMPTION_JUSTIFICATION add column GRATUITY_EXEMPTION_DISPATCH_DATE  varchar(10) default NULL;
