--  SQL file representing changes to the functionalities model
--  Generated at Thu Sep 13 12:23:36 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 238685 UUID: '72551ac3-ed0a-4e5a-8d1e-6d49dd60eb28'
DELETE FROM ap USING `AVAILABILITY_POLICY` AS ap, `ACCESSIBLE_ITEM` AS f WHERE ap.`KEY_ACCESSIBLE_ITEM` = f.`ID_INTERNAL` AND f.`UUID` = '72551ac3-ed0a-4e5a-8d1e-6d49dd60eb28';
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`KEY_AVAILABILITY_POLICY` = NULL, own.`NAME` = 'en13:Dissertationspt12:Dissertações' WHERE own.`UUID` = '72551ac3-ed0a-4e5a-8d1e-6d49dd60eb28';

COMMIT;
