DROP TABLE IF EXISTS RESEARCH_EVENT_EDITION;

CREATE TABLE `RESEARCH_EVENT_EDITION` (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `EDITION` LONGTEXT NOT NULL,
  `EVENT_LOCATION` VARCHAR(255) NOT NULL,
  `START_DATE` VARCHAR(255) NOT NULL,
  `END_DATE` VARCHAR(255),
  `ORGANIZATION` VARCHAR(255),
  `URL` VARCHAR(255),
  `KEY_EVENT` int(11) NOT NULL,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',

  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_EVENT` (`KEY_EVENT`),
  KEY `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
