ALTER TABLE DEGREE_CURRICULAR_PLAN ADD NEEDED_CREDITS DOUBLE;
ALTER TABLE DEGREE_CURRICULAR_PLAN ADD MARK_TYPE INT;


UPDATE DEGREE_CURRICULAR_PLAN SET MARK_TYPE = 20;


UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 29 WHERE ID_INTERNAL=32;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 20 WHERE ID_INTERNAL=46;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 15 WHERE ID_INTERNAL=47;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 18 WHERE ID_INTERNAL=33;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 20 WHERE ID_INTERNAL=24;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 20 WHERE ID_INTERNAL=25;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 20 WHERE ID_INTERNAL=35;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 18 WHERE ID_INTERNAL=27;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 24 WHERE ID_INTERNAL=30;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 30 WHERE ID_INTERNAL=28;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 22.5 WHERE ID_INTERNAL=37;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 22 WHERE ID_INTERNAL=40;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 20 WHERE ID_INTERNAL=43;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 24 WHERE ID_INTERNAL=44;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 24 WHERE ID_INTERNAL=45;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 20 WHERE ID_INTERNAL=36;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 23 WHERE ID_INTERNAL=34;
UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 22 WHERE ID_INTERNAL=29;
