alter table STUDENT_CURRICULAR_PLAN add SPECIALIZATION int(11);
alter table DEGREE_CURRICULAR_PLAN add KEY_DEGREE_CURRICULAR_PLAN_ENROLMENT_INFO int(11);
alter table CURRICULAR_COURSE add EXECUTION_SCOPE int(11);
alter table CURRICULAR_COURSE add MANDATORY bit;
alter table CURRICULAR_COURSE add KEY_CURRICULAR_COURSE_ENROLMENT_INFO int(11);

CREATE TABLE almeida_disc (
  codInt int(11) NOT NULL auto_increment,
  codCur int(11) default NULL,
  codRam int(11) default NULL,
  anoDis int(11) default NULL,
  semDis int(11) default NULL,
  codDis varchar(200) default NULL,
  tipo int(11) default NULL,
  teo double(11,2) default NULL,
  pra double(11,2) default NULL,
  lab double(11,2) default NULL,
  teoPra double(11,2) default NULL,
  nomeDis varchar(200) default NULL,
  PRIMARY KEY  (codInt)
) TYPE=MyISAM;

create table STUDENT_GROUP_INFO (
   ID_INTERNAL int(11) not null auto_increment,
   STUDENT_TYPE int(11) not null,
   MIN_COURSES_TO_ENROL int(11) not null,
   MAX_COURSES_TO_ENROL int(11) not null,
   MAX_NAC_TO_ENROL int(11) not null,
   primary key (ID_INTERNAL),
   unique U1 (STUDENT_TYPE)
)type=InnoDB;

CREATE TABLE almeida_inscricoes (
  codInt int(11) NOT NULL auto_increment,
  numero int(11) default NULL,
  ano int(11) default NULL,
  semestre int(11) default NULL,
  codDis varchar(200) default NULL,
  anoInscricao int(11) default NULL,
  curso int(11) default NULL,
  ramo varchar(200) default NULL,
  PRIMARY KEY  (codInt)
) TYPE=MyISAM;

create table EXAM_ROOM (
   ID_INTERNAL int(11) not null auto_increment,
   KEY_EXAM int(11) not null,
   KEY_ROOM int(11) not null,
   primary key (ID_INTERNAL),
   unique U1 (KEY_EXAM, KEY_ROOM))
   type=InnoDB;
   
   


DROP TABLE IF EXISTS COUNTRY;
CREATE TABLE COUNTRY (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  NAME varchar(50) NOT NULL default '',
  NATIONALITY varchar(50) NOT NULL default '',
  CODE varchar(10) NOT NULL default '',
  PRIMARY KEY  (ID_INTERNAL),
  UNIQUE KEY U1 (NAME),
  UNIQUE KEY U2 (NATIONALITY),
  UNIQUE KEY U3 (CODE)
) TYPE=InnoDB;

--
-- Dumping data for table 'COUNTRY'
--


INSERT INTO COUNTRY VALUES("1", "PORTUGAL", "PORTUGUESA", "PT");
INSERT INTO COUNTRY VALUES("2", "ESTRANGEIRO", "ESTRANGEIRA", "OTHER");
INSERT INTO COUNTRY VALUES("3", "ANGOLA", "ANGOLANA", "AO");
INSERT INTO COUNTRY VALUES("4", "CABO VERDE", "CABO-VERDIANA", "CV");
INSERT INTO COUNTRY VALUES("5", "GUINE-BISSAO", "GUINEENSE-BISSAU", "GW");
INSERT INTO COUNTRY VALUES("6", "MOCAMBIQUE", "MOCAMBICANA", "MZ");
INSERT INTO COUNTRY VALUES("7", "SAO TOME E PRINCIPE", "SAO TOMENSE", "ST");
INSERT INTO COUNTRY VALUES("8", "BRASIL", "BRASILEIRA", "BR");
INSERT INTO COUNTRY VALUES("9", "BELGICA", "BELGA", "BE");
INSERT INTO COUNTRY VALUES("10", "ESPANHA", "ESPANHOLA", "ES");
INSERT INTO COUNTRY VALUES("11", "FRANCA", "FRANCESA", "FR");
INSERT INTO COUNTRY VALUES("12", "HOLANDA", "HOLANDESA", "NL");
INSERT INTO COUNTRY VALUES("13", "IRLANDA", "IRLANDESA", "IE");
INSERT INTO COUNTRY VALUES("14", "ITALIA", "ITALIANA", "IT");
INSERT INTO COUNTRY VALUES("15", "LUXEMBURGO", "LUXEMBURGUESA", "LU");
INSERT INTO COUNTRY VALUES("16", "ALEMANHA", "ALEMA", "DE");
INSERT INTO COUNTRY VALUES("17", "REINO UNIDO", "BRITANICA", "GB");
INSERT INTO COUNTRY VALUES("18", "GRECIA", "GREGA", "GR");
INSERT INTO COUNTRY VALUES("19", "FINLANDIA", "FINLANDESA", "FI");
INSERT INTO COUNTRY VALUES("20", "AUSTRIA", "AUSTRIACA", "AT");
INSERT INTO COUNTRY VALUES("21", "NORUEGA", "NORUEGUESA", "NO");
INSERT INTO COUNTRY VALUES("22", "SUECIA", "SUECA", "SE");
INSERT INTO COUNTRY VALUES("23", "POLONIA", "POLACA", "PL");
INSERT INTO COUNTRY VALUES("24", "RUSSIA", "RUSSA", "RU");
INSERT INTO COUNTRY VALUES("25", "ROMENIA", "ROMENA", "RO");
INSERT INTO COUNTRY VALUES("26", "SUICA", "SUICA", "CH");
INSERT INTO COUNTRY VALUES("27", "AFRICA DO SUL", "SUL-AFRICANA", "ZA");
INSERT INTO COUNTRY VALUES("28", "MARROCOS", "MARROQUINA", "MA");
INSERT INTO COUNTRY VALUES("29", "REPUBLICA DO ZAIRE", "ZAIRENSE", "ZR");
INSERT INTO COUNTRY VALUES("30", "QUENIA", "QUENIANA", "KE");
INSERT INTO COUNTRY VALUES("31", "LIBIA", "LIBIA", "LY");
INSERT INTO COUNTRY VALUES("32", "ZIMBABUE", "ZIMBABUE", "ZW");
INSERT INTO COUNTRY VALUES("33", "PALESTINA", "PALESTINA", "PS");
INSERT INTO COUNTRY VALUES("34", "IRAO", "IRANIANA", "IR");
INSERT INTO COUNTRY VALUES("35", "PAQUISTAO", "PAQUISTANESA", "PK");
INSERT INTO COUNTRY VALUES("37", "AUSTRALIA", "AUSTRALIANA", "AU");
INSERT INTO COUNTRY VALUES("38", "ESTADOS UNIDOS DA AMERICA", "NORTE AMERICANA", "US");
INSERT INTO COUNTRY VALUES("39", "CANADA", "CANADIANA", "CA");
INSERT INTO COUNTRY VALUES("40", "ARGENTINA", "ARGENTINA", "AR");
INSERT INTO COUNTRY VALUES("41", "CHILE", "CHILENA", "CL");
INSERT INTO COUNTRY VALUES("42", "EQUADOR", "EQUATORIANO", "EC");
INSERT INTO COUNTRY VALUES("43", "VENEZUELA", "VENEZUELANA", "VE");
INSERT INTO COUNTRY VALUES("44", "MEXICO", "MEXICANA", "MX");
INSERT INTO COUNTRY VALUES("45", "BULGARIA", "BULGARA", "BG");
INSERT INTO COUNTRY VALUES("46", "COLOMBIA", "COLOMBIANA", "CO");
INSERT INTO COUNTRY VALUES("47", "ESLOVAQUIA", "ESLOVACA", "SK");
INSERT INTO COUNTRY VALUES("48", "CHINA", "CHINESA", "CN");
INSERT INTO COUNTRY VALUES("49", "TIMOR LORO SAE", "TIMORENSE", "TP");
INSERT INTO COUNTRY VALUES("50", "DINAMARCA", "DINAMARQUESA", "DK");
INSERT INTO COUNTRY VALUES("51", "IRAQUE", "IRAQUIANA", "IQ");
INSERT INTO COUNTRY VALUES("52", "PERU", "PERUANA", "PE");
INSERT INTO COUNTRY VALUES("53", "REPUBLICA CHECA", "CHECA", "CZ");



UPDATE DEGREE SET NAME = 'Engenharia Electrotécnica e de Computadores' WHERE ID_INTERNAL=24;
UPDATE DEGREE SET NAME = 'Engenharia Mecânica' WHERE ID_INTERNAL=25;
UPDATE DEGREE SET NAME = 'Gestão Estratégica e Desenvolvimento de Turismo' WHERE ID_INTERNAL=26;
UPDATE DEGREE SET NAME = 'Matemática Aplicada' WHERE ID_INTERNAL=27;
UPDATE DEGREE SET NAME = 'Georrecursos' WHERE ID_INTERNAL=28;
UPDATE DEGREE SET NAME = 'Construção' WHERE ID_INTERNAL=29;
UPDATE DEGREE SET NAME = 'Transportes' WHERE ID_INTERNAL=30;
UPDATE DEGREE SET NAME = 'Logística' WHERE ID_INTERNAL=31;
UPDATE DEGREE SET NAME = 'Engenharia e Gestão de Tecnologia' WHERE ID_INTERNAL=32;
UPDATE DEGREE SET NAME = 'Física' WHERE ID_INTERNAL=33;



#----------------------------
# Records for table DEGREE
#----------------------------

INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (34, 'MEE', 'Engenharia de Estruturas', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (35, 'MIOES', 'Investigação Operacional e Engenharia de Sistema', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (36, 'MEGMTRM', 'Ecologia, Gestão e Modelação dos Recursos Marinhos', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (37, 'MHRH', 'Hidraúlica e Recursos Hídricos', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (38, 'MB', 'Biotecnologia (Engenharia BioQuímica)', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (39, 'MEMAT', 'Engenharia de Materiais', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (40, 'MSIG', 'Sistemas de Informação Geográfica', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (41, 'MCES', 'Ciência e Engenharia de Superfícies', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (42, 'MITGI', 'Inovação Tecnológica e Gestão Industrial', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (43, 'MEIC', 'Engenharia Informática e de Computadores', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (44, 'MGT', 'Geotecnia', 2);
INSERT INTO DEGREE (ID_INTERNAL, CODE, NAME, TYPE_DEGREE) values (45, 'MUGT', 'Urbanística e Gestão do Território', 2);





#----------------------------
# Records for table TEACHER
#----------------------------


INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (12,475,127);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (13,1387,573);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (14,683,204);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (15,1787,860);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (16,2388,1443);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (17,1432,606);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (18,2080,1138);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (19,3346,2383);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (20,2729,1776);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (21,879,293);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (22,3909,2913);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (23,4121,3122);
INSERT INTO TEACHER (ID_INTERNAL, TEACHER_NUMBER, KEY_PERSON) VALUES (24,1940,1001);




#----------------------------
# Records for table PERSON_ROLE
#----------------------------

INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6691,8,127);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6692,8,573);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6693,8,204);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6694,8,860);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6695,8,1443);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6696,8,606);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6697,8,1138);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6698,8,2383);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6699,8,1776);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6700,8,293);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6701,8,2913);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6702,8,3122);
INSERT INTO PERSON_ROLE (ID_INTERNAL, KEY_ROLE, KEY_PERSON) VALUES (6703,8,1001);



#----------------------------
# Records for table DEGREE_CURRICULAR_PLAN
#----------------------------

INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (34, 'MEE02/03', 34, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (35, 'MIOES02/03', 35, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (36, 'MEGMTRM02/03', 36, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (37, 'MHRH02/03', 37, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (38, 'MB02/03', 38, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (39, 'MEMAT02/03', 39, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (40, 'MSIG02/03', 40, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (41, 'MCES02/03', 41, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (42, 'MITGI02/03', 42, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (43, 'MEIC02/03', 43, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (44, 'MGT02/03', 44, 1, NULL, NULL);
INSERT INTO DEGREE_CURRICULAR_PLAN (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE) values (45, 'MUGT02/03', 45, 1, NULL, NULL);



#----------------------------
# Records for table EXECUTION_DEGREE
#----------------------------

INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (34,1,34,13,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (35,1,35,14,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (36,1,36,15,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (37,1,37,16,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (38,1,38,17,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (39,1,39,18,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (40,1,40,19,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (41,1,41,20,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (42,1,42,21,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (43,1,43,22,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (44,1,44,23,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (45,1,45,24,NULL);


INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (46,1,24,2,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (47,1,25,6,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (48,1,27,8,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (49,1,28,5,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (50,1,29,3,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (51,1,30,4,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (52,1,31,10,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (53,1,32,9,NULL);
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (54,1,33,7,NULL);
   