alter table STUDENT_CURRICULAR_PLAN add SPECIALIZATION int(11);
alter table DEGREE_CURRICULAR_PLAN add KEY_DEGREE_CURRICULAR_PLAN_ENROLMENT_INFO int(11) not null;
alter table CURRICULAR_COURSE add MANDATORY bit;
alter table CURRICULAR_COURSE add EXECUTION_SCOPE int(11);
alter table CURRICULAR_COURSE add KEY_CURRICULAR_COURSE_ENROLMENT_INFO int(11) not null;