ALTER TABLE ASSIDUOUSNESS_CLOSED_MONTH ADD COLUMN UNJUSTIFIED_DAYS INT(2) NOT NULL DEFAULT '0';
ALTER TABLE ASSIDUOUSNESS_CLOSED_MONTH ADD COLUMN ACCUMULATED_ARTICLE66 DOUBLE NOT NULL DEFAULT '0';
ALTER TABLE ASSIDUOUSNESS_CLOSED_MONTH ADD COLUMN ACCUMULATED_UNJUSTIFIED DOUBLE NOT NULL DEFAULT '0';