


-- Inserted at 2009-05-03T17:59:26.674Z




create table `STANDALONE_ENROLMENT_CERTIFICATE_REQUEST_ENROLMENT` (KEY_ENROLMENT int(11) not null, KEY_STANDALONE_ENROLMENT_CERTIFICATE_REQUEST int(11) not null,  primary key (KEY_ENROLMENT, KEY_STANDALONE_ENROLMENT_CERTIFICATE_REQUEST), key(KEY_ENROLMENT), key(KEY_STANDALONE_ENROLMENT_CERTIFICATE_REQUEST)) type=InnoDB;
create table `EXTRA_CURRICULAR_CERTIFICATE_REQUEST_ENROLMENT` (KEY_ENROLMENT int(11) not null, KEY_EXTRA_CURRICULAR_CERTIFICATE_REQUEST int(11) not null,  primary key (KEY_ENROLMENT, KEY_EXTRA_CURRICULAR_CERTIFICATE_REQUEST), key(KEY_ENROLMENT), key(KEY_EXTRA_CURRICULAR_CERTIFICATE_REQUEST)) type=InnoDB;
