DROP TABLE IF EXISTS GENERAL_CLASS_PROPERTY;
CREATE TABLE GENERAL_CLASS_PROPERTY (
	ID_INTERNAL int(11) not null auto_increment,
	KEY_OWNER_OF_PROPERTY int(11) not null,
	CLASS_NAME varchar(255) not null,
	NAME varchar(255) not null,
	VALUE varchar(255) not null,
	ACK_OPT_LOCK int(11) not null default '1',
	PRIMARY KEY (ID_INTERNAL),
	UNIQUE U1 (KEY_OWNER_OF_PROPERTY, CLASS_NAME, NAME)
) TYPE=InnoDB;

INSERT INTO GENERAL_CLASS_PROPERTY VALUES (null, 36349, 'Dominio.classProperties.ExecutionCourseProperty', 'FASE', 'SECOND', 1);

ALTER TABLE ENROLMENT ADD CREATION_DATE datetime NOT NULL;

SELECT CONCAT('UPDATE ENROLMENT SET CREATION_DATE = "', EP.BEGIN_DATE, ' 00:00:00" WHERE ID_INTERNAL = ', E.ID_INTERNAL, ';') AS ""
FROM ENROLMENT E
INNER JOIN EXECUTION_PERIOD EP ON E.KEY_EXECUTION_PERIOD = EP.ID_INTERNAL;
