


-- Inserted at 2010-07-19T13:33:56.533+01:00


create table `DELEGATE_ELECTION_VOTING_PERIOD_VOTING_STUDENT` (OID_STUDENT bigint unsigned not null, OID_DELEGATE_ELECTION_VOTING_PERIOD bigint unsigned not null,  primary key (OID_STUDENT, OID_DELEGATE_ELECTION_VOTING_PERIOD), key(OID_STUDENT), key(OID_DELEGATE_ELECTION_VOTING_PERIOD)) type=InnoDB;

create table `DELEGATE_ELECTION_VOTING_PERIOD_STUDENT_FOR_NEW_ROUND_ELECTIONS` (OID_STUDENT bigint unsigned not null, OID_DELEGATE_ELECTION_VOTING_PERIOD bigint unsigned not null,  primary key (OID_STUDENT, OID_DELEGATE_ELECTION_VOTING_PERIOD), key(OID_STUDENT), key(OID_DELEGATE_ELECTION_VOTING_PERIOD)) type=InnoDB;

alter table `DELEGATE_ELECTION` add column `OID_DELEGATE_ELECTION_PERIOD` bigint(20);
