#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

execute "Create Student Curriculum Structure" createStudentCurriculum.sql
execute "Add Root Domain Object Keys" addRootDomainObjectKeys.sql
execute "Add Root Domain Object Relations" addRootDomainObjectRelations.sql
execute "Change Event and Project Tables" changeEventAndProjectTables.sql
