ALTER TABLE ENROLMENT_EVALUATION CHANGE COLUMN GRADE GRADE_VALUE varchar(11) default NULL, ADD GRADE varchar(50) default NULL;
ALTER TABLE EXTERNAL_ENROLMENT CHANGE COLUMN GRADE GRADE_VALUE varchar(50) NOT NULL default '', ADD GRADE varchar(50) default NULL;
ALTER TABLE CREDITS_DISMISSAL ADD GRADE varchar(50) default NULL;