--  SQL file representing changes to the functionalities model
--  Generated at Fri Dec 14 14:49:10 WET 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 252 UUID: '9cf56518-f706-4854-b28e-2108ba374c43'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt11:Comunicaçãoen9:Messaging' WHERE own.`UUID` = '9cf56518-f706-4854-b28e-2108ba374c43';

--  ID: 189877 UUID: '4cbd4716-40e1-4052-ac47-b24db983efd4'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt10:Bibliotecaen7:Library', own.`TITLE` = 'pt20:Portal da Bibliotecaen14:Library Portal' WHERE own.`UUID` = '4cbd4716-40e1-4052-ac47-b24db983efd4';

-- 
--  Inserting new functionalities
-- 

--  ID: 384519 UUID: '0892ff71-d177-41a5-adf1-e4640a7ed492'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT '0892ff71-d177-41a5-adf1-e4640a7ed492', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt17:Gestão de Estados', NULL, NULL, '/manageRegistrationState.do?method=prepare', NULL, 1, 1, NULL, 7, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = '8632c58a-c200-4fb7-ac2d-9ec68ee5635a';

COMMIT;
