
ALTER TABLE `PROCESS` add column `OID_PRESIDENT_JURY_ELEMENT` bigint(20), add index (`OID_PRESIDENT_JURY_ELEMENT`);

ALTER TABLE THESIS_JURY_ELEMENT add column `OID_PROCESS_FOR_PRESIDENT_JURY_ELEMENT` bigint(20) DEFAULT NULL;
ALTER TABLE THESIS_JURY_ELEMENT CHANGE COLUMN OID_PROCESS OID_PROCESS bigint(20) DEFAULT NULL;
ALTER TABLE THESIS_JURY_ELEMENT add index (`OID_PROCESS_FOR_PRESIDENT_JURY_ELEMENT`);
