/*
 * Created on Nov 11, 2005
 *	by mrsp
 */
package net.sourceforge.fenixedu.domain;

public enum QualificationType {
    
    DEGREE,
    DEGREE_FOREIGNER_WITH_EQUIVALENCE,
    DEGREE_FOREIGNER_WITHOUT_EQUIVALENCE,
    MASTER_DEGREE,
    MASTER_DEGREE_WITH_RECOGNITION,
    MASTER_DEGREE_FOREIGNER_WITH_EQUIVALENCE,
    MASTER_DEGREE_FOREIGNER_WITHOUT_EQUIVALENCE,
    MASTER,
    DOCTORATE_DEGREE,
    DOCTORATE_DEGREE_WITH_RECOGNITION, 
    DOCTORATE_DEGREE_WITH_REGISTER,
    DOCTORATE_DEGREE_FOREIGNER_WITH_EQUIVALENCE,
    DOCTORATE_DEGREE_FOREIGNER_WITHOUT_EQUIVALENCE,    
    BACHELOR_DEGREE,
    BACHELOR_DEGREE_FOREIGNER_WITH_EQUIVALENCE,
    BACHELOR_DEGREE_FOREIGNER_WITHOUT_EQUIVALENCE,
    
    FIRST_CLASS,
    THIRD_CLASS,
    FOUR_CLASS,
  
    SIXTH_YEAR_PREPARATORY_CYCLE,
    APCC,
    BASIC_LEVEL2,
    
    SECOND_YEAR_GERAL_COURSE_SCHOOL,
    
    FIFTH_YEAR,
    SEVEN_YEAR_INCOMPLETE,
    SEVEN_YEAR,
    EIGHTH_YEAR,
    NINETH_YEAR,
    TEN_YEAR,
    ELEVEN_YEAR,
    ELEVEN_YEAR_INCOMPLETE,
    TWELVE_YEAR,
    
    UNIVERSITY_FIRST_YEAR,
    UNIVERSITY_SECOND_YEAR,
    UNIVERSITY_THIRD_YEAR,
    UNIVERSITY_FOUR_YEAR,
    UNIVERSITY_FIVE_YEAR,
    
    PROPEDEUTICO,
    
    ACTION_FORMATION,
    AGGREGATION,   
    
    ACCOUNTING_AND_ADMINISTRATION_COMPLEMENT_COURSE,
    COURSE_COMPLEMENT,
    COURSE_COMPLEMENT_SCHOOL,
    COURSE_COMPLEMENT_SCHOOL_INCOMPLETE,    
    GERAL_COURSE,
    COMMERCE_AND_ADMINISTRATION_GERAL_COURSE,
    COMMERCE_GERAL_COURSE_INCOMPLETE,
    GERAL_COURSE_SCHOOL,
    
    SUPERIOR_COURSE_INCOMPLETE,
    
    NITH_YEAR_EQUIVALENT_FOR_PROFESSIONAL,
    ELEVEN_YEAR_EQUIVALENT_FOR_PUBLIC_FUNCTIONS,
    TWELVE_YEAR_EQUIVALENT,
    
    EQUIVALENT_FOR_PROFESSIONAL_AND_COMPLEMENTAR_COURSE,
    
    DEGREE_FREQUENCY,
    BACHELOR_FREQUENCY,
    
    PRIMARY_TEACHING;
    
    public String getName() {
        return name();
    }  
}
