alter table DEGREE_MODULE change column GRADUATE_TITLE_SUFFIX GRADUATE_TITLE_SUFFIX longtext;

update DEGREE_MODULE set GRADUATE_TITLE_SUFFIX = '__xpto__' where GRADUATE_TITLE_SUFFIX is null or GRADUATE_TITLE_SUFFIX = '';
update DEGREE_MODULE set DEGREE_MODULE.GRADUATE_TITLE_SUFFIX = concat('pt', length(replace(DEGREE_MODULE.GRADUATE_TITLE_SUFFIX, "__xpto__", "")), ':', replace(DEGREE_MODULE.GRADUATE_TITLE_SUFFIX, "__xpto__", "")); 
update DEGREE_MODULE set GRADUATE_TITLE_SUFFIX = NULL WHERE GRADUATE_TITLE_SUFFIX = "pt0:en0:" OR GRADUATE_TITLE_SUFFIX = "";
update DEGREE_MODULE set GRADUATE_TITLE_SUFFIX = replace(DEGREE_MODULE.GRADUATE_TITLE_SUFFIX, "pt0:", "");
update DEGREE_MODULE set GRADUATE_TITLE_SUFFIX = replace(DEGREE_MODULE.GRADUATE_TITLE_SUFFIX, "en0:", "");

update DEGREE_MODULE set GRADUATE_TITLE_SUFFIX = "pt22:Ciências de Engenhariaen20:Engineering Sciences" where GRADUATE_TITLE_SUFFIX = "pt22:Ciências de Engenharia";
