alter table `ASSIDUOUSNESS_CLOSED_DAY` add column `UNJUSTIFIED_DAY` tinyint(1);
alter table `ASSIDUOUSNESS_CLOSED_MONTH` add column `ACCUMULATED_ARTICLE66_DAYS` int(11);
alter table `ASSIDUOUSNESS_CLOSED_MONTH` add column `ACCUMULATED_UNJUSTIFIED_DAYS` int(11);
