update `CONTRACT_SITUATION` set HAS_MANDATORY_CREDITS = 1;
update `CONTRACT_SITUATION` set GIVE_CREDITS = 0;
update `CONTRACT_SITUATION` set MUST_HAVE_ASSOCIATED_EXEMPTION = 0;
update `GRANT_OWNER_EQUIVALENT` set HAS_MANDATORY_CREDITS = 1;
update `SERVICE_EXEMPTION` set HAS_MANDATORY_CREDITS = 1;
