ALTER TABLE THESIS
	ADD COLUMN SCIENTIFIC_AREA VARCHAR(255),
	ADD COLUMN LIBRARY_CONFIRMATION BOOLEAN DEFAULT 0,
	ADD COLUMN LIBRARY_EXPORTED BOOLEAN DEFAULT 0;

UPDATE THESIS SET LIBRARY_CONFIRMATION = 0;
UPDATE THESIS SET LIBRARY_EXPORTED = 0;
