CREATE TABLE PUBLICATION_COLLABORATORS (
  `KEY_RESEARCH_UNIT` INTEGER(11) NOT NULL,
  `KEY_PERSON` INTEGER(11) NOT NULL,
   PRIMARY KEY(`KEY_RESEARCH_UNIT`,`KEY_PERSON`),
   KEY KEY_RESEARCH_UNIT (`KEY_RESEARCH_UNIT`),
   KEY KEY_PERSON (`KEY_PERSON`)
) type=InnoDB;
