#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Create Domain Class Info table" createDomainClassInfoTable.sql
execute "Add 'Library' role" addLibraryRole.sql
execute "Add more attributes to Thesis" alterThesis.sql
execute "Add Library portal functionalities and correct some names" addLibraryEntries.sql
execute "Publication Collaborators Group" createPublicationCollaborators.sql
execute "Allowed To upload File Group" createAllowedToUploadFilesInUnit.sql
execute "Removed not null for accumulate from JustificationMotive" alterTableJustificationMotive.sql