#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Alter table Space Information" alterTableSpaceInformation.sql
execute "Fix CMS Tables" fixCmsTables.sql
execute "Alter Weight To Table Category" addWeightToTableCategory.sql
execute "Add Rectification and Rectified Columns to EnrolmentEvaluation table" alterEnrolmentEvaluationTable.sql
