UPDATE CURRICULUM_MODULE SET CURRICULUM_MODULE.WEIGTH = 3.0 WHERE CURRICULUM_MODULE.ID_INTERNAL = 137969 AND CURRICULUM_MODULE.WEIGTH = 5.0;
UPDATE CURRICULUM_MODULE SET CURRICULUM_MODULE.WEIGTH = 5.0 WHERE CURRICULUM_MODULE.ID_INTERNAL = 137963 AND CURRICULUM_MODULE.WEIGTH = 3.0;
