CREATE TABLE ENROLMENT_NOT_NEED_TO_ENROLL_IN_CURRICULAR_COURSE (
  `ID_INTERNAL` INTEGER NOT NULL AUTO_INCREMENT,
  `KEY_ENROLMENT` INTEGER(11) NOT NULL,
  `KEY_NOT_NEED_TO_ENROLL_IN_CURRICULAR_COURSE` INTEGER(11) NOT NULL,
   PRIMARY KEY(`ID_INTERNAL`),
   KEY KEY_ENROLMENT (`KEY_ENROLMENT`),
   KEY KEY_NOT_NEED_TO_ENROLL_IN_CURRICULAR_COURSE (`KEY_NOT_NEED_TO_ENROLL_IN_CURRICULAR_COURSE`)
) type=InnoDB;
