package net.sourceforge.fenixedu.domain.phd;

public enum PhdProgramCandidacyProcessState {

    PRE_CANDIDATE,

    STAND_BY_WITH_MISSING_INFORMATION,

    STAND_BY_WITH_COMPLETE_INFORMATION,

    PENDING_FOR_COORDINATOR_OPINION,

    WAITING_FOR_CIENTIFIC_COUNCIL_RATIFICATION,

    RATIFIED_BY_CIENTIFIC_COUNCIL,

    CONCLUDED;

}
