DROP TABLE IF EXISTS TX_CHANGE_LOGS;
CREATE TABLE TX_CHANGE_LOGS(
	OBJ_CLASS varchar(255) NOT NULL,
	OBJ_ID int(11) NOT NULL,
	OBJ_ATTR varchar(255) NOT NULL,
	TX_NUMBER int(11)
) TYPE=InnoDB;

DROP TABLE IF EXISTS LAST_TX_PROCESSED;
CREATE TABLE LAST_TX_PROCESSED(
        SERVER varchar(255) NOT NULL,
	LAST_TX int(11) NOT NULL,
	LAST_UPDATE timestamp
) TYPE=InnoDB;

CREATE TABLE `TRANSACTION_STATISTICS` (
  `SERVER` varchar(255) NOT NULL default '',
  `NUM_REPORT` int(11) NOT NULL,
  `NUM_READS` int(11) NOT NULL,
  `NUM_WRITES` int(11) NOT NULL,
  `NUM_ABORTS` int(11) NOT NULL,
  `NUM_CONFLICTS` int(11) NOT NULL,
  `SECONDS` int(11) NOT NULL,
  `STATS_WHEN` timestamp NOT NULL default CURRENT_TIMESTAMP
) TYPE=InnoDB;
