DROP TABLE IF EXISTS TX_CHANGE_LOGS;
CREATE TABLE TX_CHANGE_LOGS(
	OBJ_CLASS varchar(255) NOT NULL,
	OBJ_ID int(11) NOT NULL,
	OBJ_ATTR varchar(255) NOT NULL,
	TX_NUMBER int(11)
) TYPE=InnoDB;

DROP TABLE IF EXISTS LAST_TX_PROCESSED;
CREATE TABLE LAST_TX_PROCESSED(
        SERVER varchar(255) NOT NULL,
	LAST_TX int(11) NOT NULL,
	LAST_UPDATE timestamp
);
