CREATE TABLE math_RESPONSAVEIS (
ID_INTERNAL int(11) not null auto_increment,
Codigo_do_Curso VARCHAR(254),
Campus VARCHAR(254),
Nome_do_Curso VARCHAR(254),
Abreviatura_do_Curso VARCHAR(254),
Nome_da_disciplina VARCHAR(254),
Ano VARCHAR(254),
Semestre VARCHAR(254),
Tipo_de_disciplina VARCHAR(254),
Nome_da_area_cientifica VARCHAR(254),
Departamento VARCHAR(254),
Seccao VARCHAR(254),
Codigo_da_disciplina_no_IST VARCHAR(254),
Nome_da_disciplina_no_IST VARCHAR(254),
Horas_teoricas_semanais VARCHAR(254),
Horas_praticas_semanais VARCHAR(254),
Horas_laboratoriais_semanais VARCHAR(254),
Horas_de_auto_estudo_semanais VARCHAR(254),
Creditos_internos VARCHAR(254),
Creditos_ECTS VARCHAR(254),
Nome_do_responsavel VARCHAR(254),
Nome_abreviado_do_responsavel VARCHAR(254),
Telefone_do_responsavel VARCHAR(254),
Nome_da_seccao_do_responsavel VARCHAR(254),
EC_do_responsavel VARCHAR(254),
primary key (ID_INTERNAL)
) type=InnoDB;quere