-- -----------------------------
-- Data for table 'DEPARTMENT'
-- (ID_INTERNAL, NAME, CODE)
-- -----------------------------
delete from DEPARTMENT;
insert into DEPARTMENT values (1, 'Departamento de Engenharia Quimica', 'DEQ');

-- -----------------------------
-- Data for table 'DEPARTMENT_COURSE'
-- -----------------------------
-- (ID_INTERNAL, CODE, NAME, KEY_DEPARTMENT)
delete from DEPARTMENT_COURSE;
insert into DEPARTMENT_COURSE values (1, 'Disciplina Departamento', 'DD', 1);

-- -----------------------------
-- Data for table 'BRANCH'
-- (ID_INTERNAL, BRANCH_CODE, BRANCH_NAME)
-- -----------------------------
delete from BRANCH;
insert into BRANCH values (1, '', '', 1,'', 0, 0);

-- -----------------------------
-- Data for table 'DEGREE'
-- (ID_INTERNAL, CODE, NAME, TYPE_DEGREE)
-- -----------------------------
delete from DEGREE;
insert into DEGREE values (1, 'LEQ', 'Licenciatura em Engenharia Quimica', 1);

-- -----------------------------
-- Data for table 'DEGREE_CURRICULAR_PLAN'
-- (ID_INTERNAL, NAME, KEY_DEGREE, STATE, INITIAL_DATE, END_DATE, KEY_DEGREE_CURRICULAR_PLAN_ENROLMENT_INFO, DESCRIPTION, DESCRIPTION_EN)
-- -----------------------------
delete from DEGREE_CURRICULAR_PLAN;
insert into DEGREE_CURRICULAR_PLAN values (1, 'LEQ2003/2004', 1, 1, '0000-00-00', '0000-00-00', 5, 3, 20, 0, 0, null, null);

-- -----------------------------
-- Data for table 'CURRICULAR_COURSE'
-- (ID_INTERNAL, KEY_DEPARTMENT_COURSE, KEY_DEGREE_CURRICULAR_PLAN, CREDITS, THEORETICAL_HOURS, PRATICAL_HOURS, THEO_PRAT_HOURS, LAB_HOURS, 
-- NAME, CODE, TYPE, EXECUTION_SCOPE, MANDATORY, KEY_CURRICULAR_COURSE_ENROLMENT_INFO)
-- -----------------------------
-- PRIMEIRO ANO, PRIMEIRO SEMESTRE:
delete from CURRICULAR_COURSE;
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (1, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "INTRODUÇÃO À QUÍMICA-FÍSICA", "D3", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (2, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "ANÁLISE MATEMÁTICA I", "PY", 1, 1, 1, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (3, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "ÁLGEBRA LINEAR", "QN", 1, 1, 1, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (4, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "COMPUTAÇÃO E PROGRAMAÇÃO", "AZ9", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (5, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "INTRODUÇÃO À LIGAÇÃO QUÍMICA", "GU", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (6, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "LABORATÓRIO DE QUÍMICA GERAL I", "AGU", 6, 1, 0, null);
-- PRIMEIRO ANO, SEGUNDO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (7, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "QUÍMICA ORGÂNICA I", "HU", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (8, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "MECÂNICA E ONDAS", "AZH", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (9, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "ANÁLISE MATEMÁTICA II", "P5", 1, 1, 1, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (10, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "QUÍMICA DAS SOLUÇÕES AQUOSAS", "AGW", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (11, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "LABORATÓRIO DE QUÍMICA GERAL II", "AGX", 6, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (12, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "PRINCÍPIOS BÁSICOS DE ENGENHARIA DE PROCESSOS", "AH2", 1, 1, 0, null);
-- SEGUNDO ANO, PRIMEIRO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (13, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "ANÁLISE MATEMÁTICA III", "UN", 1, 1, 1, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (14, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "TERMODINÂMICA QUÍMICA", "LP", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (15, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "PROBABILIDADES E ESTATÍSTICA", "SF", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (16, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "LABORATÓRIO DE QUÍMICA ORGÂNICA", "AIF", 6, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (17, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "QUÍMICA ORGÂNICA II", "AJM", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (18, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "ELECTROMAGNETISMO E ÓPTICA", "AZI", 1, 1, 0, null);
-- SEGUNDO ANO, SEGUNDO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (19, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "FENÓMENOS DE TRANSFERÊNCIA I", "C4", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (20, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "ANÁLISE MATEMÁTICA IV", "U8", 1, 1, 1, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (21, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "QUÍMICA FÍSICA", "XW", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (22, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "TERMODINÂMICA DE ENGENHARIA QUÍMICA", "AII", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (23, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "PROCESSOS DE ENGENHARIA QUÍMICA I", "AIK", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (24, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "LABORATÓRIO DE ENGENHARIA QUÍMICA I", "AJL", 6, 1, 0, null);
-- TERCEIRO ANO, PRIMEIRO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (25, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "ANÁLISE QUÍMICA", "AN", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (26, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "FENÓMENOS DE TRANSFERÊNCIA II", "C5", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (27, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "ANÁLISE E SIMULAÇÃO NUMÉRICA", "AZ7", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (28, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "PROCESSOS DE ENGENHARIA QUÍMICA II", "AL6", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (29, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "LABORATÓRIO DE ENGENHARIA QUÍMICA II", "AL7", 6, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (30, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "MATERIAIS E CORROSÃO", "AMD", 1, 1, 0, null);
-- TERCEIRO ANO, SEGUNDO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (31, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "OPERAÇÕES EM SISTEMAS MULTIFÁSICOS", "AL8", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (32, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "LABORATÓRIO DE ENGENHARIA QUÍMICA III", "AL9", 6, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (33, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "ENGENHARIA DAS REACÇÕES I", "AME", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (34, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "FENÓMENOS DE TRANSFERÊNCIA III", "AMG", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (35, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "PROCESSOS DE SEPARAÇÃO I", "AMH", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (36, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "FUNDAMENTOS DE GESTÃO", "AX2", 1, 1, 0, null);
-- QUARTO ANO, PRIMEIRO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (37, null, 1, 4.0, 3.0, 2.0, 0.0, 2.0, "OPTIMIZAÇÃO DE PROCESSOS", "7W", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (38, null, 1, 4.0, 3.0, 0.0, 2.0, 2.0, "CONTROLO E INSTRUMENTAÇÃO DE PROCESSOS", "APK", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (39, null, 1, 4.0, 3.0, 1.0, 2.0, 2.0, "LABORATÓRIOS DE ENGENHARIA QUÍMICA IV", "APL", 6, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (40, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "ENGENHARIA DAS REACÇÕES II", "AR7", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (41, null, 1, 4.0, 3.0, 0.0, 0.0, 2.0, "PROCESSOS DE SEPARAÇÃO II", "AR8", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (42, null, 1, 4.0, 3.0, 0.0, 2.0, 0.0, "OPÇÃO I", "", 2, 1, 0, null);
-- QUARTO ANO, SEGUNDO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (43, null, 1, 4.0, 3.0, 0.0, 2.0, 0.0, "ENGENHARIA QUÍMICA INTEGRADA I", "APM", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (44, null, 1, 4.0, 3.0, 0.0, 0.0, 0.0, "SÍNTESE E INTEGRAÇÃO DE PROCESSOS", "APO", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (45, null, 1, 4.0, 3.0, 0.0, 3.0, 0.0, "LABORATÓRIOS DE ENGENHARIA QUÍMICA V", "APP", 6, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (46, null, 1, 4.0, 3.0, 0.0, 2.0, 0.0, "TECNOLOGIA AMBIENTAL", "APQ", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (47, null, 1, 4.0, 3.0, 0.0, 2.0, 0.0, "DIMENSIONAMENTO E OPTIMIZAÇÃO DE EQUIPAMENTOS E UTILIDADES", "APN", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (48, null, 1, 4.0, 3.0, 0.0, 2.0, 0.0, "OPÇÃO II", "", 2, 1, 0, null);
-- QUINTO ANO, PRIMEIRO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (49, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "PROJECTO DE INDÚSTRIAS QUÍMICAS", "AB3", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (50, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "ENGENHARIA QUÍMICA INTEGRADA II", "AV6", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (51, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "OPÇÃO III", "", 2, 1, 0, null);
-- QUINTO ANO, SEGUNDO SEMESTRE:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (52, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "ESTÁGIO", "AV2", 5, 1, 0, null);
-- QUARTO ANO, PRIMEIRO SEMESTRE, OPÇÕES:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (53, null, 1, 4.0, 3.0, 2.0, 0.0, 0.0, "RISCOS NATURAIS E TECNOLÓGICOS", "AH0", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (54, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "GESTÃO PELA QUALIDADE TOTAL", "ALE", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (55, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "ANÁLISES INDUSTRIAIS E CONTROLO", "AV7", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (56, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "LIMITES DA CIÊNCIA", "AXM", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (57, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "BIOTECNOLOGIA", "AB6", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (58, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "QUÍMICA INDUSTRIAL", "AOZ", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (59, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "ESTIMATIVA DE PROPRIEDADES PARA ENGENHARIA DE PROCESSOS", "", 1, 1, 0, null);
-- QUARTO ANO, SEGUNDO SEMESTRE, OPÇÕES:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (60, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "INVESTIGAÇÃO OPERACIONAL", "EA", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (61, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "PREVISÃO DE PROPRIEDADES", "ZC", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (62, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "TRATAMENTO DE EFLUENTES GASOSOS", "AEV", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (63, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "ESTUDOS DE CIÊNCIA:ARTE,TECNOLOGIA E SOCIEDADE", "AP9", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (64, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "GESTÃO, TRATAMENTO E VALORIZAÇÃO DE RESÍDUOS", "APR", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (65, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "SUPERVISÃO E DIAGNÓSTICO DE PROCESSOS", "APU", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (66, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "GESTÃO DA PRODUÇÃO E DAS OPERAÇÕES", "APW", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (67, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "SISTEMAS DE GESTÃO AMBIENTAL", "AV8", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (68, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "MODELAÇÃO E OPTIMIZAÇÃO DE SISTEMAS DINÂMICOS", "AX3", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (69, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "CIÊNCIA E TECNOLOGIA DE POLÍMEROS", "AXN", 1, 1, 0, null);
-- QUINTO ANO, PRIMEIRO SEMESTRE, OPÇÕES:
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (70, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "TECNOLOGIA ALIMENTAR", "AI", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (71, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "REFINAÇÃO DE PETRÓLEOS E PETROQUÍMICA", "IF", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (72, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "MODELOS MULTICRITÉRIO DE APOIO À DECISÃO", "AJA", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (73, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "SEGURANÇA E HIGIENE INDUSTRIAL", "APB", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (74, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "CONTROLO DE QUALIDADE", "APS", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (75, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "CONTROLO AVANÇADO DE PROCESSOS", "APT", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (76, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "CARACTERÍSTICAS E TRATAMENTO DE ÁGUAS", "AET", 1, 1, 0, null);
INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (77, null, 1, 4.0, 0.0, 0.0, 0.0, 0.0, "ENGENHARIA DE SUPERFÍCIES", "APY", 1, 1, 0, null);

-- -----------------------------
-- Data for table 'CURRICULAR_COURSE_SCOPE'
-- (ID_INTERNAL, KEY_CURRICULAR_SEMESTER, KEY_CURRICULAR_COURSE, KEY_BRANCH, THEORETICAL_HOURS, PRATICAL_HOURS, THEO_PRAT_HOURS, LAB_HOURS,
--  MAX_INCREMENT_NAC,  MIN_INCREMENT_NAC, WEIGTH)
-- -----------------------------
delete from CURRICULAR_COURSE_SCOPE;
insert into CURRICULAR_COURSE_SCOPE  values (1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (2, 1, 2, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (3, 1, 3, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (4, 1, 4, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (5, 1, 5, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (6, 1, 6, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (7, 2, 7, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (8, 2, 8, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (9, 2, 9, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (10, 2, 10, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (11, 2, 11, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (12, 2, 12, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (13, 3, 13, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (14, 3, 14, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (15, 3, 15, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (16, 3, 16, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (17, 3, 17, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (18, 3, 18, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (19, 4, 19, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (20, 4, 20, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (21, 4, 21, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (22, 4, 22, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (23, 4, 23, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (24, 4, 24, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (25, 5, 25, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (26, 5, 26, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (27, 5, 27, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (28, 5, 28, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (29, 5, 29, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (30, 5, 30, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (31, 6, 31, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (32, 6, 32, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (33, 6, 33, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (34, 6, 34, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (35, 6, 35, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (36, 6, 36, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (37, 7, 37, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (38, 7, 38, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (39, 7, 39, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (40, 7, 40, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (41, 7, 41, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (42, 7, 42, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (43, 8, 43, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (44, 8, 44, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (45, 8, 45, 1, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, null);
insert into CURRICULAR_COURSE_SCOPE  values (46, 8, 46, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (47, 8, 47, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (48, 8, 48, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (49, 9, 49, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (50, 9, 50, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (51, 9, 51, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (52, 10, 52, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);

-- bianuais matemáticas
insert into CURRICULAR_COURSE_SCOPE  values (53, 2, 2, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (54, 2, 3, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (55, 1, 9, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (56, 4, 13, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (57, 3, 20, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);

-- bianuais quimica
insert into CURRICULAR_COURSE_SCOPE  values (58, 2, 1, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (59, 1, 10, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (60, 1, 7, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (61, 4, 17, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (62, 4, 14, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (63, 3, 22, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (64, 3, 19, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (65, 6, 26, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (66, 5, 34, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);

-- opções
insert into CURRICULAR_COURSE_SCOPE  values (67, 7, 53, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (68, 7, 54, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (69, 7, 55, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (70, 7, 56, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (71, 7, 57, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (72, 7, 58, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (73, 7, 59, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (74, 8, 60, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (75, 8, 61, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (76, 8, 62, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (77, 8, 63, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (78, 8, 64, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (79, 8, 65, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (80, 8, 66, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (81, 8, 67, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (82, 8, 68, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (83, 8, 69, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (84, 9, 70, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (85, 9, 71, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (86, 9, 72, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (87, 9, 73, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (88, 9, 74, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (89, 9, 75, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (90, 9, 76, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);
insert into CURRICULAR_COURSE_SCOPE  values (91, 9, 77, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1, null);

-- -----------------------------
-- Data for table 'POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE'
-- (ID_INTERNAL, KEY_POSSIBLE_CURRICULAR_COURSE, KEY_OPTIONAL_CURRICULAR_COURSE)
-- -----------------------------
delete from POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE;
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (1, 53, 42);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (2, 54, 42);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (3, 55, 42);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (4, 56, 42);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (5, 57, 42);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (6, 58, 42);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (7, 59, 42);

insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (8, 60, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (9, 61, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (10, 62, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (11, 63, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (12, 64, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (13, 65, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (14, 66, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (15, 67, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (16, 68, 48);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (17, 69, 48);

insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (18, 70, 51);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (19, 71, 51);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (20, 72, 51);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (21, 73, 51);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (22, 74, 51);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (23, 75, 51);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (24, 76, 51);
insert into POSSIBLE_CURRICULAR_COURSE_FOR_OPTIONAL_CURRICULAR_COURSE values (25, 77, 51);

-- -----------------------------
-- Data for table 'PRECEDENCE'
-- -----------------------------
-- (ID_INTERNAL, KEY_CURRICULAR_COURSE, SCOPE_TO_APPLY)
delete from PRECEDENCE;
-- precedencias do tipo Dominio.RestrictionCurricularCourseDone
insert into PRECEDENCE values (1, 14, 'SP');
insert into PRECEDENCE values (2, 17, 'SP');
insert into PRECEDENCE values (3, 22, 'SP');
insert into PRECEDENCE values (4, 19, 'SP');
insert into PRECEDENCE values (5, 21, 'SP');
insert into PRECEDENCE values (6, 26, 'SP');
insert into PRECEDENCE values (7, 25, 'SP');
insert into PRECEDENCE values (8, 34, 'SP');
insert into PRECEDENCE values (9, 24, 'SP');
insert into PRECEDENCE values (10, 9, 'SP');
insert into PRECEDENCE values (11, 13, 'SP');
insert into PRECEDENCE values (12, 20, 'SP');

-- precedencias do tipo Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse
insert into PRECEDENCE values (13, 10, 'ENR');
insert into PRECEDENCE values (14, 12, 'ENR');
insert into PRECEDENCE values (15, 7, 'ENR');
insert into PRECEDENCE values (16, 14, 'ENR');
insert into PRECEDENCE values (17, 26, 'ENR');
insert into PRECEDENCE values (18, 25, 'ENR');
insert into PRECEDENCE values (19, 34, 'ENR');

-- precedencias para os laboratorios
insert into PRECEDENCE values (20, 6, 'ENR');
insert into PRECEDENCE values (21, 11, 'ENR');
insert into PRECEDENCE values (22, 16, 'ENR');
insert into PRECEDENCE values (23, 24, 'SP');
insert into PRECEDENCE values (24, 29, 'ENR');
insert into PRECEDENCE values (25, 32, 'ENR');
insert into PRECEDENCE values (26, 39, 'ENR');
insert into PRECEDENCE values (27, 45, 'ENR');

-- precedencias especial entre as cadeiras "ESTUDOS DE CIÊNCIA:ARTE,TECNOLOGIA E SOCIEDADE" e "LIMITES DA CIÊNCIA"
insert into PRECEDENCE values (28, 63, 'OP');
insert into PRECEDENCE values (29, 56, 'OP');

-- -----------------------------
-- Data for table 'RESTRICTION'
-- -----------------------------
-- (ID_INTERNAL, CLASS_NAME, KEY_PRECEDENCE, KEY_CURRICULAR_COURSE, NUMBER_OF_CURRICULAR_COURSE_DONE)
delete from RESTRICTION;
insert into RESTRICTION values (1, 'Dominio.RestrictionCurricularCourseDone', 1, 1, 0);
insert into RESTRICTION values (2, 'Dominio.RestrictionCurricularCourseDone', 2, 7, 0);
insert into RESTRICTION values (3, 'Dominio.RestrictionCurricularCourseDone', 3, 14, 0);
insert into RESTRICTION values (4, 'Dominio.RestrictionCurricularCourseDone', 4, 3, 0);
insert into RESTRICTION values (5, 'Dominio.RestrictionCurricularCourseDone', 4, 9, 0);
insert into RESTRICTION values (6, 'Dominio.RestrictionCurricularCourseDone', 5, 3, 0);
insert into RESTRICTION values (7, 'Dominio.RestrictionCurricularCourseDone', 6, 19, 0);
insert into RESTRICTION values (8, 'Dominio.RestrictionCurricularCourseDone', 7, 10, 0);
insert into RESTRICTION values (9, 'Dominio.RestrictionCurricularCourseDone', 8, 19, 0);
insert into RESTRICTION values (10, 'Dominio.RestrictionCurricularCourseDone', 9, 11, 0);
insert into RESTRICTION values (11, 'Dominio.RestrictionCurricularCourseDone', 10, 2, 0);
insert into RESTRICTION values (12, 'Dominio.RestrictionCurricularCourseDone', 11,9, 0);
insert into RESTRICTION values (13, 'Dominio.RestrictionCurricularCourseDone', 12, 13, 0);

insert into RESTRICTION values (14, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 13, 1, 0);
insert into RESTRICTION values (15, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 14, 1, 0);
insert into RESTRICTION values (16, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 15, 1, 0);
insert into RESTRICTION values (17, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 15, 5, 0);
insert into RESTRICTION values (18, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 16, 9, 0);
insert into RESTRICTION values (19, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 17, 13, 0);
insert into RESTRICTION values (20, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 18, 15, 0);
insert into RESTRICTION values (21, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 19, 20, 0);
insert into RESTRICTION values (22, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 19, 26, 0);

insert into RESTRICTION values (23, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 20, 5, 0);
insert into RESTRICTION values (24, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 21, 1, 0);
insert into RESTRICTION values (25, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 21, 10, 0);
insert into RESTRICTION values (26, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 22, 7, 0);
insert into RESTRICTION values (27, 'Dominio.RestrictionCurricularCourseDone', 23, 12, 0);
insert into RESTRICTION values (28, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 24, 22, 0);
insert into RESTRICTION values (29, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 24, 30, 0);
insert into RESTRICTION values (30, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 25, 31, 0);
insert into RESTRICTION values (31, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 25, 33, 0);
insert into RESTRICTION values (32, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 26, 35, 0);
insert into RESTRICTION values (33, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 26, 41, 0);
insert into RESTRICTION values (34, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 27, 40, 0);
insert into RESTRICTION values (35, 'Dominio.RestrictionAlreadyOrActuallyEnroledInCurricularCourse', 27, 38, 0);

insert into RESTRICTION values (36, 'Dominio.RestrictionCurricularCourseNotDone', 28, 56, 0);
insert into RESTRICTION values (37, 'Dominio.RestrictionCurricularCourseNotDone', 29, 63, 0);

-- -----------------------------
-- Data for table 'ENROLMENT'
-- (ID_INTERNAL, KEY_STUDENT_CURRICULAR_PLAN, KEY_CURRICULAR_COURSE, KEY_EXECUTION_PERIOD, STATE, CLASS_NAME, KEY_CURRICULAR_COURSE_FOR_OPTION
-- EVALUATION_TYPE, UNIVERSITY_CODE)

-- -----------------------------
delete from ENROLMENT;
insert into ENROLMENT values (1, 1, 1, 1, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (2, 1, 2, 1, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (3, 1, 3, 1, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (4, 1, 4, 1, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (5, 1, 5, 1, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (6, 1, 6, 1, 1, 'Dominio.Enrolment', null, 1);

insert into ENROLMENT values (7, 1, 7, 2, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (8, 1, 8, 2, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (9, 1, 9, 2, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (10, 1, 10, 2, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (11, 1, 11, 2, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (12, 1, 12, 2, 1, 'Dominio.Enrolment', null, 1);

insert into ENROLMENT values (13, 1, 13, 3, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (14, 1, 14, 3, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (15, 1, 15, 3, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (16, 1, 16, 3, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (17, 1, 17, 3, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (18, 1, 18, 3, 1, 'Dominio.Enrolment', null, 1);

insert into ENROLMENT values (19, 1, 19, 4, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (20, 1, 20, 4, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (21, 1, 21, 4, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (22, 1, 22, 4, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (23, 1, 23, 4, 1, 'Dominio.Enrolment', null, 1);
insert into ENROLMENT values (24, 1, 24, 4, 1, 'Dominio.Enrolment', null, 1);

-- insert into ENROLMENT values (25, 1, 25, 5, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (26, 1, 26, 5, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (27, 1, 27, 5, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (28, 1, 28, 5, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (29, 1, 29, 5, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (30, 1, 30, 5, 1, 'Dominio.Enrolment', null, 1);

-- insert into ENROLMENT values (31, 1, 31, 6, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (32, 1, 32, 6, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (33, 1, 33, 6, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (34, 1, 34, 6, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (35, 1, 35, 6, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (36, 1, 36, 6, 1, 'Dominio.Enrolment', null, 1);

-- insert into ENROLMENT values (37, 1, 37, 7, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (38, 1, 38, 7, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (39, 1, 39, 7, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (40, 1, 40, 7, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (41, 1, 41, 7, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (42, 1, 42, 7, 1, 'Dominio.EnrolmentInOptionalCurricularCourse', 56, 1);

-- insert into ENROLMENT values (43, 1, 43, 8, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (44, 1, 44, 8, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (45, 1, 45, 8, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (46, 1, 46, 8, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (47, 1, 47, 8, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (48, 1, 48, 8, 1, 'Dominio.EnrolmentInOptionalCurricularCourse', null, 1);

-- insert into ENROLMENT values (49, 1, 49, 9, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (50, 1, 50, 9, 1, 'Dominio.Enrolment', null, 1);
-- insert into ENROLMENT values (51, 1, 51, 9, 1, 'Dominio.EnrolmentInOptionalCurricularCourse', 70, 1);

-- -----------------------------
-- Data for table 'EXECUTION_DEGREE'
-- -----------------------------
DELETE FROM EXECUTION_DEGREE;
INSERT INTO EXECUTION_DEGREE VALUES (1, 1, 1, 1, 1);

-- INSERT INTO CURRICULAR_COURSE  ( ID_INTERNAL,KEY_DEPARTMENT_COURSE,KEY_DEGREE_CURRICULAR_PLAN,CREDITS,THEORETICAL_HOURS,PRATICAL_HOURS,THEO_PRAT_HOURS,LAB_HOURS,NAME,CODE,`TYPE`,EXECUTION_SCOPE,MANDATORY,KEY_UNIVERSITY) VALUES (1178, null, 1, 4.0, 3.0, 0.0, 2.0, 0.0, "OPÇÃO IV", "", 2, 1, 0, null);
-- insert into CURRICULAR_COURSE_SCOPE  values (1192, 7, 1178, 1, 0.0, 0.0, 0.0, 0.0, 2, 1, 1);
-- INSERT INTO EXECUTION_COURSE VALUES (1000,'OPÇÃO IV','APR',0,0,0,0, 2, 5,"");
-- INSERT INTO CURRICULAR_COURSE_EXECUTION_COURSE VALUES (1000, 1178, 1000);
