
insert into PARTY (ID_INTERNAL, DOCUMENT_ID_NUMBER, NAME, ID_DOCUMENT_TYPE, GENDER, MARITAL_STATUS,
    AVAILABLE_EMAIL, AVAILABLE_WEB_SITE, AVAILABLE_PHOTO, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS,
    BEGIN_DATE_YEAR_MONTH_DAY, KEY_ROOT_DOMAIN_OBJECT_FOR_INSTITUTION_UNIT, KEY_ROOT_DOMAIN_OBJECT_FOR_EXTERNAL_INSTITUTION_UNIT)
    values (1, '', 'Instituições Externas', '', '', '', 0, 0, 0, 1,
        'net.sourceforge.fenixedu.domain.organizationalStructure.Unit', CURRENT_DATE, 1, 1);

insert into PARTY (ID_INTERNAL, DOCUMENT_ID_NUMBER, NAME, ID_DOCUMENT_TYPE, GENDER, MARITAL_STATUS,
    AVAILABLE_EMAIL, AVAILABLE_WEB_SITE, AVAILABLE_PHOTO, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS,
    BEGIN_DATE_YEAR_MONTH_DAY, KEY_ROOT_DOMAIN_OBJECT_FOR_INSTITUTION_UNIT, KEY_ROOT_DOMAIN_OBJECT_FOR_EXTERNAL_INSTITUTION_UNIT)
    values (2, '', 'Instituto Superior Tcnico (IST)', '', '', '', 0, 0, 0, 1,
        'net.sourceforge.fenixedu.domain.organizationalStructure.Unit', CURRENT_DATE, 1, 1);

update ROOT_DOMAIN_OBJECT set KEY_EXTERNAL_INSTITUTION_UNIT = 1, KEY_INSTITUTION_UNIT = 2;
