
insert into PARTY (ID_INTERNAL, DOCUMENT_ID_NUMBER, NAME, ID_DOCUMENT_TYPE, GENDER, MARITAL_STATUS,
    AVAILABLE_EMAIL, AVAILABLE_WEB_SITE, AVAILABLE_PHOTO, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS,
    BEGIN_DATE_YEAR_MONTH_DAY, KEY_ROOT_DOMAIN_OBJECT_FOR_INSTITUTION_UNIT, KEY_ROOT_DOMAIN_OBJECT_FOR_EXTERNAL_INSTITUTION_UNIT)
    values (1, '', 'Instituições Externas', '', '', '', 0, 0, 0, 1,
        'net.sourceforge.fenixedu.domain.organizationalStructure.Unit', CURRENT_DATE, 1, 1);

insert into PARTY (ID_INTERNAL, DOCUMENT_ID_NUMBER, NAME, ID_DOCUMENT_TYPE, GENDER, MARITAL_STATUS,
    AVAILABLE_EMAIL, AVAILABLE_WEB_SITE, AVAILABLE_PHOTO, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS,
    BEGIN_DATE_YEAR_MONTH_DAY, KEY_ROOT_DOMAIN_OBJECT_FOR_INSTITUTION_UNIT, KEY_ROOT_DOMAIN_OBJECT_FOR_EXTERNAL_INSTITUTION_UNIT)
    values (2, '', 'Instituto Superior Tcnico (IST)', '', '', '', 0, 0, 0, 1,
        'net.sourceforge.fenixedu.domain.organizationalStructure.Unit', CURRENT_DATE, 1, 1);

update ROOT_DOMAIN_OBJECT set KEY_EXTERNAL_INSTITUTION_UNIT = 1, KEY_INSTITUTION_UNIT = 2;

insert into ACCOUNTABILITY_TYPE (ID_INTERNAL, TYPE, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS, NAME, FUNCTION_TYPE,
    BEGIN_DATE_YEAR_MONTH_DAY, END_DATE_YEAR_MONTH_DAY, KEY_UNIT, KEY_PARENT_INHERENT_FUNCTION)
values (1,'ORGANIZATIONAL_STRUCTURE',1,'net.sourceforge.fenixedu.domain.organizationalStructure.AccountabilityType',
        'ORGANIZATIONAL_STRUCTURE','',NULL,NULL,NULL,NULL);

insert into ACCOUNTABILITY_TYPE (ID_INTERNAL, TYPE, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS, NAME, FUNCTION_TYPE,
    BEGIN_DATE_YEAR_MONTH_DAY, END_DATE_YEAR_MONTH_DAY, KEY_UNIT, KEY_PARENT_INHERENT_FUNCTION)
values (2,'MANAGEMENT_FUNCTION',1,'net.sourceforge.fenixedu.domain.organizationalStructure.AccountabilityType',
        'MANAGEMENT_FUNCTION','',NULL,NULL,NULL,NULL);

insert into ACCOUNTABILITY_TYPE (ID_INTERNAL, TYPE, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS, NAME, FUNCTION_TYPE,
    BEGIN_DATE_YEAR_MONTH_DAY, END_DATE_YEAR_MONTH_DAY, KEY_UNIT, KEY_PARENT_INHERENT_FUNCTION)
values (3,'ACADEMIC_STRUCTURE',1,'net.sourceforge.fenixedu.domain.organizationalStructure.AccountabilityType',
        'ACADEMIC_STRUCTURE','',NULL,NULL,NULL,NULL);

insert into ACCOUNTABILITY_TYPE (ID_INTERNAL, TYPE, KEY_ROOT_DOMAIN_OBJECT, OJB_CONCRETE_CLASS, NAME, FUNCTION_TYPE,
    BEGIN_DATE_YEAR_MONTH_DAY, END_DATE_YEAR_MONTH_DAY, KEY_UNIT, KEY_PARENT_INHERENT_FUNCTION)
values (4,'EMPLOYEE_CONTRACT',1,'net.sourceforge.fenixedu.domain.organizationalStructure.AccountabilityType',
        'EMPLOYEE_CONTRACT','',NULL,NULL,NULL,NULL);
