ALTER TABLE ENROLMENT_EVALUATION ADD COLUMN `BOOK_REFERENCE` varchar(255),
				ADD COLUMN `PAGE` varchar(50),
				ADD COLUMN `CONTEXT` varchar(255),
				ADD COLUMN `CURRICULUM_VALIDATION_EVALUATION_PHASE` varchar(255),
				ADD COLUMN `GRADE_SCALE` varchar(255);

ALTER TABLE STUDENT_CURRICULAR_PLAN ADD COLUMN `END_STAGE_DATE` varchar(10);
