
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao.velhos;


public class Leq_restriction  
{
  private String class_name;

  private long id_internal;

  private long key_cc;

  private long key_leq_precedence;

  private long number_of_curricular_course_done;

  public String getClass_name()
  {
     return this.class_name;
  }
  public void setClass_name(String param)
  {
    this.class_name = param;
  }


  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public long getKey_cc()
  {
     return this.key_cc;
  }
  public void setKey_cc(long param)
  {
    this.key_cc = param;
  }


  public long getKey_leq_precedence()
  {
     return this.key_leq_precedence;
  }
  public void setKey_leq_precedence(long param)
  {
    this.key_leq_precedence = param;
  }


  public long getNumber_of_curricular_course_done()
  {
     return this.number_of_curricular_course_done;
  }
  public void setNumber_of_curricular_course_done(long param)
  {
    this.number_of_curricular_course_done = param;
  }


  public String toString(){
    return  " [CLASS_NAME] " + class_name + " [ID_INTERNAL] " + id_internal + " [KEY_CC] " + key_cc + " [KEY_LEQ_PRECEDENCE] " + key_leq_precedence + " [NUMBER_OF_CURRICULAR_COURSE_DONE] " + number_of_curricular_course_done;

  }
}

