
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao.velhos;


public class Leq_new_curricular_course  
{
  private String code;

  private double credits;

  private long execution_scope;

  private long id_internal;

  private long key_curricular_course_enrolment_info;

  private long key_degree_curricular_plan;

  private long key_department_course;

  private double lab_hours;

  private long mandatory;

  private String name;

  private double pratical_hours;

  private double theoretical_hours;

  private double theo_prat_hours;

  private long type;

  public String getCode()
  {
     return this.code;
  }
  public void setCode(String param)
  {
    this.code = param;
  }


  public double getCredits()
  {
     return this.credits;
  }
  public void setCredits(double param)
  {
    this.credits = param;
  }


  public long getExecution_scope()
  {
     return this.execution_scope;
  }
  public void setExecution_scope(long param)
  {
    this.execution_scope = param;
  }


  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public long getKey_curricular_course_enrolment_info()
  {
     return this.key_curricular_course_enrolment_info;
  }
  public void setKey_curricular_course_enrolment_info(long param)
  {
    this.key_curricular_course_enrolment_info = param;
  }


  public long getKey_degree_curricular_plan()
  {
     return this.key_degree_curricular_plan;
  }
  public void setKey_degree_curricular_plan(long param)
  {
    this.key_degree_curricular_plan = param;
  }


  public long getKey_department_course()
  {
     return this.key_department_course;
  }
  public void setKey_department_course(long param)
  {
    this.key_department_course = param;
  }


  public double getLab_hours()
  {
     return this.lab_hours;
  }
  public void setLab_hours(double param)
  {
    this.lab_hours = param;
  }


  public long getMandatory()
  {
     return this.mandatory;
  }
  public void setMandatory(long param)
  {
    this.mandatory = param;
  }


  public String getName()
  {
     return this.name;
  }
  public void setName(String param)
  {
    this.name = param;
  }


  public double getPratical_hours()
  {
     return this.pratical_hours;
  }
  public void setPratical_hours(double param)
  {
    this.pratical_hours = param;
  }


  public double getTheoretical_hours()
  {
     return this.theoretical_hours;
  }
  public void setTheoretical_hours(double param)
  {
    this.theoretical_hours = param;
  }


  public double getTheo_prat_hours()
  {
     return this.theo_prat_hours;
  }
  public void setTheo_prat_hours(double param)
  {
    this.theo_prat_hours = param;
  }


  public long getType()
  {
     return this.type;
  }
  public void setType(long param)
  {
    this.type = param;
  }


  public String toString(){
    return  " [CODE] " + code + " [CREDITS] " + credits + " [EXECUTION_SCOPE] " + execution_scope + " [ID_INTERNAL] " + id_internal + " [KEY_CURRICULAR_COURSE_ENROLMENT_INFO] " + key_curricular_course_enrolment_info + " [KEY_DEGREE_CURRICULAR_PLAN] " + key_degree_curricular_plan + " [KEY_DEPARTMENT_COURSE] " + key_department_course + " [LAB_HOURS] " + lab_hours + " [MANDATORY] " + mandatory + " [NAME] " + name + " [PRATICAL_HOURS] " + pratical_hours + " [THEORETICAL_HOURS] " + theoretical_hours + " [THEO_PRAT_HOURS] " + theo_prat_hours + " [TYPE] " + type;

  }
}

