
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao.velhos;


public class Leq_branch  
{
  private String branch_code;

  private String branch_name;

  private long id_internal;

  public String getBranch_code()
  {
     return this.branch_code;
  }
  public void setBranch_code(String param)
  {
    this.branch_code = param;
  }


  public String getBranch_name()
  {
     return this.branch_name;
  }
  public void setBranch_name(String param)
  {
    this.branch_name = param;
  }


  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public String toString(){
    return  " [BRANCH_CODE] " + branch_code + " [BRANCH_NAME] " + branch_name + " [ID_INTERNAL] " + id_internal;

  }
}

