#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}


execute "Creating Table AccountingTransactionDetail" CreateTableAccountingTransactionDetail.sql
execute "Migration AccountingTransaction columns to AccountingTransactionDetail" MigrateAccountingTransactionDetails.sql
executeWithTempFile "Update AccountingTransaction with AccountingTransactionDetails" UpdateAccountingTransactionWithDetails.sql
execute "Creating Module Payments on Manager" AddPaymentsModuleToManager.sql
execute "Changing Table AccountingTransaction (add not null restriction to keyTransactionDetails)" AlterTableAccountingTransactionAfterMigration.sql
execute "Changing Table Student" AlterTableStudent.sql
