
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.thor;

import Dominio.DomainObject;


public class Atribuicaodisciplinas extends DomainObject 
{
  private long alunosdivisao;

  private String disciplina;

  private double horasaula;

  private long horasdadas;

  private double horasmax;

  private long numdivisao;

  private long numepoca;

  private String salapreferencial;

  private String tipoaula;

  private String turma;

  public long getAlunosdivisao()
  {
     return this.alunosdivisao;
  }
  public void setAlunosdivisao(long param)
  {
    this.alunosdivisao = param;
  }


  public String getDisciplina()
  {
     return this.disciplina;
  }
  public void setDisciplina(String param)
  {
    this.disciplina = param;
  }


  public double getHorasaula()
  {
     return this.horasaula;
  }
  public void setHorasaula(double param)
  {
    this.horasaula = param;
  }


  public long getHorasdadas()
  {
     return this.horasdadas;
  }
  public void setHorasdadas(long param)
  {
    this.horasdadas = param;
  }


  public double getHorasmax()
  {
     return this.horasmax;
  }
  public void setHorasmax(double param)
  {
    this.horasmax = param;
  }


  public long getNumdivisao()
  {
     return this.numdivisao;
  }
  public void setNumdivisao(long param)
  {
    this.numdivisao = param;
  }


  public long getNumepoca()
  {
     return this.numepoca;
  }
  public void setNumepoca(long param)
  {
    this.numepoca = param;
  }


  public String getSalapreferencial()
  {
     return this.salapreferencial;
  }
  public void setSalapreferencial(String param)
  {
    this.salapreferencial = param;
  }


  public String getTipoaula()
  {
     return this.tipoaula;
  }
  public void setTipoaula(String param)
  {
    this.tipoaula = param;
  }


  public String getTurma()
  {
     return this.turma;
  }
  public void setTurma(String param)
  {
    this.turma = param;
  }


  public String toString(){
    return  " [AlunosDivisao] " + alunosdivisao + " [Disciplina] " + disciplina + " [HorasAula] " + horasaula + " [HorasDadas] " + horasdadas + " [HorasMax] " + horasmax + " [NumDivisao] " + numdivisao + " [NumEpoca] " + numepoca + " [SalaPreferencial] " + salapreferencial + " [TipoAula] " + tipoaula + " [Turma] " + turma;

  }
}

