
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.thor;


public class Aulas 
{
	private long id;
	
  private long dia;

  private String disciplina;

  private long fixa;

  private long hora;

  private long numepoca;

  private long numturno;

  private String sala;

  private String tipoaula;

  private String turma;

  public long getDia()
  {
     return this.dia;
  }
  public void setDia(long param)
  {
    this.dia = param;
  }


  public String getDisciplina()
  {
     return this.disciplina;
  }
  public void setDisciplina(String param)
  {
    this.disciplina = param;
  }


  public long getFixa()
  {
     return this.fixa;
  }
  public void setFixa(long param)
  {
    this.fixa = param;
  }


  public long getHora()
  {
     return this.hora;
  }
  public void setHora(long param)
  {
    this.hora = param;
  }


  public long getNumepoca()
  {
     return this.numepoca;
  }
  public void setNumepoca(long param)
  {
    this.numepoca = param;
  }


  public long getNumturno()
  {
     return this.numturno;
  }
  public void setNumturno(long param)
  {
    this.numturno = param;
  }


  public String getSala()
  {
     return this.sala;
  }
  public void setSala(String param)
  {
    this.sala = param;
  }


  public String getTipoaula()
  {
     return this.tipoaula;
  }
  public void setTipoaula(String param)
  {
    this.tipoaula = param;
  }


  public String getTurma()
  {
     return this.turma;
  }
  public void setTurma(String param)
  {
    this.turma = param;
  }


  public String toString(){
    return  " [Dia] " + dia + " [Disciplina] " + disciplina + " [Fixa] " + fixa + " [Hora] " + hora + " [NumEpoca] " + numepoca + " [NumTurno] " + numturno + " [Sala] " + sala + " [TipoAula] " + tipoaula + " [Turma] " + turma;

  }
	/**
	 * @return
	 */
	public long getId() {
		return id;
	}

	/**
	 * @param id
	 */
	public void setId(long id) {
		this.id = id;
	}

}

