
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.thor;

import Dominio.DomainObject;


public class Disciplinas extends DomainObject 
{
  private long aulas_praticas;

  private long aulas_teoricas;

  private long epoca_fim;

  private long epoca_inicio;

  private String nome;

  private String sigla;

  private String tipo_sala_laboratorio;

  private String tipo_sala_pratica;

  private String tipo_sala_teorica;

  private String tipo_sala_teorica_pratica;

  public long getAulas_praticas()
  {
     return this.aulas_praticas;
  }
  public void setAulas_praticas(long param)
  {
    this.aulas_praticas = param;
  }


  public long getAulas_teoricas()
  {
     return this.aulas_teoricas;
  }
  public void setAulas_teoricas(long param)
  {
    this.aulas_teoricas = param;
  }


  public long getEpoca_fim()
  {
     return this.epoca_fim;
  }
  public void setEpoca_fim(long param)
  {
    this.epoca_fim = param;
  }


  public long getEpoca_inicio()
  {
     return this.epoca_inicio;
  }
  public void setEpoca_inicio(long param)
  {
    this.epoca_inicio = param;
  }


  public String getNome()
  {
     return this.nome;
  }
  public void setNome(String param)
  {
    this.nome = param;
  }


  public String getSigla()
  {
     return this.sigla;
  }
  public void setSigla(String param)
  {
    this.sigla = param;
  }


  public String getTipo_sala_laboratorio()
  {
     return this.tipo_sala_laboratorio;
  }
  public void setTipo_sala_laboratorio(String param)
  {
    this.tipo_sala_laboratorio = param;
  }


  public String getTipo_sala_pratica()
  {
     return this.tipo_sala_pratica;
  }
  public void setTipo_sala_pratica(String param)
  {
    this.tipo_sala_pratica = param;
  }


  public String getTipo_sala_teorica()
  {
     return this.tipo_sala_teorica;
  }
  public void setTipo_sala_teorica(String param)
  {
    this.tipo_sala_teorica = param;
  }


  public String getTipo_sala_teorica_pratica()
  {
     return this.tipo_sala_teorica_pratica;
  }
  public void setTipo_sala_teorica_pratica(String param)
  {
    this.tipo_sala_teorica_pratica = param;
  }


  public String toString(){
    return  " [Aulas_Praticas] " + aulas_praticas + " [Aulas_Teoricas] " + aulas_teoricas + " [Epoca_Fim] " + epoca_fim + " [Epoca_Inicio] " + epoca_inicio + " [Nome] " + nome + " [Sigla] " + sigla + " [Tipo_Sala_Laboratorio] " + tipo_sala_laboratorio + " [Tipo_Sala_Pratica] " + tipo_sala_pratica + " [Tipo_Sala_Teorica] " + tipo_sala_teorica + " [Tipo_Sala_Teorica_Pratica] " + tipo_sala_teorica_pratica;

  }
}

