
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.thor;

import Dominio.DomainObject;


public class Turmas extends DomainObject 
{
  private String epoca_fim;

  private double epoca_inicio;

  private String sigla;

  private String titulo;

  public String getEpoca_fim()
  {
     return this.epoca_fim;
  }
  public void setEpoca_fim(String param)
  {
    this.epoca_fim = param;
  }


  public double getEpoca_inicio()
  {
     return this.epoca_inicio;
  }
  public void setEpoca_inicio(double param)
  {
    this.epoca_inicio = param;
  }


  public String getSigla()
  {
     return this.sigla;
  }
  public void setSigla(String param)
  {
    this.sigla = param;
  }


  public String getTitulo()
  {
     return this.titulo;
  }
  public void setTitulo(String param)
  {
    this.titulo = param;
  }


  public String toString(){
    return  " [Epoca_Fim] " + epoca_fim + " [Epoca_Inicio] " + epoca_inicio + " [Sigla] " + sigla + " [Titulo] " + titulo;

  }
}

