ALTER TABLE EVALUATION ADD COLUMN ONLINE_SUBMISSIONS_ALLOWED BIT NULL;
ALTER TABLE EVALUATION ADD COLUMN MAX_SUBMISSIONS_TO_KEEP INT(2) NULL;
ALTER TABLE EVALUATION ADD COLUMN KEY_GROUPING INT(11) NULL;

