#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Creating Table PaymentPlan" CreateTablePaymentPlan.sql
execute "Creating Table Installment" CreateTableInstallment.sql
execute "Creating Table PaymentCode" CreateTablePaymentCode.sql
execute "Changing Table AccountingEvent" AlterTableAccountingEvent.sql
execute "Changing Table AccountingTransaction" AlterTableAccountingTransaction.sql
execute "Chaging Table PostingRule" AlterTablePostingRule.sql
execute "Delete not closed insurance events" DeleteNotClosedInsuranceEvents.sql
