CREATE TABLE `REGISTRATION_DATA_BY_PERIOD` (
  `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
  `KEY_STUDENT_KIND` int(11) NULL,
  `KEY_EXECUTION_PERIOD` int(11) NOT NULL,
  `KEY_REGISTRATION` int(11) NOT NULL,
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_STUDENT_KIND` (`KEY_STUDENT_KIND`),
  KEY `KEY_EXECUTION_PERIOD` (`KEY_EXECUTION_PERIOD`),
  KEY `KEY_REGISTRATION` (`KEY_REGISTRATION`),
  KEY `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`)
) ENGINE=InnoDB;
