update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, ',', ',monthOfYear=');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, '200', 'year=200');

update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'JANUARY', '1');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'FEBRUARY', '2');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'MARCH', '3');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'APRIL', '4');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'MAY', '5');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'JUNE', '6');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'JULY', '7');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'AUGUST', '8');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'SEPTEMBER', '9');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'OCTOBER', '10');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'NOVEMBER', '11');
update ANUAL_BONUS_INSTALLMENT set ASSIDUOUSNESS_YEAR_MONTHS= REPLACE(ASSIDUOUSNESS_YEAR_MONTHS, 'DECEMBER', '12');


ALTER TABLE ANUAL_BONUS_INSTALLMENT CHANGE COLUMN ASSIDUOUSNESS_YEAR_MONTHS ASSIDUOUSNESS_PARTIALS text NOT NULL;