
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao;


public class Almeida_curricular_course  
{
  private String code;

  private long id_internal;

  private String name;

  public String getCode()
  {
     return this.code;
  }
  public void setCode(String param)
  {
    this.code = param;
  }


  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public String getName()
  {
     return this.name;
  }
  public void setName(String param)
  {
    this.name = param;
  }


  public String toString(){
    return  " [CODE] " + code + " [ID_INTERNAL] " + id_internal + " [NAME] " + name;

  }
  
  public boolean equals(Object obj) {
    boolean resultado = false;
    if (obj instanceof Almeida_curricular_course) {
      Almeida_curricular_course almeida_curricular_course = (Almeida_curricular_course) obj;
      resultado = this.code == almeida_curricular_course.getCode();
    }
    return resultado;
  }
}