
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao;


public class Almeida_enrolment  
{
  private long anodis;

  private long anoins;

  private String coddis;

  private String coduniv;

  private String curso;

  private String datexa;

  private long epoca;

  private long id_internal;

  private String numalu;

  private String numdoc;

  private String observ;

  private long ramo;

  private String result;

  private long semdis;

  public long getAnodis()
  {
     return this.anodis;
  }
  public void setAnodis(long param)
  {
    this.anodis = param;
  }


  public long getAnoins()
  {
     return this.anoins;
  }
  public void setAnoins(long param)
  {
    this.anoins = param;
  }


  public String getCoddis()
  {
     return this.coddis;
  }
  public void setCoddis(String param)
  {
    this.coddis = param;
  }


  public String getCoduniv()
  {
     return this.coduniv;
  }
  public void setCoduniv(String param)
  {
    this.coduniv = param;
  }


  public String getCurso()
  {
     return this.curso;
  }
  public void setCurso(String param)
  {
    this.curso = param;
  }


  public String getDatexa()
  {
     return this.datexa;
  }
  public void setDatexa(String param)
  {
    this.datexa = param;
  }


  public long getEpoca()
  {
     return this.epoca;
  }
  public void setEpoca(long param)
  {
    this.epoca = param;
  }


  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public String getNumalu()
  {
     return this.numalu;
  }
  public void setNumalu(String param)
  {
    this.numalu = param;
  }


  public String getNumdoc()
  {
     return this.numdoc;
  }
  public void setNumdoc(String param)
  {
    this.numdoc = param;
  }


  public String getObserv()
  {
     return this.observ;
  }
  public void setObserv(String param)
  {
    this.observ = param;
  }


  public long getRamo()
  {
     return this.ramo;
  }
  public void setRamo(long param)
  {
    this.ramo = param;
  }


  public String getResult()
  {
     return this.result;
  }
  public void setResult(String param)
  {
    this.result = param;
  }


  public long getSemdis()
  {
     return this.semdis;
  }
  public void setSemdis(long param)
  {
    this.semdis = param;
  }


  public String toString(){
    return  " [ANODIS] " + anodis + " [ANOINS] " + anoins + " [CODDIS] " + coddis + " [CODUNIV] " + coduniv + " [CURSO] " + curso + " [DATEXA] " + datexa + " [EPOCA] " + epoca + " [ID_INTERNAL] " + id_internal + " [NUMALU] " + numalu + " [NUMDOC] " + numdoc + " [OBSERV] " + observ + " [RAMO] " + ramo + " [RESULT] " + result + " [SEMDIS] " + semdis;

  }

//------------------------------------------------------------------------------------------------------

  public long getNumaluLong() {
	 return (new Integer(this.numalu)).longValue();
  }

  public long getCursoInt() {
	 return (new Integer(this.curso)).longValue();
  }

  public long getNumdocLong() {
	 return (new Integer(this.numdoc)).longValue();
  }
}