
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao;


public class Leq_cc_scope  
{
  private long id_internal;

  private long key_branch;

  private long key_curricular_semester;

  private long key_leq_cc;

  private double lab_hours;

  private double pratical_hours;

  private double theoretical_hours;

  private double theo_prat_hours;
  
  private Leq_branch branch;
  private Leq_curricular_semester curricularSemester;
  private Leq_new_curricular_course curricularCourse;

  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public long getKey_branch()
  {
     return this.key_branch;
  }
  public void setKey_branch(long param)
  {
    this.key_branch = param;
  }


  public long getKey_curricular_semester()
  {
     return this.key_curricular_semester;
  }
  public void setKey_curricular_semester(long param)
  {
    this.key_curricular_semester = param;
  }


  public long getKey_leq_cc()
  {
     return this.key_leq_cc;
  }
  public void setKey_leq_cc(long param)
  {
    this.key_leq_cc = param;
  }


  public double getLab_hours()
  {
     return this.lab_hours;
  }
  public void setLab_hours(double param)
  {
    this.lab_hours = param;
  }


  public double getPratical_hours()
  {
     return this.pratical_hours;
  }
  public void setPratical_hours(double param)
  {
    this.pratical_hours = param;
  }


  public double getTheoretical_hours()
  {
     return this.theoretical_hours;
  }
  public void setTheoretical_hours(double param)
  {
    this.theoretical_hours = param;
  }


  public double getTheo_prat_hours()
  {
     return this.theo_prat_hours;
  }
  public void setTheo_prat_hours(double param)
  {
    this.theo_prat_hours = param;
  }


  public String toString(){
    return  " [ID_INTERNAL] " + id_internal + " [KEY_BRANCH] " + key_branch + " [KEY_CURRICULAR_SEMESTER] " + key_curricular_semester + " [KEY_LEQ_CC] " + key_leq_cc + " [LAB_HOURS] " + lab_hours + " [PRATICAL_HOURS] " + pratical_hours + " [THEORETICAL_HOURS] " + theoretical_hours + " [THEO_PRAT_HOURS] " + theo_prat_hours;

  }

	public Leq_branch getBranch() {
		return branch;
	}
	
	public Leq_new_curricular_course getCurricularCourse() {
		return curricularCourse;
	}
	
	public Leq_curricular_semester getCurricularSemester() {
		return curricularSemester;
	}
	
	public void setBranch(Leq_branch leq_branch) {
		branch = leq_branch;
	}
	
	public void setCurricularCourse(Leq_new_curricular_course leq_new_curricular_course) {
		curricularCourse = leq_new_curricular_course;
	}
	
	public void setCurricularSemester(Leq_curricular_semester leq_curricular_semester) {
		curricularSemester = leq_curricular_semester;
	}
	
}

