
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao;


public class Leq_possible_cc_4_optional_cc  
{
  private long id_internal;

  private long key_optional_cc;

  private long key_possible_cc;

  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public long getKey_optional_cc()
  {
     return this.key_optional_cc;
  }
  public void setKey_optional_cc(long param)
  {
    this.key_optional_cc = param;
  }


  public long getKey_possible_cc()
  {
     return this.key_possible_cc;
  }
  public void setKey_possible_cc(long param)
  {
    this.key_possible_cc = param;
  }


  public String toString(){
    return  " [ID_INTERNAL] " + id_internal + " [KEY_OPTIONAL_CC] " + key_optional_cc + " [KEY_POSSIBLE_CC] " + key_possible_cc;

  }
}

