
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao;


public class Leq_precedence  
{
  private long id_internal;

  private long key_cc;

  private String scope_to_apply;

  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public long getKey_cc()
  {
     return this.key_cc;
  }
  public void setKey_cc(long param)
  {
    this.key_cc = param;
  }


  public String getScope_to_apply()
  {
     return this.scope_to_apply;
  }
  public void setScope_to_apply(String param)
  {
    this.scope_to_apply = param;
  }


  public String toString(){
    return  " [ID_INTERNAL] " + id_internal + " [KEY_CC] " + key_cc + " [SCOPE_TO_APPLY] " + scope_to_apply;

  }
}

