
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao;


public class Leq_curricular_year  
{
  private long id_internal;

  private long year;

  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public long getYear()
  {
     return this.year;
  }
  public void setYear(long param)
  {
    this.year = param;
  }


  public String toString(){
    return  " [ID_INTERNAL] " + id_internal + " [YEAR] " + year;

  }
}

