
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.almeida.dcsrjao;


public class Leq_curricular_semester  
{
  private long id_internal;

  private long key_curricular_year;

  private long semester;

  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public long getKey_curricular_year()
  {
     return this.key_curricular_year;
  }
  public void setKey_curricular_year(long param)
  {
    this.key_curricular_year = param;
  }


  public long getSemester()
  {
     return this.semester;
  }
  public void setSemester(long param)
  {
    this.semester = param;
  }


  public String toString(){
    return  " [ID_INTERNAL] " + id_internal + " [KEY_CURRICULAR_YEAR] " + key_curricular_year + " [SEMESTER] " + semester;

  }
}

