UPDATE JUSTIFICATION_MOTIVE SET JUSTIFICATION_TYPE="HALF_OCCURRENCE_TIME" WHERE JUSTIFICATION_TYPE="HALF_OCCURRENCE";

INSERT INTO JUSTIFICATION_MOTIVE VALUES (null,0,"1/2 FÉRIAS", "1/2 dia de Férias do ano corrente", "HALF_OCCURRENCE", "WORKDAY", "CURRENT_YEAR_HOLIDAYS", null, null,1,1,25,25,0);

ALTER TABLE JUSTIFICATION_MOTIVE ADD COLUMN ACTIVE tinyint(1) default '1';

UPDATE JUSTIFICATION_MOTIVE SET ACTIVE=0 WHERE ID_INTERNAL=2;

