#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Dropping Old Cms Tables" DropOldCmsMessagingTables.sql
execute "Creating Messaging Tables" CreateMessagingTables.sql
execute "Alter Homepage Table" alterTableHomepage.sql