DROP TABLE IF EXISTS XPTO;
CREATE TABLE XPTO SELECT * FROM ENROLMENT_EVALUATION WHERE GRADE IS NOT NULL GROUP BY KEY_ENROLMENT HAVING COUNT(*) = 1;

DROP TABLE IF EXISTS XPTI;
CREATE TABLE XPTI SELECT * FROM XPTO WHERE GRADE = 'RE';

DROP TABLE IF EXISTS XPTE;
CREATE TABLE XPTE SELECT E.* FROM ENROLMENT E
INNER JOIN XPTI X ON X.KEY_ENROLMENT = E.ID_INTERNAL
WHERE E.STATE <> 2 AND E.STATE <> 5;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = ', X.ID_INTERNAL, ';') AS "" FROM XPTE X;


DROP TABLE IF EXISTS XPTI;
CREATE TABLE XPTI SELECT * FROM XPTO WHERE GRADE = 'NA';

DROP TABLE IF EXISTS XPTE;
CREATE TABLE XPTE SELECT E.* FROM ENROLMENT E
INNER JOIN XPTI X ON X.KEY_ENROLMENT = E.ID_INTERNAL
WHERE E.STATE <> 6 AND E.STATE <> 5;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 6 WHERE ID_INTERNAL = ', X.ID_INTERNAL, ';') AS "" FROM XPTE X;


DROP TABLE IF EXISTS XPTI;
CREATE TABLE XPTI SELECT * FROM XPTO WHERE GRADE IS NULL;

DROP TABLE IF EXISTS XPTE;
CREATE TABLE XPTE SELECT E.* FROM ENROLMENT E
INNER JOIN XPTI X ON X.KEY_ENROLMENT = E.ID_INTERNAL
WHERE E.STATE <> 3 AND E.STATE <> 5;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 3 WHERE ID_INTERNAL = ', X.ID_INTERNAL, ';') AS "" FROM XPTE X;


DROP TABLE IF EXISTS XPTI;
CREATE TABLE XPTI SELECT * FROM XPTO WHERE GRADE <> 'NA' AND GRADE <> 'RE' AND GRADE IS NOT NULL;

DROP TABLE IF EXISTS XPTE;
CREATE TABLE XPTE SELECT E.* FROM ENROLMENT E
INNER JOIN XPTI X ON X.KEY_ENROLMENT = E.ID_INTERNAL
WHERE E.STATE <> 1 AND E.STATE <> 5;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = ', X.ID_INTERNAL, ';') AS "" FROM XPTE X;


DROP TABLE IF EXISTS XPTO;
DROP TABLE IF EXISTS XPTI;
DROP TABLE IF EXISTS XPTE;
