SELECT CONCAT('UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = ', ID_INTERNAL, ';') AS ""
FROM CURRICULAR_COURSE
WHERE (NAME NOT LIKE 'TRABALHO FINAL DE CURSO%' AND NAME NOT LIKE 'OPÇÃO%')
AND KEY_DEGREE_CURRICULAR_PLAN = 48;
