CREATE TABLE `PERSONAL_GROUP` (
  `ID_INTERNAL` INTEGER NOT NULL AUTO_INCREMENT,
  `ACK_OPT_LOCK` INTEGER DEFAULT NULL,
  `NAME` VARCHAR(100),
  `DESCRIPTION` VARCHAR(255),
  `CONCRETE_GROUP` BLOB NOT NULL,
  `KEY_PERSON` INTEGER NOT NULL,
  PRIMARY KEY(`ID_INTERNAL`)
)
ENGINE = InnoDB;
