#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}


execute "Alter Table Curriculum Module" alterTableCurriculumModule.sql
execute "Dismissal Changes" dismissalChanges.sql
execute "Update CREDITS_MANAGER portal roles and remove unused portal" UpdatePortalRoles.sql
execute "Adding search functionality to public courses site" changes-20070104205158.sql
