DROP TABLE IF EXISTS MW_DISTINCT_ENROLLMENT_YEAR_AND_SEMESTER;
CREATE TABLE MW_DISTINCT_ENROLLMENT_YEAR_AND_SEMESTER
SELECT DISTINCT ENROLMENTYEAR, CURRICULARCOURSESEMESTER FROM MW_ENROLMENT ORDER BY ENROLMENTYEAR;

SELECT CONCAT('INSERT INTO EXECUTION_YEAR VALUES (0,"', DEYS.ENROLMENTYEAR, '/', DEYS.ENROLMENTYEAR + 1,'","CL");') AS ""
FROM MW_DISTINCT_ENROLLMENT_YEAR_AND_SEMESTER DEYS WHERE CURRICULARCOURSESEMESTER = "1";

SELECT CONCAT('INSERT INTO EXECUTION_PERIOD VALUES (0,"', DEYS.CURRICULARCOURSESEMESTER, ' Semestre",',
EY.ID_INTERNAL, ',"CL",', DEYS.CURRICULARCOURSESEMESTER, ',"',
CASE DEYS.CURRICULARCOURSESEMESTER WHEN 1 THEN CONCAT_WS('-', DEYS.ENROLMENTYEAR, '09', '01') ELSE
CONCAT_WS('-', DEYS.ENROLMENTYEAR + 1, '03', '01') END, '","',
CASE DEYS.CURRICULARCOURSESEMESTER WHEN 1 THEN CONCAT_WS('-', DEYS.ENROLMENTYEAR, '12', '31') ELSE
CONCAT_WS('-', DEYS.ENROLMENTYEAR + 1, '07', '31') END, '");') AS ""
FROM MW_DISTINCT_ENROLLMENT_YEAR_AND_SEMESTER DEYS
INNER JOIN EXECUTION_YEAR EY ON DEYS.ENROLMENTYEAR = CONCAT(EY.YEAR, '/', EY.YEAR + 1)
WHERE EY.YEAR < '2002/2003';
