DROP TABLE IF EXISTS mw_DISTINCT_ENROLLMENT_YEAR_AND_SEMESTER;
CREATE TABLE mw_DISTINCT_ENROLLMENT_YEAR_AND_SEMESTER
SELECT DISTINCT enrolmentYear, curricularCourseSemester FROM mw_ENROLMENT_temp WHERE enrolmentYear < 2002 ORDER BY enrolmentYear;
