-- select concat('delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = ', scp.ID_INTERNAL, ');') AS "QQ"
-- from STUDENT_CURRICULAR_PLAN scp
-- inner join STUDENT s on scp.KEY_STUDENT = s.ID_INTERNAL
-- inner join mw_STUDENT_AUXILIARY_TABLE mws on s.NUMBER = mws.number
-- where mws.degreeCode = 24 and scp.CURRENT_STATE = 6;

delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 19769;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 19770;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 19771;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 19772;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 19773;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 19774;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 19775;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21249;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21250;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21251;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21252;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21253;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21254;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21255;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21256;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21257;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21258;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21259;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21260;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21261;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21262;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21263;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21264;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21265;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21266;
delete from STUDENT_CURRICULAR_PLAN where ID_INTERNAL = 21267;
