#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

echo Using database: $1
echo Enter password for $2:
read -s password

mysql -u$2 -f $1 < createCmsTables.sql
mysql -u$2 -f $1 < createMailer.sql

mysql -u$2 -f $1 < updateTableSummaryWithSummaryType.sql > res
mysql -u$2 -f $1 < res
rm -r res
