
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.sigla;

import Dominio.DomainObject;

public class Curr_licenciatura extends DomainObject{

	private Integer ano_curricular;

	private Integer ano_lectivo;

	private String bib_princ_1;

	private String bib_princ_2;

	private String bib_princ_3;

	private String bib_sec_1;

	private String bib_sec_2;

	private String bib_sec_3;

	private String codigo_disc;

	private Integer codigo_lic;

	private Integer codigo_ramo;

	private String crit_av;

	private String ender_web;

	private String nome_disc;

	private Integer no_mec_act;

	private String objectivos;

	private String objectivos_op;

	private String progr_res;

	private Integer semestre;

	/**
	 * 
	 */
	public Curr_licenciatura() {
		super();
		
	}

	public Integer getAno_curricular() {
		return this.ano_curricular;
	}
	public void setAno_curricular(Integer param) {
		this.ano_curricular = param;
	}

	public Integer getAno_lectivo() {
		return this.ano_lectivo;
	}
	public void setAno_lectivo(Integer param) {
		this.ano_lectivo = param;
	}

	public String getBib_princ_1() {
		return this.bib_princ_1;
	}
	public void setBib_princ_1(String param) {
		this.bib_princ_1 = param;
	}

	public String getBib_princ_2() {
		return this.bib_princ_2;
	}
	public void setBib_princ_2(String param) {
		this.bib_princ_2 = param;
	}

	public String getBib_princ_3() {
		return this.bib_princ_3;
	}
	public void setBib_princ_3(String param) {
		this.bib_princ_3 = param;
	}

	public String getBib_sec_1() {
		return this.bib_sec_1;
	}
	public void setBib_sec_1(String param) {
		this.bib_sec_1 = param;
	}

	public String getBib_sec_2() {
		return this.bib_sec_2;
	}
	public void setBib_sec_2(String param) {
		this.bib_sec_2 = param;
	}

	public String getBib_sec_3() {
		return this.bib_sec_3;
	}
	public void setBib_sec_3(String param) {
		this.bib_sec_3 = param;
	}

	public String getCodigo_disc() {
		return this.codigo_disc;
	}
	public void setCodigo_disc(String param) {
		this.codigo_disc = param;
	}

	public Integer getCodigo_lic() {
		return this.codigo_lic;
	}
	public void setCodigo_lic(Integer param) {
		this.codigo_lic = param;
	}

	public Integer getCodigo_ramo() {
		return this.codigo_ramo;
	}
	public void setCodigo_ramo(Integer param) {
		this.codigo_ramo = param;
	}

	public String getEnder_web() {
		return this.ender_web;
	}
	public void setEnder_web(String param) {
		this.ender_web = param;
	}

	public String getNome_disc() {
		return this.nome_disc;
	}
	public void setNome_disc(String param) {
		this.nome_disc = param;
	}

	public Integer getNo_mec_act() {
		return this.no_mec_act;
	}
	public void setNo_mec_act(Integer param) {
		this.no_mec_act = param;
	}

	public String getObjectivos() {
		return this.objectivos;
	}
	public void setObjectivos(String param) {
		this.objectivos = param;
	}

	public String getObjectivos_op() {
		return this.objectivos_op;
	}
	public void setObjectivos_op(String param) {
		this.objectivos_op = param;
	}

	

	public String getProgr_res() {
		return this.progr_res;
	}
	public void setProgr_res(String param) {
		this.progr_res = param;
	}

	public Integer getSemestre() {
		return this.semestre;
	}
	public void setSemestre(Integer param) {
		this.semestre = param;
	}

	public String toString() {
		return " [ANO_CURRICULAR] "
			+ ano_curricular
			+ " [ANO_LECTIVO] "
			+ ano_lectivo
			+ " [BIB_PRINC_1] "
			+ bib_princ_1
			+ " [BIB_PRINC_2] "
			+ bib_princ_2
			+ " [BIB_PRINC_3] "
			+ bib_princ_3
			+ " [BIB_SEC_1] "
			+ bib_sec_1
			+ " [BIB_SEC_2] "
			+ bib_sec_2
			+ " [BIB_SEC_3] "
			+ bib_sec_3
			+ " [CODIGO_DISC] "
			+ codigo_disc
			+ " [CODIGO_LIC] "
			+ codigo_lic
			+ " [CODIGO_RAMO] "
			+ codigo_ramo
			+ " [CRIT_AV] "
			+ crit_av
			+ " [ENDER_WEB] "
			+ ender_web
			+ " [NOME_DISC] "
			+ nome_disc
			+ " [NO_MEC_ACT] "
			+ no_mec_act
			+ " [OBJECTIVOS] "
			+ objectivos
			+ " [OBJECTIVOS_OP] "
			+ objectivos_op
			+ " [PROGR_RES] "
			+ progr_res
			+ " [SEMESTRE] "
			+ semestre;

	}
	/**
	 * @return
	 */
	public String getCrit_av() {
		return crit_av;
	}

	/**
	 * @param string
	 */
	public void setCrit_av(String string) {
		crit_av = string;
	}

}
