
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.sigla;

import Dominio.DomainObject;

public class Plano_curricular_2003final extends DomainObject {

	

	private String ano_curricular;
	private Integer ano_lectivo;
	private String codigo_disc;
	private Integer codigo_lic;
	private String codigo_ramo;
	private String crit_av;
	private String ingles_crit_av;
	private String ingles_nome_disc;
	private String ingles_objectivos;
	private String ingles_progr_res;
	private java.sql.Timestamp ingles_data_act;
	private String ingles_relatorio;
	private String nome_disc;
	private String objectivos;
	private String progr_res;
	private String semestre;
	private String bib_princ_1;
	private String bib_princ_2;
	private String bib_princ_3;
	private String bib_sec_1;
	private String bib_sec_2;
	private String bib_sec_3;
	private String ciencia_base;
	private String data_act;
	private String ender_web;
	
	public String getAno_curricular() {
		return this.ano_curricular;
	}
	public void setAno_curricular(String param) {
		this.ano_curricular = param;
	}

	public Integer getAno_lectivo() {
		return this.ano_lectivo;
	}
	public void setAno_lectivo(Integer param) {
		this.ano_lectivo = param;
	}

	public String getCodigo_disc() {
		return this.codigo_disc;
	}
	public void setCodigo_disc(String param) {
		this.codigo_disc = param;
	}

	public Integer getCodigo_lic() {
		return this.codigo_lic;
	}
	public void setCodigo_lic(Integer param) {
		this.codigo_lic = param;
	}

	public String getCodigo_ramo() {
		return this.codigo_ramo;
	}
	public void setCodigo_ramo(String param) {
		this.codigo_ramo = param;
	}

	public String getCrit_av() {
		return this.crit_av;
	}
	public void setCrit_av(String param) {
		this.crit_av = param;
	}

	public String getIngles_crit_av() {
		return this.ingles_crit_av;
	}
	public void setIngles_crit_av(String param) {
		this.ingles_crit_av = param;
	}

	public String getIngles_nome_disc() {
		return this.ingles_nome_disc;
	}
	public void setIngles_nome_disc(String param) {
		this.ingles_nome_disc = param;
	}

	public String getIngles_objectivos() {
		return this.ingles_objectivos;
	}
	public void setIngles_objectivos(String param) {
		this.ingles_objectivos = param;
	}

	public String getIngles_progr_res() {
		return this.ingles_progr_res;
	}
	public void setIngles_progr_res(String param) {
		this.ingles_progr_res = param;
	}

	public java.sql.Timestamp getIngles_data_act() {
		return this.ingles_data_act;
	}
	public void setIngles_data_act(java.sql.Timestamp param) {
		this.ingles_data_act = param;
	}

	public String getIngles_relatorio() {
		return this.ingles_relatorio;
	}
	public void setIngles_relatorio(String param) {
		this.ingles_relatorio = param;
	}

	public String getNome_disc() {
		return this.nome_disc;
	}
	public void setNome_disc(String param) {
		this.nome_disc = param;
	}

	public String getObjectivos() {
		return this.objectivos;
	}
	public void setObjectivos(String param) {
		this.objectivos = param;
	}

	public String getProgr_res() {
		return this.progr_res;
	}
	public void setProgr_res(String param) {
		this.progr_res = param;
	}

	public String getSemestre() {
		return this.semestre;
	}
	public void setSemestre(String param) {
		this.semestre = param;
	}

	public String getBib_princ_1() {
		return this.bib_princ_1;
	}
	public void setBib_princ_1(String param) {
		this.bib_princ_1 = param;
	}

	public String getBib_princ_2() {
		return this.bib_princ_2;
	}
	public void setBib_princ_2(String param) {
		this.bib_princ_2 = param;
	}

	public String getBib_princ_3() {
		return this.bib_princ_3;
	}
	public void setBib_princ_3(String param) {
		this.bib_princ_3 = param;
	}

	public String getBib_sec_1() {
		return this.bib_sec_1;
	}
	public void setBib_sec_1(String param) {
		this.bib_sec_1 = param;
	}

	public String getBib_sec_2() {
		return this.bib_sec_2;
	}
	public void setBib_sec_2(String param) {
		this.bib_sec_2 = param;
	}

	public String getBib_sec_3() {
		return this.bib_sec_3;
	}
	public void setBib_sec_3(String param) {
		this.bib_sec_3 = param;
	}

	public String getCiencia_base() {
		return this.ciencia_base;
	}
	public void setCiencia_base(String param) {
		this.ciencia_base = param;
	}

	public String getData_act() {
		return this.data_act;
	}
	public void setData_act(String param) {
		this.data_act = param;
	}

	public String getEnder_web() {
		return this.ender_web;
	}
	public void setEnder_web(String param) {
		this.ender_web = param;
	}

	public String toString() {
		return " [Ano_Curricular] "
			+ ano_curricular
			+ " [Ano_Lectivo] "
			+ ano_lectivo
			+ " [Codigo_Disc] "
			+ codigo_disc
			+ " [Codigo_Lic] "
			+ codigo_lic
			+ " [Nome_Disc] "
			+ nome_disc
			+ " [Semestre] "
			+ semestre
			+ " [ciencia_base] "
			+ ciencia_base;	

	}
}
