
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package middleware.sigla;

import Dominio.DomainObject;

public class Responsavel extends DomainObject {
	private Integer ano_curr;
	private Integer ano_lectivo;
	private Integer cod_curso;
	private String cod_disc;
	private Integer cod_ramo;
	private Integer no_mec;
	private String observacoes;
	private Integer semestre;

	public Integer getAno_curr() {
		return this.ano_curr;
	}
	public void setAno_curr(Integer param) {
		this.ano_curr = param;
	}

	public Integer getAno_lectivo() {
		return this.ano_lectivo;
	}
	public void setAno_lectivo(Integer param) {
		this.ano_lectivo = param;
	}

	public Integer getCod_curso() {
		return this.cod_curso;
	}
	public void setCod_curso(Integer param) {
		this.cod_curso = param;
	}

	public String getCod_disc() {
		return this.cod_disc;
	}
	public void setCod_disc(String param) {
		this.cod_disc = param;
	}

	public Integer getCod_ramo() {
		return this.cod_ramo;
	}
	public void setCod_ramo(Integer param) {
		this.cod_ramo = param;
	}

	

	public Integer getNo_mec() {
		return this.no_mec;
	}
	public void setNo_mec(Integer param) {
		this.no_mec = param;
	}

	public String getObservacoes() {
		return this.observacoes;
	}
	public void setObservacoes(String param) {
		this.observacoes = param;
	}

	public Integer getSemestre() {
		return this.semestre;
	}
	public void setSemestre(Integer param) {
		this.semestre = param;
	}

	public String toString() {
		return " [Ano_Curr] "
			+ ano_curr
			+ " [Ano_Lectivo] "
			+ ano_lectivo
			+ " [Cod_Curso] "
			+ cod_curso
			+ " [Cod_Disc] "
			+ cod_disc
			+ " [Cod_Ramo] "
			+ cod_ramo
			+ " [No_Mec] "
			+ no_mec
			+ " [Observacoes] "
			+ observacoes
			+ " [Semestre] "
			+ semestre;

	}
}
