CREATE TABLE TEACHER_EXPECTATION_DEFINITION_PERIOD (
	ID_INTERNAL int(11) NOT NULL auto_increment,
	ACK_OPT_LOCK int(11) default NULL,
	START_DATE date NOT NULL,
	END_DATE date NOT NULL,
	KEY_EXECUTION_YEAR int(11) NOT NULL,
	KEY_DEPARTMENT int(11) NOT NULL,
	PRIMARY KEY (ID_INTERNAL),
	UNIQUE U1 (KEY_DEPARTMENT,KEY_EXECUTION_YEAR)
) Type=InnoDB;
