select concat('insert into TEACHER_EXPECTATION_DEFINITION_PERIOD set START_DATE=\'2005-11-01\',END_DATE=\'2006-01-31\',KEY_DEPARTMENT=',D.ID_INTERNAL,',KEY_EXECUTION_YEAR=',E.ID_INTERNAL,';') as "" FROM DEPARTMENT D,EXECUTION_YEAR E WHERE D.CODE = '28' AND E.YEAR = '2005/2006';

