#!/bin/bash
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f  -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f  -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f  -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Alter table content" alterTableContent.sql
execute "Creating International Relation Office" createInternationalRelatOffice.sql 

execute "Add column subject to table AcademicServiceRequest" alterTableAcademicServiceRequest.sql
execute "Create table CourseLoadEnrolments" createCourseLoadEnrolments.sql
execute "Adding ExamCertificateRequestEnrolment table" AddExamCertificateRequestEnrolmentTable.sql
execute "Update ExecutionCourses Siglas" updateExecutionCoursesSiglas.sql
