--  SQL file representing changes to the functionalities model
--  Generated at Wed Sep 5 16:23:24 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 174 UUID: '48888108-288b-4233-9c34-1caa5388fd85'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt19:Ver Funcionalidades' WHERE own.`UUID` = '48888108-288b-4233-9c34-1caa5388fd85';

--  ID: 189878 UUID: '4caaa9c0-1db1-449b-a91a-487454cc62ec'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en5:Startpt6:Início', own.`TITLE` = 'en19:Portal inicial pagept24:Página inicial do portal', own.`VISIBLE` = 0 WHERE own.`UUID` = '4caaa9c0-1db1-449b-a91a-487454cc62ec';

--  ID: 189879 UUID: '9dc80775-4df0-4876-b991-cff3bcbd59cb'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en6:Thesespt12:Dissertações', own.`VISIBLE` = 0 WHERE own.`UUID` = '9dc80775-4df0-4876-b991-cff3bcbd59cb';

--  ID: 189880 UUID: '6a502dd9-0466-4e58-82e3-05a5b93a8c67'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en16:List Unconfirmedpt16:Listar Pendentes', own.`TITLE` = 'en23:List unconfirmed thesespt35:Listar dissertações não confirmadas' WHERE own.`UUID` = '6a502dd9-0466-4e58-82e3-05a5b93a8c67';

--  ID: 189881 UUID: '11ab0ab3-56a2-4bb8-9256-2bde9d159697'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en19:Verify Dissertationpt21:Verificar Dissertação', own.`TITLE` = 'en33:Verify and correct thesis detailspt47:Verificar e corrigir os detalhes da dissertação' WHERE own.`UUID` = '11ab0ab3-56a2-4bb8-9256-2bde9d159697';

--  ID: 189882 UUID: '2faa16c6-6696-44a9-9d0c-d6c9d51b42b9'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en14:List confirmedpt18:Listar Confirmadas', own.`TITLE` = 'en21:List confirmed thesespt31:Listar dissertações confirmadas' WHERE own.`UUID` = '2faa16c6-6696-44a9-9d0c-d6c9d51b42b9';

--  ID: 189883 UUID: '384a11b9-351d-46a1-9bce-0235e0fe31a7'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en13:List Exportedpt17:Listar Exportadas', own.`TITLE` = 'en20:List exported thesespt30:Listar dissertações exportadas' WHERE own.`UUID` = '384a11b9-351d-46a1-9bce-0235e0fe31a7';

--  ID: 189884 UUID: '81237d1d-e3ef-4252-936f-e9da63667d39'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'en13:Export Thesespt21:Exportar Dissertações', own.`TITLE` = 'en29:Export selected theses to XMLpt43:Exportar dissertações selecionadas para XML' WHERE own.`UUID` = '81237d1d-e3ef-4252-936f-e9da63667d39';

-- 
--  Inserting new functionalities
-- 

--  ID: 269519 UUID: 'b3d6942c-bdca-4083-86cb-6eeb34f39c37'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT 'b3d6942c-bdca-4083-86cb-6eeb34f39c37', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt16:Listagem utentes', 'pt17:Cartão Biblioteca', NULL, '/cardManagement.do?method=showUsers', NULL, 1, 1, NULL, 0, 1, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = 'b3d6942c-bdca-4083-86cb-6eeb34f39c37';

--  ID: 269520 UUID: 'e3cc1382-7912-47e3-9f97-3aadf9e32ea0'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT 'e3cc1382-7912-47e3-9f97-3aadf9e32ea0', 'net.sourceforge.fenixedu.domain.functionalities.Module', 1, `ID_INTERNAL`, `ID_INTERNAL`, NULL, 'pt7:Cartões', NULL, NULL, '', '/', 1, 1, NULL, 2, 1, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = '4cbd4716-40e1-4052-ac47-b24db983efd4';

COMMIT;
