CREATE TABLE `OLD_CURRICULAR_COURSE_CURRICULAR_COURSE_EQUIVALENCE` (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `KEY_CURRICULAR_COURSE_EQUIVALENCE` int(11) NOT NULL default '0',
  `KEY_CURRICULAR_COURSE` int(11) NOT NULL default '0',
  PRIMARY KEY  (`ID_INTERNAL`),
  UNIQUE KEY `U1` (`KEY_CURRICULAR_COURSE_EQUIVALENCE`,`KEY_CURRICULAR_COURSE`),
  KEY `KEY_CURRICULAR_COURSE` (`KEY_CURRICULAR_COURSE`),
  KEY `KEY_CURRICULAR_COURSE_EQUIVALENCE` (`KEY_CURRICULAR_COURSE_EQUIVALENCE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;