#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Update Bolonha Type in Curricular Rules" updateCurricularRulesBolonhaType.sql
execute "alter table FILE (added keyResult)" alterTableFile.sql
execute "Create Table OLD_CURRICULAR_COURSE_CURRICULAR_COURSE_EQUIVALENCE" createOLD_CURRICULAR_COURSE_CURRICULAR_COURSE_EQUIVALENCEtable.sql
executeWithTempFile "Migrate CurricularCourseEquivalences" migrateCurricularCourseEquivalences.sql
execute "Alter Table CurricularCourseEquivalence" alterCurricularCourseEquivalenceTable.sql