ALTER TABLE CANDIDACY drop column DISTRICT_OF_RESIDENCE;
ALTER TABLE CANDIDACY drop column DISTRICT_SUBDIVISION_OF_RESIDENCE;
ALTER TABLE CANDIDACY drop column SCHOOL_TIME_DISTRICT_OF_RESIDENCE;
ALTER TABLE CANDIDACY drop column SCHOOL_TIME_DISTRICT_SUBDIVISION_OF_RESIDENCE;


