ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `CYCLE_TYPE` varchar(250) NULL DEFAULT NULL;
ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `CONCLUSION_DATE` text NULL DEFAULT NULL;
ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `NUMBER_OF_ENROLED_CURRICULAR_COURSES` int(11) NULL DEFAULT NULL;
ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `NUMBER_OF_APPROVED_CURRICULAR_COURSES` int(11) NULL DEFAULT NULL;
ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `GRADE_SUM` varchar(250) NULL DEFAULT NULL;
ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `APPROVED_ECTS` varchar(250) NULL DEFAULT NULL;
ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `ENROLED_ECTS` varchar(250) NULL DEFAULT NULL;
ALTER TABLE PRECEDENT_DEGREE_INFORMATION ADD COLUMN `OID_INDIVIDUAL_CANDIDACY` bigint(20) unsigned NULL DEFAULT NULL;

ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN `OID_REFACTORED_PRECEDENT_DEGREE_INFORMATION` bigint(20) unsigned unsigned NULL DEFAULT NULL;
