alter table EXTRA_WORK_REQUEST add column REQUESTED_NIGHT_HOURS int(11) default NULL;
alter table EXTRA_WORK_REQUEST add column REQUESTED_EXTRA_NIGHT_HOURS int(11) default NULL;
alter table EXTRA_WORK_REQUEST add column REQUESTED_HOLIDAY_HOURS int(11) default NULL;
alter table EXTRA_WORK_REQUEST add column REQUESTED_SATURDAY_HOURS int(11) default NULL;
alter table EXTRA_WORK_REQUEST add column REQUESTED_SUNDAY_HOURS int(11) default NULL;
alter table EXTRA_WORK_REQUEST add column REQUESTED_WORKDAY_HOURS int(11) default NULL;

update EXTRA_WORK_REQUEST set REQUESTED_NIGHT_HOURS = NIGHT_HOURS where REQUESTED_NIGHT_HOURS is null;
update EXTRA_WORK_REQUEST set REQUESTED_EXTRA_NIGHT_HOURS = EXTRA_NIGHT_HOURS where REQUESTED_EXTRA_NIGHT_HOURS is null;
update EXTRA_WORK_REQUEST set REQUESTED_HOLIDAY_HOURS = HOLIDAY_HOURS where REQUESTED_HOLIDAY_HOURS is null;
update EXTRA_WORK_REQUEST set REQUESTED_SATURDAY_HOURS = SATURDAY_HOURS where REQUESTED_SATURDAY_HOURS is null;
update EXTRA_WORK_REQUEST set REQUESTED_SUNDAY_HOURS = SUNDAY_HOURS where REQUESTED_SUNDAY_HOURS is null;
update EXTRA_WORK_REQUEST set REQUESTED_WORKDAY_HOURS = WORKDAY_HOURS where REQUESTED_WORKDAY_HOURS is null;

alter table EXTRA_WORK_REQUEST add column HOLIDAY_AMOUNT double default '0';
alter table EXTRA_WORK_REQUEST add column SATURDAY_AMOUNT double default '0';
alter table EXTRA_WORK_REQUEST add column SUNDAY_AMOUNT double default '0';
