
DROP TABLE IF EXISTS `CURRICULAR_PERIOD`;
CREATE TABLE `CURRICULAR_PERIOD` (
	`ID_INTERNAL` int NOT NULL auto_increment, 
	`KEY_PARENT` int,
	`KEY_DEGREE_CURRICULAR_PLAN` int,			
	`CHILD_ORDER` int,
	`PERIOD_TYPE` varchar(50) NOT NULL,	
    PRIMARY KEY (`ID_INTERNAL`)
)TYPE=InnoDB;

alter table DEGREE_CURRICULAR_PLAN add column KEY_DEGREE_CURRICULAR_PERIOD int default NULL;
alter table CONTEXT add column KEY_CURRICULAR_PERIOD int default NULL;
