alter table SEMINARYCANDIDACY_SEMINARYCASESTUDY drop primary key;
alter table SEMINARYCANDIDACY_SEMINARYCASESTUDY add column ID_INTERNAL int(11) default null;
update SEMINARYCANDIDACY_SEMINARYCASESTUDY 
set SEMINARYCANDIDACY_SEMINARYCASESTUDY.ID_INTERNAL = 
	concat(SEMINARYCANDIDACY_SEMINARYCASESTUDY.KEY_CANDIDACY, SEMINARYCANDIDACY_SEMINARYCASESTUDY.KEY_CASE_STUDY);
alter table SEMINARYCANDIDACY_SEMINARYCASESTUDY add primary key (ID_INTERNAL);
alter table SEMINARYCANDIDACY_SEMINARYCASESTUDY change column ID_INTERNAL ID_INTERNAL int(11) not null auto_increment;
alter table SEMINARYCANDIDACY_SEMINARYCASESTUDY add unique (KEY_CANDIDACY, KEY_CASE_STUDY);