alter table RESULT add column KEY_ARTICLE_ASSOCIATION INTEGER(11);

CREATE TABLE JOURNAL_ISSUE(
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  KEY_SCIENTIFIC_JOURNAL int(11) NOT NULL,
  YEAR INTEGER,
  MONTH VARCHAR(60),
  VOLUME VARCHAR(255),
  NUMBER VARCHAR(255),
  PUBLISHER varchar(255),
  URL varchar(255), 
  PRIMARY KEY  (ID_INTERNAL),
  KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT),
  KEY KEY_SCIENTIFIC_JOURNAL (KEY_SCIENTIFIC_JOURNAL)
) ENGINE=InnoDB;

CREATE TABLE ARTICLE_ASSOCIATION(
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  KEY_JOURNAL_ISSUE int(11) NOT NULL,
  KEY_ARTICLE int(11) NOT NULL, 
  KEY_CREATOR int(11) NOT NULL,
  PRIMARY KEY  (ID_INTERNAL),
  KEY KEY_ROOT_DOMAIN_OBJECT (KEY_ROOT_DOMAIN_OBJECT),
  KEY KEY_JOURNAL_ISSUE (KEY_JOURNAL_ISSUE),
  KEY KEY_ARTICLE (KEY_ARTICLE),
  KEY KEY_CREATOR (KEY_CREATOR) 
) ENGINE=InnoDB;

alter table RESEARCH_ACTIVITY add column ISSN varchar(255);
alter table RESEARCH_ACTIVITY add column URL varchar(255);

