
SET AUTOCOMMIT = 0;
START TRANSACTION;

ALTER TABLE PHD_ALERT ADD COLUMN MAX_DAYS INT(11) DEFAULT NULL;

UPDATE PHD_ALERT SET MAX_DAYS = 20 WHERE OJB_CONCRETE_CLASS = "net.sourceforge.fenixedu.domain.phd.alert.PhdRegistrationFormalizationAlert";

COMMIT;
