#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

execute "Adding CMS_MANAGER role" addCmsManager.sql
execute "Creating more CMS tables" createCmsTables.sql
execute "Added column BIBLIOGRAPHIC_REFERENCES to CompetenceCourseInformation" alterTableCompetenceCourseInformation.sql