ALTER TABLE EMPLOYEE_BONUS_INSTALLMENT ADD COLUMN BONUS_TYPE VARCHAR(50) NOT NULL;

ALTER TABLE EMPLOYEE_BONUS_INSTALLMENT DROP COLUMN INSTALLMENT_P1_VALUE;
ALTER TABLE EMPLOYEE_BONUS_INSTALLMENT CHANGE COLUMN INSTALLMENT_P2_VALUE VALUE double not null;

ALTER TABLE EMPLOYEE_BONUS_INSTALLMENT DROP KEY U1;
ALTER TABLE EMPLOYEE_BONUS_INSTALLMENT ADD UNIQUE KEY U1 (KEY_EMPLOYEE,KEY_ANUAL_BONUS_INSTALLMENT, BONUS_TYPE);

ALTER TABLE EMPLOYEE_MONTHLY_BONUS_INSTALLMENT DROP COLUMN P2_VALUE;
ALTER TABLE EMPLOYEE_MONTHLY_BONUS_INSTALLMENT CHANGE COLUMN P1_VALUE VALUE double not null;

ALTER TABLE EMPLOYEE_MONTHLY_BONUS_INSTALLMENT ADD UNIQUE KEY U1 (KEY_EMPLOYEE_BONUS_INSTALLMENT,MONTH);