ALTER TABLE PARTY DROP COLUMN PARTY.ADDRESS;
ALTER TABLE PARTY DROP COLUMN PARTY.AREA_CODE;
ALTER TABLE PARTY DROP COLUMN PARTY.AREA_OF_AREA_CODE;
ALTER TABLE PARTY DROP COLUMN PARTY.AREA;
ALTER TABLE PARTY DROP COLUMN PARTY.PARISH_OF_RESIDENCE;
ALTER TABLE PARTY DROP COLUMN PARTY.DISTRICT_SUBDIVISION_OF_RESIDENCE;
ALTER TABLE PARTY DROP COLUMN PARTY.DISTRICT_OF_RESIDENCE;
ALTER TABLE PARTY DROP COLUMN PARTY.KEY_COUNTRY_OF_RESIDENCE;

ALTER TABLE PARTY DROP COLUMN PARTY.EMAIL;
ALTER TABLE PARTY DROP COLUMN PARTY.INSTITUTIONAL_EMAIL;

ALTER TABLE PARTY DROP COLUMN PARTY.WEB_ADDRESS;

ALTER TABLE PARTY DROP COLUMN PARTY.PHONE;
ALTER TABLE PARTY DROP COLUMN PARTY.MOBILE;
