ALTER TABLE CURRICULAR_RULE ADD COLUMN KEY_EXCLUSIVE_DEGREE_MODULE int default NULL;

ALTER TABLE CURRICULAR_RULE ADD COLUMN MINIMUM_YEAR int default NULL;
ALTER TABLE CURRICULAR_RULE ADD COLUMN MAXIMUM_YEAR int default NULL;

ALTER TABLE CURRICULAR_RULE ADD COLUMN KEY_DEGREE int default NULL;
ALTER TABLE CURRICULAR_RULE ADD COLUMN KEY_DEPARTMENT_UNIT int default NULL;

ALTER TABLE CURRICULAR_RULE ADD COLUMN CREDITS int default NULL;

ALTER TABLE CURRICULAR_RULE ADD COLUMN BOLONHA_DEGREE_TYPE varchar(50) default NULL;
