#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

echo Using database: $1
echo Enter password for $2:
read -s password

echo Altering table degree module
mysql -u$2 -f -p$password $1 < alterDegreeAndDCPlanTable.sql
echo done.
