DROP TABLE IF EXISTS VIGILANT_BOUND;
CREATE TABLE VIGILANT_BOUND(
ID_INTERNAL int(11) NOT NULL auto_increment,
CONVOKABLE tinyint(1) NOT NULL DEFAULT 1,
JUSTIFICATION varchar(255),
KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
KEY_VIGILANT int(11) NOT NULL,
KEY_VIGILANT_GROUP int(11) NOT NULL,
PRIMARY KEY(`ID_INTERNAL`)
) TYPE=InnoDB;

DROP TABLE IF EXISTS CONVOKE;
CREATE TABLE CONVOKE (
ID_INTERNAL int(11) NOT NULL auto_increment,
ATTENDED_TO_CONVOKE tinyint(1),
CONFIRMED tinyint(1),
ACTIVE tinyint(1) ,
KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
KEY_VIGILANT int(11) NOT NULL,
KEY_WRITTEN_EVALUATION int(11) NOT NULL,
PRIMARY KEY(`ID_INTERNAL`)
) TYPE=InnoDB;


drop table VIGILANT_BELONGS_TO_GROUP;
alter table VIGILANT add column START_POINTS INTEGER(4) NOT NULL DEFAULT '0';
alter table VIGILANT_GROUP add column CONTACT_EMAIL varchar(100);
alter table VIGILANT_GROUP add column RULES_LINK varchar(255);
update ROLE set PAGE='/index.do' where ROLE_TYPE='EXAM_COORDINATOR';
