#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Correct AvailabilityPolicy table and some availability expressions" CorrectAvailabilityPolicyTable.sql
execute "Fix portal mappings" FixPortalMappings.sql
execute "Add column to studentTestQuestion" alterStudentTestQuestionTable.sql
execute "Add column to VigilancyTables" alterVigilancyTables.sql
execute "Remove BolonhaDegreeType column from Degree table" dropBolonhaDegreeTypeFromDegreeTable.sql
execute "Change DegreeType enum value" updateDegreeTypeValues.sql
