#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}


execute "Add order column to bibliographic references" ChangeBiblioReferences.sql
execute "Added functionality to manager portal" CreateManageSitesFunctionality.sql
execute "Create SiteTemplate table and relations" CreateSiteTemplate.sql
execute "Create ExecutionCourse site template" CreateExecutionCourseSiteTemplate.sql

execute "Create Penalty Exemption Table" CreatePenaltyExemptionTable.sql
