insert into COUNTRY (NAME, NATIONALITY, CODE, KEY_ROOT_DOMAIN_OBJECT) values ('ARGÉLIA', 'ARGELINA', 'DZ', 1);
insert into COUNTRY (NAME, NATIONALITY, CODE, KEY_ROOT_DOMAIN_OBJECT) values ('SÉRVIA', 'SÉRVIA', 'SR', 1);
update COUNTRY set NAME = 'IRÃO (REPUBLICA ISLÁMICA DO)' where NAME = 'IRAO';
update COUNTRY set NAME = 'RÚSSIA (FEDERAÇÃO DA)' where NAME = 'RUSSIA';