UPDATE CURRICULUM_MODULE SET CURRICULUM_MODULE.WEIGTH = 3.0 WHERE CURRICULUM_MODULE.ID_INTERNAL = 1320403 AND CURRICULUM_MODULE.WEIGTH = 1.0;
UPDATE CURRICULUM_MODULE SET CURRICULUM_MODULE.WEIGTH = 3.0 WHERE CURRICULUM_MODULE.ID_INTERNAL = 1320359 AND CURRICULUM_MODULE.WEIGTH = 1.0;
