create table `INQUIRY_RESULT` (
	`OID` bigint unsigned, 
	`OID_INQUIRY_GROUP_QUESTION` bigint unsigned, 
	`OID_EXECUTION_DEGREE` bigint unsigned, 
	`RESULT_TYPE` text, 
	`OID_EXECUTION_COURSE` bigint unsigned, 
	`OID_INQUIRY_BLOCK` bigint unsigned, 
	`OID_EXECUTION_PERIOD` bigint unsigned, 
	`RESULT_CLASSIFICATION` text, 
	`VALUE` text, 
	`OID_INQUIRY_QUESTION` bigint unsigned, 
	`OID_PROFESSORSHIP` bigint unsigned, 
	`SHIFT_TYPE` text, 
	`CONNECTION_TYPE` text, 
	`OID_ROOT_DOMAIN_OBJECT` bigint unsigned, 
	`ID_INTERNAL` int(11) NOT NULL auto_increment, 
	primary key (ID_INTERNAL), 
	index (OID), 
	index (OID_INQUIRY_GROUP_QUESTION), 
	index (OID_EXECUTION_DEGREE), 
	index (OID_PROFESSORSHIP), 
	index (OID_INQUIRY_QUESTION), 
	index (OID_EXECUTION_COURSE), 
	index (OID_ROOT_DOMAIN_OBJECT), 
	index (OID_EXECUTION_PERIOD), 
	index (OID_INQUIRY_BLOCK)) type=InnoDB, 
	character set latin1;