-- DROP TABLE IF EXISTS COMPETENCE_COURSE_LOAD;
CREATE TABLE COMPETENCE_COURSE_LOAD (
	ID_INTERNAL int(11) NOT NULL auto_increment,
	KEY_COMPETENCE_COURSE_INFORMATION int(11) NOT NULL,
	THEORETICAL_HOURS double NOT NULL default 0.0,
	PROBLEMS_HOURS double NOT NULL default 0.0,
	LABORATORIAL_HOURS double NOT NULL default 0.0,
	SEMINARY_HOURS double NOT NULL default 0.0,
	FIELD_WORK_HOURS double NOT NULL default 0.0,
	TRAINING_PERIOD_HOURS double NOT NULL default 0.0,
	TUTORIAL_ORIENTATION_HOURS double NOT NULL default 0.0,
	AUTONOMOUS_WORK_HOURS double NOT NULL default 0.0,
	ECTS_CREDITS double NOT NULL default 0.0,
	PRIMARY KEY (ID_INTERNAL)
) TYPE=InnoDB;
