#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

echo Using database: $1
echo Enter password for $2:
read -s password

echo Altering table CompetenceCourse
mysql -u$2 -f -p$password $1 < alterTableCompetenceCourse.sql
echo done.

echo Altering table CompetenceCourseInformation
mysql -u$2 -f -p$password $1 < alterTableCompetenceCourseInformation.sql
echo done.

echo Creating table CompetenceCourseLoad
mysql -u$2 -f -p$password $1 < createTableCompetenceCourseLoad.sql
echo done.

echo Altering table InquiriesCourse
mysql -u$2 -f -p$password $1 < alterTableInquiriesCourse.sql
echo done.

