drop table if exists ADMINISTRATIVE_OFFICE;
create table ADMINISTRATIVE_OFFICE (
  ID_INTERNAL int(11) NOT NULL auto_increment,
  ADMINISTRATIVE_OFFICE_TYPE varchar(250) NOT NULL,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL,
  KEY_UNIT int(11) NOT NULL,
  KEY_SERVICE_AGREEMENT_TEMPLATE int(11) NULL,
  primary key (ID_INTERNAL)
) type=InnoDB;
