#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Changing table Receipt" AlterTableReceipt.sql
executeWithTempFile "Updating table Receipt" UpdateTableReceipt.sql
execute "Changing table Receipt (assert KeyEmployee not null)" AlterTableReceiptAssertKeyEmployeeNotNull.sql
execute "Changing table AccountablityType" UpdateTableAccountabilityType.sql
execute "Changing table Party" AlterTableParty.sql
execute "Changing table ServiceAgreementTemplate" AlterTableServiceAgreementTemplate.sql
execute "Creating table AdministrativeOffice" CreateTableAdministrativeOffice.sql
execute "Changing table AccountingEvent" AlterTableAccountingEvent.sql


