SET AUTOCOMMIT = 0;

START TRANSACTION;

INSERT INTO AVAILABILITY_POLICY (OID,EXPRESSION,TARGET_GROUP,CONTENT_ID,OJB_CONCRETE_CLASS,KEY_CONTENT,OID_CONTENT,KEY_ROOT_DOMAIN_OBJECT,OID_ROOT_DOMAIN_OBJECT) VALUES (1937031096493,'internalOrExternalTeacher()','internalOrExternalTeacher()','bd721b89-ec45-4750-8c45-4dce7f2d9ef4','net.sourceforge.fenixedu.domain.functionalities.ExpressionGroupAvailability',1,403727020464,1,1035087118337)  ;

UPDATE CONTENT SET OID=403727020464,ENABLED=null,MODIFICATION_DATE=null,MAXIMIZABLE=null,PREFIX=null,KEY_INITIAL_CONTENT=null,OID_INITIAL_CONTENT=null,CONTENT_ID='20e0ca73d61dd1816ebf7fa000ca3fec',CREATION_DATE='2008-01-14 20:40:18',NAME='pt8:Docência',TITLE=null,BODY=null,DESCRIPTION=null,NORMALIZED_NAME=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.Section',KEY_PORTAL=null,OID_PORTAL=null,KEY_AVAILABILITY_POLICY=2,OID_AVAILABILITY_POLICY=1937031096493,KEY_ROOT_DOMAIN_OBJECT=1,OID_ROOT_DOMAIN_OBJECT=1035087118337,KEY_CREATOR=null,OID_CREATOR=null WHERE CONTENT_ID = '20e0ca73d61dd1816ebf7fa000ca3fec'  ;

UPDATE AVAILABILITY_POLICY SET OID=1937031096492,EXPRESSION='role(TEACHER)',TARGET_GROUP='role(TEACHER)',CONTENT_ID='7041fc0c-4fb1-47ed-b569-7d9be4cd5b64',OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.functionalities.ExpressionGroupAvailability',KEY_CONTENT=null,OID_CONTENT=null,KEY_ROOT_DOMAIN_OBJECT=1,OID_ROOT_DOMAIN_OBJECT=1035087118337 WHERE CONTENT_ID = '7041fc0c-4fb1-47ed-b569-7d9be4cd5b64'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));

INSERT INTO UUID_TEMP_TABLE(COUNTER,UUID,FROM_UUID) VALUES(1,'20e0ca73d61dd1816ebf7fa000ca3fec','bd721b89-ec45-4750-8c45-4dce7f2d9ef4') ;
INSERT INTO UUID_TEMP_TABLE(COUNTER,UUID,FROM_UUID) VALUES(2,'bd721b89-ec45-4750-8c45-4dce7f2d9ef4','20e0ca73d61dd1816ebf7fa000ca3fec') ;
ALTER TABLE UUID_TEMP_TABLE ADD INDEX (COUNTER), ADD INDEX (UUID), ADD INDEX (FROM_UUID); 


UPDATE NODE T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_PARENT=CT.ID_INTERNAL WHERE T.KEY_PARENT=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE NODE T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_CHILD=CT.ID_INTERNAL WHERE T.KEY_CHILD=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_FUNCTIONALITY=CT.ID_INTERNAL WHERE T.KEY_FUNCTIONALITY=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, EXECUTION_PATH CT set T.KEY_EXECUTION_PATH_VALUE=CT.ID_INTERNAL WHERE T.KEY_EXECUTION_PATH_VALUE=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_INITIAL_CONTENT=CT.ID_INTERNAL WHERE T.KEY_INITIAL_CONTENT=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_PORTAL=CT.ID_INTERNAL WHERE T.KEY_PORTAL=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, AVAILABILITY_POLICY CT set T.KEY_AVAILABILITY_POLICY=CT.ID_INTERNAL WHERE T.KEY_AVAILABILITY_POLICY=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE AVAILABILITY_POLICY T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_CONTENT=CT.ID_INTERNAL WHERE T.KEY_CONTENT=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE EXECUTION_PATH T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_FUNCTIONALITY=CT.ID_INTERNAL WHERE T.KEY_FUNCTIONALITY=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
DROP TABLE UUID_TEMP_TABLE;

INSERT INTO AVAILABILITY_POLICY (OID,EXPRESSION,TARGET_GROUP,CONTENT_ID,OJB_CONCRETE_CLASS,KEY_CONTENT,OID_CONTENT,KEY_ROOT_DOMAIN_OBJECT,OID_ROOT_DOMAIN_OBJECT) VALUES (1937031096494,'internalOrExternalTeacher()','internalOrExternalTeacher()','f0cab6c2-2e8e-4a18-834c-74bc4d21b446','net.sourceforge.fenixedu.domain.functionalities.ExpressionGroupAvailability',3,3749506658262,1,1035087118337)  ;

UPDATE CONTENT SET OID=3749506658262,KEY_FUNCTIONALITY=4,OID_FUNCTIONALITY=8590029298,CONTENT_ID='20e0ca73d61dd1816ebf7fa000ca3fec:25b139a3-19e6-446b-b190-74e4caaaac6d',CREATION_DATE=null,NAME='pt8:Docência',TITLE=null,BODY=null,DESCRIPTION=null,NORMALIZED_NAME=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.contents.FunctionalityCall',KEY_PORTAL=null,OID_PORTAL=null,KEY_AVAILABILITY_POLICY=5,OID_AVAILABILITY_POLICY=1937031096494,KEY_ROOT_DOMAIN_OBJECT=1,OID_ROOT_DOMAIN_OBJECT=1035087118337,KEY_CREATOR=null,OID_CREATOR=null WHERE CONTENT_ID = '20e0ca73d61dd1816ebf7fa000ca3fec:25b139a3-19e6-446b-b190-74e4caaaac6d'  ;

UPDATE AVAILABILITY_POLICY SET OID=1937031096293,EXPRESSION='role(TEACHER)',TARGET_GROUP='role(\'TEACHER\')',CONTENT_ID='3eaa4144-6c20-499c-b12a-cac9781f7edd',OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.functionalities.ExpressionGroupAvailability',KEY_CONTENT=null,OID_CONTENT=null,KEY_ROOT_DOMAIN_OBJECT=1,OID_ROOT_DOMAIN_OBJECT=1035087118337 WHERE CONTENT_ID = '3eaa4144-6c20-499c-b12a-cac9781f7edd'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));

INSERT INTO UUID_TEMP_TABLE(COUNTER,UUID,FROM_UUID) VALUES(3,'20e0ca73d61dd1816ebf7fa000ca3fec:25b139a3-19e6-446b-b190-74e4caaaac6d','f0cab6c2-2e8e-4a18-834c-74bc4d21b446') ;
INSERT INTO UUID_TEMP_TABLE(COUNTER,UUID,FROM_UUID) VALUES(4,'25b139a3-19e6-446b-b190-74e4caaaac6d','20e0ca73d61dd1816ebf7fa000ca3fec:25b139a3-19e6-446b-b190-74e4caaaac6d') ;
INSERT INTO UUID_TEMP_TABLE(COUNTER,UUID,FROM_UUID) VALUES(5,'f0cab6c2-2e8e-4a18-834c-74bc4d21b446','20e0ca73d61dd1816ebf7fa000ca3fec:25b139a3-19e6-446b-b190-74e4caaaac6d') ;
ALTER TABLE UUID_TEMP_TABLE ADD INDEX (COUNTER), ADD INDEX (UUID), ADD INDEX (FROM_UUID); 


UPDATE NODE T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_PARENT=CT.ID_INTERNAL WHERE T.KEY_PARENT=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE NODE T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_CHILD=CT.ID_INTERNAL WHERE T.KEY_CHILD=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_FUNCTIONALITY=CT.ID_INTERNAL WHERE T.KEY_FUNCTIONALITY=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, EXECUTION_PATH CT set T.KEY_EXECUTION_PATH_VALUE=CT.ID_INTERNAL WHERE T.KEY_EXECUTION_PATH_VALUE=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_INITIAL_CONTENT=CT.ID_INTERNAL WHERE T.KEY_INITIAL_CONTENT=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_PORTAL=CT.ID_INTERNAL WHERE T.KEY_PORTAL=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE CONTENT T, UUID_TEMP_TABLE UIT, AVAILABILITY_POLICY CT set T.KEY_AVAILABILITY_POLICY=CT.ID_INTERNAL WHERE T.KEY_AVAILABILITY_POLICY=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE AVAILABILITY_POLICY T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_CONTENT=CT.ID_INTERNAL WHERE T.KEY_CONTENT=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
UPDATE EXECUTION_PATH T, UUID_TEMP_TABLE UIT, CONTENT CT set T.KEY_FUNCTIONALITY=CT.ID_INTERNAL WHERE T.KEY_FUNCTIONALITY=UIT.COUNTER AND T.CONTENT_ID = UIT.FROM_UUID AND CT.CONTENT_ID=UIT.UUID;
DROP TABLE UUID_TEMP_TABLE;



COMMIT;
