#!/bin/bash
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f  -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f  -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f  -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Update ExecutionCourses Siglas" updateExecutionCoursesSiglas.sql
execute "Adding column keyExecutionPeriod to academicServiceRequest" AddKeyExecutionPeriodToAcademicServiceRequest.sql
execute "Resolve Problem With Content Names" resolveProblemWithContentNames.sql

execute "Fix availability Policies UUID" fixAvailabilityPoliciesUUID.sql
execute "Update Content KEY_PERSON key" updateContentKEY_PERSON.sql
execute "hardcoreFixOnAcademicServiceRequestData" hardcoreFixOnAcademicServiceRequestData.sql
