DROP TABLE EMPLOYEE_PROFESSIONAL_DATA;
DROP TABLE EMPLOYEE_CONTRACT_SITUATION;
DROP TABLE EMPLOYEE_PROFESSIONAL_CATEGORY;
DROP TABLE EMPLOYEE_PROFESSIONAL_RELATION;
DROP TABLE EMPLOYEE_PROFESSIONAL_REGIME;
DROP TABLE EMPLOYEE_FUNCTIONS_ACCUMULATION;
DROP TABLE EMPLOYEE_PROFESSIONAL_CONTRACT;
DROP TABLE EMPLOYEE_PROFESSIONAL_EXEMPTION;

alter table `EMPLOYEE` drop column `OID_EMPLOYEE_PROFESSIONAL_DATA`;