
// Generated by impart OJB Generator
// www.impart.ch matthias.roth@impart.ch

package almeida;


public class Almeida_curricular_course  
{
  private long code;

  private long id_internal;

  private String name;

  public long getCode()
  {
     return this.code;
  }
  public void setCode(long param)
  {
    this.code = param;
  }


  public long getId_internal()
  {
     return this.id_internal;
  }
  public void setId_internal(long param)
  {
    this.id_internal = param;
  }


  public String getName()
  {
     return this.name;
  }
  public void setName(String param)
  {
    this.name = param;
  }


  public String toString(){
    return  " [CODE] " + code + " [ID_INTERNAL] " + id_internal + " [NAME] " + name;

  }
}

