-- SELECT
-- S.NUMBER AS STUDENT_NUMBER,
-- E.ID_INTERNAL AS ENROLLMENT_ID,
-- E.STATE AS ENROLLMENT_STATE,
-- E.KEY_EXECUTION_PERIOD AS ENROLLMENT_EXECUTION_PERIOD,
-- CC.CODE AS COURSE_CODE,
-- CC.NAME AS COURSE_NAME,
-- EE1.GRADE AS EVALUATION_WITH_GRADE_GRADE,
-- EE1.WHEN_ALTER AS EVALUATION_WITH_GRADE_WHEN_ALTEREED,
-- D.NAME AS DEGREE_NAME,
-- EE2.GRADE AS EVALUATION_WITHOUT_GRADE_GRADE,
-- EE2.WHEN_ALTER AS EVALUATION_WITHOUT_GRADE_WHENALTERED
-- FROM ENROLMENT E
-- INNER JOIN ENROLMENT_EVALUATION EE1 ON EE1.KEY_ENROLMENT = E.ID_INTERNAL
-- INNER JOIN ENROLMENT_EVALUATION EE2 ON EE2.KEY_ENROLMENT = E.ID_INTERNAL
-- INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
-- INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
-- INNER JOIN DEGREE D ON DCP.KEY_DEGREE = D.ID_INTERNAL
-- INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
-- INNER JOIN STUDENT S ON SCP.KEY_STUDENT = S.ID_INTERNAL
-- WHERE
-- EE1.GRADE <> 'RE' AND
-- EE1.GRADE <> 'NA' AND
-- EE2.GRADE = 'RE' AND
-- E.STATE = 2
-- ORDER BY D.NAME,CC.NAME;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = ', E.ID_INTERNAL, ';') as ""
FROM ENROLMENT E
INNER JOIN ENROLMENT_EVALUATION EE1 ON EE1.KEY_ENROLMENT = E.ID_INTERNAL
INNER JOIN ENROLMENT_EVALUATION EE2 ON EE2.KEY_ENROLMENT = E.ID_INTERNAL
INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
INNER JOIN DEGREE D ON DCP.KEY_DEGREE = D.ID_INTERNAL
INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
INNER JOIN STUDENT S ON SCP.KEY_STUDENT = S.ID_INTERNAL
WHERE
EE1.GRADE <> 'RE' AND
EE1.GRADE <> 'NA' AND
EE2.GRADE = 'RE' AND
E.STATE = 2;

-- **************************************************************************************************************

-- SELECT
-- S.NUMBER AS STUDENT_NUMBER,
-- E.ID_INTERNAL AS ENROLLMENT_ID,
-- E.STATE AS ENROLLMENT_STATE,
-- E.KEY_EXECUTION_PERIOD AS ENROLLMENT_EXECUTION_PERIOD,
-- CC.CODE AS COURSE_CODE,
-- CC.NAME AS COURSE_NAME,
-- EE1.GRADE AS EVALUATION_WITH_GRADE_GRADE,
-- EE1.WHEN_ALTER AS EVALUATION_WITH_GRADE_WHEN_ALTEREED,
-- D.NAME AS DEGREE_NAME,
-- EE2.GRADE AS EVALUATION_WITHOUT_GRADE_GRADE,
-- EE2.WHEN_ALTER AS EVALUATION_WITHOUT_GRADE_WHENALTERED
-- FROM ENROLMENT E
-- INNER JOIN ENROLMENT_EVALUATION EE1 ON EE1.KEY_ENROLMENT = E.ID_INTERNAL
-- INNER JOIN ENROLMENT_EVALUATION EE2 ON EE2.KEY_ENROLMENT = E.ID_INTERNAL
-- INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
-- INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
-- INNER JOIN DEGREE D ON DCP.KEY_DEGREE = D.ID_INTERNAL
-- INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
-- INNER JOIN STUDENT S ON SCP.KEY_STUDENT = S.ID_INTERNAL
-- WHERE
-- EE1.GRADE <> 'RE' AND
-- EE1.GRADE <> 'NA' AND
-- EE2.GRADE = 'NA' AND
-- E.STATE = 6
-- ORDER BY D.NAME,CC.NAME;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = ', E.ID_INTERNAL, ';') as ""
FROM ENROLMENT E
INNER JOIN ENROLMENT_EVALUATION EE1 ON EE1.KEY_ENROLMENT = E.ID_INTERNAL
INNER JOIN ENROLMENT_EVALUATION EE2 ON EE2.KEY_ENROLMENT = E.ID_INTERNAL
INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
INNER JOIN DEGREE D ON DCP.KEY_DEGREE = D.ID_INTERNAL
INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
INNER JOIN STUDENT S ON SCP.KEY_STUDENT = S.ID_INTERNAL
WHERE
EE1.GRADE <> 'RE' AND
EE1.GRADE <> 'NA' AND
EE2.GRADE = 'NA' AND
E.STATE = 6;

-- **************************************************************************************************************

-- SELECT
-- S.NUMBER AS STUDENT_NUMBER,
-- E.ID_INTERNAL AS ENROLLMENT_ID,
-- E.STATE AS ENROLLMENT_STATE,
-- E.KEY_EXECUTION_PERIOD AS ENROLLMENT_EXECUTION_PERIOD,
-- CC.CODE AS COURSE_CODE,
-- CC.NAME AS COURSE_NAME,
-- EE1.GRADE AS EVALUATION_WITH_GRADE_GRADE,
-- EE1.WHEN_ALTER AS EVALUATION_WITH_GRADE_WHEN_ALTEREED,
-- EE1.EVALUATION_TYPE AS EVALUATION_WITH_GRADE_EVALUATION_TYPE,
-- D.NAME AS DEGREE_NAME,
-- EE2.GRADE AS EVALUATION_WITHOUT_GRADE_GRADE,
-- EE2.WHEN_ALTER AS EVALUATION_WITHOUT_GRADE_WHENALTERED,
-- EE2.EVALUATION_TYPE AS EVALUATION_WITHOUT_GRADE_EVALUATION_TYPE
-- FROM ENROLMENT E
-- INNER JOIN ENROLMENT_EVALUATION EE1 ON EE1.KEY_ENROLMENT = E.ID_INTERNAL
-- INNER JOIN ENROLMENT_EVALUATION EE2 ON EE2.KEY_ENROLMENT = E.ID_INTERNAL
-- INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
-- INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
-- INNER JOIN DEGREE D ON DCP.KEY_DEGREE = D.ID_INTERNAL
-- INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
-- INNER JOIN STUDENT S ON SCP.KEY_STUDENT = S.ID_INTERNAL
-- WHERE
-- EE1.GRADE = 'RE' AND
-- EE2.GRADE = 'NA' AND
-- E.STATE = 6
-- ORDER BY D.NAME,CC.NAME;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = ', E.ID_INTERNAL, ';') as ""
FROM ENROLMENT E
INNER JOIN ENROLMENT_EVALUATION EE1 ON EE1.KEY_ENROLMENT = E.ID_INTERNAL
INNER JOIN ENROLMENT_EVALUATION EE2 ON EE2.KEY_ENROLMENT = E.ID_INTERNAL
INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
INNER JOIN DEGREE D ON DCP.KEY_DEGREE = D.ID_INTERNAL
INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
INNER JOIN STUDENT S ON SCP.KEY_STUDENT = S.ID_INTERNAL
WHERE
EE1.GRADE = 'RE' AND
EE2.GRADE = 'NA' AND
E.STATE = 6;

-- **************************************************************************************************************

