-- SELECT CONCAT('UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = ', E.ID_INTERNAL, ';') AS "QQ"
-- FROM ENROLMENT_EVALUATION EE
-- INNER JOIN ENROLMENT E ON EE.KEY_ENROLMENT = E.ID_INTERNAL
-- INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
-- INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
-- WHERE
-- CC.KEY_DEGREE_CURRICULAR_PLAN = 48 AND
-- CC.CODE = 'APD' AND
-- EE.GRADE = 'RE' AND
-- E.STATE = 3;

SELECT CONCAT('UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = ', E.ID_INTERNAL, ';') AS ""
FROM ENROLMENT_EVALUATION EE
INNER JOIN ENROLMENT E ON EE.KEY_ENROLMENT = E.ID_INTERNAL
INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
WHERE
EE.GRADE = 'RE' AND
E.STATE = 3;
