SELECT CONCAT('UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = ', CC.ID_INTERNAL, ';') AS ""
FROM mw_DISCIPLINAS_ILEEC MWDILEEC
INNER JOIN CURRICULAR_COURSE CC ON MWDILEEC.CODIGO_DISCIPLINA = CC.CODE
INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
WHERE (DCP.ID_INTERNAL = 48 AND MWDILEEC.INSC_OBRIGATORIA = 0) OR (DCP.ID_INTERNAL = 48 AND CC.NAME LIKE 'TRABALHO FINAL DE CURSO%');
