-- SELECT E.*
-- FROM ENROLMENT E
-- INNER JOIN ENROLMENT_EVALUATION EE ON EE.KEY_ENROLMENT = E.ID_INTERNAL
-- WHERE
-- EE.GRADE = 'NA' AND
-- E.STATE <> 2 AND
-- E.STATE <> 5 AND
-- E.STATE <> 6 AND
-- E.STATE <> 1
-- order by E.KEY_EXECUTION_PERIOD;




SELECT CONCAT('UPDATE ENROLMENT SET STATE = 6 WHERE ID_INTERNAL = ', E.ID_INTERNAL, ';') AS ""
FROM ENROLMENT E
INNER JOIN ENROLMENT_EVALUATION EE ON EE.KEY_ENROLMENT = E.ID_INTERNAL
WHERE
EE.GRADE = 'NA' AND
E.STATE <> 2 AND
E.STATE <> 5 AND
E.STATE <> 6 AND
E.STATE <> 1;
