ALTER TABLE RESTRICTION ADD PERIOD_TO_APPLY int(11) default null;

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = ', cc.ID_INTERNAL, ';') as "QQ"
-- from mw_disciplinas_ileec mwdileec
-- inner join curricular_course cc on mwdileec.codigo_disciplina = cc.code
-- inner join degree_curricular_plan dcp on cc.key_degree_curricular_plan = dcp.id_internal
-- where dcp.id_internal = 48 and mwdileec.insc_obrigatoria = 1 and mwdileec.nome not like 'Trabalho Final de Curso%';
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2698;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2687;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2731;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2724;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2705;

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = ', ID_INTERNAL, ';') as "QQ"
-- from curricular_course
-- where (name not like 'Trabalho Final de Curso%' and name not like 'Opção%')
-- and key_degree_curricular_plan = 48;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 11255;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2566;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2628;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2765;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2943;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2992;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2993;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2994;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2995;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2996;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2997;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2998;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2999;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3000;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3001;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3002;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3003;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3004;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3005;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3006;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3007;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3008;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3009;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3010;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3011;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3012;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3013;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3014;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3015;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3016;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3017;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3018;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3019;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3020;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3021;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3022;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3023;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3024;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3025;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3026;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3027;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3028;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3029;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3030;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3031;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3032;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3033;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3034;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3035;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3036;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3037;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3038;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3040;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3041;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3042;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3043;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3044;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3045;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3046;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3047;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3048;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3049;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3050;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3051;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3058;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3059;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3060;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3061;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3062;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3063;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3064;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3070;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3071;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3072;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3073;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3074;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3075;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3078;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3112;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3119;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 3125;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2669;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2675;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2683;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2687;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2698;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2701;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2705;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2714;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2724;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2731;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2738;
UPDATE CURRICULAR_COURSE SET TYPE = 1 WHERE ID_INTERNAL = 2739;

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('UPDATE CURRICULAR_COURSE SET TYPE = 2 WHERE ID_INTERNAL = ', ID_INTERNAL, ';') as "QQ"
-- from curricular_course
-- where name like 'Opção%' and key_degree_curricular_plan = 48;
UPDATE CURRICULAR_COURSE SET TYPE = 2 WHERE ID_INTERNAL = 4921;

-- select concat('UPDATE CURRICULAR_COURSE SET TYPE = 4 WHERE ID_INTERNAL = ', ID_INTERNAL, ';') as "QQ"
-- from curricular_course
-- where name like 'Trabalho Final de Curso%' and key_degree_curricular_plan = 48;
UPDATE CURRICULAR_COURSE SET TYPE = 4 WHERE ID_INTERNAL = 2574;
UPDATE CURRICULAR_COURSE SET TYPE = 4 WHERE ID_INTERNAL = 2576;
UPDATE CURRICULAR_COURSE SET TYPE = 4 WHERE ID_INTERNAL = 2766;

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = ', cc.ID_INTERNAL, ';') as "QQ"
-- from mw_disciplinas_ileec mwdileec
-- inner join curricular_course cc on mwdileec.codigo_disciplina = cc.code
-- inner join degree_curricular_plan dcp on cc.key_degree_curricular_plan = dcp.id_internal
-- where (dcp.id_internal = 48 and mwdileec.insc_obrigatoria = 0) or (dcp.id_internal = 48 and cc.name like 'Trabalho Final de Curso%');
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2714;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2669;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3112;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3119;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3125;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2683;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2701;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2943;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2993;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2992;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2628;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2994;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2995;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3000;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2738;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2739;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2997;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2566;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2996;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2999;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2998;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3001;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3002;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3003;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3004;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3005;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3006;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3007;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3008;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3009;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3010;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3011;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3012;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3013;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3014;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3015;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3016;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3017;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3018;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3019;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3020;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3021;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3022;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3023;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3024;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3025;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3026;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3027;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3028;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3029;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3031;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3032;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3033;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3034;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3035;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3037;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3038;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3040;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3041;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3042;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3043;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3044;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3045;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3046;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3047;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3048;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3049;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3050;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3051;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3030;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3073;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3074;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2675;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2765;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3060;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3061;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3063;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3071;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3078;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3036;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3059;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3064;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3058;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3062;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3072;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3075;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 3070;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2574;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 4921;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2576;
UPDATE CURRICULAR_COURSE SET MANDATORY = 0 WHERE ID_INTERNAL = 2766;

-- -------------------------------------------------------------------------------------------------------------------------

UPDATE CURRICULAR_COURSE SET CREDITS = 4 WHERE KEY_DEGREE_CURRICULAR_PLAN = 48;

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO PRECEDENCE VALUES (113,2687,'SP',1);
INSERT INTO PRECEDENCE VALUES (114,2687,'SP',1);

INSERT INTO PRECEDENCE VALUES (115,2731,'SP',1);
INSERT INTO PRECEDENCE VALUES (116,2731,'SP',1);
INSERT INTO PRECEDENCE VALUES (117,2731,'SP',1);

INSERT INTO PRECEDENCE VALUES (118,2724,'SP',1);
INSERT INTO PRECEDENCE VALUES (119,2724,'SP',1);
INSERT INTO PRECEDENCE VALUES (120,2724,'SP',1);
INSERT INTO PRECEDENCE VALUES (121,2724,'SP',1);
INSERT INTO PRECEDENCE VALUES (122,2576,'SP',1);
INSERT INTO PRECEDENCE VALUES (123,2766,'SP',1);


INSERT INTO RESTRICTION VALUES (125,'Dominio.RestrictionDoneCurricularCourse',113,2698,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (126,'Dominio.RestrictionPeriodToApply',113,NULL,NULL,1,2);

INSERT INTO RESTRICTION VALUES (127,'Dominio.RestrictionByNumberOfDoneCurricularCourses',114,NULL,1,1,NULL);
INSERT INTO RESTRICTION VALUES (128,'Dominio.RestrictionPeriodToApply',114,NULL,NULL,1,1);


INSERT INTO RESTRICTION VALUES (129,'Dominio.RestrictionDoneCurricularCourse',115,2698,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (130,'Dominio.RestrictionPeriodToApply',115,NULL,NULL,1,1);

INSERT INTO RESTRICTION VALUES (131,'Dominio.RestrictionDoneCurricularCourse',116,2687,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (132,'Dominio.RestrictionPeriodToApply',116,NULL,NULL,1,1);

INSERT INTO RESTRICTION VALUES (133,'Dominio.RestrictionDoneCurricularCourse',117,2698,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (134,'Dominio.RestrictionDoneCurricularCourse',117,2687,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (135,'Dominio.RestrictionPeriodToApply',117,NULL,NULL,1,2);


INSERT INTO RESTRICTION VALUES (136,'Dominio.RestrictionDoneCurricularCourse',118,2698,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (137,'Dominio.RestrictionDoneCurricularCourse',118,2687,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (138,'Dominio.RestrictionPeriodToApply',118,NULL,NULL,1,1);

INSERT INTO RESTRICTION VALUES (139,'Dominio.RestrictionDoneCurricularCourse',119,2731,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (140,'Dominio.RestrictionDoneCurricularCourse',119,2687,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (141,'Dominio.RestrictionPeriodToApply',119,NULL,NULL,1,1);

INSERT INTO RESTRICTION VALUES (142,'Dominio.RestrictionDoneCurricularCourse',120,2731,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (143,'Dominio.RestrictionDoneCurricularCourse',120,2698,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (144,'Dominio.RestrictionPeriodToApply',120,NULL,NULL,1,1);

INSERT INTO RESTRICTION VALUES (145,'Dominio.RestrictionDoneCurricularCourse',121,2731,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (146,'Dominio.RestrictionDoneCurricularCourse',121,2698,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (147,'Dominio.RestrictionDoneCurricularCourse',121,2687,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (148,'Dominio.RestrictionPeriodToApply',121,NULL,NULL,1,2);

INSERT INTO RESTRICTION VALUES (149,'Dominio.RestrictionHasEverBeenOrIsCurrentlyEnrolledInCurricularCourse',122,2574,NULL,1,NULL);
INSERT INTO RESTRICTION VALUES (150,'Dominio.RestrictionHasEverBeenOrIsCurrentlyEnrolledInCurricularCourse',123,2576,NULL,1,NULL);

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = ', e.ID_INTERNAL, ';') as "QQ"
-- from enrolment_evaluation ee
-- inner join enrolment e on ee.key_enrolment = e.id_internal
-- inner join curricular_course cc on e.key_curricular_course = cc.id_internal
-- inner join student_curricular_plan scp on e.key_student_curricular_plan = scp.id_internal
-- where
-- cc.key_degree_curricular_plan = 48 and
-- cc.code = 'APD' and
-- ee.grade = 'RE' and
-- e.state = 3;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 3898;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 5799;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 5869;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 7401;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 7414;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 9570;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 9758;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 11323;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 14498;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 14668;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 16962;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 17572;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 19331;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 19475;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 19631;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 19798;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 19864;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 19915;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 20177;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 26287;
UPDATE ENROLMENT SET STATE = 2 WHERE ID_INTERNAL = 26356;

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = ', e.ID_INTERNAL, ';') as "QQ"
-- from enrolment_evaluation ee
-- inner join enrolment e on ee.key_enrolment = e.id_internal
-- inner join curricular_course cc on e.key_curricular_course = cc.id_internal
-- inner join student_curricular_plan scp on e.key_student_curricular_plan = scp.id_internal
-- where 
-- cc.key_degree_curricular_plan = 48 and
-- cc.code = 'APD' and
-- (ee.grade is not null and ee.grade <> 'RE') and 
-- e.state = 3;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 3902;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 4118;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 4142;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 4690;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 4948;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 4976;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 4985;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 5385;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 5795;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 5853;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 7530;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 7669;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 8937;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 9596;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 9945;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 10008;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 12126;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 13945;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14101;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14174;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14237;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14258;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14325;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14360;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14533;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14633;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 14662;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 17092;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 17130;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 17427;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 17433;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19248;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19267;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19271;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19297;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19302;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19306;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19351;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19386;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19461;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19490;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19520;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19546;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19555;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19562;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19610;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19640;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19644;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19658;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19698;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19755;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19763;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19787;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19817;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19827;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19842;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19886;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19924;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 19948;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 20050;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 20067;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 20078;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 20124;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 20149;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 20151;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 23088;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 23140;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 23534;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25415;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25439;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25449;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25454;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25460;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25509;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25513;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25519;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25529;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25538;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25549;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25565;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25593;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25603;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25639;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25654;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25670;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25683;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25692;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25699;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25704;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25719;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25737;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25747;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25762;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25770;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25785;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25817;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25828;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25833;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25842;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25868;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25871;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25908;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25915;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25927;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25932;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25941;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25954;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25964;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25978;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25982;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 25989;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26002;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26006;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26011;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26019;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26055;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26058;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26066;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26092;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26115;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26118;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26129;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26154;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26166;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26173;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26181;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26201;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26211;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26215;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26219;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26230;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26256;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26268;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26277;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26292;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26298;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26302;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26317;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26322;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26347;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 26374;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 28988;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 29217;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 29242;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 36218;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 36223;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 36725;
UPDATE ENROLMENT SET STATE = 1 WHERE ID_INTERNAL = 36748;

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = ', ee2.id_internal, ';') as "QQ"
-- from enrolment e
-- inner join enrolment_evaluation ee1 on ee1.key_enrolment = e.id_internal
-- inner join enrolment_evaluation ee2 on ee2.key_enrolment = e.id_internal
-- inner join curricular_course cc on e.key_curricular_course = cc.id_internal
-- where
-- cc.key_degree_curricular_plan = 48 and
-- cc.code = 'APD' and
-- ee1.grade is not null and
-- ee2.grade is null and
-- e.state = 3;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 3911;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 3915;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 4131;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 4155;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 4703;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 4961;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 4989;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 4998;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 5398;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 5808;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 5812;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 5866;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 5882;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 7414;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 7427;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 7543;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 7682;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 8950;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 9583;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 9609;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 9771;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 9958;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 10021;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 11336;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 12139;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 13958;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14114;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14187;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14250;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14271;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14338;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14373;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14511;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14546;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14646;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14675;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 14681;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 16975;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 17105;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 17143;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 17440;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 17446;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 17585;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19261;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19280;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19284;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19310;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19315;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19319;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19344;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19364;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19399;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19474;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19488;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19503;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19533;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19559;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19568;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19575;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19623;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19644;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19653;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19657;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19671;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19711;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19768;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19776;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19800;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19811;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19830;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19840;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19855;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19877;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19899;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19928;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19937;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 19961;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 20063;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 20080;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 20091;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 20137;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 20162;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 20164;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 20190;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 23101;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 23153;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 23547;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25428;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25452;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25462;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25467;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25473;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25522;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25526;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25532;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25542;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25551;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25562;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25578;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25606;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25616;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25652;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25667;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25683;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25696;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25705;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25712;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25717;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25732;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25750;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25760;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25775;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25783;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25798;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25830;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25841;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25846;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25855;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25881;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25884;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25921;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25928;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25940;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25945;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25954;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25967;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25977;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25991;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 25995;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26002;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26015;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26019;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26024;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26032;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26068;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26071;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26079;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26105;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26128;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26131;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26142;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26167;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26179;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26186;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26194;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26214;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26224;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26228;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26232;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26243;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26269;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26281;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26290;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26300;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26305;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26311;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26315;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26330;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26335;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26360;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26369;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 26387;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 29001;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 29230;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 29255;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 36231;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 36236;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 36738;
DELETE FROM ENROLMENT_EVALUATION WHERE ID_INTERNAL = 36761;

-- -------------------------------------------------------------------------------------------------------------------------

