DROP TABLE IF EXISTS ACCOUNTING_TRANSACTION_DETAIL;
CREATE TABLE ACCOUNTING_TRANSACTION_DETAIL (
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  WHEN_REGISTERED datetime NOT NULL,
  WHEN_PROCESSED datetime NOT NULL,
  PAYMENT_MODE VARCHAR(255) NOT NULL,
  OJB_CONCRETE_CLASS VARCHAR(255) NOT NULL,
  COMMENTS text NULL,
  KEY_TRANSACTION int(11) NOT NULL,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  SIBS_TRANSACTION_ID VARCHAR(50) NULL,
  SIBS_CODE VARCHAR(50) NULL,
  PRIMARY KEY  (ID_INTERNAL),
  KEY (KEY_ROOT_DOMAIN_OBJECT),
  KEY (KEY_TRANSACTION)
) ENGINE=InnoDB;



