#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Changes in Functionalities" changes-20070117194619.sql
execute "Create Academic Calendar Tables" createAcademicCalendarTables.sql

execute "Add Column keyEarthUnit" alterTableRootDomainObject.sql
execute "Add Column keyRootDomainObjectForEarthUnit" alterTableParty.sql

execute "---" DropBlogTables.sql
execute "---" MergeHomepageInSite.sql

