--  SQL file representing changes to the functionalities model
--  Generated at Tue Oct 10 21:02:58 WEST 2006
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Deleting functionalities
-- 

--  ID: 15 UUID: '27767d03-18ec-40c1-b28e-c45f594d6572'
DELETE FROM ap, f USING `AVAILABILITY_POLICY` AS ap, `FUNCTIONALITY` AS f WHERE f.`UUID` = '27767d03-18ec-40c1-b28e-c45f594d6572' AND ap.`KEY_FUNCTIONALITY` = f.`ID_INTERNAL`;
  
--  ID: 17 UUID: 'a4b9c5f0-a451-400b-a4f5-064f80b0ea0a'
DELETE FROM ap, f USING `AVAILABILITY_POLICY` AS ap, `FUNCTIONALITY` AS f WHERE f.`UUID` = 'a4b9c5f0-a451-400b-a4f5-064f80b0ea0a' AND ap.`KEY_FUNCTIONALITY` = f.`ID_INTERNAL`;
  
--  ID: 18 UUID: '8215581c-3601-48bb-a2df-bd70baef2091'
DELETE FROM ap, f USING `AVAILABILITY_POLICY` AS ap, `FUNCTIONALITY` AS f WHERE f.`UUID` = '8215581c-3601-48bb-a2df-bd70baef2091' AND ap.`KEY_FUNCTIONALITY` = f.`ID_INTERNAL`;
  
--  ID: 19 UUID: '4c18159d-ea92-4dc0-910a-8ee6e0bb862e'
DELETE FROM ap, f USING `AVAILABILITY_POLICY` AS ap, `FUNCTIONALITY` AS f WHERE f.`UUID` = '4c18159d-ea92-4dc0-910a-8ee6e0bb862e' AND ap.`KEY_FUNCTIONALITY` = f.`ID_INTERNAL`;
  
-- 
--  Updating existing functionalities
-- 

--  ID: 16 UUID: '1b93ed76-0947-4628-9a10-adae46846e01'
UPDATE `FUNCTIONALITY` AS own SET own.`ORDER_IN_MODULE` = 0 WHERE own.`UUID` = '1b93ed76-0947-4628-9a10-adae46846e01';
  
-- 
--  Inserting new functionalities
-- 

--  ID: 250 UUID: '41f83107-f634-4c9b-9395-9acd8dab9bf7'
INSERT INTO `FUNCTIONALITY` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`) SELECT '41f83107-f634-4c9b-9395-9acd8dab9bf7', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt16:Gestão de Avisos', NULL, NULL, '/manageAdvisories.do?method=start', NULL, 1, 1, NULL, 1, 1, 0, 1 FROM `FUNCTIONALITY` WHERE `UUID` = '436a0eab-5fa1-4d9e-b485-47b79f208d3e';
  
--  ID: 251 UUID: '9b4fdbc4-e0c4-439f-bcc1-be923f783d66'
INSERT INTO `FUNCTIONALITY` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`) SELECT '9b4fdbc4-e0c4-439f-bcc1-be923f783d66', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt16:Gestão de Boards', NULL, NULL, '/announcements/announcementBoardsManagement.do?method=start', NULL, 1, 1, NULL, 2, 1, 0, 1 FROM `FUNCTIONALITY` WHERE `UUID` = '436a0eab-5fa1-4d9e-b485-47b79f208d3e';
  
COMMIT;
