alter table `EMPLOYEE_CONTRACT_SITUATION` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);
alter table `EMPLOYEE_CONTRACT_SITUATION` add index (`OID_EMPLOYEE_PROFESSIONAL_DATA`);
alter table `EMPLOYEE_FUNCTIONS_ACCUMULATION` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);
alter table `EMPLOYEE_FUNCTIONS_ACCUMULATION` add index (`OID_EMPLOYEE_PROFESSIONAL_DATA`);
alter table `EMPLOYEE_PROFESSIONAL_CATEGORY` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);
alter table `EMPLOYEE_PROFESSIONAL_CATEGORY` add index (`OID_EMPLOYEE_PROFESSIONAL_DATA`);
alter table `EMPLOYEE_PROFESSIONAL_CONTRACT` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);
alter table `EMPLOYEE_PROFESSIONAL_CONTRACT` add index (`OID_EMPLOYEE_PROFESSIONAL_DATA`);
alter table `EMPLOYEE_PROFESSIONAL_EXEMPTION` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);
alter table `EMPLOYEE_PROFESSIONAL_EXEMPTION` add index (`OID_EMPLOYEE_PROFESSIONAL_DATA`);
alter table `EMPLOYEE_PROFESSIONAL_REGIME` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);
alter table `EMPLOYEE_PROFESSIONAL_REGIME` add index (`OID_EMPLOYEE_PROFESSIONAL_DATA`);
alter table `EMPLOYEE_PROFESSIONAL_RELATION` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);
alter table `EMPLOYEE_PROFESSIONAL_RELATION` add index (`OID_EMPLOYEE_PROFESSIONAL_DATA`);
alter table `EMPLOYEE` add column `OID_EMPLOYEE_PROFESSIONAL_DATA` bigint(20);


create table `EMPLOYEE_PROFESSIONAL_DATA` (
  `ANULATION_DATE` timestamp NULL default NULL,
  `CONTRACT_SITUATION_DATE` text,
  `CONTRACT_SITUATION_GIAF_ID` longtext,
  `CREATION_DATE` timestamp NULL default NULL,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `IMPORTATION_DATE` timestamp NULL default NULL,
  `MODIFIED_DATE` timestamp NULL default NULL,
  `OID` bigint(20),
  `OID_CONTRACT_SITUATION` bigint(20),
  `OID_EMPLOYEE` bigint(20),
  `OID_PROFESSIONAL_CATEGORY` bigint(20),
  `OID_PROFESSIONAL_CONTRACT_TYPE` bigint(20),
  `OID_PROFESSIONAL_REGIME` bigint(20),
  `OID_PROFESSIONAL_RELATION` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  `PROFESSIONAL_CATEGORY_DATE` text,
  `PROFESSIONAL_CATEGORY_GIAF_ID` longtext,
  `PROFESSIONAL_CONTRACT_TYPE_GIAF_ID` longtext,
  `PROFESSIONAL_REGIME_DATE` text,
  `PROFESSIONAL_REGIME_GIAF_ID` longtext,
  `PROFESSIONAL_RELATION_DATE` text,
  `PROFESSIONAL_RELATION_GIAF_ID` longtext,
  primary key (ID_INTERNAL),
  index (OID),
  index (OID_CONTRACT_SITUATION),
  index (OID_PROFESSIONAL_CATEGORY),
  index (OID_PROFESSIONAL_CONTRACT_TYPE),
  index (OID_PROFESSIONAL_REGIME),
  index (OID_PROFESSIONAL_RELATION),
  index (OID_ROOT_DOMAIN_OBJECT)
) type=InnoDB, character set latin1 ;

create table `PROFESSIONAL_CONTRACT_TYPE` (
  `GIAF_ID` longtext,
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `NAME` longtext,
  `OID` bigint(20),
  `OID_ROOT_DOMAIN_OBJECT` bigint(20),
  primary key (ID_INTERNAL),
  index (OID),
  index (OID_ROOT_DOMAIN_OBJECT)
) type=InnoDB, character set latin1 ;

alter table `EMPLOYEE_PROFESSIONAL_EXEMPTION` add column `GRANT_OWNER_EQUIVALENT_GIAF_ID` text;
alter table `EMPLOYEE_PROFESSIONAL_EXEMPTION` add column `SERVICE_EXEMPTION_GIAF_ID` text;
