DROP TABLE IF EXISTS FORUM_BOOKMARK;
CREATE TABLE FORUM_BOOKMARK (
  ID_INTERNAL INT(11) NOT NULL auto_increment,
  RECEIVE_POSTS_BY_EMAIL TINYINT(1) NOT NULL,
  KEY_PERSON INT(11) NOT NULL,
  KEY_FORUM INT(11) NOT NULL,
  PRIMARY KEY  (ID_INTERNAL),
  UNIQUE (KEY_PERSON,KEY_FORUM)
) ENGINE=InnoDB;
