CREATE TABLE `MARKSHEET` (
  `ID_INTERNAL` int NOT NULL auto_increment,
  `KEY_EXECUTION_PERIOD` int NOT NULL DEFAULT 0,
  `KEY_RESPONSIBLE_TEACHER` int NOT NULL DEFAULT 0,  
  `KEY_EMPLOYEE` int DEFAULT NULL,  
  `KEY_CURRICULAR_COURSE` int NOT NULL DEFAULT 0,  
  `CREATION_DATE` datetime NOT NULL DEFAULT '0000-00-00',
  `EVALUATION_DATE` datetime NOT NULL DEFAULT '0000-00-00',
  `CONFIRMATION_DATE` datetime DEFAULT NULL,
  `CHECKSUM` varchar(150) NOT NULL DEFAULT '',
  `MARKSHEET_TYPE` varchar(150) NOT NULL DEFAULT '',
  `MARKSHEET_STATE` varchar(150) NOT NULL DEFAULT '',
  `KEY_ROOT_DOMAIN_OBJECT` int(11) NOT NULL default '1',
  PRIMARY KEY  (`ID_INTERNAL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
