select concat('insert into PERSON_ROLE set KEY_PERSON=', KEY_PERSON, ' , KEY_ROLE= (select ROLE.ID_INTERNAL FROM ROLE WHERE ROLE.ROLE_TYPE="RESEARCHER") ;')
as "" from PERSON_ROLE where PERSON_ROLE.KEY_ROLE=3;
