CREATE TABLE `DISLOCATED_STUDENT` (
  `ID_INTERNAL` int(11) NOT NULL auto_increment,
  `ACK_OPT_LOCK` int(11) default NULL,
  `KEY_STUDENT` int(11) NOT NULL,  
  `KEY_COUNTRY` int(11) NOT NULL,
  `KEY_DISLOCATED_COUNTRY` int(11),
  `KEY_DISTRICT` int(11),  
  PRIMARY KEY  (`ID_INTERNAL`),
  UNIQUE KEY `U1` (`KEY_STUDENT`)
) Type=InnoDB;