insert into DISTRICT (CODE,NAME) values(1,"Aveiro");
insert into DISTRICT (CODE,NAME) values(2,"Beja");
insert into DISTRICT (CODE,NAME) values(3,"Braga");
insert into DISTRICT (CODE,NAME) values(4,"Bragança");
insert into DISTRICT (CODE,NAME) values(5,"Castelo Branco");
insert into DISTRICT (CODE,NAME) values(6,"Coimbra");
insert into DISTRICT (CODE,NAME) values(7,"Évora");
insert into DISTRICT (CODE,NAME) values(8,"Faro");
insert into DISTRICT (CODE,NAME) values(9,"Guarda");
insert into DISTRICT (CODE,NAME) values(10,"Leiria");
insert into DISTRICT (CODE,NAME) values(11,"Lisboa");
insert into DISTRICT (CODE,NAME) values(12,"Portalegre");
insert into DISTRICT (CODE,NAME) values(13,"Porto");
insert into DISTRICT (CODE,NAME) values(14,"Santarém");
insert into DISTRICT (CODE,NAME) values(15,"Setúbal");
insert into DISTRICT (CODE,NAME) values(16,"Viana do Castelo");
insert into DISTRICT (CODE,NAME) values(17,"Vila Real");
insert into DISTRICT (CODE,NAME) values(18,"Viseu");
insert into DISTRICT (CODE,NAME) values(19,"R. A. Açores");
insert into DISTRICT (CODE,NAME) values(22,"R. A. Madeira");