select concat('UPDATE GROUPING_ATTENDS set GROUPING_ATTENDS.KEY_GROUPING = ', 
       ATTENDS_SET.KEY_GROUP_PROPERTIES, 
       ' where GROUPING_ATTENDS.KEY_GROUPING = ', 
       ATTENDS_SET.ID_INTERNAL, ';') 
as "" from ATTENDS_SET;