select concat('update PERSON set PERSON.KEY_EMPLOYEE = ',
	ass_FUNCIONARIO.CODIGOINTERNO, 
	' where PERSON.ID_INTERNAL = ', 
	ass_FUNCIONARIO.CHAVEPESSOA, ';') 
as "" from ass_FUNCIONARIO where ass_FUNCIONARIO.CHAVEPESSOA IS NOT NULL;