alter table VIGILANT_GROUP add column POINTS_FOR_DISMISSED_TEACHER INTEGER;
update VIGILANT_GROUP SET POINTS_FOR_DISMISSED_TEACHER=0;

alter table VIGILANT_GROUP add column POINTS_FOR_MISSING_TEACHER INTEGER;
update VIGILANT_GROUP SET POINTS_FOR_MISSING_TEACHER=-2;
