#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Changing Table ParkingRequest" addColumnToParkingRequest.sql
execute "Updating Accounting Event Table" UpdateAccountingEventTable.sql
execute "Changing Table Accounting Event" AlterTableAccountingEvent.sql
execute "Changing Table Registration" AlterTableRegistration.sql
execute "Changing Table Candidacy" AlterTableCandidacy.sql

execute "Correct Contexts with key 0 for begin ExecutionPeriod " updateContextTable.sql
execute "Alter Convoke table" addColumnConvokes.sql
execute "Alter table Result" alterTableResult.sql