select concat('update REIMBURSEMENT_GUIDE_ENTRY set REIMBURSEMENT_GUIDE_ENTRY.KEY_REIMBURSEMENT_TRANSACTION = ', 
	REIMBURSEMENT_TRANSACTION.ID_INTERNAL,
	' where REIMBURSEMENT_GUIDE_ENTRY.ID_INTERNAL = ', 
	REIMBURSEMENT_TRANSACTION.KEY_REIMBURSEMENT_GUIDE_ENTRY, ';')
as "" from REIMBURSEMENT_TRANSACTION where REIMBURSEMENT_TRANSACTION.KEY_REIMBURSEMENT_GUIDE_ENTRY IS NOT NULL;
