alter table DEPARTMENT add column KEY_COMPETENCE_COURSE_MEMBERS_GROUP int default NULL;

DROP TABLE IF EXISTS `AC_COMPETENCE_COURSE_MEMBERS_GROUP`;
CREATE TABLE `AC_COMPETENCE_COURSE_MEMBERS_GROUP` (
	`ID_INTERNAL` int NOT NULL auto_increment, 
	`CREATION_DATE` timestamp NOT NULL,	
	`KEY_CREATOR` int NOT NULL,
	`KEY_MAILING_LIST` int,			
	`KEY_WRITERS_GROUP` int,
	`KEY_READERS_GROUP` int,	
	`KEY_DEPARTMENT` int,		
	`NAME` text ,
	`DESCRIPTION` text,	
    PRIMARY KEY (`ID_INTERNAL`)
)TYPE=InnoDB;



alter table DEGREE_CURRICULAR_PLAN add column KEY_DEGREE_CURRICULAR_PLAN_MEMBERS_GROUP int default NULL;

DROP TABLE IF EXISTS `AC_DEGREE_CURRICULAR_PLAN_MEMBERS_GROUP`;
CREATE TABLE `AC_DEGREE_CURRICULAR_PLAN_MEMBERS_GROUP` (
	`ID_INTERNAL` int NOT NULL auto_increment, 
	`CREATION_DATE` timestamp NOT NULL,	
	`KEY_CREATOR` int NOT NULL,
	`KEY_MAILING_LIST` int,			
	`KEY_WRITERS_GROUP` int,
	`KEY_READERS_GROUP` int,	
	`KEY_DEGREE_CURRICULAR_PLAN` int,		
	`NAME` text ,
	`DESCRIPTION` text,	
    PRIMARY KEY (`ID_INTERNAL`)
)TYPE=InnoDB;
