--  SQL file representing changes to the functionalities model
--  Generated at Wed Mar 7 16:54:48 WET 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Deleting functionalities
-- 

--  ID: 23 UUID: 'c2c332ca-d676-4c47-b053-66b6325413c9'
DELETE FROM ap USING `AVAILABILITY_POLICY` AS ap, `ACCESSIBLE_ITEM` AS f WHERE ap.`KEY_ACCESSIBLE_ITEM` = f.`ID_INTERNAL` AND f.`UUID` = 'c2c332ca-d676-4c47-b053-66b6325413c9';
DELETE FROM `ACCESSIBLE_ITEM` WHERE `UUID` = 'c2c332ca-d676-4c47-b053-66b6325413c9';

-- 
--  Inserting new functionalities
-- 

--  ID: 72063 UUID: 'e1c6122a-8cbe-4153-a513-ba6de3e21d15'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`) SELECT 'e1c6122a-8cbe-4153-a513-ba6de3e21d15', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt26:Merge de Unidades Externas', NULL, NULL, '/unitsMerge.do?method=chooseUnitToStart', NULL, 1, 1, NULL, 2, 1, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = 'f0ce9502-abeb-4f54-96e8-0aafa607d119';

COMMIT;
