alter table VIGILANT add key `KEY_PERSON` (`KEY_PERSON`);
alter table VIGILANT add key `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`);
alter table VIGILANT add key `KEY_EXECUTION_YEAR` (`KEY_EXECUTION_YEAR`);
alter table VIGILANT add key `KEY_INCOMPATIBLE_PERSON` (`KEY_INCOMPATIBLE_PERSON`);

alter table VIGILANT_GROUP add key `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`);
alter table VIGILANT_GROUP add key `KEY_UNIT` (`KEY_UNIT`);
alter table VIGILANT_GROUP add key `KEY_EXECUTION_YEAR` (`KEY_EXECUTION_YEAR`);

alter table EXAM_COORDINATOR add key `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`);
alter table EXAM_COORDINATOR add key `KEY_UNIT` (`KEY_UNIT`);
alter table EXAM_COORDINATOR add key `KEY_PERSON` (`KEY_PERSON`);
alter table EXAM_COORDINATOR add key `KEY_EXECUTION_YEAR` (`KEY_EXECUTION_YEAR`);

alter table CONVOKE add key `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`);
alter table CONVOKE add key `KEY_VIGILANT` (`KEY_VIGILANT`);
alter table CONVOKE add key `KEY_WRITTEN_EVALUATION` (`KEY_WRITTEN_EVALUATION`);

alter table VIGILANT_BOUND add key `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`);
alter table VIGILANT_BOUND add key `KEY_VIGILANT` (`KEY_VIGILANT`);
alter table VIGILANT_BOUND add key `KEY_VIGILANT_GROUP` (`KEY_VIGILANT_GROUP`);

alter table UNAVAILABLE_PERIOD add key `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`);
alter table UNAVAILABLE_PERIOD add key `KEY_VIGILANT` (`KEY_VIGILANT`);

alter table EXAM_COORDINATOR_MANAGES_VIGILANT_GROUP add key `KEY_EXAM_COORDINATOR` (`KEY_EXAM_COORDINATOR`);
alter table EXAM_COORDINATOR_MANAGES_VIGILANT_GROUP add key `KEY_VIGILANT_GROUP` (`KEY_VIGILANT_GROUP`);

alter table EXECUTION_COURSE add key `KEY_VIGILANT_GROUP` (`KEY_VIGILANT_GROUP`);

