
UPDATE PHD_PROCESS_STATE SET TYPE = "WAITING_FOR_SCIENTIFIC_COUNCIL_RATIFICATION" WHERE TYPE = "WAITING_FOR_CIENTIFIC_COUNCIL_RATIFICATION";
UPDATE PHD_PROCESS_STATE SET TYPE = "RATIFIED_BY_SCIENTIFIC_COUNCIL" WHERE TYPE = "RATIFIED_BY_CIENTIFIC_COUNCIL";
