alter table STUDENT_CURRICULAR_PLAN change column GIVEN_CREDITS GIVEN_CREDITS double default NULL;
alter table REIMBURSEMENT_TRANSACTION change column WAS_INTERNAL_BALANCE WAS_INTERNAL_BALANCE tinyint(1) NOT NULL default '0';
alter table IDENTIFICATION change column ACTIVE ACTIVE tinyint(1) unsigned default NULL;
alter table WEBSITE_ITEM change column PUBLISHED PUBLISHED tinyint(1) NOT NULL default '0';
alter table BIBLIOGRAPHIC_REFERENCE change column OPTIONAL OPTIONAL tinyint(1) NOT NULL default '0';
alter table CURRICULUM_MODULE change column GIVEN_CREDITS GIVEN_CREDITS double default NULL;
alter table SEMINARY change column HAS_THEME HAS_THEME tinyint(1) null;
alter table PAYMENT_TRANSACTION change column WAS_INTERNAL_BALANCE WAS_INTERNAL_BALANCE tinyint(1) NOT NULL default '0';
alter table DISTRIBUTED_TESTS change column IMS_FEEDBACK IMS_FEEDBACK tinyint(1) NOT NULL default '0';
alter table RESULT change column PATENT_NUMBER PATENT_NUMBER int default NULL;
alter table ITEM change column URGENT URGENT tinyint(1) unsigned default NULL;
alter table SEMINARY change column HAS_CASE_STUDY HAS_CASE_STUDY tinyint(1) null;
alter table STUDENT_CURRICULAR_PLAN change column CLASSIFICATION CLASSIFICATION double default '0.00';
alter table PROFESSORSHIPS change column HOURS HOURS double default NULL;
alter table CMS_WEBSITE_ITEM change column URGENT URGENT tinyint(1) NOT NULL default '0';
