#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Alter Tables Types" alterTablesTypes.sql
execute "Rename Columns" renameColumns.sql
execute "Rename Date Columns" renameDateColumns.sql
execute "Add Assiduity Missing Columns" addAssiduityMissingColumns.sql
execute "Add Missing Columns" addMissingColumns.sql
execute "Add REASON to MARKSHEET" alterMarkSheetTableAddReason.sql
execute "Add columns to Space" alterTableSpace.sql
executeWithTempFile "Migrate Room To Space" migrateRoomToSpace.sql
executeWithTempFile "Migrate Building To Space" migrateBuildingToSpace.sql
execute "Fix Result Table" fixResultTable.sql
executeWithTempFile "Add and populate missing fields in FinalDegreeWorkGroup Table" fixMissingColumns.sql
execute "Creating Messaging Tables" CreateMessagingTables.sql