
package net.sourceforge.fenixedu.domain.protocols.util;

public enum ProtocolActionType {
    STUDENTS_INTERCHANGE,
    TEACHERS_INTERCHANGE,
    INVESTIGATION_AND_DEVELOPMENT,
    RENDERING_SERVICES,
    RENDERING_SERVICE_IST_TEACHER,
    RENDERING_SERVICE_OTHER_INSTITUTION_TEACHER,
    WORKSHOPS,
    FORMATION_TRAINEE,
    DOCUMENTATION,
    TECHNICAL_COOPERATION;
}
