alter table `ACADEMIC_SERVICE_REQUEST` add column `OID_RECTORATE_SUBMISSION_BATCH` bigint(20), add index (`OID_RECTORATE_SUBMISSION_BATCH`), add index (`OID_REGISTRY_CODE`);
alter table `REGISTRY_CODE` drop column `OID_RECTORATE_SUBMISSION_BATCH`;

alter table `RECTORATE_SUBMISSION_BATCH` add column `OID_ADMINISTRATIVE_OFFICE` bigint(20), add index (`OID_ADMINISTRATIVE_OFFICE`), drop column `OID_REGISTRY_CODE_GENERATOR`;
delete from RECTORATE_SUBMISSION_BATCH;
