alter table `SANTANDER_BATCH_REQUESTER` add index (OID_PERSON);
alter table `PARTY` drop OID_SANTANDER_BATCH_SENDER, drop OID_SANTANDER_BATCH_REQUESTER;
alter table `SANTANDER_BATCH_SENDER` add index (OID_PERSON);

