ALTER TABLE QUEUE_JOB 	ADD COLUMN `EXPORT_GRATUITY_EVENTS` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `EXPORT_ACADEMIC_SERVICE_REQUEST_EVENTS` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `EXPORT_INDIVIDUAL_CANDIDACY_EVENTS` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `EXPORT_PHD_EVENTS` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `EXPORT_RESIDENCE_EVENTS` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `EXPORT_OTHERS` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `FOR_DEGREE_ADMINISTRATIVE_OFFICE` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `FOR_MASTER_DEGREE_ADMINISTRATIVE_OFFICE` tinyint(1) NULL DEFAULT 0,
						ADD COLUMN `OID_FOR_EXECUTION_YEAR` bigint(20) unsigned NULL,
						ADD COLUMN `OID_FOR_ADMINISTRATIVE_OFFICE` bigint(20) unsigned NULL;

UPDATE QUEUE_JOB SET BEGIN_DATE = '2005-01-01' WHERE OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.accounting.report.events.EventReportQueueJob';
UPDATE QUEUE_JOB SET END_DATE = '2012-12-31' WHERE OJB_CONCRETE_CLASS = 'net.sourceforge.fenixedu.domain.accounting.report.events.EventReportQueueJob';
