ALTER TABLE PAYMENT_CODE ADD COLUMN KEY_GRATUITY_SITUATION INT(11) DEFAULT NULL;
ALTER TABLE PAYMENT_CODE ADD COLUMN KEY_EXECUTION_YEAR INT(11) DEFAULT NULL;
ALTER TABLE PAYMENT_CODE ADD COLUMN WHEN_UPDATED DATETIME NULL;

UPDATE PAYMENT_CODE SET WHEN_UPDATED = WHEN_CREATED;

ALTER TABLE PAYMENT_CODE MODIFY COLUMN WHEN_UPDATED DATETIME NOT NULL;
