package net.sourceforge.fenixedu.domain.assiduousness.util;

public enum RegimeType {
    NORMAL, TRABALHADOR_ESTUDANTE, IPF, APOIO_FAMILIA, AMAMENTACAO, ALEITACAO, MENORES12, FILHOS_DEFICIENTES, FILHOS_DEFICIENTES_MENORES1, MOTIVOS_SAUDE, SERVICO, OUTRAS_CIRCUNSTANCIAS, DIRIGENTES
}
