DROP TABLE IF EXISTS FILE_ITEM;
CREATE TABLE FILE_ITEM (
	ID_INTERNAL int NOT NULL auto_increment, 
	CREATION_DATE timestamp NOT NULL,	
	FILENAME VARCHAR(255) NOT NULL,
	DISPLAY_NAME VARCHAR(255) NOT NULL,
	MIME_TYPE VARCHAR(48) NOT NULL,			
	CHECKSUM VARCHAR(64) NOT NULL,
	CHECKSUM_ALGORITHM VARCHAR(32) NOT NULL,	
	SIZE int,		
	DSPACE_BITSTREAM_IDENTIFICATION VARCHAR(255),
	KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL DEFAULT 1,	
    PRIMARY KEY (ID_INTERNAL),
    UNIQUE (DSPACE_BITSTREAM_IDENTIFICATION)
)TYPE=InnoDB;
