ALTER TABLE PARKING_REQUEST ADD COLUMN PARKING_REQUEST_TYPE  varchar(50) default NULL;
ALTER TABLE PARKING_REQUEST DROP COLUMN FIRST_REQUEST;
ALTER TABLE PARKING_PARTY ADD COLUMN REQUESTED_AS varchar(50) default NULL;
ALTER TABLE PARKING_PARTY ADD COLUMN USED_NUMBER int(11) default NULL;

CREATE TABLE PARKING_PARTY_HISTORY (
  ID_INTERNAL int(11) unsigned NOT NULL auto_increment,
  KEY_PARTY int(11) unsigned NOT NULL default '0',
  CARD_NUMBER bigint(20) default NULL,
  KEY_PARKING_GROUP int(11) unsigned default NULL,
  KEY_ROOT_DOMAIN_OBJECT int(11) NOT NULL default '1',
  PHD_NUMBER int(11) default NULL,
  CARD_START_DATE datetime default NULL,
  CARD_END_DATE datetime default NULL,
  NOTES text,
  REQUESTED_AS  varchar(50) default '',
  USED_NUMBER int(11) default NULL,
  HISTORY_DATE datetime NOT NULL default '0000-00-00 00:00:00',
  ONLINE_REQUEST  tinyint(1) NOT NULL,
  PRIMARY KEY  (`ID_INTERNAL`),
  KEY `KEY_ROOT_DOMAIN_OBJECT` (`KEY_ROOT_DOMAIN_OBJECT`),
  KEY `KEY_PARKING_GROUP` (`KEY_PARKING_GROUP`),
  KEY `KEY_PARTY` (`KEY_PARTY`)
); 

