#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password $DB < tmp.sql	
	rm tmp.sql
	echo
}


execute "Changing AssiduousnessRecord column name" AlterTableAssiduousnessRecord.sql
execute "Changing Party column address" AlterPartyAddress.sql
execute "Create Service Agreement Tables" CreateServiceAgreementTables.sql
execute "Altering table AccountingEntry" AlterTableAccountingEntry.sql
execute "Altering table Account" AlterTableAccount.sql
execute "Altering table AccountingTransaction" AlterTableAccountingTransaction.sql
execute "Dropping duplicate indexes on Accounting Tables" DropDuplicateIndexesOnAccountingTables.sql
execute "Altering table degree curricular plan" AlterTableDegreeCurricularPlan.sql
execute "Changing table AccountingEvent" AlterAccountingEvent.sql
