
function hideButtons()
{
	document.getElementById("javascriptButtonID").style.display="none";
	document.getElementById("javascriptButtonID2").style.display="none";
	document.getElementById("javascriptButtonID3").style.display="none";
	document.getElementById("javascriptButtonID4").style.display="none";
	document.getElementById("javascriptButtonID5").style.display="none";
	document.getElementById("javascriptButtonID6").style.display="none";
	document.getElementById("javascriptButtonID7").style.display="none";
	document.getElementById("id0").style.display="block";
	document.getElementById("id1").style.display="block";
	document.getElementById("id2").style.display="block";
	document.getElementById("id3").style.display="block";
	document.getElementById("id4").style.display="block";
	document.getElementById("id5").style.display="block";
	document.getElementById("id6").style.display="block";
	document.getElementById("id7").style.display="block";
	document.getElementById("id8").style.display="block";
	document.getElementById("id9").style.display="block";
	document.getElementById("id10").style.display="block";
	document.getElementById("id11").style.display="block";
	document.getElementById("id12").style.display="block";
	document.getElementById("id13").style.display="block";
	document.getElementById("id14").style.display="block";
	document.getElementById("id15").style.display="block";
	document.getElementById("id16").style.display="block";
	document.getElementById("id17").style.display="block";
	document.getElementById("id18").style.display="block";
	document.getElementById("id19").style.display="block";
	document.getElementById("id20").style.display="block";
}
