/*
 * Created on Feb 10, 2006
 *	by mrsp
 */
package net.sourceforge.fenixedu.domain.organizationalStructure;

public enum PartyTypeEnum {

    // UNIT ENUMERATIONS
    CENTRAL_ORG,
    DIRECTIVE_COUNCIL,
    EXECUTIVE_DIRECTION,
    ADMINISTRATIVE_DIRECTION,
    TECHNIQUE_DIRECTION,
    ACADEMIC_UNIT,
    DEPARTMENT,
    DEGREE_UNIT,
    SCIENTIFIC_AREA,
    COMPETENCE_COURSE_GROUP,
    AUTONOMOUS_SECTION,
    SECTION,
    EXTERNAL_INSTITUTION,
    ACADEMIC_SERVICES_SUPERVISION,
    OUT_RELATION_SERVICES_SUPERVISION,
    SCIENTIFIC_PEDAGOGICAL_MANAGEMENT_RESOURCES_SERVICES_SUPERVISION,
    DEGREE_COORDINATION,
    RESEARCH_UNIT,
    SCIENCE_INFRASTRUCTURE,
    INFORMATION_TECHNOLOGY_LABORATORY,
    ASSOCIATED_LABORATORY,
    TAGUSPARK,
    DIRECTIVE_COUNCIL_TAGUSPARK,
    EXECUTIVE_DIRECTION_TAGUSPARK,    
    EXTRA_CURRICULAR_ACTIVITIES,    
    PARTICIPATED_IST_INSTITUTION,
    DIVERSE_CONSTRUCTION_BUILDING,
    OUT,
    SERVICES,
    AGGREGATE_UNIT,

    // PERSON ENUMERATIONS
    
    
    
    // GERAL    
    UNKNOWN;
            
    public String getName() {
        return name();
    }      
}
