/*
 * Created on Oct 6, 2005
 *	by mrsp
 */
package net.sourceforge.fenixedu.domain.organizationalStructure;

public enum UnitType {
    
    CENTRAL_ORG,
    DEPARTMENT,
    DEGREE,
    MASTER_DEGREE,
    SCIENTIFIC_AREA,
    COMPETENCE_COURSE_GROUP,
    DIVERSE_CONSTRUCTION_BUILDING,
    RESEARCH_UNIT,
    PARTICIPATED_IST_INSTITUTION,
    INFORMATION_TECHNOLOGY_LABORATORY,
    ASSOCIATED_LABORATORY,
    SCIENCE_INFRASTRUCTURE,
    DEGREE_COORDINATION,
    AUTONOMOUS_SECTION,
    ACADEMIC_SERVICES_SUPERVISION,
    OUT_RELATION_SERVICES_SUPERVISION,
    SCIENTIFIC_PEDAGOGICAL_MANAGEMENT_RESOURCES_SERVICES_SUPERVISION,
    EXECUTIVE_DIRECTION,
    ADMINISTRATIVE_DIRECTION,
    EXTRA_CURRICULAR_ACTIVITIES,    
    TECHNIQUE_DIRECTION,
    OUT;
          
    public String getName() {
        return name();
    }  
}
