
delete from MARK where MARK.KEY_ATTEND in (52046, 360469) and MARK.KEY_EVALUATION in (select ID_INTERNAL from EVALUATION where OJB_CONCRETE_CLASS like '%OnlineTest' and KEY_DISTRIBUTED_TEST in (select ID_INTERNAL FROM DISTRIBUTED_TEST where KEY_TEST_SCOPE= (select ID_INTERNAL FROM TEST_SCOPE where KEY_CLASS=74194)));

delete from ATTENDS where ID_INTERNAL=1066178;
delete from ATTENDS where ID_INTERNAL=1168482;

