update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'CONSELHO DIRECTIVO';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'CONSELHO PEDAGOGICO';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'CONSELHO CIENTIFICO';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'GABINETE DE APOIO JURIDÍCO';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'GABINETE DE ESTUDOS E PLANEAMENTO';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'ASSESSORIA DO CONSELHO DIRECTIVO';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'CONSELHO DIRECTIVO/TAGUSPARK';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'BIBLIOTECA DO IST/TAGUSPARK';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'CENTRO INFORMATICA IST/TAGUSPARK';
update UNIT set TYPE = 'ORGAO_CENTRAL' where UNIT.NAME = 'NUCLEO ACADEMICO DO TAGUSPARK';

update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'DIRECCAO ADMINISTRATIVA';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'AREA FINANCEIRA E PATRIMONIAL';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCLEO DE GESTAO ORCAMENTAL';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCLEO DE ECONOMATO';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCLEO DE PATRIMONIO';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'AREA DE ASSUNTOS DE PESSOAL';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCLEO DE PROCESSOS E ABONOS';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCLEO DE GESTAO DE PESSOAL';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'AREA CONTABILISTICA';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCL.APOIO TECN.EXEC.PROJECTOS';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCLEO DE TESOURARIA';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUCLEO CONTABILIDADE CENTRAL';
update UNIT set TYPE = 'DIRECCAO_ADMINISTRATIVA' where UNIT.NAME = 'NUC.CONTABILIZACAO GEST. PROJECTOS';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE FISICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'BIBLIOTECA DEP.ENG.FISICA E TECN.';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE FISICA-PRESIDENCIA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEP. ENG. ELECT. E COMPUTADORES';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'BIBLIOTECA DEP.ENG.ELE. E COMP.';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SEC. MAQ. ELECT. E ELECT. POTENCIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEEC - PRESIDENCIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'AREA CIENT.SIST.,DECISAO E CONTROLO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'AREA CIENTIFICA DE ELECTRONICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'AREA CIENTIFICA DE TELECOMUNICACOES';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'AREA CIENTIFICA DE COMPUTADORES';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'AREA CIENTIFICA DE ENERGIA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE MATEMATICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPART. MATEMATICA - PRESIDENCIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO CIENCIA DE COMPUTACAO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SEC. MATEM. APLIC.E ANAL. NUMERICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO ESTATISTICA E APLICACOES';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO ALGEBRA E ANALISE';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE ENGENHARIA QUIMICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE QUIMICA ORGANICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'LABORATORIO DE ANALISES';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'BIBLIOTECA DEP.ENG.QUIMICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEQ - PRESIDENCIA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEP. DE ENGENHARIA MECANICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'BIBLIOTECA DEP.ENG.MECANICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE AMBIENTE E ENERGIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE MECANICA AEROESPACIAL';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE SISTEMAS';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEM - PRESIDENCIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE PROJECTO MECANICO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE TECNOLOGIA MECANICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO TERMOFLUIDOS E ENERGIA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPART. DE ENGENHARIA DE MATERIAIS';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEP. ENG. MATERIAIS - PRESIDENCIA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE ENGENHARIA CIVIL';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE ESTRUTURAS E CONSTRUCAO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE ARQUITECTURA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'BIBLIOTECA DEP.ENG.CIVIL E ARQ.';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE GEOTECNIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SEC.SISTEMAS DE APOIO AO PROJECTO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE CONSTRUCAO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEC - PRESIDENCIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SEC.HIDRAULICA E REC.HID.AMBIENTAIS';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SEC.URBANISMO,TRANSP,VIAS,SISTEMAS';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SEC.MECANICA ESTRUTURAL E ESTRUTURA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE ENGENHARIA MINAS';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEP. MINAS - PRESIDENCIA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'SECCAO DE EXPLORACAO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'LABORATORIO DE GEOLOGIA APLICADA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'LAB. MINERALURGIA E PLAN. MINEIRO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'LAB. MINERALOGIA E PETROLOGIA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE ENGENHARIA E GESTAO';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEP.ENGENHARIA E GESTAO-PRESIDENCIA';

update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEPARTAMENTO DE ENG. INFORMATICA';
update UNIT set TYPE = 'UNIDADE_ACADEMICA' where UNIT.NAME = 'DEP. ENG. INFORMATICA - PRESIDENCIA';

update UNIT set TYPE = 'SUPERVISAO_SERVICOS_ACADEMICOS' where UNIT.NAME = 'SUPERVISÃO DOS SERVICOS ACADÉMICOS';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_ACADEMICOS' where UNIT.NAME = 'NUCLEO POS-GRAD.E FORMACAO CONTINUA';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_ACADEMICOS' where UNIT.NAME = 'NÚCLEO DE GRADUAÇÃO';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_ACADEMICOS' where UNIT.NAME = 'SUPERVISÃO DOS SERVICOS ACADÉMICOS';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_ACADEMICOS' where UNIT.NAME = 'NÚCLEO DE GRADUAÇÃO';

update UNIT set TYPE = 'SUPERVISAO_SERVICOS_GESTAO_RECURSOS_PEDAGOGICOS_E_CIENTIFICOS' where UNIT.NAME = 'SUP.SERV.GESTÃO RECUR.PEDAG.CIENTÍ.';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_GESTAO_RECURSOS_PEDAGOGICOS_E_CIENTIFICOS' where UNIT.NAME = 'EDITORA IST/PRESS';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_GESTAO_RECURSOS_PEDAGOGICOS_E_CIENTIFICOS' where UNIT.NAME = 'GAB.APOIO PROD.CONTEU.MULTIMÉDIA';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_GESTAO_RECURSOS_PEDAGOGICOS_E_CIENTIFICOS' where UNIT.NAME = 'CENTRO DE INFORMÁTICA DO IST';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_GESTAO_RECURSOS_PEDAGOGICOS_E_CIENTIFICOS' where UNIT.NAME = 'GABINETE DE ORGANIZAÇÃO PEDAGÓGICA';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_GESTAO_RECURSOS_PEDAGOGICOS_E_CIENTIFICOS' where UNIT.NAME = 'BIBLIOTECA DO IST';

update UNIT set TYPE = 'SUPERVISAO_SERVICOS_RELACOES_C_EXTERIOR' where UNIT.NAME = 'SUPERVISÃO SERV.RELAÇÕES C/EXTERIOR';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_RELACOES_C_EXTERIOR' where UNIT.NAME = 'GAB.COMUNICACAO E REL.PUBLICAS';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_RELACOES_C_EXTERIOR' where UNIT.NAME = 'GAB.GES.MUSEU CENTRO DE CONGRESSOS';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_RELACOES_C_EXTERIOR' where UNIT.NAME = 'GAB.DE RELAÇÕES INTERNACIONAIS';
update UNIT set TYPE = 'SUPERVISAO_SERVICOS_RELACOES_C_EXTERIOR' where UNIT.NAME = 'GAB.LICENCIAMENTO DE TECNOLOGIA';

update UNIT set TYPE = 'SECCAO_AUTONOMA' where UNIT.NAME = 'SECCAO AUTONOMA DE ENGENHARIA NAVAL';

update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'C.FISICA TEORICA DE PARTICULAS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO FISICA INTERAC.FUNDAMENTAIS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE FUSAO NUCLEAR';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO FUSAO NUCLEAR-LAB.ASSOCIADO';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE AUTOMATICA';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE FISICA DOS PLASMAS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO FISICA PLASMAS-LAB.ASSOCIADO';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO SIST. URBANOS E REGIONAIS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE PETROLOGIA E GEOQUIMICA';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE ANALISES E PROC.SINAIS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE FISICA MOLECULAR';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO VALOR. RECURSOS MINERAIS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE ESTUDOS E HIDROSISTEMAS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO MOD. RESERV. PETROLIFEROS';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'SAID: SERV. APOIO I&D-COMPLEXO';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'UNIDADE DE ENG.TECNOLOGIA NAVAL';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE ENG.BIOLOGICA E QUIMICA';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'C.ESTUDOS INOV.TECN.POL.DESENVOLV.';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'UNIDADE DE ENG.TECNOLOGIA NAVAL';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE QUIMICA ESTRUTURAL';
update UNIT set TYPE = 'UNIDADE_DE_INVESTIGACAO' where UNIT.NAME = 'CENTRO DE QUIMICA-FISICA MOLECULAR';

update UNIT set TYPE = 'INFRAESTRUTURA_CIENCIA' where UNIT.NAME = 'INST.CIENCIA E ENG.MATERIAIS E SUP.';
update UNIT set TYPE = 'INFRAESTRUTURA_CIENCIA' where UNIT.NAME = 'ICIST - INSTITUTO DA CONSTRUCAO';
update UNIT set TYPE = 'INFRAESTRUTURA_CIENCIA' where UNIT.NAME = 'POLO IST - ISR';
update UNIT set TYPE = 'INFRAESTRUTURA_CIENCIA' where UNIT.NAME = 'POLO IST - INST.TELECOMUNICACOES';
update UNIT set TYPE = 'INFRAESTRUTURA_CIENCIA' where UNIT.NAME = 'POLO IST - IDMEC';
update UNIT set TYPE = 'INFRAESTRUTURA_CIENCIA' where UNIT.NAME = 'LABORATORIO DE MECATRONICA';

update UNIT set TYPE = 'EDIFICIO_CONSTRUCAO_DIVERSA' where UNIT.NAME = 'TAGUS PARQUE - POLO OEIRAS';
update UNIT set TYPE = 'EDIFICIO_CONSTRUCAO_DIVERSA' where UNIT.NAME = 'TAGUSPARK';

update UNIT set TYPE = 'INSTITUICAO_PARTICIPADA_IST' where UNIT.NAME = 'INESC';

update UNIT set TYPE = 'COORDENACAO_DE_LICENCIATURA' where UNIT.NAME = 'COORDENACAO DE LICENCIATURA';
update UNIT set TYPE = 'COORDENACAO_DE_LICENCIATURA' where UNIT.NAME = 'COORD. LICENCIATURA ENG. AMBIENTE';

update UNIT set TYPE = 'DIRECCAO_EXECUTIVA' where UNIT.NAME = 'DIRECCAO EXECUTIVA_GERAL';
update UNIT set TYPE = 'DIRECCAO_EXECUTIVA' where UNIT.NAME = 'ASSESSORIA DA DIRECÇÃO-EXECUTIVA';
update UNIT set TYPE = 'DIRECCAO_EXECUTIVA' where UNIT.NAME = 'DIRECCAO EXECUTIVA/TAGUSPARK';
update UNIT set TYPE = 'DIRECCAO_EXECUTIVA' where UNIT.NAME = 'NUCLEO TECNICO DO TAGUSPARK';
update UNIT set TYPE = 'DIRECCAO_EXECUTIVA' where UNIT.NAME = 'NUCLEO ADMINISTRATIVO DO TAGUSPARK';

update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'DIRECCAO TECNICA';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'DIRECCAO TECNICA_GERAL';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'AREA DE APOIO GERAL';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE ARQUIVO';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE SUPERVISAO';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE SERVICOS GERAIS';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE REPROGRAFIA';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'AREA DE APOIO SOCIAL';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE APOIO AO ESTUDANTE';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE APOIO SOCIAL';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE ALOJAMENTOS';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'AREA DE INSTALACOES E EQUIPAMENTOS';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE OBRAS';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE SEGURANCA,HIGIENE E SAUDE';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUC.GES.ESTRU.FISICAS TECNOLOGICAS';
update UNIT set TYPE = 'DIRECCAO_TECNICA' where UNIT.NAME = 'NUCLEO DE MANUTENCAO';

update UNIT set TYPE = 'OUTROS' where UNIT.NAME = 'ORGAOS CENTRAIS';

