#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password $DB < $2
	echo
}

execute "Updating CurricularCourseType for new curricular courses" updateCurricularCourseType.sql
execute "Adding RootDomainObject to Person Relation" createRootDomainObjectToPersonRelation.sql
