alter table `DEGREE` add column `OID_PHD_PROGRAM` bigint(20);
ALTER TABLE FILE ADD COLUMN OID_INDIVIDUAL_CANDIDACY bigint(20);
ALTER TABLE PROCESS ADD COLUMN OID_CANDIDACY_HASH_CODE bigint(20);
ALTER TABLE PUBLIC_CANDIDACY_HASH_CODE ADD COLUMN OID bigint(20);
ALTER TABLE PUBLIC_CANDIDACY_HASH_CODE ADD COLUMN OID_ROOT_DOMAIN_OBJECT bigint(20);
ALTER TABLE PUBLIC_CANDIDACY_HASH_CODE ADD COLUMN OID_INDIVIDUAL_CANDIDACY_PROCESS bigint(20);
ALTER TABLE QUALIFICATION ADD COLUMN OID_INDIVIDUAL_CANDIDACY bigint(20);
ALTER TABLE QUALIFICATION ADD COLUMN OID_CONCLUSION_EXECUTION_YEAR bigint(20);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN OID_COUNTRY_OF_RESIDENCE bigint(20);
ALTER TABLE INDIVIDUAL_CANDIDACY_PERSONAL_DETAILS ADD COLUMN OID_NATIONALITY bigint(20);

