DROP TABLE IF EXISTS SCIENTIFIC_AREA;
CREATE TABLE SCIENTIFIC_AREA (
   ID_INTERNAL int(11) NOT NULL auto_increment,
   NAME varchar(255) NOT NULL,
   ACK_OPT_LOCK int(11) not null default '1',
   PRIMARY KEY (ID_INTERNAL),
   UNIQUE U1 (NAME)
) TYPE=InnoDB;

DROP TABLE IF EXISTS CURRICULAR_COURSE_GROUP;
CREATE TABLE CURRICULAR_COURSE_GROUP (
   ID_INTERNAL int(11) not null auto_increment,
   KEY_BRANCH int(11) not null,
   MINIMUM_CREDITS int(11) not null,
   MAXIMUM_CREDITS int(11) not null,
   AREA_TYPE int(11) not null,
   ACK_OPT_LOCK int(11) not null default '1',
   PRIMARY KEY (ID_INTERNAL)
) TYPE=InnoDB;

DROP TABLE IF EXISTS CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP;
CREATE TABLE CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (
   ID_INTERNAL int(11) not null auto_increment,
   KEY_CURRICULAR_COURSE_GROUP int(11) not null,
   KEY_CURRICULAR_COURSE int(11) not null,
   PRIMARY KEY (ID_INTERNAL),
   UNIQUE U1(KEY_CURRICULAR_COURSE_GROUP,KEY_CURRICULAR_COURSE)
) TYPE=InnoDB;

DROP TABLE IF EXISTS SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP;
CREATE TABLE SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (
   ID_INTERNAL int(11) not null auto_increment,
   KEY_CURRICULAR_COURSE_GROUP int(11) not null,
   KEY_SCIENTIFIC_AREA int(11) not null,
   PRIMARY KEY (ID_INTERNAL),
   UNIQUE U1(KEY_CURRICULAR_COURSE_GROUP,KEY_SCIENTIFIC_AREA)
) TYPE=InnoDB;

DROP TABLE IF EXISTS CREDITS_IN_SPECIFIC_SCIENTIFIC_AREA;
CREATE TABLE CREDITS_IN_SCIENTIFIC_AREA (
   ID_INTERNAL int(11) not null auto_increment,
   KEY_STUDENT_CURRICULAR_PLAN int(11) not null,
   KEY_SCIENTIFIC_AREA int(11) not null,
   KEY_ENROLMENT int(11) not null,
   GIVEN_CREDITS int(11) not null,
   ACK_OPT_LOCK int(11) not null default '1',
   PRIMARY KEY (ID_INTERNAL),
   UNIQUE U1(KEY_STUDENT_CURRICULAR_PLAN,KEY_SCIENTIFIC_AREA,KEY_ENROLMENT)
) TYPE=InnoDB;

DROP TABLE IF EXISTS CREDITS_IN_ANY_SECUNDARY_AREA;
CREATE TABLE CREDITS_IN_ANY_SECUNDARY_AREA (
   ID_INTERNAL int(11) not null auto_increment,
   KEY_STUDENT_CURRICULAR_PLAN int(11) not null,
   KEY_ENROLMENT int(11) not null,
   GIVEN_CREDITS int(11) not null,
   ACK_OPT_LOCK int(11) not null default '1',
   PRIMARY KEY (ID_INTERNAL),
   UNIQUE U1(KEY_STUDENT_CURRICULAR_PLAN,KEY_ENROLMENT)
) TYPE=InnoDB;

-- ALTER TABLE CURRICULAR_COURSE ADD KEY_SCIENTIFIC_AREA int(11);
ALTER TABLE BRANCH ADD BRANCH_TYPE varchar(6);
ALTER TABLE STUDENT_CURRICULAR_PLAN ADD KEY_SECUNDARY_BRANCH int(11);
ALTER TABLE STUDENT_CURRICULAR_PLAN CHANGE KEY_BRANCH KEY_SPECIALIZATION_BRANCH int(11) not null;

-- select concat('UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = ', ID_INTERNAL, ';') AS ""
-- from BRANCH where branch_name = '';
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 1;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 2;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 3;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 4;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 5;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 6;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 9;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 10;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 11;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 12;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 13;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 14;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 15;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 16;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 17;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 18;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 19;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 20;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 21;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 22;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 23;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 24;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 25;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 26;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 27;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 28;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 29;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 30;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 31;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 39;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 47;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 51;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 55;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 59;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 60;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 61;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 64;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 65;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 70;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 74;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 75;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 78;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 83;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 84;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7902;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7903;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7906;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7908;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7913;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7915;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7917;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7918;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 7919;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8262;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8263;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8264;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8266;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8267;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8269;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8270;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8271;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8272;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8282;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8284;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8286;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8290;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8291;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8404;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8415;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8420;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8424;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8426;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8429;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8453;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8458;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8464;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8471;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8490;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8506;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8508;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8512;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8524;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8525;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8555;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8556;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8557;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8559;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8561;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8562;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8567;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8569;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8573;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8588;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8593;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8599;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8604;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8611;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8612;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8613;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8615;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8618;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8619;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8620;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8621;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8622;
UPDATE BRANCH SET BRANCH_TYPE = "COMNBR" where ID_INTERNAL = 8625;

-- select concat('UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = ', ID_INTERNAL, ';') AS ""
-- from BRANCH where branch_name <> '';
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 37;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 38;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 40;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 41;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 42;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 43;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 44;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 45;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 46;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 48;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 49;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 50;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 52;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 53;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 54;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 56;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 57;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 58;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 62;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 63;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 66;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 67;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 68;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 69;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 71;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 72;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 73;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 76;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 77;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 79;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 80;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 81;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 82;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 85;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 86;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 87;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 88;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 89;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 90;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 91;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 92;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 94;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 95;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 96;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7904;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7905;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7907;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7909;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7910;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7911;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7912;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7914;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 7916;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8265;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8268;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8273;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8274;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8275;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8283;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8285;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8287;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8288;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8289;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8292;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8293;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8294;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8295;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8296;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8297;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8298;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8299;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8300;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8301;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8302;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8303;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8304;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8305;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8306;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8307;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8308;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8309;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8310;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8311;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8312;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8313;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8314;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8315;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8316;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8317;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8318;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8319;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8320;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8321;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8322;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8323;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8324;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8325;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8326;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8327;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8328;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8329;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8330;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8331;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8332;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8333;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8334;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8335;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8336;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8337;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8338;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8339;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8340;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8341;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8342;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8343;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8344;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8345;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8346;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8347;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8348;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8349;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8350;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8351;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8352;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8353;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8354;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8355;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8356;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8357;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8358;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8359;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8360;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8361;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8362;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8363;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8364;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8365;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8366;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8367;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8368;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8369;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8370;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8371;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8372;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8373;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8374;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8375;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8376;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8377;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8378;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8379;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8380;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8381;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8382;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8383;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8384;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8385;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8386;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8387;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8388;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8389;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8390;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8391;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8392;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8393;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8394;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8395;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8396;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8397;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8398;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8399;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8400;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8401;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8402;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8403;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8405;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8406;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8407;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8408;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8409;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8410;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8411;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8412;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8413;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8414;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8416;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8417;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8418;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8419;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8421;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8422;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8423;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8425;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8427;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8428;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8430;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8431;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8432;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8433;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8434;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8435;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8436;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8437;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8438;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8439;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8454;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8455;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8456;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8457;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8459;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8460;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8461;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8462;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8463;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8465;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8466;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8467;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8468;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8469;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8470;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8479;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8480;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8481;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8483;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8484;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8485;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8487;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8488;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8489;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8491;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8492;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8493;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8494;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8495;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8496;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8497;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8498;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8499;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8500;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8501;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8502;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8503;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8504;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8505;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8507;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8509;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8510;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8511;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8513;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8514;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8515;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8516;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8517;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8521;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8522;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8523;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8526;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8527;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8528;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8529;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8530;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8531;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8532;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8534;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8535;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8536;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8558;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8560;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8563;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8564;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8565;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8566;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8568;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8570;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8571;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8572;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8574;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8575;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8576;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8577;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8578;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8579;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8580;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8581;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8582;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8583;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8584;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8585;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8586;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8587;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8589;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8590;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8591;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8592;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8594;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8595;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8596;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8597;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8598;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8600;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8601;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8602;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8603;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8605;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8606;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8607;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8608;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8609;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8610;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8614;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8616;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8617;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8623;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8624;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8635;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8655;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8656;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8676;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8677;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8678;
UPDATE BRANCH SET BRANCH_TYPE = "SPECBR" where ID_INTERNAL = 8679;

-- select concat('UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = ', ID_INTERNAL, ';') AS ""
-- from BRANCH where branch_name = 'BRANCH THAT NO LONGER EXISTS';
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8558;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8560;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8564;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8566;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8578;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8579;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8581;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8582;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8583;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8584;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8585;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8586;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8587;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8598;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8600;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8601;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8602;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8603;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8606;
UPDATE BRANCH SET BRANCH_NAME = "RAMO QUE JÁ NÃO EXISTE" where ID_INTERNAL = 8635;
