UPDATE BRANCH SET BRANCH_NAME = 'SISTEMAS ELECTRÓNICOS' WHERE ID_INTERNAL = 8529;
UPDATE BRANCH SET BRANCH_NAME = 'SISTEMAS, DECISÃO E CONTROLO' WHERE ID_INTERNAL = 8528;
UPDATE BRANCH SET BRANCH_NAME = 'TELECOMUNICAÇÕES' WHERE ID_INTERNAL = 8527;
UPDATE BRANCH SET BRANCH_NAME = 'ENERGIA' WHERE ID_INTERNAL = 8526;

INSERT INTO BRANCH (BRANCH_CODE, BRANCH_NAME, KEY_DEGREE_CURRICULAR_PLAN,ACK_OPT_LOCK,BRANCH_TYPE) VALUES ('1450', 'COMPUTADORES', 48, 1, 'SPECBR');

ALTER TABLE CURRICULAR_COURSE_GROUP DROP INDEX U1, ADD UNIQUE U1 (KEY_BRANCH,ID_INTERNAL);
