#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

echo Using database: $1
echo Enter password for $2:
read -s password

echo Altering table CompetenceCourseLoad
mysql -u$2 -f -p$password $1 < alterTableCompetenceCourseLoad.sql
echo done.

echo Altering Teacher Table
mysql -u$2 -f -p$password $1 < alterTeacherTable.sql
echo done.

echo Altering table TeacherPersonExpectation
mysql -u$2 -f -p$password $1 < alterTableTeacherPersonalExpectation.sql
echo done





