alter table NODE add column CONTENT_ID varchar(255);
alter table AVAILABILITY_POLICY add column CONTENT_ID varchar(255);

update AVAILABILITY_POLICY set CONTENT_ID = UUID();
UPDATE CONTENT SET CONTENT_ID = UUID() WHERE CONTENT_ID IS NULL;
update NODE as N, CONTENT as C, CONTENT as C2 SET N.CONTENT_ID=concat(C.CONTENT_ID, ':', C2.CONTENT_ID) WHERE C.ID_INTERNAL=N.KEY_PARENT AND N.KEY_CHILD = C2.ID_INTERNAL;
