update PROFESSIONAL_SITUATION set SITUATION_TYPE = 'SERVICE_COMMISSION_OVERTIME_NOMINATION' where SITUATION_TYPE = 'COMMISSION_OVERTIME_NOMINATION';
update PROFESSIONAL_SITUATION set SITUATION_TYPE = 'TEMPORARY_SUBSTITUTION_CONTRACT' where SITUATION_TYPE = 'TEMPORARY_SUBSTITUTION';
