alter table `POSTING_RULE` add `SPECIALIZATION_DEGREE_TOTAL_AMOUNT` text, add `SPECIALIZATION_DEGREE_AMOUNT_PER_ECTS_CREDIT` text, add `SPECIALIZATION_DEGREE_PARTIAL_ACCEPTED_PERCENTAGE` text;
alter table `REGISTRATION` add `OID_SPECIALIZATION_DEGREE_REGISTRATION_EVENT` bigint unsigned;
