--  SQL file representing changes to the functionalities model
--  Generated at Mon Sep 10 18:53:33 WEST 2007
--  DO NOT EDIT THIS FILE, run the generating script instead

--  Preamble
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- 
--  Updating existing functionalities
-- 

--  ID: 252 UUID: '9cf56518-f706-4854-b28e-2108ba374c43'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt11:Comunicaçãoen9:Messaging' WHERE own.`UUID` = '9cf56518-f706-4854-b28e-2108ba374c43';

--  ID: 189877 UUID: '4cbd4716-40e1-4052-ac47-b24db983efd4'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`NAME` = 'pt10:Bibliotecaen7:Library', own.`TITLE` = 'pt20:Portal da Bibliotecaen14:Library Portal' WHERE own.`UUID` = '4cbd4716-40e1-4052-ac47-b24db983efd4';

--  ID: 269519 UUID: 'b3d6942c-bdca-4083-86cb-6eeb34f39c37'
UPDATE `ACCESSIBLE_ITEM` AS own SET own.`TITLE` = 'pt16:Listagem utentes' WHERE own.`UUID` = 'b3d6942c-bdca-4083-86cb-6eeb34f39c37';

-- 
--  Inserting new functionalities
-- 

--  ID: 269718 UUID: '6797c053-576f-4ec4-b50a-489470709106'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT '6797c053-576f-4ec4-b50a-489470709106', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt31:Gerar pdf para cartões em falta', 'pt31:Gerar pdf para cartões em falta', NULL, '/cardManagement.do?method=generateMissingCards', NULL, 1, 1, NULL, 1, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = 'e3cc1382-7912-47e3-9f97-3aadf9e32ea0';

--  ID: 269719 UUID: 'dc040672-f9f9-4bb4-a1c3-21bcc55ba8f7'
INSERT INTO `ACCESSIBLE_ITEM` (`UUID`, `OJB_CONCRETE_CLASS`, `KEY_ROOT_DOMAIN_OBJECT`, `KEY_PARENT`, `KEY_MODULE`, `KEY_AVAILABILITY_POLICY`, `NAME`, `TITLE`, `DESCRIPTION`, `PATH`, `PREFIX`, `RELATIVE`, `ENABLED`, `PARAMETERS`, `ORDER_IN_MODULE`, `VISIBLE`, `MAXIMIZED`, `PRINCIPAL`, `KEY_SUPERIOR_SECTION`, `SECTION_ORDER`, `KEY_SITE`, `LAST_MODIFIED_DATE_YEAR_MONTH_DAY`, `KEY_SECTION`, `ITEM_ORDER`, `INFORMATION`, `KEY_FUNCTIONALITY`, `SHOW_NAME`, `KEY_INTRODUCTION_UNIT_SITE`) SELECT 'dc040672-f9f9-4bb4-a1c3-21bcc55ba8f7', 'net.sourceforge.fenixedu.domain.functionalities.ConcreteFunctionality', 1, NULL, `ID_INTERNAL`, NULL, 'pt21:Gerar cartas em falta', 'pt21:Gerar cartas em falta', NULL, '/cardManagement.do?method=generateMissingLetters', NULL, 1, 1, NULL, 2, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL FROM `ACCESSIBLE_ITEM` WHERE `UUID` = 'e3cc1382-7912-47e3-9f97-3aadf9e32ea0';

COMMIT;
