SET AUTOCOMMIT = 0;

START TRANSACTION;

UPDATE CONTENT SET EXECUTION_PATH='/viewEmployeeAssiduousness.do?method=chooseEmployee&action=showSchedule',VISIBLE=1,KEY_EXECUTION_PATH_VALUE=736,CONTENT_ID='48e76566-47fd-4b59-8597-1f13462f0aef',CREATION_DATE='2008-01-14 20:38:27',NAME='pt7:Horário',TITLE='pt7:Horário',BODY=null,DESCRIPTION=null,KEY_ROOT_DOMAIN_OBJECT=1,KEY_AVAILABILITY_POLICY=null,KEY_PORTAL=null,KEY_CREATOR=null,OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.functionalities.Functionality' WHERE CONTENT_ID = '48e76566-47fd-4b59-8597-1f13462f0aef'  ;

CREATE TEMPORARY TABLE UUID_TEMP_TABLE(COUNTER integer, UUID varchar(255), FROM_UUID varchar(255));

ALTER TABLE UUID_TEMP_TABLE ADD INDEX (COUNTER), ADD INDEX (UUID), ADD INDEX (FROM_UUID); 


DROP TABLE UUID_TEMP_TABLE;



COMMIT;
