alter table `OUTBOUND_MOBILITY_CANDIDACY_SUBMISSION` add `OID_SELECTED_CANDIDACY` bigint unsigned;
alter table `OUTBOUND_MOBILITY_CANDIDACY` add `OID_SUBMISSION_FROM_SELECTED_CANDIDACY` bigint unsigned;
