ALTER TABLE INQUIRIES_COURSE ADD COLUMN ENTRY_GRADE_CLASSIFICATION char(1) default NULL;
ALTER TABLE INQUIRIES_COURSE ADD COLUMN APPROVATION_RATIO_CLASSIFICATION char(1) default NULL;
ALTER TABLE INQUIRIES_COURSE ADD COLUMN ARITHMETIC_MEAN_CLASSIFICATION char(1) default NULL;
