select concat('update GUIDE_ENTRY set GUIDE_ENTRY.KEY_PAYMENT_TRANSACTION = ',
	PAYMENT_TRANSACTION.ID_INTERNAL,' where GUIDE_ENTRY.ID_INTERNAL = ', 
	PAYMENT_TRANSACTION.KEY_GUIDE_ENTRY, ';') 
as "" from PAYMENT_TRANSACTION where PAYMENT_TRANSACTION.KEY_GUIDE_ENTRY IS NOT NULL;
