-- ACK_OPT_LOCK_
SELECT COUNT(*) FROM PERSON WHERE ACK_OPT_LOCK IS NULL;
SELECT COUNT(*) FROM ass_FUNCIONARIO WHERE ACK_OPT_LOCK IS NULL;
SELECT COUNT(*) FROM TEACHER WHERE ACK_OPT_LOCK IS NULL;
SELECT COUNT(*) FROM ass_FUNCIONARIO_HISTORICO WHERE ACK_OPT_LOCK IS NULL;
SELECT COUNT(*) FROM ass_FUNC_NAO_DOCENTE WHERE ACK_OPT_LOCK IS NULL;

UPDATE PERSON SET ACK_OPT_LOCK = 1 WHERE ACK_OPT_LOCK IS NULL;
UPDATE ass_FUNCIONARIO SET ACK_OPT_LOCK = 1 WHERE ACK_OPT_LOCK IS NULL;
UPDATE TEACHER SET ACK_OPT_LOCK = 1 WHERE ACK_OPT_LOCK IS NULL;
UPDATE ass_FUNCIONARIO_HISTORICO SET ACK_OPT_LOCK = 1 WHERE ACK_OPT_LOCK IS NULL;
UPDATE ass_FUNC_NAO_DOCENTE SET ACK_OPT_LOCK = 1 WHERE ACK_OPT_LOCK IS NULL;