ALTER TABLE SUMMARY ADD KEY_PROFESSORSHIP int(11) unsigned default NULL;
ALTER TABLE SUMMARY ADD KEY_TEACHER int(11) unsigned default NULL;
ALTER TABLE SUMMARY ADD TEACHER_NAME varchar(100) default NULL;
ALTER TABLE SUMMARY ADD STUDENTS_NUMBER int(11) unsigned default '0';
ALTER TABLE SUMMARY ADD EXTRA_LESSON tinyint(1) NOT NULL default '0';
ALTER TABLE SUMMARY ADD KEY_ROOM int(11) default NULL;
ALTER TABLE SUMMARY CHANGE SUMMARY_DATE SUMMARY_DATE date NOT NULL;
ALTER TABLE SUMMARY CHANGE SUMMARY_HOUR SUMMARY_HOUR time NOT NULL;

-- estas duas instruções são provisórias
ALTER TABLE SUMMARY ADD KEY_SHIFT int(11) unsigned default NULL;
ALTER TABLE SUMMARY CHANGE KEY_EXECUTION_COURSE KEY_EXECUTION_COURSE int(11) unsigned default '0';

-- estas quatro instruções correr só depois da migração
ALTER TABLE SUMMARY CHANGE KEY_SHIFT KEY_SHIFT int(11) unsigned NOT NULL default '0';
ALTER TABLE SUMMARY ADD UNIQUE (KEY_SHIFT, SUMMARY_DATE, SUMMARY_HOUR);

ALTER TABLE SUMMARY DROP KEY_EXECUTION_COURSE;
ALTER TABLE SUMMARY DROP SUMMARY_TYPE;



-- SUMMARY
-- CREATE TABLE `SUMMARY` (
-- `ID_INTERNAL` int(11) unsigned NOT NULL auto_increment,
-- `KEY_EXECUTION_COURSE` int(11) unsigned NOT NULL default '0',
-- `TITLE` text,
-- `SUMMARY_DATE` date default NULL,
-- `SUMMARY_HOUR` time default NULL,
-- `LAST_MODIFICATION_DATE` timestamp(14) NOT NULL,
-- `SUMMARY_TEXT` text,
-- `SUMMARY_TYPE` int(11) default NULL,
-- `ACK_OPT_LOCK` int(11) default NULL,
-- PRIMARY KEY  (`ID_INTERNAL`)
-- TYPE=InnoDB;