UPDATE DEGREE_CURRICULAR_PLAN SET NEEDED_CREDITS= 27 WHERE ID_INTERNAL=49;
INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (95, 2, 39, 18, 0);
