
UPDATE DEGREE_CURRICULAR_PLAN set MARK_TYPE = 5 where NAME like 'M%';

UPDATE DEGREE_CURRICULAR_PLAN SET MARK_TYPE= 20 WHERE ID_INTERNAL=24;
UPDATE DEGREE_CURRICULAR_PLAN SET MARK_TYPE= 20 WHERE ID_INTERNAL=29;
UPDATE DEGREE_CURRICULAR_PLAN SET MARK_TYPE= 20 WHERE ID_INTERNAL=33;
UPDATE DEGREE_CURRICULAR_PLAN SET MARK_TYPE= 20 WHERE ID_INTERNAL=34;


