ALTER TABLE MASTER_DEGREE_CANDIDATE ADD GIVEN_CREDITS FLOAT;
ALTER TABLE MASTER_DEGREE_CANDIDATE ADD GIVEN_CREDITS_REMARKS TEXT;

#----------------------------
# Table structure for CANDIDATE_ENROLMENT
#----------------------------
drop table if exists CANDIDATE_ENROLMENT;
create table CANDIDATE_ENROLMENT(
   ID_INTERNAL integer(11) not null auto_increment,
   KEY_MASTER_DEGREE_CANDIDATE integer(11) not null ,
   KEY_CURRICULAR_COURSE_SCOPE integer(11) not null ,
   primary key (ID_INTERNAL),
   unique u1 (KEY_MASTER_DEGREE_CANDIDATE, KEY_CURRICULAR_COURSE_SCOPE))
   type=InnoDB;


INSERT INTO EXECUTION_DEGREE (ID_INTERNAL, ACADEMIC_YEAR, KEY_DEGREE_CURRICULAR_PLAN, KEY_TEACHER, TEMPORARY_EXAM_MAP) VALUES (97, 2, 45, 24, 0);
