-- ALTERAR O NOME DA TABELA EVALUATION PARA EVALUATION_METHOD
ALTER TABLE EVALUATION RENAME EVALUATION_METHOD;

-- ALTERAR O NOME DA TABELA EXAM PARA EVALUATION
ALTER TABLE EXAM RENAME EVALUATION;

-- ADICIONAR O CAMPO CLASS-NAME NA TABELA EVALUATION
ALTER TABLE EVALUATION ADD CLASS_NAME varchar(250) NOT NULL AFTER ID_INTERNAL;

-- --------------------------------------------------------------
-- ALTERAR O NOME DO CAMPO CHAVE DE EXAM PARA CHAVE DE EVALUATION
-- --------------------------------------------------------------
ALTER TABLE EXAM_EXECUTION_COURSE CHANGE KEY_EXAM KEY_EVALUATION int(11) not null;
ALTER TABLE EXAM_ROOM CHANGE KEY_EXAM KEY_EVALUATION int(11) not null;
ALTER TABLE EXAM_STUDENT CHANGE KEY_EXAM KEY_EVALUATION int(11) not null;
ALTER TABLE EXAM_STUDENT_ROOM CHANGE KEY_EXAM KEY_EVALUATION int(11) not null;
ALTER TABLE MARK CHANGE KEY_EXAM KEY_EVALUATION int(11) not null;

-- --------------------------------------------------------------
-- ALTERAR OS RECORDS DA TABELA EVALUATION
-- --------------------------------------------------------------
UPDATE EVALUATION SET CLASS_NAME='Dominio.Exam';

-- --------------------------------------------------------------
-- ALTER TABLE CREDITS
-- --------------------------------------------------------------
ALTER TABLE CREDITS ADD ADDITIONAL_CREDITS float;
ALTER TABLE CREDITS ADD ADDITIONAL_CREDITS_JUSTIFICATION varchar (250);
UPDATE CREDITS set ADDITIONAL_CREDITS = NULL , ADDITIONAL_CREDITS_JUSTIFICATION = NULL;
s