ALTER TABLE `STUDENT_CURRICULAR_PLAN` ADD `OBSERVATIONS` TEXT AFTER `CLASSIFICATION`;
ALTER TABLE `ITEM` DROP INDEX ID_INTERNAL;
ALTER TABLE `ITEM` ADD UNIQUE U1 (KEY_SECTION,NAME);
ALTER TABLE `ANNOUNCEMENT` DROP INDEX U1;
ALTER TABLE `ANNOUNCEMENT` CHANGE `CREATION_DATE` `CREATION_DATE` TIMESTAMP(8);
ALTER TABLE `ANNOUNCEMENT` CHANGE `LAST_MODIFICATION_DATE` `LAST_MODIFICATION_DATE` TIMESTAMP(8);
ALTER TABLE `ANNOUNCEMENT` ADD UNIQUE U1 (CREATION_DATE,KEY_SITE,TITLE);