ALTER TABLE `STUDENT_CURRICULAR_PLAN` ADD `KEY_EMPLOYEE` INT(11)  UNSIGNED;
ALTER TABLE `STUDENT_CURRICULAR_PLAN` ADD `WHEN_ALTER` TIMESTAMP;

alter table WEBSITE_ITEM add KEY_AUTHOR int(11) not null after KEY_EDITOR;
update WEBSITE_ITEM set KEY_AUTHOR=2525;

alter table WEBSITE_ITEM delete KEY_AUTHOR;
alter table WEBSITE_ITEM add AUTHOR_NAME varchar(100) not null after KEY_EDITOR;
alter table WEBSITE_ITEM add AUTHOR_EMAIL varchar(100) not null after AUTHOR_NAME;
update WEBSITE_ITEM set AUTHOR_NAME='Jorge Machado';
update WEBSITE_ITEM set AUTHOR_EMAIL=' ';
alter table WEBSITE_ITEM change ONLINE_BEGIN_DAY ONLINE_BEGIN_DAY date;
alter table WEBSITE_ITEM change ONLINE_END_DAY ONLINE_END_DAY date;
