UPDATE DEGREE_CURRICULAR_PLAN SET STATE = 2 WHERE NAME LIKE "L%" AND NAME NOT LIKE "%2003/2004";
UPDATE DEGREE_CURRICULAR_PLAN SET STATE = 1 WHERE NAME LIKE "L%2003/2004";

ALTER TABLE CURRICULAR_COURSE_SCOPE ADD ECTS_CREDITS double after CREDITS;
ALTER TABLE CURRICULAR_COURSE_SCOPE ADD BEGIN_DATE date NOT NULL DEFAULT '2003-10-24';
ALTER TABLE CURRICULAR_COURSE_SCOPE ADD END_DATE date;
UPDATE CURRICULAR_COURSE_SCOPE SET END_DATE='2003-10-24';

ALTER TABLE CURRICULAR_COURSE_SCOPE DROP INDEX U1;
ALTER TABLE CURRICULAR_COURSE_SCOPE ADD unique U1(KEY_CURRICULAR_SEMESTER, KEY_CURRICULAR_COURSE, KEY_BRANCH, BEGIN_DATE);
