SELECT CONCAT('UPDATE CURRICULAR_COURSE_SCOPE SET END_DATE = NULL WHERE ID_INTERNAL = ', CCS.ID_INTERNAL, ';') AS ""
FROM CURRICULAR_COURSE_SCOPE CCS
INNER JOIN CURRICULAR_COURSE CC ON CCS.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
WHERE DCP.STATE = 1;

# make this select in mysql prompt to make sure end_date is null in 2632 records 
#SELECT CCS.ID_INTERNAL, CCS.END_DATE FROM CURRICULAR_COURSE_SCOPE CCS
#INNER JOIN CURRICULAR_COURSE CC ON CCS.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
#INNER JOIN DEGREE_CURRICULAR_PLAN DCP ON CC.KEY_DEGREE_CURRICULAR_PLAN = DCP.ID_INTERNAL
#WHERE DCP.STATE = 1;