alter table CREDITS rename crd_CREDITS;
alter table CREDITS_MANAGER_DEPARTMENT rename crd_CREDITS_MANAGER_DEPARTMENT;
alter table TEACHER_INSTITUTION_WORK_TIME rename crd_TEACHER_INSTITUTION_WORK_TIME;
alter table TEACHER_DEGREE_FINAL_PROJECT_STUDENT rename crd_TEACHER_DEGREE_FINAL_PROJECT_STUDENT;


alter table crd_CREDITS add CONTAINS_MANAGEMENT_POSITIONS tinyint(1);
alter table crd_CREDITS add CONTAINS_SERVICE_EXEMPTIONS_SITUATIONS tinyint(1);