-- ATENÇÃO!!!!!!
-- OS SEGUINTES UPDATES PODEM SER EXECUTADOS AUTOMATICAMENTE QUANDO SE CORREM OS SCRIPTS DE PREECHIMENTO DAS TABELAS PARA A LEEC:
UPDATE BRANCH SET BRANCH_NAME = 'SISTEMAS ELECTRÓNICOS' WHERE ID_INTERNAL = 8529;
UPDATE BRANCH SET BRANCH_NAME = 'SISTEMAS, DECISÃO E CONTROLO' WHERE ID_INTERNAL = 8528;
UPDATE BRANCH SET BRANCH_NAME = 'TELECOMUNICAÇÕES' WHERE ID_INTERNAL = 8527;
UPDATE BRANCH SET BRANCH_NAME = 'ENERGIA' WHERE ID_INTERNAL = 8526;

INSERT INTO BRANCH (BRANCH_CODE, BRANCH_NAME, KEY_DEGREE_CURRICULAR_PLAN,ACK_OPT_LOCK,BRANCH_TYPE) VALUES ('1450', 'COMPUTADORES', 48, 1, 'SPECBR');

ALTER TABLE CURRICULAR_COURSE_GROUP DROP INDEX U1, ADD UNIQUE U1 (KEY_BRANCH,ID_INTERNAL);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO ROLE VALUES(0, 12, '/degreeAdministrativeOffice', '/index.do', 'portal.degreeAdministrativeOffice', 1);
INSERT INTO ROLE VALUES(0, 16, '/degreeAdministrativeOffice', '/index.do', 'portal.degreeAdministrativeOfficeSuperUser', 1);

INSERT INTO PERSON_ROLE VALUES(0, 27, 876, 1);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO BRANCH VALUES("8681", "1401", "BASES DE ENGENHARIA", "48", NULL, "52", "52", "1", "COMNBR");
INSERT INTO BRANCH VALUES("8682", "1402", "BASES DE ENGENHARIA ELECTROTÉCNIA E DE COMPUTADORES", "48", "", "56", "56", "1", "COMNBR");

-- -------------------------------------------------------------------------------------------------------------------------

CREATE INDEX CURRICULAR_COURSE_GROUP_INDEX_1 on CURRICULAR_COURSE_GROUP(KEY_BRANCH);
CREATE INDEX CURRICULAR_COURSE_GROUP_INDEX_2 on CURRICULAR_COURSE_GROUP(KEY_BRANCH,AREA_TYPE);

CREATE INDEX CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP_INDEX_2 on CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP(KEY_CURRICULAR_COURSE);
CREATE INDEX CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP_INDEX_3 on CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP(KEY_CURRICULAR_COURSE_GROUP);

CREATE INDEX SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP_INDEX_2 on SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP(KEY_SCIENTIFIC_AREA);
CREATE INDEX SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP_INDEX_3 on SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP(KEY_CURRICULAR_COURSE_GROUP);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2698);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2687);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2731);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2724);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2705);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 29, 2714);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 30, 2669);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 31, 3112);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 31, 3119);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 31, 3125);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 32, 2683);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 33, 2701);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 34, 3078);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 35, 2943);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 36, 2993);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 37, 2992);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 37, 2628);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 38, 2994);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 38, 2995);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 39, 3000);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 40, 2738);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 40, 2739);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 41, 2997);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 42, 2998);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 43, 2566);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 44, 2996);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 45, 2999);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (28, 8681, 20, 20, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (29, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 12, 12, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);


INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 8, 8, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 8, 8, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 8, 8, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 28, 1);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 29, 15);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 30, 2);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 31, 11);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 32, 17);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 33, 14);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 34, 5);

INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 35, 20);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 36, 22);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 37, 3);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 38, 9);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 39, 16);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 40, 6);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 41, 4);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 42, 10);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 43, 14);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 44, 19);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 45, 12);

-- -------------------------------------------------------------------------------------------------------------------------

ALTER TABLE STUDENT_CURRICULAR_PLAN CHANGE KEY_SPECIALIZATION_BRANCH KEY_SPECIALIZATION_BRANCH int(11) default NULL;
UPDATE STUDENT_CURRICULAR_PLAN SET KEY_SPECIALIZATION_BRANCH=NULL, KEY_SECUNDARY_BRANCH=NULL WHERE KEY_DEGREE_CURRICULAR_PLAN = 48;

-- -------------------------------------------------------------------------------------------------------------------------

CREATE INDEX PRECEDENCE_INDEX_1 on PRECEDENCE(KEY_CURRICULAR_COURSE);
CREATE INDEX RESTRICTION_INDEX_1 on RESTRICTION(KEY_PRECEDENCE);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO ENROLMENT_PERIOD (ID_INTERNAL, KEY_DEGREE_CURRICULAR_PLAN, KEY_EXECUTION_PERIOD, START_DATE, END_DATE, ACK_OPT_LOCK) VALUES (1, 48, 80, '2004-02-01', '2004-02-28', 1);
-- UPDATE EXECUTION_PERIOD SET STATE = 'O' WHERE ID_INTERNAL = 2;
-- UPDATE EXECUTION_PERIOD SET STATE = 'C' WHERE ID_INTERNAL = 80;

-- -------------------------------------------------------------------------------------------------------------------------

-- select concat('UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = ', cc.ID_INTERNAL, ';') as "QQ"
-- from mw_disciplinas_ileec mwdileec
-- inner join curricular_course cc on mwdileec.codigo_disciplina = cc.code
-- inner join degree_curricular_plan dcp on cc.key_degree_curricular_plan = dcp.id_internal
-- where dcp.id_internal = 48 and mwdileec.obrigatoria = 1;

UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2698;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2687;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2731;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2724;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2705;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2714;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2669;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 3112;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 3119;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 3125;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2683;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2701;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2943;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2993;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2992;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2628;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2994;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2995;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 3000;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2738;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2739;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2997;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2566;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2996;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2999;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2998;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2574;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2576;
UPDATE CURRICULAR_COURSE SET MANDATORY = 1 WHERE ID_INTERNAL = 2766;

