-- OS SEGUINTES SÃO EXECUTADOS AUTOMATICAMENTE QUANDO SE CORREM OS SCRIPTS DE PREECHIMENTO DAS TABELAS PARA A LEEC:
-- UPDATE BRANCH SET BRANCH_NAME = 'SISTEMAS ELECTRÓNICOS' WHERE ID_INTERNAL = 8529;
-- UPDATE BRANCH SET BRANCH_NAME = 'SISTEMAS, DECISÃO E CONTROLO' WHERE ID_INTERNAL = 8528;
-- UPDATE BRANCH SET BRANCH_NAME = 'TELECOMUNICAÇÕES' WHERE ID_INTERNAL = 8527;
-- UPDATE BRANCH SET BRANCH_NAME = 'ENERGIA' WHERE ID_INTERNAL = 8526;

-- INSERT INTO BRANCH (BRANCH_CODE, BRANCH_NAME, KEY_DEGREE_CURRICULAR_PLAN,ACK_OPT_LOCK,BRANCH_TYPE) VALUES ('1450', 'COMPUTADORES', 48, 1, 'SPECBR');

-- ALTER TABLE CURRICULAR_COURSE_GROUP DROP INDEX U1, ADD UNIQUE U1 (KEY_BRANCH,ID_INTERNAL);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO ROLE VALUES(0, 12, '/degreeAdministrativeOffice', '/index.do', 'portal.degreeAdministrativeOffice', 1);
INSERT INTO ROLE VALUES(0, 16, '/degreeAdministrativeOffice', '/index.do', 'portal.degreeAdministrativeOfficeSuperUser', 1);

INSERT INTO PERSON_ROLE VALUES(0, 27, 876, 1);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO BRANCH VALUES("8681", "1401", "BASES DE ENGENHARIA", "48", NULL, "52", "52", "1", "COMNBR");
INSERT INTO BRANCH VALUES("8682", "1402", "BASES DE ENGENHARIA ELECTROTÉCNIA E DE COMPUTADORES", "48", "", "56", "56", "1", "COMNBR");

-- -------------------------------------------------------------------------------------------------------------------------

CREATE INDEX CURRICULAR_COURSE_GROUP_INDEX_1 on CURRICULAR_COURSE_GROUP(KEY_BRANCH);
CREATE INDEX CURRICULAR_COURSE_GROUP_INDEX_2 on CURRICULAR_COURSE_GROUP(KEY_BRANCH,AREA_TYPE);

CREATE INDEX CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP_INDEX_2 on CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP(KEY_CURRICULAR_COURSE);
CREATE INDEX CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP_INDEX_3 on CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP(KEY_CURRICULAR_COURSE_GROUP);

CREATE INDEX SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP_INDEX_2 on SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP(KEY_SCIENTIFIC_AREA);
CREATE INDEX SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP_INDEX_3 on SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP(KEY_CURRICULAR_COURSE_GROUP);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2698);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2687);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2731);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2724);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 28, 2705);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 29, 2714);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 30, 2669);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 31, 3112);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 31, 3119);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 31, 3125);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 32, 2683);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 33, 2701);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 34, 3078);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 35, 2943);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 36, 2993);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 37, 2992);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 37, 2628);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 38, 2994);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 38, 2995);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 39, 3000);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 40, 2738);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 40, 2739);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 41, 2997);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 42, 2998);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 43, 2566);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 44, 2996);

INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (NULL, 45, 2999);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (28, 8681, 20, 20, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (29, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 12, 12, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8681, 4, 4, 3, 1);


INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 8, 8, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 8, 8, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 8, 8, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);
INSERT INTO CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_BRANCH, MINIMUM_CREDITS, MAXIMUM_CREDITS, AREA_TYPE, ACK_OPT_LOCK) VALUES (NULL, 8682, 4, 4, 3, 1);

-- -------------------------------------------------------------------------------------------------------------------------

INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 28, 1);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 29, 15);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 30, 2);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 31, 11);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 32, 17);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 33, 14);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 34, 5);

INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 35, 20);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 36, 22);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 37, 3);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 38, 9);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 39, 16);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 40, 6);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 41, 4);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 42, 10);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 43, 14);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 44, 19);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_SCIENTIFIC_AREA) VALUES (NULL, 45, 12);

-- -------------------------------------------------------------------------------------------------------------------------

ALTER TABLE STUDENT_CURRICULAR_PLAN CHANGE KEY_SPECIALIZATION_BRANCH KEY_SPECIALIZATION_BRANCH int(11) default NULL;
UPDATE STUDENT_CURRICULAR_PLAN SET KEY_SPECIALIZATION_BRANCH=NULL, KEY_SECUNDARY_BRANCH=NULL WHERE KEY_DEGREE_CURRICULAR_PLAN = 48;

-- -------------------------------------------------------------------------------------------------------------------------

CREATE INDEX PRECEDENCE_INDEX_1 on PRECEDENCE(KEY_CURRICULAR_COURSE);
CREATE INDEX RESTRICTION_INDEX_1 on RESTRICTION(KEY_PRECEDENCE);
