-- Guias com número maior que 5000000 de alunos dos planos curriculares de 2002/2004
-- devem ser corrigidos o execution degree para este ano lectivo.

-- -------------------------------------------------------------------------------------------------------------------
-- DCP MB02/04 (38, 162) 
SELECT DCP.NAME, DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MB02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 38;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 162
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MB02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 38;

-- **********************************************************************************************************************************************-- DCP MC02/04 (50, 182) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MC02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 50;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 182
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MC02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 50;

-- **********************************************************************************************************************************************-- DCP MCEM02/04 (164, 165) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MCEM02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 164;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 165
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MCEM02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 164;

-- **********************************************************************************************************************************************-- DCP MCES02/04 (41, 163) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MCES02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 41;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 163
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MCES02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 41;

-- **********************************************************************************************************************************************-- DCP MEA02/04 (121, 184) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEA02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 121;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 184
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEA02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 121;

-- **********************************************************************************************************************************************-- DCP MEE02/04 (34, 185) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEE02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 34;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 185
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEE02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 34;

-- **********************************************************************************************************************************************-- DCP MEEC02/04 (46, 188) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEEC02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 46;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 188
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEEC02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 46;

-- **********************************************************************************************************************************************-- DCP MEGMTRM02/04 (36, 183) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEGMTRM02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 36;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 183
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEGMTRM02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 36;

-- **********************************************************************************************************************************************-- DCP MEGT02/04 (53, 187) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEGT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 53;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 187
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEGT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 53;

-- **********************************************************************************************************************************************-- DCP MEIC02/04 (43, 189) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEIC02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 43;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 189
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEIC02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 43;

-- **********************************************************************************************************************************************-- DCP MEM02/04 (47, 190) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEM02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 47;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 190
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEM02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 47;

-- **********************************************************************************************************************************************-- DCP MEMAT02/04 (166, 186) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEMAT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 166;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 186
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MEMAT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 166;

-- **********************************************************************************************************************************************-- DCP MF02/04 (54, 191) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MF02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 54;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 191
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MF02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 54;

-- **********************************************************************************************************************************************-- DCP MG02/04 (49, 192) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MG02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 49;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 192
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MG02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 49;

-- **********************************************************************************************************************************************-- DCP MGT02/04 (44, 193) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MGT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 44;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 193
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MGT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 44;

-- **********************************************************************************************************************************************-- DCP MHRH02/04 (37, 194) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MHRH02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 37;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 194
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MHRH02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 37;

-- **********************************************************************************************************************************************-- DCP MIOES02/04 (35, 196) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MIOES02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 35;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 196
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MIOES02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 35;

-- **********************************************************************************************************************************************-- DCP MITGI02/04 (42, 195) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MITGI02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 42;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 195
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MITGI02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 42;

-- **********************************************************************************************************************************************-- DCP ML02/04 (52, 197) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'ML02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 52;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 197
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'ML02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 52;

-- **********************************************************************************************************************************************-- DCP MMA02/04 (48, 201) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MMA02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 48;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 201
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MMA02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 48;

-- **********************************************************************************************************************************************-- DCP MSIG02/04 (40, 198) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MSIG02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 40;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 198
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MSIG02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 40;

-- **********************************************************************************************************************************************-- DCP MT02/04 (51, 199) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 51;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 199
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 51;

-- **********************************************************************************************************************************************-- DCP MUGT02/04 (45, 200) 
SELECT DCP.NAME, S.NUMBER, G.NUMBER FROM GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MUGT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 45;

UPDATE GUIDE G, PERSON P, STUDENT S, STUDENT_CURRICULAR_PLAN SCP, DEGREE_CURRICULAR_PLAN DCP
SET G.KEY_EXECUTION_DEGREE = 200
WHERE G.KEY_PERSON = P.ID_INTERNAL
AND P.ID_INTERNAL = S.KEY_PERSON
AND S.ID_INTERNAL = SCP.KEY_STUDENT
AND DCP.ID_INTERNAL = SCP.KEY_DEGREE_CURRICULAR_PLAN
AND DCP.NAME LIKE 'MUGT02/04'
AND G.NUMBER < 500000
AND G.KEY_EXECUTION_DEGREE = 45;

