-- SELECT E.* FROM ENROLMENT E
-- INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
-- INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
-- WHERE SCP.KEY_DEGREE_CURRICULAR_PLAN = 113 AND CC.ID_INTERNAL = 3110;

SELECT CONCAT('UPDATE ENROLMENT SET KEY_CURRICULAR_COURSE = 11334 WHERE ID_INTERNAL = ', E.ID_INTERNAL) AS ""
FROM ENROLMENT E
INNER JOIN STUDENT_CURRICULAR_PLAN SCP ON E.KEY_STUDENT_CURRICULAR_PLAN = SCP.ID_INTERNAL
INNER JOIN CURRICULAR_COURSE CC ON E.KEY_CURRICULAR_COURSE = CC.ID_INTERNAL
WHERE SCP.KEY_DEGREE_CURRICULAR_PLAN = 113 AND CC.ID_INTERNAL = 3110;

UPDATE ENROLMENT SET KEY_CURRICULAR_COURSE = 11334 WHERE ID_INTERNAL = 479883;
UPDATE ENROLMENT SET KEY_CURRICULAR_COURSE = 11334 WHERE ID_INTERNAL = 480319;
UPDATE ENROLMENT SET KEY_CURRICULAR_COURSE = 11334 WHERE ID_INTERNAL = 479878;


DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=178;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=155;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=120;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=119;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=118;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=117;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=116;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=115;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=191;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=190;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=189;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=188;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=187;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=186;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=185;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=183;
DELETE FROM mw_CURRICULAR_COURSE_OUTSIDE_STUDENT_DEGREE WHERE idInternal=182;


INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP VALUES(170, 23, 3059);
INSERT INTO SCIENTIFIC_AREA_CURRICULAR_COURSE_GROUP VALUES(58, 23, 20);

UPDATE CURRICULAR_COURSE_EXECUTION_COURSE SET KEY_CURRICULAR_COURSE = 11334 WHERE INTERNAL_CODE = 13519;


