ALTER TABLE METADATA ADD DESCRIPTION text;
ALTER TABLE METADATA ADD DIFFICULTY text;
ALTER TABLE METADATA ADD LEARNINGTIME varchar(10);
ALTER TABLE METADATA ADD LEVEL text;
ALTER TABLE METADATA ADD MAIN_SUBJECT text;
ALTER TABLE METADATA ADD SECONDARY_SUBJECT text;
ALTER TABLE METADATA ADD AUTHOR text;
ALTER TABLE METADATA ADD NUMBER_OF_MEMBERS int(5) not null default '1';
