ALTER TABLE EVALUATION ADD KEY_DISTRIBUTED_TEST int(11) unsigned;
ALTER TABLE METADATA MODIFY LEARNINGTIME TIME;

drop table if exists TEST_SCOPE;
CREATE TABLE TEST_SCOPE(
  ID_INTERNAL int(11) unsigned not null auto_increment,
  CLASS_NAME varchar(250) NOT NULL,
  KEY_CLASS int(11) unsigned,
  ACK_OPT_LOCK int(11),
  PRIMARY KEY  (ID_INTERNAL)
) TYPE=InnoDB;


ALTER TABLE DISTRIBUTED_TESTS DROP COLUMN KEY_EXECUTION_COURSE;
ALTER TABLE DISTRIBUTED_TESTS ADD KEY_TEST_SCOPE int(11) unsigned not null default '0';

ALTER TABLE TESTS DROP COLUMN KEY_EXECUTION_COURSE;
ALTER TABLE TESTS ADD KEY_TEST_SCOPE int(11) unsigned not null default '0';