alter table STUDENT_TEST_QUESTION add TEST_QUESTION_MARK double not null default "0" after TEST_QUESTION_VALUE;
alter table XML_DOCUMENTS add VISIBILITY bit not null default 1;
alter table METADATA add VISIBILITY bit not null default 1;

ALTER TABLE EVALUATION_METHOD CHANGE KEY_CURRICULAR_COURSE KEY_EXECUTION_COURSE INT(11) DEFAULT NULL;
DELETE FROM EVALUATION_METHOD;
ALTER TABLE EVALUATION_METHOD auto_increment=1;

-- ALTER TABLE CURRICULUM ADD LAST_MODIFICATION_DATE DATE;


-- ALTER TABLE CURRICULUM DROP EVALUATION_ELEMENTS;
-- ALTER TABLE CURRICULUM DROP EVALUATION_ELEMENTS_EN;



