INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (171, 23, 3049);
INSERT INTO CURRICULAR_COURSE_CURRICULAR_COURSE_GROUP (ID_INTERNAL, KEY_CURRICULAR_COURSE_GROUP, KEY_CURRICULAR_COURSE) VALUES (172, 23, 3071);
