ALTER TABLE CURRICULAR_COURSE ADD MAX_INCREMENT_NAC int(11) DEFAULT '2';
ALTER TABLE CURRICULAR_COURSE ADD MIN_INCREMENT_NAC int(11) DEFAULT '1';
ALTER TABLE CURRICULAR_COURSE ADD ENROLLMENT_WEIGTH int(11) DEFAULT '1';
ALTER TABLE CURRICULAR_COURSE ADD ECTS_CREDITS double;

UPDATE CURRICULAR_COURSE_SCOPE SET CREDITS = 0 WHERE CREDITS IS NULL;
UPDATE CURRICULAR_COURSE_SCOPE SET ECTS_CREDITS = 0 WHERE ECTS_CREDITS IS NULL;
UPDATE CURRICULAR_COURSE_SCOPE SET THEORETICAL_HOURS = 0 WHERE THEORETICAL_HOURS IS NULL;
UPDATE CURRICULAR_COURSE_SCOPE SET PRATICAL_HOURS = 0 WHERE PRATICAL_HOURS IS NULL;
UPDATE CURRICULAR_COURSE_SCOPE SET LAB_HOURS = 0 WHERE LAB_HOURS IS NULL;
UPDATE CURRICULAR_COURSE_SCOPE SET THEO_PRAT_HOURS = 0 WHERE THEO_PRAT_HOURS IS NULL;

-- UPDATE CURRICULAR_COURSE_SCOPE SET MAX_INCREMENT_NAC = 0 WHERE MAX_INCREMENT_NAC IS NULL;
-- UPDATE CURRICULAR_COURSE_SCOPE SET MIN_INCREMENT_NAC = 0 WHERE MIN_INCREMENT_NAC IS NULL;
-- UPDATE CURRICULAR_COURSE_SCOPE SET WEIGTH = 0 WHERE WEIGTH IS NULL;

select concat('UPDATE CURRICULAR_COURSE SET CREDITS = ', ccs.CREDITS,
', THEORETICAL_HOURS = ', ccs.THEORETICAL_HOURS,
', PRATICAL_HOURS = ', ccs.PRATICAL_HOURS,
', THEO_PRAT_HOURS = ', ccs.THEO_PRAT_HOURS,
', LAB_HOURS = ', ccs.LAB_HOURS,
', ECTS_CREDITS = ', ccs.ECTS_CREDITS,
' WHERE ID_INTERNAL = ', cc.ID_INTERNAL, ';') AS "QQ"
from CURRICULAR_COURSE_SCOPE ccs
inner join CURRICULAR_COURSE cc on ccs.KEY_CURRICULAR_COURSE = cc.ID_INTERNAL;

-- ', MAX_INCREMENT_NAC = ', ccs.MAX_INCREMENT_NAC,
-- ', MIN_INCREMENT_NAC = ', ccs.MIN_INCREMENT_NAC,
-- ', ENROLLMENT_WEIGTH = ', ccs.WEIGTH,
