ALTER TABLE DEGREE_CURRICULAR_PLAN ADD ENROLLMENT_STRATEGY_CLASS_NAME VARCHAR(255) AFTER DESCRIPTION_EN;
UPDATE DEGREE_CURRICULAR_PLAN SET ENROLLMENT_STRATEGY_CLASS_NAME = 'class ServidorAplicacao.strategy.enrolment.strategys.student.EnrolmentStrategyLEEC' WHERE ID_INTERNAL = 48;
