ALTER TABLE EVALUATION_METHOD CHANGE KEY_CURRICULAR_COURSE KEY_EXECUTION_COURSE INT(11) DEFAULT NULL;
DELETE FROM EVALUATION_METHOD;
ALTER TABLE EVALUATION_METHOD auto_increment=1;

-- ALTER TABLE CURRICULUM ADD LAST_MODIFICATION_DATE DATE;


-- ALTER TABLE CURRICULUM DROP EVALUATION_ELEMENTS;
-- ALTER TABLE CURRICULUM DROP EVALUATION_ELEMENTS_EN;



