ALTER TABLE WEBSITE_SECTION ADD FTP_NAME varchar(100) NOT NULL DEFAULT '' AFTER NAME;
UPDATE WEBSITE_SECTION SET FTP_NAME='ev' where NAME = 'Eventos';
UPDATE WEBSITE_SECTION SET FTP_NAME='not' where NAME = 'Noticias';
UPDATE WEBSITE_SECTION SET NAME ='Notícias' where NAME = 'Noticias';

UPDATE WEBSITE_SECTION SET SIZE=3;

UPDATE WEBSITE_SECTION SET NAME ='Notícias' where NAME = 'Noticias';

UPDATE WEBSITE_ITEM SET ONLINE_BEGIN_DAY='2004-12-01', ONLINE_END_DAY='2004-12-31' WHERE ID_INTERNAL=451;

UPDATE WEBSITE_ITEM SET ITEM_BEGIN_DAY=NULL, ITEM_END_DAY=NULL WHERE KEY_WEBSITE_SECTION = 1;