ALTER TABLE PAYMENT_PLAN CHANGE COLUMN KEY_SERVICE_AGREEMENT_TEMPLATE KEY_SERVICE_AGREEMENT_TEMPLATE INT(11) DEFAULT NULL;
ALTER TABLE PAYMENT_PLAN ADD COLUMN KEY_SERVICE_AGREEMENT INT(11) DEFAULT NULL;
ALTER TABLE PAYMENT_PLAN ADD INDEX (KEY_SERVICE_AGREEMENT);
