alter table CONCLUSION_PROCESS add column KEY_LAST_VERSION int(11), add index (KEY_LAST_VERSION);
alter table CONCLUSION_PROCESS_VERSION add column KEY_LAST_VERSION_CONCLUSION_PROCESS int(11), add index (KEY_LAST_VERSION_CONCLUSION_PROCESS);
UPDATE CONCLUSION_PROCESS_VERSION SET CONCLUSION_PROCESS_VERSION.KEY_LAST_VERSION_CONCLUSION_PROCESS = CONCLUSION_PROCESS_VERSION.KEY_CONCLUSION_PROCESS;
