ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN RESPONSIBLE VARCHAR(100) DEFAULT NULL;
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN DISABILITIES TEXT DEFAULT NULL;
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN EDUCATION TEXT DEFAULT NULL;
ALTER TABLE INDIVIDUAL_CANDIDACY ADD COLUMN LANGUAGES TEXT DEFAULT NULL;

ALTER TABLE CANDIDACY_PERIOD ADD COLUMN OJB_CONCRETE_CLASS VARCHAR(250);
