 insert into PARTY_TYPE(TYPE,KEY_ROOT_DOMAIN_OBJECT) values('RESEARCH_UNIT','1');
 update PARTY SET OJB_CONCRETE_CLASS='net.sourceforge.fenixedu.domain.organizationalStructure.ResearchUnit' where CLASSIFICATION LIKE 'RESEARCH_UNIT' OR CLASSIFICATION LIKE 'ASSOCIATED_LABORATORY' OR CLASSIFICATION LIKE 'SCIENCE_INFRASTRUCTURE';
 update PARTY P, PARTY_TYPE PT set P.KEY_PARTY_TYPE=PT.ID_INTERNAL WHERE P.OJB_CONCRETE_CLASS like 'net.sourceforge.fenixedu.domain.organizationalStructure.ResearchUnit' AND PT.TYPE='RESEARCH_UNIT';

