ALTER TABLE ASSIDUOUSNESS_VACATIONS CHANGE COLUMN ARTICLE17_DAYS ACCUMULATED_ARTICLE17_DAYS double NOT NULL default '0';

ALTER TABLE ASSIDUOUSNESS_VACATIONS ADD COLUMN EFECTIVE_WORK_DAYS int(3) NOT NULL default '0';
#ALTER TABLE ASSIDUOUSNESS_VACATIONS ADD COLUMN ARTICLE17_DAYS double NOT NULL default '0';
#ALTER TABLE ASSIDUOUSNESS_VACATIONS ADD COLUMN ARTICLE18_DAYS double NOT NULL default '0';
