alter table RESULT add column ORGANIZATION varchar(255);
alter table RESULT add column PUBLISHER varchar(255);

 update RESULT as R1, PARTY as P set R1.PUBLISHER = P.NAME WHERE R1.KEY_PUBLISHER IS NOT NULL AND R1.KEY_PUBLISHER = P.ID_INTERNAL; 
 update RESULT as R1, PARTY as P set R1.ORGANIZATION = P.NAME WHERE R1.KEY_ORGANIZATION IS NOT NULL AND R1.KEY_ORGANIZATION = P.ID_INTERNAL;

alter table RESULT drop column KEY_ORGANIZATION;
alter table RESULT drop column KEY_PUBLISHER;
