UPDATE RESEARCHER SET ALLOWS_CONTACT_BY_MEDIA = 0 WHERE ALLOWS_CONTACT_BY_MEDIA IS NULL;
UPDATE RESEARCHER SET ALLOWS_CONTACT_BY_OTHER_RESEARCHERS = 0 WHERE ALLOWS_CONTACT_BY_OTHER_RESEARCHERS IS NULL;
UPDATE RESEARCHER SET ALLOWS_CONTACT_BY_STUDENTS = 0 WHERE ALLOWS_CONTACT_BY_STUDENTS IS NULL;
UPDATE RESEARCHER SET ALLOWS_TO_BE_SEARCHED = 1 WHERE ALLOWS_TO_BE_SEARCHED IS NULL;
