#!/bin/sh
# -----------------------------------------------------------------------------
#
#   Runs sql scripts to update database from previous release.
#
# -----------------------------------------------------------------------------
#

DB=$1
USER=$2

echo Using database: $DB
echo Enter password for $USER:
read -s password

function execute() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2
	echo
}

function executeWithTempFile() {
	echo ---------------------------------------- $1
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < $2 > tmp.sql
	mysql -u$USER -f -p$password --default-character-set=latin1 $DB < tmp.sql	
	rm tmp.sql
	echo
}

execute "Delete Thesis Participations whithout Thesis" deleteLooseThesisParticipations.sql
execute "Increase restriction of 255 charactes in the proposal title" increaseThesisProposalTitleSize.sql
execute "Alter Table AssiduousnessClosedMonth" alterTableAssiduousnessClosedMonth.sql
execute "alter Table JustificationMotive" alterTableJustificationMotive.sql
execute "Create Tables For UnitExtraWork" createTablesForUnitExtraWork.sql
