update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do IST'; 
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice-Presidente'; 
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice-Presidente Aluno';
update FUNCTION set TYPE = 'ASSISTANCE_PRESIDENT' where NAME = 'Presidente-Adjunto para os assuntos científicos';
update FUNCTION set TYPE = 'ASSISTANCE_PRESIDENT' where NAME = 'Presidente-Adjunto para os assuntos pedagógicos';
update FUNCTION set TYPE = 'DIRECTOR' where NAME = 'Director De Serviços De Recursos';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador';
update FUNCTION set TYPE = 'CHIEF' where NAME = 'Chefe De Repartição De Recursos';
update FUNCTION set TYPE = 'TEACHER' where NAME = 'Docente';
update FUNCTION set TYPE = 'EMPLOYEE' where NAME = 'Funcionário'; 
update FUNCTION set TYPE = 'NON_TEACHING_EMPLOYEE' where NAME = 'Funcionário não docente';
update FUNCTION set TYPE = 'TEACHER_MEMBER' where NAME = 'Membro (Docente)';
update FUNCTION set TYPE = 'EMPLOYEE_MEMBER' where NAME = 'Membro (Não Docente)';
update FUNCTION set TYPE = 'EMPLOYEE_MEMBER' where NAME = 'Membro Não Docente';
update FUNCTION set TYPE = 'STUDENT_MEMBER' where NAME = 'Membro (Aluno)';
update FUNCTION set TYPE = 'TEACER_VOWEL' where NAME = 'Vogal (Docente)';
update FUNCTION set TYPE = 'TEACER_VOWEL' where NAME = 'Vogal Docente';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal (Aluno)';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal (Assistente)';
update FUNCTION set TYPE = 'SECRETARY' where NAME = 'Secretário(a)';
update FUNCTION set TYPE = 'MEMBER' where NAME = 'Membro';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal do Conselho Directivo';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal da Comissão Executiva do Conselho Pedagógico';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal da Comissão Executiva';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal da Comissão de Pós Graduação';
update FUNCTION set TYPE = 'VOWEL' where NAME = 'Vogal da CE do DEMG';
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice-Presidente do Departamento para os Assuntos Pedagógicos';
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice-Presidente do Departamento para os Assuntos Cientificos';
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice-Presidente do Dapartmento';
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice-Presidente do CIIST';
update FUNCTION set TYPE = 'VICE_COORDINATOR' where NAME = 'vice-coordenador LEFT';
update FUNCTION set TYPE = 'VICE_COORDINATOR' where NAME = 'vice-coordenador LEBM';
update FUNCTION set TYPE = 'VICE_COORDINATOR' where NAME = 'Vice-Presidente do Departamento para os Assuntos Cientificos';
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice- Presidente do Conselho Científico';
update FUNCTION set TYPE = 'VICE_PRESIDENT' where NAME = 'Vice- Presidente da Pós Graduação do DEG';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável pelo Marketing do DEI';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável pelo Marketing';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável pela UPC-DEEC';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável pela Biblioteca no Taguspark';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável Laboratorio do Taguspark';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável Laboratorio';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável do Site Web do DEI';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável do Site Web';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável  pelas Visitas de Estudo';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável  pela ligação as Empresas';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável  Oficinas';
update FUNCTION set TYPE = 'RESPONSIBLE' where NAME = 'Responsável  do Tutorado dos Alunos Licenciatura';
update FUNCTION set TYPE = 'REPRESENTATIVE' where NAME = 'Representante na Coordenadora/DEI';
update FUNCTION set TYPE = 'REPRESENTATIVE' where NAME = 'Representante da Coordenadora/DEI';
update FUNCTION set TYPE = 'REPRESENTATIVE' where NAME = 'Representante Comissão Coordenadora Conselho Científico';
update FUNCTION set TYPE = 'REPRESENTATIVE' where NAME = 'Representante Com. Coord. C ons.Científico';
update FUNCTION set TYPE = 'REPRESENTATIVE' where NAME = 'Representante  ao Conselho Pedagógico';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidentes de Centros Coord de Areas Científicas';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do IDMEC/IST';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do ICEMS';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do CVRM';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do CPD';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do Conselho da Biblioteca Central';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do CLC';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do Centro de Informática (CIIST)';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do CEMAT';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do CAMGSD';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente Departamento';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente do Conselho de Departamento';
update FUNCTION set TYPE = 'PRESIDENT' where NAME = 'Presidente da Comissão Executiva';

update FUNCTION set TYPE = 'ASSISTANCE_PRESIDENT' where NAME = 'Presidente Adjunto Assuntos Administrativos';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Director-Adjunto para a Auditoria Interna';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Director-Adjunto para  as Residências';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Director-Adjunto da IST Press';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Directora- Adjunta para Gestão  de Projectos';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Directora- Adjunta';
update FUNCTION set TYPE = 'DIRECTOR' where NAME = 'Director Executivo';
update FUNCTION set TYPE = 'DIRECTOR' where NAME = 'Director do LEMAC/LTI';
update FUNCTION set TYPE = 'DIRECTOR' where NAME = 'Director de Biblioteca';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Director -Adjunto para as Novas Tecnologias Ensino';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Director- Adjunto do SOP';
update FUNCTION set TYPE = 'ASSOCIATE_DIRECTOR' where NAME = 'Director - Adjunto do LEMAC/LTI';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenadores de Pós-Graduação';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenadores de Licenciaturas';
update FUNCTION set TYPE = 'ASSOCIATE_COORDINATOR' where NAME = 'Coordenador-Adjunto de Licenciaturas';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador Programa Sócrates/Erasmus';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador dos TFC"s';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador dos Meios Informaticos-Tagus';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador dos Meios Informaticos';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do Serviço Docente noTaguspark';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do Serviço de Exames';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do LMPM';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do LEMat/Avaliação da Licenciatura';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do LEMat';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do Lampist';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do Laga';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do GAEL';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do Ensino Graduado';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador do  Programa de Doutoramento';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador de Mestrado Eng.Materias';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador de Mestrado Eng. Gestão Tecnologia';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador de Mestrado Cienc.EngªMaterias';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador de Mestrado  Ciencia Eng.Superficies';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador de Mestrado';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador de Centro';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador das Equivalências';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da Secção de Exploração';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da LESIM';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da LEM';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da LEIC-Tagus';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da LEIC';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da LEFT';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da LAGA';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da Comissão de Equivalências';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da Area Cientifica de MTP';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador da Area Cientifica';
update FUNCTION set TYPE = 'ASSOCIATE_COORDINATOR' where NAME = 'Coordenador -Adjunto de Secção';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador  do Research Report';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador  da Seccção';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador  da LERCI';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação de Secções';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação de Secção';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação de Área';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação da LEGI';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação da LEBM';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação da Especialização em PE da LMAC';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação da Especialização em  PE (MMA e Dout';
update FUNCTION set TYPE = 'ASSOCIATE_COORDINATOR' where NAME = 'Coordenação- Adjunto de Secção';
update FUNCTION set TYPE = 'VOWEL' where NAME = ' Vogal Comissão de Equivalências';
update FUNCTION set TYPE = 'DIRECTOR' where NAME = 'Coordenador Adjunto para as Novas Tecnologias de Ensino';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'coordenador da Area Cientifica';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenador de Mestrado';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação da LEGI';
update FUNCTION set TYPE = 'ASSOCIATE_COORDINATOR' where NAME = 'Adjunto do Coordenador da Licenciatura';
update FUNCTION set TYPE = 'COORDINATOR' where NAME = 'Coordenação da LEGI';








