
--                                                            Monitor-E.C.D.U. c/Licenciatura
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'MESTRADO' where GIAF_ID = '078510091';

--                                                            Equip.Assistente Estagiario
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ  ASSIST ESTAG' where GIAF_ID = '070000087';

--                                                            Equip. Assistente
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSISTENTE' where GIAF_ID = '070000083';

--                                                            Equip. Prof. Auxiliar
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROF.AUXILIAR' where GIAF_ID = '070000075';

--                                                            Monitor-E.C.D.U.s/Licenciatura
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROGRAMA DOUTORAL' where GIAF_ID = '078510090';

--                                                            Assistente Convidado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSIST CONVIDADO' where GIAF_ID = '078510084';

--                                                            Assistente
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSISTENTE' where GIAF_ID = '078510083';

--                                                            Prof Auxiliar Convidado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROF AUX CONV' where GIAF_ID = '078510076';

--                                                            Professor Auxiliar
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROF AUXILIAR' where GIAF_ID = '078510075';

--                                                            Professor Associado Convidado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROF ASSOC CONV' where GIAF_ID = '078510066';

--                                                            Professor Associado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROF ASSOCIADO' where GIAF_ID = '078510065';

--                                                            Professor Catedratico Convidado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROF CAT CONV' where GIAF_ID = '078510051';

--                                                            Professor Catedratico
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PROF CATEDRATICO' where GIAF_ID = '078510050';

--                                                            Dir.Superior 1º Grau
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'DIR SUPER GRAU 1' where GIAF_ID = '090020010';

--                                                            Dir.Intermédia 5º Grau
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'DIR INTERM GRAU 5' where GIAF_ID = '090030050';

--                                                            Dir.Intermédia 4º Grau
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'DIR INTERM GRAU 4' where GIAF_ID = '090030040';

--                                                            Dir.Intermédia 3º Grau
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'DIR INTERM GRAU 3' where GIAF_ID = '090030030';

--                                                            Dir.Intermédia 2º Grau
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'DIR INTERM GRAU 2' where GIAF_ID = '090030020';

--                                                            Dir.Intermédia 1º Grau
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'DIR INTERM GRAU 1' where GIAF_ID = '090030010';

--                                                            Eq. Assistente Operacional
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ ASSIST OPERAC' where GIAF_ID = '110000320';

--                                                            Encarregado Operacional
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ENCARREGADO OPER' where GIAF_ID = '110010310';

--                                                            Assistente Operacional
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSIS OPERACIONAL' where GIAF_ID = '110010320';

--                                                            Eq. Assistente Técnico
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ ASSIS TECNICO' where GIAF_ID = '100000110';

--                                                            Assistente Técnico
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSIST TECNICO' where GIAF_ID = '100010110';

--                                                            Eq. Coordenador Técnico
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ COORD TECNICO' where GIAF_ID = '100000100';

--                                                            Coordenador Técnico
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'COORD TECNICO' where GIAF_ID = '100010100';

--                                                            Técnico Superior
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECNICO SUPERIOR' where GIAF_ID = '050010200';

--                                                            Eq. Técnico Superior
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ TECN SUPERIOR' where GIAF_ID = '050000200';

--                                                            Colaborador da ADIST
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'COLABORADOR ADIST' where GIAF_ID = '990000001';

--                                                            Especialista Informática Grau 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC.INFORM.GR.2' where GIAF_ID = '089101101';

--                                                            Eq. Tecnico Profissional 2Cl
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = '' where GIAF_ID = '040000365';

--                                                            Eq. Tecnico Profissional Especialista
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECN.PROF.ESP.' where GIAF_ID = '040000341';

--                                                            Auxiliar Administrativo
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'AUX. ADMINISTR.' where GIAF_ID = '021030755';

--                                                            Eq. Especialista Inform. Grau 1 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC INFORM GR 1' where GIAF_ID = '080001380';

--                                                            Auxiliar Tecnico
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'AUXILIAR TECNICO' where GIAF_ID = '022750055';

--                                                            Assistente Administrativo Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSIST.ADM.PRINC.' where GIAF_ID = '010110660';

--                                                            Assistente Administrativo Especialista
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSIST.ADMN.ESP.' where GIAF_ID = '010110655';

--                                                            Chefe Secção
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'CHEFE DE SECCAO' where GIAF_ID = '010100654';

--                                                            Tecnico Profissional Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECN.PROF.PRINC.' where GIAF_ID = '040100355';

--                                                            Tecnico Profissional Especialista Princi
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECN.PROF.ESP.PR.' where GIAF_ID = '040100340';

--                                                            Eq. Especialista Inform. Grau 1 Nível 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC.INFORM.GR.1' where GIAF_ID = '080001370';

--                                                            Eq. Especialista Inform. Grau 1 Nível 3
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC.INFORM.GR.1' where GIAF_ID = '080001350';

--                                                            Eq. Especialista Inform. Grau 2 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC.INFORM.GR.1' where GIAF_ID = '080001340';

--                                                            Eq. Especialista Inform. Grau 2 Nível 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'MEIC A' where GIAF_ID = '080001330';

--                                                            Eq. Auxiliar Manutencao
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'AUXILAR MANUTENCA' where GIAF_ID = '020000855';

--                                                            Eq. Assistente Administrativo
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ASSIST.ADMIN.' where GIAF_ID = '010000665';

--                                                            Eq. Tecnico 2 Cl
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'DEME' where GIAF_ID = '030000265';

--                                                            Eq. Tecnico Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'MESTR INTEGRADO' where GIAF_ID = '030000255';

--                                                            Tecnico Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECN. PRINCIPAL' where GIAF_ID = '030100255';

--                                                            Tecnico Especialista Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECN.ESPEC.PRINC.' where GIAF_ID = '030100225';

--                                                            Tecnico Profissional Especialista
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECN.PROF.ESP.' where GIAF_ID = '043800341';

--                                                            Técnico Superior 1 Cl
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TECN.SUP.1 CLASSE' where GIAF_ID = '055830160';

--                                                            Pintor Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'PINTOR PRINCIPAL' where GIAF_ID = '067250855';

--                                                            Especialista Informática Grau 1 Nível 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC INFORM GR 1' where GIAF_ID = '089101170';

--                                                            Especialista Informática Grau 1 Nível 3
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ ESP INF GRAU 1' where GIAF_ID = '089101150';

--                                                            Especialista Informática Grau 2 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC INFORM GR 3' where GIAF_ID = '089101140';

--                                                            Especialista Informática Grau 2 Nível 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC INFORM GR 2' where GIAF_ID = '089101130';

--                                                            Especialista Informática Grau 3 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC INFORM GR 3' where GIAF_ID = '089101120';

--                                                            Especialista Informática Grau 3 Nível 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC INFORM GR 3' where GIAF_ID = '089101110';

--                                                            Técnico Informática Grau 1 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TEC INFORM GRAU 1' where GIAF_ID = '088011180';

--                                                            Técnico Informática Grau 1 Nível 3
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TEC INFORM GRAU 1' where GIAF_ID = '088011150';

--                                                            Técnico Informática Grau 2 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TEC INFORM GRAU 2' where GIAF_ID = '088011140';

--                                                            Técnico Informática Grau 2 Nível 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TEC INFORM GRAU 2' where GIAF_ID = '088011130';

--                                                            Técnico Informática Grau 3 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TEC INFORM GRAU 3' where GIAF_ID = '088011120';

--                                                            Técnico Informática Grau 3 Nível 2
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'TEC INFORM GRAU 3' where GIAF_ID = '088011110';

--                                                            Especialista Informática Grau 1 Nível 1
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'ESPEC INFORM GR 1' where GIAF_ID = '089101180';

--                                                            Chefe Divisão
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'CHEFE DE DIVISAO' where GIAF_ID = '090010127';

--                                                            Eq. Técnico Superior (Estag)
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ TECN SUP ESTAG' where GIAF_ID = '050000300';

--                                                            Investigador Auxiliar Convidado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INV AUX CONVIDADO' where GIAF_ID = '125340173';

--                                                            Experienced Researcher
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INVESTIGADOR' where GIAF_ID = '126000001';

--                                                            Early Stage Researcher
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INVESTIGADOR' where GIAF_ID = '126000002';

--                                                            Equip.Investigador Auxiliar Convidado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ INV AUX CONV' where GIAF_ID = '120000173';

--                                                            Equip.Estagiario Investigador
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EST.INVESTIGACAO' where GIAF_ID = '120000176';

--                                                            Equip.Assistente de Investigaçao
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ ASSIST INV' where GIAF_ID = '120000175';

--                                                            Equip.Investigador Auxiliar
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'EQ INVEST AUX' where GIAF_ID = '120000171';

--                                                            Equip.Investigador Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INVESTIGADOR PR' where GIAF_ID = '120000155';

--                                                            Investigador Auxiliar
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INVESTIGADOR AUX' where GIAF_ID = '125340171';

--                                                            Investigador Coordenador Convidado
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INV.COORD.CONV.' where GIAF_ID = '125340156';

--                                                            Investigador Principal
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INVESTIGADOR PR' where GIAF_ID = '125340155';

--                                                            Investigador Coordenador
update PROFESSIONAL_CATEGORY set IDENTIFICATION_CARD_LABEL = 'INVESTIG COORD' where GIAF_ID = '125340152';



update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:CIENCIAS BIOLOGICAS' where OID = 863289242477
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt39:CENTRO DE FISICA TEORICA DAS PARTICULAS' where OID = 343597444866
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt26:AREA CIENTIFICA DE ENERGIA' where OID = 863288487641
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:NUCLEO DE GRADUACAO' where OID = 2160369273412
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt28:AREA DE COMUNICACAO E IMAGEM' where OID = 2160369273428
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt37:AREA CIENTIFICA DE AMBIENTE E ENERGIA' where OID = 863288488020
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt41:NUCLEO SECRETARIADO DO CONSELHO DE GESTAO' where OID = 2160369273454
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENTIFICA DE CIENCIAS DE ENG QUIMICA' where OID = 863288487741
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:SECCAO DE MECANICA ESTRUTURAL E ESTRUTURAS' where OID = 751619337971
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt15:AREA DE PESSOAL' where OID = 2160368610985
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:CONSELHO CIENTIFICO' where OID = 3109556383354
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:NUCLEO DE COMPRAS E ECONOMATO' where OID = 2160368610983
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:C ANALISE MAT GEOM E SIST DINAMICOS       ' where OID = 343597445130
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt31:NUCLEO DE APLICACOES ACADEMICAS' where OID = 2160369273423
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt15:DEC-PRESIDENCIA' where OID = 2160368611056
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt39:DEPARTAMENTO ENG.E GESTAO - PRESIDENCIA' where OID = 2160368611063
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:AREA DE ESTUDOS E PLANEAMENTO' where OID = 2160369273439
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt30:AREA COMUM DE RECURSOS HUMANOS' where OID = 2160369273394
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt10:BIBLIOTECA' where OID = 2160368611002
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt25:NUCLEO DE SERVICOS GERAIS' where OID = 2160368610969
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt15:NUCLEO DE OBRAS' where OID = 2160368610976
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:DIRECCAO DE SERVICOS DE INFORMATICA' where OID = 2160369273416
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:SECCAO DE GEOTECNIA' where OID = 751619337965
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt40:UNIDADE DE ENGENHARIA E TECNOLOGIA NAVAL' where OID = 343597444877
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:SEC MAT  APLIC  ANAL  NUMERICA            ' where OID = 751619337932
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt32:NUCLEO DE PROJECTOS COMUNITARIOS' where OID = 2160368622346
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt30:NUCLEO FINANCEIRO DO TAGUSPARK' where OID = 2160369273401
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUCLEO GESTAO MUSEU E CONTRO DE CONGRESSOS' where OID = 2160369273430
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt12:POLO IST-ISR' where OID = 343597444893
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt23:AREA DE INFRAESTRUTURAS' where OID = 2160369273424
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIEN SINTESE  ESTRU MOLEC E ANAL QUIM' where OID = 863288487962
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt37:NUCLEO DE COMUNICACOES DE VOZ E VIDEO' where OID = 2160369273425
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUCL GESTAO E ACOMP DE CONTRATOS          ' where OID = 2160368610968
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt38:CENTRO DE SISTEMAS URBANOS E REGIONAIS' where OID = 343597444870
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:GESTAO ESPACO PAVILHAO MATEMATICA E FISICA' where OID = 2160369273270
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:DEP ENGEN ELECTROTECNICA E DE COMPUTADORES' where OID = 2160368611028
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:AREA DE BIBLIOTECAS' where OID = 2160369273441
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:GABINETE DE APOIO AO TUTORADO' where OID = 2160369273413
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt39:SECCAO DE SISTEMAS DE APOIO AO PROJECTO' where OID = 751619337966
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:NUCLEO DE DOCENTES E INVESTIGADORES' where OID = 2160369273393
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:AREA CIENTIFICA DE TELECOMUNICACOES' where OID = 863288487639
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt25:AREA TECNICA DO TAGUSPARK' where OID = 2160368611104
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt28:NUCLEO DE APOIO AO ESTUDANTE' where OID = 2160369273431
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt27:SECCAO DE ALGEBRA E ANALISE' where OID = 751619337934
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:CENTRO DE ENG BIOLOGICA E QUIMICA         ' where OID = 343597654248
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt31:SISTEMAS BIOMEDICOS E BIOSINAIS' where OID = 863289242479
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:C ESTUDOS INOV TECN POL DESENVOLV         ' where OID = 343597444881
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt14:POLO IST-IDMEC' where OID = 343597444889
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUC METAIS PREP AMOSTRAS SOLIDAS          ' where OID = 2160369273448
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA DE APLICACOES SISTEMAS INFORMACAO    ' where OID = 2160369273421
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:CENTRO FISICA INTERAC FUNDAMENTAIS        ' where OID = 343597444867
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt31:NUCLEO DE SUPORTE AO UTILIZADOR' where OID = 2160369273418
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt38:DEPARTAMENTO DE ENGENHARIA INFORMATICA' where OID = 2160368611067
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt36:INSTITUTO DE PLASMAS E FUSAO NUCLEAR' where OID = 343597705249
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT TECNOLOGIA MECANICA E G INDUS  ' where OID = 863288487924
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt30:AREA CIENTIFICA DE ELECTRONICA' where OID = 863288487638
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt20:NUCLEO DE TESOURARIA' where OID = 2160368610990
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT SIST  DECISAO E CONTROLO       ' where OID = 863288487637
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt33:NUCLEO DE RELACOES INTERNACIONAIS' where OID = 2160369273453
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:GESTAO DO CAMPUS DO IST NO TAGUSPARK_GERAL' where OID = 2160368625966
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt22:SECCAO DE ARQUITECTURA' where OID = 751619337963
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:BIOMATERIA  NANOTECNO E MEDICINA REGENERAT' where OID = 863289242472
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt38:CENTRO MULTIDISCIPLINAR DE ASTROFISICA' where OID = 343597445027
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT QUIM-FISICA  MATERI E NANOCIENC' where OID = 863288487740
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt34:AREA DE INSTALACOES E EQUIPAMENTOS' where OID = 2160368610975
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUCLEO REM PROT BENEF SOCIAIS             ' where OID = 2160369273395
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt31:DIRECCAO RECURSOS HUMANOS_GERAL' where OID = 2160369273398
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:DEPARTAM DE ENGENHARIA QUIMICA E BIOLOGICA' where OID = 2160368611003
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt10:BIBLIOTECA' where OID = 2160368611052
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt24:DIRECCAO EXECUTIVA GERAL' where OID = 2160368610962
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:GESTAO ESP COMPLEXO INTERDISCIPLINAR      ' where OID = 2160369273403
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt32:NUCLEO DE PARCERIAS EMPRESARIAIS' where OID = 2160369273375
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt39:DEPARTAMENTO DE ENGENHARIA DE MATERIAIS' where OID = 2160368610996
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt31:CENTRO VALOR. RECURSOS MINERAIS' where OID = 343597444876
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt32:NUCLEO DE ARQUIVO E DOCUMENTACAO' where OID = 2160369273397
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT TERMOFLUIDOS E TECNOL CONV EN  ' where OID = 863288487925
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt40:DEP ENG ELECTROTECNICA E COMPUTADORES TP' where OID = 2160368958062
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:NUCLEO DE EXECUCAO ORCAMENTAL' where OID = 2160368610992
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt17:AREA DE PROJECTOS' where OID = 2160368623566
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt33:NUCLEO DE MULTIMEDIA E E-LEARNING' where OID = 2160369273419
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt20:SECCAO DE CONSTRUCAO' where OID = 751619337967
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:GAB COMUNIC RELACOES PUBLICAS             ' where OID = 2160369273429
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt33:CENTRO DE PETROLOGIA E GEOQUIMICA' where OID = 343597444871
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt20:NUCLEO DE MANUTENCAO' where OID = 2160368610979
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:COORD LICENCIATURA ENG AMBIENTE           ' where OID = 2160368611095
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt17:NUCLEO DE ARQUIVO' where OID = 2160368610967
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUC ANAL GER APLIC AGUAS RESIDUAIS        ' where OID = 2160369273450
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:CONSELHO PEDAGOGICO' where OID = 3100966448764
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt7:MARETEC' where OID = 2160368611110
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUC MOBILID COOP INTERNACIONAL            ' where OID = 2160369273455
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt34:CENTRO DE ESTUDOS DE GESTAO DO IST' where OID = 343597445155
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt31:AREA CIENTIFICA DE COMPUTADORES' where OID = 863288487640
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:SEC URBANISMO TRANSP VIAS SISTEMAS        ' where OID = 751619337970
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT PROJECTO MECANICO E MAT ESTR   ' where OID = 863288487923
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:INST CIENCIA E ENG MATERIAIS E SUP        ' where OID = 343597444892
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUC GEST COLHEIT AMB SAUDE E SEGURANCA    ' where OID = 2160369273445
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT MECANICA APLIC E AEROESPACIAL  ' where OID = 863288487921
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:AREA DE APOIO GERAL' where OID = 2160368610966
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt27:NUCLEO DE REDES DE SISTEMAS' where OID = 2160369273426
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:DEPARTAMENTO DE ENGENHARIA MECANICA' where OID = 2160368611011
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUC POS-GRAD FORM CONTINUA                ' where OID = 1902671263701
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt22:DIRECCAO TECNICA GERAL' where OID = 2160368610965
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt34:NUCLEO DE NAO DOCENTES E BOLSEIROS' where OID = 2160369273392
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:AREA DE LIGACAO AO UTILIZADOR' where OID = 2160369273417
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt40:CENTRO ANALISE E PROCESSAMENTO DE SINAIS' where OID = 343597444873
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:CENTRO DE ESTUDOS DE HIDROSSISTEMAS' where OID = 343597444878
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt20:NUCLEO DE PATRIMONIO' where OID = 2160368610984
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT CONTROLO AUTO INF INDUSTRIAL   ' where OID = 863288487920
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt26:DIRECCAO DE APOIO JURIDICO' where OID = 2160369273433
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:AREA FINANCEIRA E PATRIMONIAL' where OID = 2160368610981
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:NUCLEO DE ESTATISTICA E PROSPECTIVA' where OID = 2160369273440
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt34:GABINETE DE ORGANIZACAO PEDAGOGICA' where OID = 2160369273414
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENT MECANICA ESTRUTURAL E COMPUT   ' where OID = 863288487922
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:CONTABILID INTEG DO DEP ENG CIVIL E ARQUIT' where OID = 2160368694639
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:DEPARTAMENTO DE BIOENGENHARIA' where OID = 2160369362864
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt38:AREA ESPECIALIZADA DE RECURSOS HUMANOS' where OID = 2160369273391
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt18:DIRECCAO ACADEMICA' where OID = 2160369273410
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:SERVICOS ADMIN E FIN COMPLEXO INTERDISCIPL' where OID = 2160369273406
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt9:IST PRESS' where OID = 2160369273458
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt10:BIBLIOTECA' where OID = 2160368611007
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt18:CONSELHO DE GESTAO' where OID = 2160368610936
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt38:CENTRO DE RECURSOS NATURAIS E AMBIENTE' where OID = 343597587437
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUC SERV MED APOIO AVALIAC PSICOLOGICA    ' where OID = 2160369273457
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt27:INSTITUTO BIOTECNICA Q.FINA' where OID = 343597732859
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt40:NUCLEO DE ANALISE DE COMPOSTOS ORGANICOS' where OID = 2160369273451
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:SECCAO DE LOGICA E COMPUTACAO' where OID = 751619337931
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt41:ENGENHARIA BIOMOLECULAR E DE BIOPROCESSOS' where OID = 863289242478
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:AREA DE TRANSFERENCIA DE TECNOLOGIA' where OID = 2160369273374
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt30:SECCAO DE MINAS E GEORRECURSOS' where OID = 751620084185
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt34:CENTRO DE QUIMICA-FISICA MOLECULAR' where OID = 343597444864
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt27:BIBLIOTECA DO IST/TAGUSPARK' where OID = 2160369273400
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt21:NUCLEO DE ALOJAMENTOS' where OID = 2160369273404
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUCLEO MICROBIOCLASSI E NOVAS METODOLOGIAS' where OID = 2160369273449
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt26:NUCLEO DE MICROINFORMATICA' where OID = 2160369273420
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt37:PRESIDENCIA DO DEPARTAMENTO DE FISICA' where OID = 2160368611038
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt35:AREA CIENTIFICA DE ENGENHARIA NAVAL' where OID = 863289179077
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt41:AREA PARA A QUALIDADE E AUDITORIA INTERNA' where OID = 2160369273447
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt28:NUCLEO CONTABILIDADE CENTRAL' where OID = 2160368610991
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt36:NUCLEO DE SEGURANCA  HIGIENE E SAUDE' where OID = 2160368610977
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:NUC ANAL GER APLIC AGUAS LIMPAS           ' where OID = 2160369273446
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA DE SERVICOS INFORMATICOS DO TAGUSPARK' where OID = 2160369273399
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt10:BIBLIOTECA' where OID = 2160368611037
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt33:NUCLEO DE PROPRIEDADE INTELECTUAL' where OID = 2160369273376
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt29:NUCLEO DE PROJECTOS NACIONAIS' where OID = 2160368625986
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt21:NUCLEO DE REPROGRAFIA' where OID = 2160368610970
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt34:SECCAO DE ESTATISTICA E APLICACOES' where OID = 751619337933
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt40:AREA ACADEMICA E DE PESSOAL DO TAGUSPARK' where OID = 2160369273402
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt31:NUCLEO DE PRESTACAO DE TRABALHO' where OID = 2160369273396
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:AREA CIENTI DE ENG DE PROCESSOS E PROJECTO' where OID = 863288487742
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt41:INST ENG ESTRUTURAS TERRITORIO CONSTRUCAO' where OID = 343597444890
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt23:LABORATORIO DE ANALISES' where OID = 2160369273444
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt41:NUCLEO PROJECTOS CONSULTADORIA E SERVICOS' where OID = 2160368622726
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt28:CENTRO DE QUIMICA ESTRUTURAL' where OID = 343597444865
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt33:CENTRO DE MATEMATICA E APLICACOES' where OID = 343597445128
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt32:ASSESSORIA AO CONSELHO DE GESTAO' where OID = 2160369273456
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt42:SEC  HIDRAULICA REC HIDRICOS AMBIENTAIS   ' where OID = 751619337969
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt32:ASSESSORIA DO CONSELHO DIRECTIVO' where OID = 2160368610945
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt41:PRESIDENCIA DO DEPARTAMENTO DE MATEMATICA' where OID = 2160368611018
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt10:BIBLIOTECA' where OID = 2160368611026
update PARTY set IDENTIFICATION_CARD_LABEL = 'pt19:AREA CONTABILISTICA' where OID = 2160368610988

