alter table JUSTIFICATION_MOTIVE change column GIAF_CODE_CONTRACTED_STATUS GIAF_CODE_CONTRACTED_STATUS varchar(20) default NULL;
alter table JUSTIFICATION_MOTIVE change column GIAF_CODE_OTHER_STATUS GIAF_CODE_OTHER_STATUS varchar(20) default NULL;

update JUSTIFICATION_MOTIVE set GIAF_CODE_OTHER_STATUS = lpad(GIAF_CODE_OTHER_STATUS,3,'000') where GIAF_CODE_OTHER_STATUS <>0;
update JUSTIFICATION_MOTIVE set GIAF_CODE_CONTRACTED_STATUS= lpad(GIAF_CODE_CONTRACTED_STATUS,3,'000') where GIAF_CODE_OTHER_STATUS<>0;
